# -*- coding: utf-8 -*-
"""
Har bir darsning ANIQ amaliy natijasi (nima yasaladi/dasturlanadi).
"—" = shu darsda yangi qurish yo'q (kirish/muhokama/sinov/tuzatish kabi, oldingi bosqich davomi).
0-2-sinf va 3-sinf Q1-Q2: yo'riqnoma asosida aniq model.
3-sinf Q3-Q4 va 4-sinf (barcha chorak): hayotiy misol asosida o'quvchi o'zi loyihalaydi (kam yo'riqnoma).
"""

AMALIY = {
    "0-sinf": [
        {  # Q1
            "lessons": ["—", "—", "Ranglar/shakllar bo'yicha saralash o'yini",
                        "Minora (erkin balandlik musobaqasi)", "Oddiy ko'prik (2 minora orasida)",
                        "Devor (mustahkamlik sinovi)", "Detallarni o'lchamiga qarab saralash",
                        "Wheel Car — g'ildirak qismi", "Wheel Car (to'liq)",
                        "Uy modeli (erkin dizayn)", "Fil modeli (erkin dizayn)",
                        "Daraxt modeli (erkin dizayn)", "Ertak qahramoni (erkin dizayn)",
                        "Ko'prik (juftlikda, mustahkamlik sinovi)", "Qal'a (juftlikda, erkin dizayn)",
                        "—", "—"],
            "nazorat": "Amaliy: bloklarni tanib, oddiy shakl yig'ish",
            "loyiha": "Orzudagi uy (erkin dizayn)",
        },
        {  # Q2
            "lessons": ["—", "Bola o'zi \"robot\" bo'lib buyruq bajaradi", "Marshrut kartasi (qog'ozda)",
                        "Labirint chizmasi", "—", "—", "—",
                        "G'ildirak-o'q namunasi", "Tishli g'ildirak namunasi", "Shkiv-tasma namunasi",
                        "Richag bilan yuk ko'tarish namunasi", "Aylanuvchi karusel",
                        "Mashina shassisi (erkin)", "—", "—",
                        "Motorli aravacha (o'qituvchi yordamida)", "—"],
            "nazorat": "Amaliy: mexanizm nomlarini ko'rsatib berish",
            "loyiha": "Mening aravacham (Wheel Car asosida, motorli)",
        },
        {  # Q3
            "lessons": ["—", "Motor+controller ulanishi", "—", "Mashinacha (boshlang'ich)", "—", "—", "—",
                        "Mashinacha (to'liq)", "—", "Aylanuvchi yulduzcha", "—", "—", "—",
                        "Erkin model (tayyor namunalardan tanlab)", "—", "—", "—"],
            "nazorat": "Amaliy: controllerni ulab, ilovada yurgizish",
            "loyiha": "Yuradigan robotim (erkin model)",
        },
        {  # Q4
            "lessons": ["—", "—", "—", "Yakuniy loyiha — asos qismi",
                        "Yakuniy loyiha — harakatlanuvchi qism", "—", "—", "—", "—", "—", "—", "—",
                        "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy-og'zaki nazorat",
            "loyiha": "Mening birinchi robotim (erkin model, ko'rgazma)",
        },
    ],
    "1-sinf": [
        {  # Q1
            "lessons": ["—", "—", "—", "—", "—", "Labirint chizmasi", "—", "—", "—",
                        "Sinov minorasi (mustahkamlik)", "Minora (musobaqa)", "Ko'prik",
                        "Tishli g'ildirak namunasi", "Ikki xil tishli taqqoslash",
                        "Shkiv-tasma namunasi", "Richag namunasi", "Arava (Wheel Car)"],
            "nazorat": "Amaliy: algoritm+mexanizm bo'yicha kichik topshiriq",
            "loyiha": "O'z arava modelim",
        },
        {  # Q2
            "lessons": ["—", "—", "—", "—", "Aylanuvchi karusel", "—",
                        "Gear Shifting Fan (yelpig'ich)", "—", "—", "Mashina shassisi", "—", "—",
                        "—", "—", "—", "Dancing Man (raqsga tushuvchi robot)",
                        "Erkin model (o'quvchi tanlaydi)"],
            "nazorat": "Amaliy: motor bilan oddiy dastur yozib ko'rsatish",
            "loyiha": "Raqsga tushuvchi robotim (Dancing Man asosida)",
        },
        {  # Q3
            "lessons": ["—", "—", "Automatic Gate (sezgir darvoza)", "—", "—",
                        "Obstacle Avoiding Car (soddalashtirilgan)", "Score Indicator (ovozli qo'riqchi)",
                        "Little Bear (gorilla o'rniga)", "Little Deer/Rabbit (AI)", "—",
                        "Mini-loyiha: aqlli o'yinchoq", "—", "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy: sensor ulab, reaksiya dasturini ko'rsatish",
            "loyiha": "Aqlli qo'riqchi robotim",
        },
        {  # Q4
            "lessons": ["—", "—", "—", "Yakuniy loyiha — asos", "Yakuniy loyiha — harakat qismi",
                        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy: yil bo'yicha bilimlarni robot orqali ko'rsatish",
            "loyiha": "Yakuniy loyiham (erkin tanlangan model)",
        },
    ],
    "2-sinf": [
        {  # Q1
            "lessons": ["—", "—", "Tezkor qurish musobaqasi (erkin)", "—", "—",
                        "Tishli g'ildirak taqqoslash namunasi", "Uzatma tizimi namunasi",
                        "Shkiv tizimi namunasi", "Richag bilan yuk ko'tarish", "Manual Joint Motion",
                        "Excavator, Gear-driven", "Crane", "Conveyor", "Rail Gate",
                        "4 g'ildirakli arava", "—", "—"],
            "nazorat": "Amaliy: bitta mexanizmni yig'ib, ishlash tamoyilini tushuntirish",
            "loyiha": "Yuk ko'taruvchi kran (Crane/Tower Crane asosida)",
        },
        {  # Q2
            "lessons": ["—", "—", "—", "—", "—", "Hisoblagich namunasi", "—", "—", "—", "—",
                        "Soat-robot (Weirdo Clock asosida, motorlashtirilgan)", "—", "—", "—",
                        "Rocking/Dotting Machine dasturi", "—", "—"],
            "nazorat": "Amaliy: shart+sikl ishlatilgan dasturni ko'rsatish",
            "loyiha": "Aqlli soat-robot (Weirdo Clock asosida)",
        },
        {  # Q3
            "lessons": ["—", "—", "Obstacle Avoiding Car", "—", "Line Patrol Tank", "Line Patrol Dog",
                        "Svetofor modeli (erkin dizayn)", "—", "Score Indicator", "—", "—",
                        "Little Bear", "—", "Guruh loyihasi: aqlli shahar elementi", "—", "—", "—"],
            "nazorat": "Amaliy: sensor+shart logikasi bilan modelni ko'rsatish",
            "loyiha": "Aqlli uy qo'riqchisi (Score Indicator/Automatic Gate asosida)",
        },
        {  # Q4
            "lessons": ["—", "—", "—", "Yakuniy loyiha — asosiy qism",
                        "Yakuniy loyiha — harakat qismi", "—", "—", "—", "—", "—", "—", "—", "—",
                        "—", "—", "—", "—"],
            "nazorat": "Amaliy nazorat",
            "loyiha": "Yakuniy loyiham (erkin tanlangan model)",
        },
    ],
    "3-sinf": [
        {  # Q1 - guided
            "lessons": ["—", "Burchakli ulanish namunasi", "Differensial namunasi",
                        "Murakkab uzatma namunasi", "3 bosqichli mexanizm namunasi",
                        "Eggbeater (manipulyator)", "—", "—", "—", "Balance/Tumbler namunasi", "—",
                        "—", "Trailer/Formula Car (murakkab arava)", "—", "—", "—", "—"],
            "nazorat": "Amaliy: murakkab mexanizmni yig'ib, ishlash tamoyilini tushuntirish",
            "loyiha": "Robot-manipulyator (Eggbeater/Tower Crane asosida)",
        },
        {  # Q2 - guided
            "lessons": ["—", "—", "Harakat naqshi dasturi", "—", "—", "—", "—", "—",
                        "Ball tizimi dasturi", "—", "—", "Telecar (robot-kuryer)", "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy: funksiyalardan foydalangan dasturni ko'rsatish",
            "loyiha": "Kuryer-robot (Telecar/Patrol Car asosida)",
        },
        {  # Q3 - OCHIQ: hayotiy misol asosida o'zi loyihalaydi
            "lessons": ["—", "—", "—",
                        "Hayotiy misol: robot-pilesos (avtomatik supurgich) → o'zi loyihalaydi",
                        "—", "—", "—",
                        "Hayotiy misol: qidiruv-qutqaruv robotlari → o'zi loyihalaydi",
                        "—", "—", "—", "—", "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy: o'zi ixtiro qilgan robotini sinovdan o'tkazib ko'rsatish",
            "loyiha": "Hayotiy muammoga yechim: labirint/qutqaruv roboti (o'z ixtirosi)",
        },
        {  # Q4 - OCHIQ
            "lessons": ["—", "—", "—", "—", "Hayotiy muammoga o'z yechimi — qurilish boshlanishi",
                        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy nazorat",
            "loyiha": "Ijodiy robot — hayotiy muammoga o'z yechimi",
        },
    ],
    "4-sinf": [
        {  # Q1 - OCHIQ
            "lessons": ["—", "—", "Hayotiy muammo: omborda/qurilishda yuk qanday tashiladi?", "—",
                        "—", "—", "Hayotiy misol: real forklift/kran → o'zi loyihalaydi", "—", "—",
                        "—", "—", "—", "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy: o'zi ixtiro qilgan yuk tashish robotini namoyish qilish",
            "loyiha": "Hayotiy muammoga yechim: yuk tashish roboti (o'z ixtirosi)",
        },
        {  # Q2 - OCHIQ
            "lessons": ["—", "—", "—",
                        "Hayotiy misol: svetofor/xavfsizlik tizimlari qanday qaror qabul qiladi?",
                        "—", "—", "—", "—", "—", "—", "—",
                        "Hayotiy misol: patrul/qo'riqlash robotlari → o'zi loyihalaydi",
                        "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy: to'liq avtonom robotni namoyish qilish",
            "loyiha": "Hayotiy muammoga yechim: avtonom qo'riqlash/patrul roboti (o'z ixtirosi)",
        },
        {  # Q3 - OCHIQ
            "lessons": ["—", "—", "—", "—",
                        "Hayotiy misol: qidiruv-qutqaruv/kosmik missiyalar → o'z vazifasini loyihalaydi",
                        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy: musobaqa vazifasini bajarib ko'rsatish",
            "loyiha": "Musobaqa roboti (o'z ixtirosi, ichki turnir)",
        },
        {  # Q4 - OCHIQ
            "lessons": ["—", "—", "—", "Bitiruv loyihasi: real hayotiy muammoga o'z yechimi", "—",
                        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—"],
            "nazorat": "Amaliy: bitiruv loyihasini to'liq namoyish qilish",
            "loyiha": "Bitiruv loyihasi — hayotiy muammoga o'z ixtirosi (ko'rgazma)",
        },
    ],
    "4-sinf-spike": [
        {  # Q1 — 100% qurish, LEGO rasmiy modellari
            "lessons": ["—", "Driving Base 1", "Driving Base 2", "Driving Base 3 (Advanced)",
                        "StarterBot", "Robot Arm", "Line Follower attachment",
                        "Ultrasonic sensor mount", "Color sensor mount", "Bumper attachment",
                        "Gripper attachment", "Tractor", "Catapult attachment",
                        "Plow attachment", "Scoop attachment", "Fork-lift attachment", "Ball Shooter attachment",
                        "Kriket (box robot)", "Sensor arm attachment"],
            "nazorat": "Amaliy: Driving Base va 2 attachmentni tanlab, ishlash tamoyilini tushuntirish",
            "loyiha": "O'z Driving Base + tanlagan attachmentlar kombinatsiyasi (erkin)",
        },
        {  # Q2
            "lessons": ["—", "—", "—", "Chiziq kuzatuvchi robot", "—", "—",
                        "To'siqdan qochuvchi robot", "—", "—", "Sensorli darvoza", "—", "—", "—", "—",
                        "Aqlli parking roboti", "—", "—", "—", "—"],
            "nazorat": "Amaliy: kamida 2 sensor ishlatilgan dasturni ko'rsatish",
            "loyiha": "Aqlli parking robot",
        },
        {  # Q3 — Missiya 1 va 2
            "lessons": ["—", "—", "—", "Missiya 1 attachment (dizayn)", "Missiya 1 attachment",
                        "—", "—", "Missiya 1 — ball qo'yiladi", "—", "Missiya 2 attachment (dizayn)",
                        "Missiya 2 attachment", "—", "—", "Missiya 2 — ball qo'yiladi",
                        "—", "—", "—", "—", "—"],
            "nazorat": "Missiya musobaqasi: 1-2-missiya ball asosida baholanadi (jami 50 ball)",
            "loyiha": "1-2-missiya uchun mukammal robot+attachment yechimi",
        },
        {  # Q4 — Missiya 3, 4 va yakuniy turnir
            "lessons": ["—", "Missiya 3 attachment (dizayn)", "Missiya 3 attachment", "—", "—",
                        "Missiya 3 — ball qo'yiladi", "—", "Missiya 4 attachment (dizayn)",
                        "Missiya 4 attachment", "—", "—", "Missiya 4 — ball qo'yiladi",
                        "—", "—", "—", "—", "—", "Bitiruv turniri (4 missiya)", "—"],
            "nazorat": "To'liq missiya turi: 4 missiya ball asosida baholanadi (jami 100 ball)",
            "loyiha": "To'liq 4-missiyali bitiruv musobaqasi (ochiq turnir)",
        },
    ],
}
