# -*- coding: utf-8 -*-
"""
0-4-sinf robototexnika dasturi (Makerzoid Robot Master Standard, 1-yil)
va 4-sinf SPIKE Prime (2-yil) uchun to'liq kontent.
Har bir sinf: 4 chorak x (17 mavzu darsi + 1 nazorat + 1 loyiha) = 76 dars.
"""

MAKERZOID = "Makerzoid Robot Master Standard"
MAKERZOID_PLUS = "Makerzoid + qo'shimcha motor/sensor"
SPIKE = "SPIKE Prime"

# ---------- 0-SINF ----------
sinf0 = {
    "platforma": MAKERZOID,
    "quarters": [
        {
            "nomi": "M1. Tanishuv va qurish asoslari",
            "jihoz": MAKERZOID,
            "lessons": [
                "Robot nima? Suhbat va rasmlar",
                "Xavfsizlik qoidalari va tartib",
                "Bloklar bilan tanishuv: rangi, shakli",
                "Baland minora qurish o'yini",
                "Ko'prik qurish o'yini",
                "Uzun devor qurish",
                "Katta-kichik detallarni ajratish",
                "Mashina g'ildiragini yig'ish",
                "Oddiy arava qurish",
                "Uy modelini yig'ish",
                "Hayvon modelini yig'ish (fil)",
                "Daraxt modelini yig'ish",
                "Ertak qahramoni modelini yig'ish",
                "Juftlikda qurish: ko'prik",
                "Juftlikda qurish: qal'a",
                "Qurilgan modellarni ko'rgazmaga qo'yish",
                "Modellarni tasvirlash: bu nima, nima uchun kerak",
            ],
            "nazorat": "1-chorak nazorat ishi: bloklarni tanish va oddiy qurish topshirig'i",
            "loyiha": "1-chorak loyihasi: orzudagi uyimni quraman",
        },
        {
            "nomi": "M2. Algoritm va harakat",
            "jihoz": MAKERZOID,
            "lessons": [
                "Algoritm nima? Kundalik misollar (ertalabki tayyorgarlik)",
                "Ketma-ketlik o'yini: \"Robot-do'stim\"",
                "Buyruqlar kartochkalari bilan yo'l chizish",
                "Labirintdan chiqish o'yini (qog'ozda)",
                "Chapga-o'ngga, oldinga-orqaga tushunchalari",
                "Xato buyruqni topish o'yini",
                "Guruh bilan \"robot yurishi\" o'yini",
                "Mexanizm nima? G'ildirak va o'q",
                "Tishli g'ildirakni aylantirib ko'ramiz",
                "Shkiv va tasma bilan tanishuv",
                "Richag: og'ir narsani ko'tarish o'yini",
                "Aylanuvchi karusel modelini yig'ish",
                "Harakatlanuvchi mashina shassisini yig'ish",
                "Motor nima? Motorli qutichani ko'ramiz (namoyish)",
                "Motorsiz va motorli modelni solishtirish",
                "Motorli aravachani yig'ish (o'qituvchi yordamida)",
                "Modelni namoyish qilish",
            ],
            "nazorat": "2-chorak nazorat ishi: mexanizm nomlarini bilish va yo'nalish tushunchalari",
            "loyiha": "2-chorak loyihasi: mening aravacham",
        },
        {
            "nomi": "M3. Birinchi jonli robot",
            "jihoz": MAKERZOID,
            "lessons": [
                "Host controller bilan tanishuv (asosiy blok)",
                "Motorni controllerga ulash",
                "Ilovani ochish: birinchi qadamlar",
                "Rangli tugmalar bilan robotni yurgizish (ilovada)",
                "Robotni to'xtatish va qayta yurgizish",
                "Oldinga-orqaga harakat: ilovada sinab ko'rish",
                "Tezlikni oshirish-pasaytirish (tugma bilan)",
                "Birinchi tayyor modelni yig'amiz: mashinacha",
                "Mashinachani ilova bilan boshqarish",
                "Ikkinchi model: aylanuvchi yulduzcha",
                "Yulduzchani ilovada aylantirish",
                "Musiqa/tovush tugmasini sinab ko'rish",
                "Rangli chiroqni yoqish (agar controllerda bo'lsa)",
                "O'z modelimni tanlab yig'ish (tayyor namunalardan)",
                "Modelimni ilovada boshqarish",
                "Juftlikda ishlash: bir-birining modelini sinash",
                "Kichik ko'rgazma: \"mening robotim yuradi!\"",
            ],
            "nazorat": "3-chorak nazorat ishi: controllerni ulash va ilovada boshqarish",
            "loyiha": "3-chorak loyihasi: yuradigan robotimni yasayman",
        },
        {
            "nomi": "M4. Sensor va yakuniy loyiha",
            "jihoz": MAKERZOID,
            "lessons": [
                "Sensor nima? Ko'z va qo'l bilan solishtirish",
                "Sensorni controllerga ulash",
                "Sensorga qo'l yaqinlashtirib sinash",
                "\"To'xta-yur\" o'yini sensor bilan",
                "Sensorli darvoza modelini yig'ish",
                "Darvozani sensor bilan ochish-yopish",
                "Sensorli hayvon modeli (masalan quyon)",
                "Hayvonni \"uyg'otish\" — sensor bilan",
                "Tayyor loyiha g'oyalarini ko'rib chiqamiz",
                "Loyiha uchun model tanlash",
                "Loyihani qurish — 1-qadam",
                "Loyihani qurish — 2-qadam",
                "Controller va sensorni ulash",
                "Ilovada dasturni sozlash",
                "Sinash va xatolarni tuzatish",
                "Taqdimotga tayyorgarlik: nima deymiz?",
                "Yakuniy mashq: robotni oxirgi marta sinash",
            ],
            "nazorat": "4-chorak nazorat ishi: yil davomida o'rganilganlarni umumlashtirish (og'zaki-amaliy)",
            "loyiha": "4-chorak yakuniy loyihasi: ota-onalar oldida ko'rgazma — mening birinchi robotim",
        },
    ],
}

# ---------- 1-SINF ----------
sinf1 = {
    "platforma": MAKERZOID,
    "quarters": [
        {
            "nomi": "M1. Kirish va algoritmik tafakkur",
            "jihoz": MAKERZOID,
            "lessons": [
                "Tanishuv: Robot nima? Zamonaviy robotlar",
                "Xavfsizlik qoidalari va ish tartibi",
                "Algoritm nima? Kundalik algoritmlar",
                "Ketma-ketlik o'yinlari (ekransiz)",
                "Buyruqlar bilan boshqarish: \"robot-o'qituvchi\"",
                "Labirintdan chiqish: qog'ozda algoritm",
                "Xatolarni topish o'yinlari",
                "Jamoaviy algoritm o'yini",
                "Makerzoid to'plami bilan tanishuv, detallar nomlari",
                "Mustahkam qurish qoidalari",
                "Baland minora tanlovi",
                "Ko'prik qurish",
                "Tishli g'ildiraklar bilan tanishuv",
                "Katta-kichik tishli: tezlik o'zgarishi",
                "Shkiv va tasma",
                "Richag va uning kuchi",
                "G'ildirak va o'q: arava qurish",
            ],
            "nazorat": "1-chorak nazorat ishi: algoritm va mexanizm asoslari",
            "loyiha": "1-chorak loyihasi: o'z arava modelim",
        },
        {
            "nomi": "M2. Birinchi jonli robot (motor)",
            "jihoz": MAKERZOID,
            "lessons": [
                "Host controller va motor bilan tanishuv",
                "Motorni modelga ulash",
                "Ilova bilan birinchi ulanish",
                "Birinchi dastur: motorni yoqish-o'chirish",
                "Aylanuvchi model: karusel",
                "Karuselni ilovada boshqarish",
                "Yelpig'ich modelini yig'ish (model: Gear Shifting Fan)",
                "Yelpig'ichni ikki yo'nalishda aylantirish",
                "Motor tezligini o'zgartirish",
                "Mashina shassisini yig'ish",
                "Mashinani yurgizish: oldinga-orqaga",
                "Mashinani to'xtatish dasturlari",
                "Tovush effekti qo'shish",
                "Ekranda rang va raqam ko'rsatish",
                "Takrorlash bloki (sikl) bilan tanishuv",
                "Sikl bilan raqsga tushuvchi robot (model: Dancing Man)",
                "O'z robotim: erkin qurish va dasturlash",
            ],
            "nazorat": "2-chorak nazorat ishi: motor va oddiy dasturlash",
            "loyiha": "2-chorak loyihasi: raqsga tushuvchi robotim",
        },
        {
            "nomi": "M3. Sensorlar dunyosi",
            "jihoz": MAKERZOID,
            "lessons": [
                "Sensor nima? Harakat sensori bilan tanishuv",
                "Harakat sensori: qo'l yaqinlashsa to'xta",
                "Sezgir darvoza modeli (model: Automatic Gate)",
                "Og'ish sensori bilan tanishuv",
                "Og'ish sensori: qiyalikda signal",
                "Mashina: to'siqni sezib to'xtash",
                "Ovozli signalli qo'riqchi",
                "Sensorli hayvon: gorilla",
                "Sensorli hayvon: qurbaqa",
                "Ikkala holatni birlashtirish: harakat+ovoz",
                "Mini-loyiha: aqlli o'yinchoq (qurish)",
                "Mini-loyiha: dasturlash",
                "Sensor xatolarini tuzatish",
                "Sensorli modelni yaxshilash",
                "Juftlikda ishlash: sensorli o'yin",
                "Namoyish va muhokama",
                "Sensorlar bo'yicha takrorlash",
            ],
            "nazorat": "3-chorak nazorat ishi: sensorlar va ularning qo'llanilishi",
            "loyiha": "3-chorak loyihasi: aqlli qo'riqchi robotim",
        },
        {
            "nomi": "M4. Yakuniy loyiha",
            "jihoz": MAKERZOID,
            "lessons": [
                "Loyiha g'oyasini tanlash",
                "Reja va eskiz chizish",
                "Kerakli detallarni tanlash",
                "Qurish — asos qismi",
                "Qurish — harakatlanuvchi qism",
                "Motorni ulash",
                "Sensorni ulash",
                "Dasturlash — asosiy harakatlar",
                "Dasturlash — sensor reaksiyasi",
                "Sinash — 1-urinish",
                "Xatolarni tuzatish",
                "Sinash — 2-urinish",
                "Modelni bezash va yakunlash",
                "Taqdimot matnini tayyorlash",
                "Repetitsiya: taqdimotni sinab ko'rish",
                "Yakuniy sozlashlar",
                "Umumiy takrorlash: yil davomida nimalarni o'rgandik",
            ],
            "nazorat": "4-chorak (yakuniy) nazorat ishi: yil bo'yicha umumiy bilim",
            "loyiha": "4-chorak yakuniy loyihasi: ota-onalar oldida ko'rgazma",
        },
    ],
}

# ---------- 2-SINF ----------
sinf2 = {
    "platforma": MAKERZOID,
    "quarters": [
        {
            "nomi": "M1. Takrorlash va mexanizmlar chuqur",
            "jihoz": MAKERZOID,
            "lessons": [
                "Kirish: o'tgan yilni eslaymiz, xavfsizlik",
                "Algoritmlar: blok-sxema bilan tanishuv",
                "Tezkor qurish tanlovi",
                "Ilova: eslab qolganlarimiz",
                "Dastur o'qish: bu dastur nima qiladi?",
                "Tishli g'ildiraklar: tezlik va kuch",
                "Ikki tishlini ulash: uzatma nisbati",
                "Shkiv tizimi: kuchni oshirish",
                "Richagli mexanizm: og'ir yukni ko'tarish",
                "Krivoship-shatun mexanizmi bilan tanishuv",
                "Ekskavator qo'lini yig'ish (model: Excavator, Gear-driven)",
                "Kranni yig'ish (model: Crane)",
                "Konveyer modelini yig'ish (model: Conveyor)",
                "Qulf mexanizmi (eshik ochish-yopish) (model: Rail Gate)",
                "Murakkab arava: 4 g'ildirakli",
                "Mexanizmlar bo'yicha viktorina-o'yin",
                "Eng yaxshi mexanizm tanlovi",
            ],
            "nazorat": "1-chorak nazorat ishi: mexanizmlar (tishli, shkiv, richag)",
            "loyiha": "1-chorak loyihasi: yuk ko'taruvchi kran",
        },
        {
            "nomi": "M2. Dasturlash chuqur",
            "jihoz": MAKERZOID,
            "lessons": [
                "Motor va controller: takrorlash",
                "Shart (agar...bo'lsa) tushunchasi",
                "Shart bilan oddiy o'yin",
                "Sikl (takrorlash) chuqurroq",
                "Sikl ichida shart: murakkab dastur",
                "O'zgaruvchi nima? Hisoblagich yaratish",
                "Hisoblagich bilan o'yin: necha marta aylandi?",
                "Ikki harakatni ketma-ket bajarish",
                "Parallel harakatlar: motor+tovush",
                "Vaqt bo'yicha boshqarish (timer)",
                "Taymer bilan soat-robot",
                "Tugmalar orqali boshqaruv menyusi",
                "Xato dasturni topib tuzatish (debugging)",
                "Debugging o'yini: kim tezroq topadi",
                "Murakkab mashina dasturi",
                "Mashinani masofadan (ilova) boshqarish",
                "Dasturlash bo'yicha yakuniy mashq",
            ],
            "nazorat": "2-chorak nazorat ishi: shart, sikl, o'zgaruvchi",
            "loyiha": "2-chorak loyihasi: aqlli soat-robot",
        },
        {
            "nomi": "M3. Sensorli aqlli modellar",
            "jihoz": MAKERZOID,
            "lessons": [
                "Sensor turlarini eslaymiz",
                "Sensor + shart: aqlli reaksiya",
                "To'siqdan qochuvchi mashina — 1-qadam (model: Obstacle Avoiding Car)",
                "To'siqdan qochuvchi mashina — dasturlash (model: Obstacle Avoiding Car)",
                "Chiziq bo'ylab harakat (model: Line Patrol Tank)",
                "Chiziqni \"sezish\" o'yini (model: Line Patrol Dog)",
                "Sensorli svetofor modeli",
                "Svetofor: ranglarni almashtirish dasturi",
                "Sensorli signalizatsiya (uy qo'riqchisi) (model: Score Indicator)",
                "Signalizatsiyani sozlash",
                "Sensor+motor+tovush: to'liq reaksiya",
                "Aqlli hayvon modeli: ovqat \"sezadi\" (model: Little Bear)",
                "Ikki xil sensor stsenariysi bilan o'ynash",
                "Guruh loyihasi: aqlli shahar elementi",
                "Guruh loyihasi: dasturlash",
                "Guruh loyihasini sinash",
                "Sensorli modellar bo'yicha takrorlash",
            ],
            "nazorat": "3-chorak nazorat ishi: sensor+shart kombinatsiyalari",
            "loyiha": "3-chorak loyihasi: aqlli uy qo'riqchisi",
        },
        {
            "nomi": "M4. Yakuniy loyiha",
            "jihoz": MAKERZOID,
            "lessons": [
                "Loyiha mavzusini tanlash (murakkabroq)",
                "Texnik topshiriq yozish (oddiy reja)",
                "Eskiz va konstruksiya rejasi",
                "Asosiy qismni qurish",
                "Harakatlanuvchi qismni qurish",
                "Motor va sensorni joylashtirish",
                "Asosiy dastur tuzish",
                "Shart va sikl qo'shish",
                "1-sinov va kuzatish",
                "Xatolarni ro'yxatga olish",
                "Xatolarni tuzatish",
                "2-sinov",
                "Dizaynni yaxshilash (bezash)",
                "Taqdimot uchun tayyorgarlik",
                "Repetitsiya",
                "Yakuniy tuzatishlar",
                "Yil davomida o'rganilganlarni umumlashtirish",
            ],
            "nazorat": "4-chorak (yakuniy) nazorat ishi",
            "loyiha": "4-chorak yakuniy loyihasi: ko'rgazma va taqdimot",
        },
    ],
}

# ---------- 3-SINF ----------
sinf3 = {
    "platforma": MAKERZOID,
    "quarters": [
        {
            "nomi": "M1. Chuqur mexanika va murakkab qurilish",
            "jihoz": MAKERZOID,
            "lessons": [
                "Kirish: yangi imkoniyatlar, xavfsizlik",
                "Murakkab birikmalar: burchakli ulanishlar",
                "Differensial mexanizm bilan tanishuv (tushuncha darajasida)",
                "Ikki tishli tizim: murakkab uzatma",
                "Uch bosqichli mexanizm (richag+shkiv+tishli)",
                "Robot-qo'l (manipulyator) asoslari (model: Eggbeater)",
                "Manipulyatorni yig'ish — 1-qadam",
                "Manipulyatorni yig'ish — 2-qadam",
                "Og'irlikni ko'tarish sinovi",
                "Muvozanat: robotning barqarorligi",
                "Rezina g'ildirak vs boshqa g'ildirak: tortishish kuchi",
                "Sur'at (tezlik) va kuch nisbati",
                "Murakkab transport modeli",
                "Transport modelini mustahkamlash",
                "Guruh muhokamasi: eng yaxshi konstruksiya",
                "Konstruksiya tanlovi",
                "Mexanika bo'yicha yakuniy mashq",
            ],
            "nazorat": "1-chorak nazorat ishi: murakkab mexanizmlar",
            "loyiha": "1-chorak loyihasi: robot-manipulyator",
        },
        {
            "nomi": "M2. Dasturlash: o'zgaruvchi va funksiyalar",
            "jihoz": MAKERZOID,
            "lessons": [
                "O'tgan yilni eslaymiz: shart va sikl",
                "Ichma-ich sikllar (nested loop)",
                "Ichma-ich sikl bilan naqsh yasash (harakat naqshi)",
                "Funksiya (blok guruhi) tushunchasi",
                "O'z funksiyamni yarataman",
                "Funksiyalardan qayta foydalanish",
                "Murakkab shartlar: VA, YOKI",
                "Mantiqiy o'yin: VA/YOKI bilan",
                "Hisoblagich + shart: ball tizimi",
                "O'yin yarataman: ball to'plash roboti",
                "Vaqt boshqaruvi: ketma-ket vazifalar",
                "Ko'p qadamli dastur: robot-kuryer (model: Telecar)",
                "Kuryer-robot marshrutini dasturlash",
                "Xatolarni tizimli qidirish (debugging usullari)",
                "Dasturni optimallashtirish: qisqartiramiz",
                "Juftlikda dastur almashish va tekshirish",
                "Dasturlash bo'yicha yakuniy mashq",
            ],
            "nazorat": "2-chorak nazorat ishi: funksiyalar va murakkab shartlar",
            "loyiha": "2-chorak loyihasi: kuryer-robot",
        },
        {
            "nomi": "M3. Kengaytirilgan sensorika",
            "jihoz": MAKERZOID_PLUS,
            "lessons": [
                "Qo'shimcha sensor bilan tanishuv (agar mavjud)",
                "Ikki sensorni birga ulash",
                "Ikki sensorli qaror qabul qilish dasturi",
                "To'siqdan qochish + chiziq kuzatish (model: Line Patrol Dragon)",
                "Ikki motorli harakat asoslari (agar qo'shimcha motor mavjud)",
                "Ikki motor: burilish mantig'i",
                "Kvadrat/uchburchak yo'nalishda yurish dasturi",
                "Labirintdan avtomatik chiqish — reja (model: Mine Clearance)",
                "Labirint dasturi — 1-qadam",
                "Labirint dasturi — 2-qadam va sinov",
                "Musobaqa formatida sinov: kim tezroq",
                "Musobaqa qoidalarini tushunish (kichik FLL uslubida)",
                "Jamoa bilan strategiya tuzish",
                "Robotni musobaqa uchun sozlash",
                "Ichki musobaqa-mashq 1",
                "Ichki musobaqa-mashq 2",
                "Musobaqa bo'yicha xulosalar",
            ],
            "nazorat": "3-chorak nazorat ishi: kombinatsiyalangan sensor/motor mantig'i",
            "loyiha": "3-chorak loyihasi: labirint-yechuvchi robot",
        },
        {
            "nomi": "M4. Yakuniy ijodiy loyiha",
            "jihoz": MAKERZOID_PLUS,
            "lessons": [
                "Erkin mavzu tanlash (o'z g'oyasi)",
                "Loyiha texnik topshirig'ini yozish",
                "Konstruksiya eskizi",
                "Dastur arxitekturasi rejasi (qanday funksiyalar kerak)",
                "Asosiy qurilish — 1",
                "Asosiy qurilish — 2",
                "Elektronikani ulash (motor+sensor(lar))",
                "Asosiy dasturni yozish",
                "Funksiyalarni qo'shish",
                "1-sinov va kuzatuv jurnali",
                "Muammolarni tahlil qilish",
                "Tuzatish va yaxshilash",
                "2-sinov",
                "Dizayn va bezak",
                "Taqdimot slaydlarini (yoki plakat) tayyorlash",
                "Repetitsiya va fikr-mulohaza",
                "Yil yakuni: nimalarni o'rgandik, keyingi yil (SPIKE) haqida qisqacha",
            ],
            "nazorat": "4-chorak (yakuniy) nazorat ishi",
            "loyiha": "4-chorak yakuniy loyihasi: ijodiy robot — ota-onalar ko'rgazmasi",
        },
    ],
}

# ---------- 4-SINF (1-yil, Makerzoid) ----------
sinf4_y1 = {
    "platforma": MAKERZOID,
    "quarters": [
        {
            "nomi": "M1. Muhandislik dizayni va murakkab konstruksiyalar",
            "jihoz": MAKERZOID_PLUS,
            "lessons": [
                "Kirish: 4-sinf maqsadlari, xavfsizlik",
                "Muhandislik dizayni jarayoni (5 bosqich): tanishuv",
                "Muammoni aniqlash mashqi",
                "G'oyalar generatsiyasi (brainstorm) mashqi",
                "Eng murakkab mexanizm: differensial+richag",
                "Ko'p bosqichli uzatma tizimi",
                "Og'ir yuk tashish roboti — dizayn (model: Fork Lift Truck)",
                "Og'ir yuk tashish roboti — qurish (model: Fork Lift Truck)",
                "Barqarorlik va muvozanat testi",
                "Tezlik vs kuch: optimallashtirish",
                "Modulli konstruksiya: qismlarni almashtirish imkoniyati",
                "Modulli robotni yig'ish",
                "Turnir maydonchasi tushunchasi (competition field)",
                "Maydoncha elementlarini o'rganish",
                "Robotni maydonchada sinash",
                "Dizaynni takomillashtirish",
                "Chorak yakuni: eng yaxshi konstruksiya tanlovi",
            ],
            "nazorat": "1-chorak nazorat ishi: muhandislik dizayni jarayoni",
            "loyiha": "1-chorak loyihasi: yuk tashuvchi murakkab robot",
        },
        {
            "nomi": "M2. Ilg'or dasturlash va avtomatlashtirish",
            "jihoz": MAKERZOID_PLUS,
            "lessons": [
                "O'tgan yillarni eslaymiz: funksiyalar, shartlar",
                "Holat mashinasi (state machine) tushunchasi — sodda",
                "Holatlar bilan o'yin: yorug'lik-navbat",
                "Ko'p sensorli qaror daraxti",
                "Qaror daraxti dasturi — 1",
                "Qaror daraxti dasturi — 2 va sinov",
                "Xato-bardosh dastur: agar sensor ishlamasa nima bo'ladi?",
                "Zaxira stsenariy qo'shish",
                "Dasturni bo'laklarga bo'lib sinash (modul test)",
                "Jamoaviy dasturlash: rol taqsimoti",
                "Versiya nazorati tushunchasi (oddiy: \"v1, v2\" saqlash)",
                "Murakkab avtomatik robot — reja (model: Patrol Car)",
                "Avtomatik robot — dasturlash 1",
                "Avtomatik robot — dasturlash 2",
                "To'liq avtonom sinov (odam aralashuvisiz)",
                "Natijalarni tahlil qilish",
                "Dasturlash bo'yicha yakuniy mashq",
            ],
            "nazorat": "2-chorak nazorat ishi: holat mashinasi va avtonom dasturlash",
            "loyiha": "2-chorak loyihasi: to'liq avtonom robot",
        },
        {
            "nomi": "M3. Musobaqa tayyorgarligi",
            "jihoz": MAKERZOID_PLUS,
            "lessons": [
                "Robotika musobaqalari haqida (FLL va boshqalar)",
                "Musobaqa qoidalarini tahlil qilish (namunaviy)",
                "Jamoa strategiyasini ishlab chiqish",
                "Vazifalarni bosqichlarga bo'lish",
                "1-vazifa uchun robot sozlash",
                "1-vazifa dasturi",
                "2-vazifa uchun robot sozlash",
                "2-vazifa dasturi",
                "Vazifalar orasida tezkor almashtirish (attachment tizimi)",
                "Vaqt boshqaruvi: musobaqa formatida mashq",
                "Ichki mashq-musobaqa — 1-tur",
                "Natijalarni tahlil qilish, xatolarni tuzatish",
                "Ichki mashq-musobaqa — 2-tur",
                "Jamoaviy fikr-mulohaza (retrospektiva)",
                "Robotni yakuniy sozlash",
                "Taqdimot/portfolio tayyorlash (muhandislik daftari)",
                "Musobaqa bo'yicha yakuniy tayyorgarlik",
            ],
            "nazorat": "3-chorak nazorat ishi: musobaqa qoidalari va strategiya",
            "loyiha": "3-chorak loyihasi: musobaqa roboti (ichki turnir)",
        },
        {
            "nomi": "M4. Yakuniy loyiha va SPIKE'ga tayyorgarlik",
            "jihoz": MAKERZOID_PLUS,
            "lessons": [
                "Yil davomidagi eng yaxshi loyihalarni ko'rib chiqish",
                "Yakuniy loyiha mavzusini tanlash (erkin)",
                "To'liq texnik topshiriq yozish",
                "Dizayn va eskiz",
                "Qurilish — 1",
                "Qurilish — 2",
                "Elektronika va sensorlarni joylashtirish",
                "To'liq dasturni yozish — 1",
                "To'liq dasturni yozish — 2",
                "Sinov va debugging — 1",
                "Sinov va debugging — 2",
                "Dizaynni yakunlash",
                "SPIKE Prime bilan tanishuv (video/rasm, taqqoslash)",
                "Blok-dasturlash mantig'i: Makerzoid va SPIKE o'xshashligi",
                "Taqdimotga tayyorgarlik",
                "Repetitsiya",
                "Ikki yillik yakun: nimalarni o'rgandik, oldinda nima kutmoqda",
            ],
            "nazorat": "4-chorak (yakuniy) nazorat ishi: 4-sinf bo'yicha umumiy bilim",
            "loyiha": "4-chorak yakuniy loyihasi va bitiruv ko'rgazmasi (0-4-sinf Makerzoid bosqichi yakuni)",
        },
    ],
}

# ---------- 4-SINF (2-yil, SPIKE Prime) — rasmiy LEGO Education modellari asosida ----------
# Manba: LEGO Education rasmiy sayti (education.lego.com) — "Driving Base", "StarterBot", "Robot Arm",
# "Invention Squad", "Life Hacks", "Kickstart a Business" birlik nomlari; primelessons.org / pybricks.com
# orqali tasdiqlangan qo'shimcha qurilma (attachment) nomlari.
sinf4_y2_spike = {
    "platforma": SPIKE,
    "quarters": [
        {
            "nomi": "M1. Qurish asoslari (LEGO rasmiy modellari) — dasturlashsiz",
            "jihoz": SPIKE,
            "lessons": [
                "SPIKE Prime to'plami bilan tanishuv: qismlar, xavfsizlik",
                "Driving Base 1 — yig'ish (1 darslik)",
                "Driving Base 2 — yig'ish (1 darslik)",
                "Driving Base 3 (Advanced Driving Base) — yig'ish (1 darslik)",
                "StarterBot — yig'ish (1 darslik)",
                "Robot Arm (robot-qo'l) — yig'ish (1 darslik)",
                "Line Follower attachment — yig'ish (1 darslik)",
                "Ultrasonic sensor mount — yig'ish (1 darslik)",
                "Color sensor mount — yig'ish (1 darslik)",
                "Bumper attachment (to'siq sezuvchi) — yig'ish (1 darslik)",
                "Gripper (ushlagich) attachment — yig'ish (1 darslik)",
                "Tractor — yig'ish (1 darslik)",
                "Catapult attachment — yig'ish (1 darslik)",
                "Plow attachment (belkurak) — yig'ish (1 darslik)",
                "Scoop attachment (cho'mich) — yig'ish (1 darslik)",
                "Fork-lift attachment — yig'ish (1 darslik)",
                "Ball Shooter attachment — yig'ish (1 darslik)",
                "Kriket (box robot) — yig'ish (1 darslik)",
                "Sensor arm attachment — yig'ish (1 darslik)",
            ],
            "nazorat": "1-chorak nazorat ishi: Driving Base va 2 attachmentni tanlab, ishlash tamoyilini tushuntirish",
            "loyiha": "1-chorak loyihasi: o'z Driving Base + tanlagan attachmentlar kombinatsiyasi (erkin)",
        },
        {
            "nomi": "M2. Sensorlar va birinchi dasturlar",
            "jihoz": SPIKE,
            "lessons": [
                "Rang sensori bilan tanishuv",
                "Rangni aniqlash dasturi",
                "Line Follower — dasturlash nazariyasi",
                "Line Follower — dasturlash 1",
                "Line Follower — dasturlash 2 va sinov",
                "Ultrasonic sensor — dasturlash",
                "Bumper attachment — to'siqni sezib to'xtash dasturi",
                "Gripper — ushlab olish dasturi",
                "Kuch (bosim) sensori bilan ishlash",
                "Gyroskopik sensor bilan aniq burilish",
                "Bir nechta sensorni birlashtirish",
                "Qaror qabul qilish dasturi (agar...aks holda)",
                "Sensorlar bo'yicha amaliy mashq — 1",
                "Sensorlar bo'yicha amaliy mashq — 2",
                "Kichik loyiha: aqlli parking robot",
                "Loyihani dasturlash va sinash",
                "Chorak yakuni: sensorlar bo'yicha takrorlash",
                "Touch sensor bilan ishlash",
                "Kombinatsiyalangan attachment sinovi",
            ],
            "nazorat": "2-chorak nazorat ishi: SPIKE sensorlari va reaktiv dastur",
            "loyiha": "2-chorak loyihasi: aqlli parking robot",
        },
        {
            "nomi": "M3. Missiya 1 va 2 (LEGO Education FLL uslubi)",
            "jihoz": SPIKE,
            "lessons": [
                "FLL / musobaqa maydonchasi bilan tanishuv",
                "Missiya nima? Ball tizimi bilan tanishuv",
                "Missiya 1 — Yuk tashish: vazifa tahlili va reja",
                "Missiya 1 — Yuk tashish: attachment dizayni",
                "Missiya 1 — Yuk tashish: attachment yig'ish",
                "Missiya 1 — Yuk tashish: dasturlash",
                "Missiya 1 — Yuk tashish: sinov va tuzatish",
                "Missiya 1 — Yuk tashish: yakuniy sinov (ballga qo'yiladi)",
                "Missiya 2 — Chiziq bo'ylab yetkazish: vazifa tahlili va reja",
                "Missiya 2 — Chiziq bo'ylab yetkazish: attachment dizayni",
                "Missiya 2 — Chiziq bo'ylab yetkazish: attachment yig'ish",
                "Missiya 2 — Chiziq bo'ylab yetkazish: dasturlash",
                "Missiya 2 — Chiziq bo'ylab yetkazish: sinov va tuzatish",
                "Missiya 2 — Chiziq bo'ylab yetkazish: yakuniy sinov (ballga qo'yiladi)",
                "Ikki missiyani ketma-ket bajarish dasturi",
                "Attachment tez almashtirish mashqi",
                "Jamoa bilan mashq-turnir — 1-tur",
                "Natijalarni tahlil qilish",
                "Chorak yakuni: 1-2 missiya bo'yicha umumiy ko'rik",
            ],
            "nazorat": (
                "3-chorak nazorat ishi — Missiya musobaqasi: 1 va 2-missiya ketma-ket bajariladi, "
                "har biri muvaffaqiyatli bajarilsa 25 balldan (jami 50 ball). Baholash: 45-50 ball = 5 "
                "(a'lo); 35-44 ball = 4 (yaxshi); 25-34 ball = 3 (qoniqarli); 15-24 ball = 2 "
                "(qoniqarsiz); 15 balldan kam = FAILED."
            ),
            "loyiha": "3-chorak loyihasi: 1-2-missiya uchun mukammal robot+attachment yechimi",
        },
        {
            "nomi": "M4. Missiya 3, 4 va yakuniy turnir (Kickstart a Business uslubida)",
            "jihoz": SPIKE,
            "lessons": [
                "Missiya 3 — To'siqli yo'l va richag: vazifa tahlili va reja",
                "Missiya 3 — To'siqli yo'l va richag: attachment dizayni",
                "Missiya 3 — To'siqli yo'l va richag: attachment yig'ish",
                "Missiya 3 — To'siqli yo'l va richag: dasturlash",
                "Missiya 3 — To'siqli yo'l va richag: sinov va tuzatish",
                "Missiya 3 — To'siqli yo'l va richag: yakuniy sinov (ballga qo'yiladi)",
                "Missiya 4 — Aqlli saralash va ko'tarish: vazifa tahlili va reja",
                "Missiya 4 — Aqlli saralash va ko'tarish: attachment dizayni",
                "Missiya 4 — Aqlli saralash va ko'tarish: attachment yig'ish",
                "Missiya 4 — Aqlli saralash va ko'tarish: dasturlash",
                "Missiya 4 — Aqlli saralash va ko'tarish: sinov va tuzatish",
                "Missiya 4 — Aqlli saralash va ko'tarish: yakuniy sinov (ballga qo'yiladi)",
                "Barcha 4 missiyani ketma-ket bajarish dasturi",
                "Vaqt boshqaruvi: 2.5 daqiqalik to'liq missiya turi mashqi",
                "Muhandislik daftarini (Inventor Notebook) yakunlash",
                "Jamoaviy prezentatsiya tayyorlash",
                "Yakuniy repetitsiya",
                "Ichki bitiruv turniri — barcha 4 missiya",
                "Ota-onalar uchun ochiq ko'rgazma va natijalar e'loni",
            ],
            "nazorat": (
                "4-chorak (yakuniy) nazorat ishi — To'liq missiya turi (FLL formatida): barcha 4 "
                "missiya 2.5 daqiqada bajariladi, har biri 25 balldan (jami 100 ball). Baholash: "
                "85-100 ball = 5 (a'lo); 65-84 ball = 4 (yaxshi); 45-64 ball = 3 (qoniqarli); "
                "25-44 ball = 2 (qoniqarsiz); 25 balldan kam = FAILED."
            ),
            "loyiha": "4-chorak yakuniy loyihasi: to'liq 4-missiyali bitiruv musobaqasi (ochiq turnir)",
        },
    ],
}

from year1_generator import ALL_GRADES_Y1_NEW

ALL_GRADES_Y1 = ALL_GRADES_Y1_NEW

GRADE4_Y2 = sinf4_y2_spike
