# -*- coding: utf-8 -*-
"""2-yil, 7-sinf — ESP32 va sun'iy intellekt (TinyML)."""

from kb_5_8 import T

MAVZULAR = {

# ==================================================== 1-CHORAK: ESP32 platformasi
"ESP32 arxitekturasi va Arduino'dan farqi": T(
 "Ikki platani yonma-yon qo'yib, imkoniyatlarini jadvalga solishtirish",
 ["ESP32: ikki yadroli 240 MHz protsessor, 520 KB SRAM, 4 MB flesh, WiFi va Bluetooth o'rnatilgan.",
  "Arduino Uno: bir yadroli 16 MHz, 2 KB SRAM, 32 KB flesh, simsiz aloqa yo'q.",
  "Ya'ni ESP32 protsessor tezligi bo'yicha 15 marta, xotira bo'yicha 260 marta kuchli.",
  "Asosiy farq esa mantiq darajasida: ESP32 3.3 V, Arduino 5 V. Bu barcha sxemalarga ta'sir qiladi."],
 "Solishtirish jadvalini o'quvchilar to'ldirsin. Raqamlar farqni gapirishdan ko'ra ishonarli ko'rsatadi.",
 [("ESP32 da qancha SRAM bor?", "520 kilobayt."),
  ("Ikki plataning mantiq darajasi qanday farq qiladi?", "ESP32 — 3.3 V, Arduino — 5 V.")],
 "Arduino sxemalarini o'zgartirmasdan ESP32 ga ko'chirish."),

"Pinlar xaritasi va 3.3V mantiq": T(
 "Xavfsiz va cheklangan pinlarni ajratib, ish uchun pin ro'yxati tuzish",
 ["Mantiq darajasi 3.3 V. 5 V signalni kirishga berish pinni shikastlaydi.",
  "Cheklangan pinlar: GPIO 6-11 ichki fleshga ulangan — umuman ishlatilmaydi.",
  "GPIO 34-39 faqat kirish: chiqish bo'la olmaydi va ichki tortuvchi rezistori yo'q.",
  "GPIO 0, 2, 12, 15 yuklash jarayoniga ta'sir qiladi — ularga komponent ulansa plata yuklanmasligi mumkin."],
 "\"Xavfsiz pinlar\" ro'yxatini tuzib tarqating (4, 5, 13, 14, 16-19, 21-23, 25-27, 32, 33). Bu chorak davomida eng ko'p ishlatiladigan qog'oz.",
 [("Qaysi pinlar faqat kirish uchun?", "GPIO 34-39."),
  ("GPIO 6-11 nima uchun ishlatilmaydi?", "Ular ichki flesh xotiraga ulangan.")],
 "Boot pinlariga komponent ulash — plata yuklanmaydi va sabab topilmaydi."),

"IDE'ga ESP32 qo'shish va birinchi yuklash": T(
 "ESP32 paketini o'rnatib, birinchi dasturni yuklash",
 ["Preferences > Additional Board Manager URLs ga ESP32 paketi manzili qo'shiladi, keyin Boards Manager dan o'rnatiladi.",
  "Paket katta (~200 MB) — uni oldindan o'rnatib qo'yish kerak.",
  "Plata turi (ESP32 Dev Module) va port tanlanadi. Drayver: CP2102 yoki CH340.",
  "Ba'zi platalarda yuklash boshlanishi uchun BOOT tugmasini bosib turish kerak."],
 "Paketni oldindan barcha kompyuterlarga o'rnating. 200 MB yuklash sinf internetida butun darsni yeb qo'yadi.",
 [("ESP32 paketi qanday o'rnatiladi?", "Board Manager URL qo'shib, keyin Boards Manager orqali."),
  ("Yuklash boshlanmasa nima qilinadi?", "BOOT tugmasi bosib turiladi.")],
 "Paketni dars vaqtida yuklashga urinish."),

"5V va 3.3V mos kelmasligi muammosi": T(
 "5V sensorni ESP32 ga xavfsiz ulash usullarini sinash",
 ["ESP32 kirishiga maksimal 3.3 V. 5 V signal pinni shikastlaydi.",
  "Yechim 1 — kuchlanish bo'luvchi: 1 kOm va 2 kOm. 5 x 2/3 = 3,3 V. Faqat sekin signallar uchun.",
  "Yechim 2 — daraja o'tkazgich moduli: tez signallar va ikki tomonlama aloqa uchun.",
  "Teskari yo'nalish (ESP32 dan 5 V qurilmaga) odatda muammosiz — ko'p 5 V kirishlar 3,3 V ni HIGH deb qabul qiladi."],
 "HC-SR04 ning ECHO pinini namunali holat sifatida ko'rsating va bo'luvchini birgalikda hisoblang.",
 [("Bo'luvchi uchun qanday rezistorlar olinadi?", "Masalan 1 kOm va 2 kOm."),
  ("Qaysi holatda daraja o'tkazgich kerak?", "Tez signallar va ikki tomonlama aloqada.")],
 "5V sensorni to'g'ridan-to'g'ri ESP32 ga ulash."),

"Raqamli kirish va chiqish": T(
 "ESP32 da raqamli kirish-chiqishni sinab, Arduino bilan farqlarni aniqlash",
 ["pinMode, digitalWrite, digitalRead buyruqlari Arduino bilan bir xil.",
  "Chiqish 3.3 V beradi. LED rezistori: (3,3-2)/0,015 = 87 Om, ya'ni 100 Om.",
  "Ko'k va oq LED (3,2 V) 3.3 V da juda xira yonadi — kuchlanish deyarli yetmaydi.",
  "Pin toki: xavfsiz 12 mA, mutlaq chegara 40 mA — Arduino'dagidan kamroq."],
 "Ko'k LED muammosini ko'rsating — bu tushish kuchlanishi mavzusining amaliy oqibati va bog'lanishni yaqqol ko'rsatadi.",
 [("ESP32 chiqishi qancha kuchlanish beradi?", "3.3 V."),
  ("Pindan xavfsiz qancha tok olinadi?", "Taxminan 12 mA.")],
 "Arduino uchun hisoblangan rezistorlarni o'zgartirmasdan ishlatish."),

"ADC: analog o'qish va uning xususiyatlari": T(
 "ADC ni kalibrlab, chiziqsizligini o'lchab, grafik chizish",
 ["ESP32 ADC 12 razryadli: 0-4095 (Arduino da 0-1023).",
  "Kirish diapazoni 0-3.3 V, lekin standart sozlamada ishonchli o'lchov 0,15-2,45 V oralig'ida.",
  "ADC CHIZIQSIZ, ayniqsa chekka qiymatlarda. Aniq o'lchov uchun kalibrlash yoki tuzatish jadvali kerak.",
  "ADC2 kanallari (GPIO 0, 2, 4, 12-15, 25-27) WiFi yoqilganda ISHLAMAYDI. WiFi bilan faqat ADC1 (GPIO 32-39)."],
 "ADC2 va WiFi to'qnashuvi — bu chorakning eng ko'p vaqt yeydigan sirli nosozligi. Xavfsiz pinlar ro'yxatiga yozib qo'ying.",
 [("ESP32 ADC qanday oraliq beradi?", "0 dan 4095 gacha."),
  ("WiFi yoqilganda qaysi kanallar ishlamaydi?", "ADC2 kanallari.")],
 "WiFi bilan birga ADC2 pinini ishlatish — qiymat doim 0 chiqadi."),

"PWM (LEDC) kanallari": T(
 "LEDC bilan bir necha mustaqil PWM kanalini sozlab ishlatish",
 ["ESP32 da 16 ta mustaqil LEDC kanali bor, har biriga o'z chastotasi va razryadi beriladi.",
  "Sozlash: ledcSetup(kanal, chastota, razryad); ledcAttachPin(pin, kanal); ledcWrite(kanal, qiymat);",
  "Razryad 8 bo'lsa 0-255, 10 bo'lsa 0-1023, 12 bo'lsa 0-4095. Yuqori razryad silliqroq boshqaruv.",
  "Chastota va razryad o'zaro bog'liq: yuqori chastotada yuqori razryadga imkon bo'lmasligi mumkin."],
 "Chastota va razryad bog'liqligini sinab ko'rsating — juda yuqori chastotada razryad avtomatik kamayadi. Bu apparat cheklovi.",
 [("ESP32 da nechta PWM kanali bor?", "16 ta."),
  ("12 razryadli PWM da qiymat oralig'i qanday?", "0 dan 4095 gacha.")],
 "Bir kanalni bir necha pinga bog'lab, mustaqil boshqarmoqchi bo'lish."),

"Touch (sensorli) pinlar": T(
 "Sensorli pinlarni sinab, sezgirlik chegarasini aniqlash",
 ["ESP32 da 10 ta sig'imli sensorli pin bor (T0-T9). Ular barmoq tegishini sig'im o'zgarishi orqali sezadi.",
  "touchRead(pin) qiymat qaytaradi: tegilmaganda katta (masalan 70), tegilganda kichik (masalan 20).",
  "Chegara har muhitda farq qiladi — namlik, sim uzunligi va yaqindagi metall ta'sir qiladi. Kalibrlash shart.",
  "Sensorli tugma mexanik tugmadan afzal: harakatlanuvchi qismi yo'q, yeyilmaydi va suv o'tkazmaydigan korpus ostidan ishlaydi."],
 "Sensorli pinni folga yoki metall buyumga ulab kengaytirib ko'rsating — bu sensorli panel yasashning oddiy usuli va juda qiziq.",
 [("touchRead tegilganda qanday qiymat beradi?", "Kichikroq qiymat."),
  ("Sensorli tugmaning afzalligi nima?", "Harakatlanuvchi qismi yo'q, yeyilmaydi.")],
 "Kalibrlashsiz tayyor chegara ishlatish — u boshqa sharoitda ishlamaydi."),

"Hall datchigi (plata ichida)": T(
 "Plata ichidagi Hall datchigini magnit bilan sinab, sezgirligini o'lchash",
 ["ESP32 chipida o'rnatilgan Hall datchigi bor — u magnit maydonni sezadi.",
  "hallRead() qiymat qaytaradi. Magnit yo'q bo'lganda qiymat nolga yaqin, magnit yaqinlashsa musbat yoki manfiy tomonga siljiydi.",
  "Sezgirligi past va shovqinli — bir necha o'lchov o'rtachasi olinishi kerak.",
  "Amaliy foydasi cheklangan: tashqi Hall moduli ancha sezgir. Lekin u ESP32 ning integratsiya darajasini ko'rsatadi."],
 "Ichki datchikning cheklovlarini ochiq ayting — har imkoniyat amaliy foydali bo'lavermaydi va buni baholay olish muhandislik ko'nikmasi.",
 [("hallRead nimani o'lchaydi?", "Chip ichidagi magnit maydon datchigi qiymatini."),
  ("Uning kamchiligi nima?", "Sezgirligi past va shovqinli.")],
 "Ichki Hall datchigidan aniq o'lchov kutish."),

"I2C: bir nechta qurilmani ulash": T(
 "I2C skaner bilan bir necha modulni bir shinaga ulab, manzillarini aniqlash",
 ["I2C ikki sim: SDA (GPIO21) va SCL (GPIO22). Tortuvchi rezistorlar modullarda odatda o'rnatilgan.",
  "Har qurilmaning 7 bitli manzili bor. Bir shinada 100 dan ortiq qurilma bo'lishi mumkin.",
  "Bir xil manzilli ikki qurilma konflikt yaratadi. Ko'p modullarda manzilni jamper bilan o'zgartirish mumkin.",
  "I2C skaner dasturi shinadagi barcha qurilmalarni topib, manzillarini ko'rsatadi."],
 "I2C skanerni har o'quvchida saqlab qo'ying — bu barcha I2C modullari bilan ishlashda birinchi qadam.",
 [("I2C nechta sim ishlatadi?", "Ikkita: SDA va SCL."),
  ("Bir xil manzilli ikki qurilma ulansa nima bo'ladi?", "Konflikt — ikkalasi ishlamaydi.")],
 "Manzillarni tekshirmasdan modullarni birga ulash."),

"OLED ekranni ulash": T(
 "SSD1306 OLED ni ulab, ishga tushirish va birinchi matnni chiqarish",
 ["SSD1306 I2C bilan ulanadi: VCC (3.3V), GND, SDA (21), SCL (22). Manzil odatda 0x3C.",
  "Kutubxonalar: Adafruit SSD1306 va Adafruit GFX.",
  "Kodda o'lcham to'g'ri ko'rsatilishi kerak: 128x64 yoki 128x32.",
  "MUHIM: har o'zgarishdan keyin display.display() chaqirilishi shart — usiz ekran yangilanmaydi."],
 "display.display() ni unutish muammosini oldindan ayting: kod to'g'ri, ekran bo'sh — sabab topilmaydi va ko'p vaqt ketadi.",
 [("Ekran yangilanishi uchun nima chaqiriladi?", "display.display()."),
  ("SSD1306 ning odatiy manzili qanday?", "0x3C.")],
 "display.display() ni unutish."),

"OLED'da matn va raqam": T(
 "Turli o'lcham va joylashuvdagi matn bilan ma'lumot paneli yasash",
 ["setTextSize(1-3) — matn o'lchami. 1-o'lchamda 21x8 belgi, 2-o'lchamda 10x4 sig'adi.",
  "setCursor(x, y) piksel koordinatalarini oladi (LCD dagi kabi belgi emas).",
  "Yangilash tartibi: clearDisplay(), chizish, display().",
  "I2C da yangilash tezligi ~20-30 kadr/sekund. Har loop siklida yangilash keraksiz — 200-500 ms yetarli."],
 "Piksel va belgi koordinatalari farqini ta'kidlang — LCD dan kelgan o'quvchilar buni chalkashtiradi.",
 [("setCursor qanday koordinata oladi?", "Piksel koordinatalarini."),
  ("Yangilash tartibi qanday?", "clearDisplay, chizish, display.")],
 "Har loop siklida ekranni to'liq yangilash — dastur sekinlashadi."),

"OLED'da grafik va diagramma": T(
 "Sensor qiymatlarining real vaqtli grafigini ekranda chizish",
 ["GFX kutubxonasi: drawPixel, drawLine, drawRect, fillRect, drawCircle.",
  "Grafik uchun oxirgi N ta qiymat aylanma buferda saqlanadi va har yangilanishda qayta chiziladi.",
  "Qiymatni ekran balandligiga moslash: y = map(qiymat, min, maks, 63, 0). Y o'qi teskari — yuqorida 0.",
  "Ustunli diagramma fillRect bilan chiziladi — bu bir necha qiymatni solishtirish uchun qulay."],
 "Y o'qining teskari ekanini alohida ayting — bu barcha ekran grafikasida uchraydi va ko'p chalkashtiradi.",
 [("Ekranda y = 0 qayerda?", "Yuqorida."),
  ("Grafik qiymatlari qayerda saqlanadi?", "Aylanma buferli massivda.")],
 "Y o'qini teskari moslashni unutish — grafik ag'darilib chiqadi."),

"SPI protokoli haqida tushuncha": T(
 "SPI qurilmasini ulab, I2C bilan farqini solishtirish",
 ["SPI to'rt sim ishlatadi: MOSI (ma'lumot chiqish), MISO (kirish), SCK (takt), CS (qurilma tanlash).",
  "Har qurilmaga alohida CS pini kerak — manzil o'rniga shu bilan tanlanadi.",
  "SPI I2C dan ancha tez (o'nlab megabit), lekin ko'proq sim talab qiladi.",
  "Tanlov: tez va katta ma'lumot uchun SPI (SD kart, TFT ekran), kam ma'lumot va ko'p qurilma uchun I2C."],
 "Ikki protokolni jadval qilib solishtiring: simlar soni, tezlik, qurilmalar soni. Bu texnologiya tanlash mantiqini shakllantiradi.",
 [("SPI nechta sim ishlatadi?", "To'rtta."),
  ("Har SPI qurilmasiga nima kerak?", "Alohida CS pini.")],
 "Bir necha SPI qurilmasiga bitta CS pinini ishlatish."),

"microSD kart va ma'lumot yozish": T(
 "SD kartga ma'lumot yozib, kompyuterda ochib tekshirish",
 ["SD kart moduli SPI bilan ulanadi. Kutubxona: SD.h.",
  "Ishga tushirish SD.begin(CS_PIN) — muvaffaqiyatni tekshirish shart.",
  "Fayl ochish, yozish va YOPISH: File f = SD.open(\"/log.csv\", FILE_APPEND); f.println(...); f.close();",
  "close() chaqirilmasa ma'lumot kartaga yozilmaydi va quvvat uzilganda yo'qoladi."],
 "close() ni unutish muammosini ta'kidlang: dastur ishlagandek ko'rinadi, lekin kartada hech narsa bo'lmaydi.",
 [("SD kart qaysi protokol bilan ulanadi?", "SPI."),
  ("Yozgandan keyin nima shart?", "Faylni close() bilan yopish.")],
 "Faylni yopmaslik."),

"RTC DS3231 va real vaqt": T(
 "DS3231 ni sozlab, aniq vaqt bilan ma'lumot yozib borish",
 ["DS3231 — quvvat o'chsa ham vaqtni saqlaydigan aniq soat. I2C manzili 0x68.",
  "Batareya (CR2032) quvvat o'chganda vaqtni saqlaydi.",
  "Aniqligi yiliga ±2 daqiqa — oddiy RTC ga nisbatan ancha yuqori, chunki termokompensatsiya bor.",
  "Vaqtni sozlash bir marta bajariladi va sozlash kodi keyin izohga olinishi kerak."],
 "Sozlash kodini izohga olishni albatta ayting — aks holda har yuklashda vaqt qayta o'rnatiladi va sabab topilmaydi.",
 [("DS3231 ning aniqligi qanday?", "Yiliga ±2 daqiqa atrofida."),
  ("Sozlashdan keyin kod bilan nima qilinadi?", "Izohga olinadi.")],
 "Sozlash kodini qoldirish."),

"Deep sleep va quvvat tejash": T(
 "Deep sleep ni sinab, tok iste'molini o'lchash",
 ["Deep sleep da ESP32 deyarli hamma qismini o'chiradi: iste'mol 150 mA dan 10 mikroamperga tushadi.",
  "Uyg'onish: esp_sleep_enable_timer_wakeup(mikrosekund), keyin esp_deep_sleep_start().",
  "Uyg'ongandan keyin dastur BOSHIDAN (setup dan) boshlanadi. Oddiy o'zgaruvchilar saqlanmaydi.",
  "Saqlash uchun RTC xotira ishlatiladi: RTC_DATA_ATTR int sanoq = 0;"],
 "Iste'molni multimetr bilan o'lchatib, batareya muddatini hisoblang. 13 soat va 66 kun farqi juda ta'sirchan.",
 [("Deep sleep da iste'mol qancha?", "Taxminan 10 mikroamper."),
  ("Uyg'ongandan keyin dastur qayerdan boshlanadi?", "setup() dan.")],
 "Oddiy o'zgaruvchilarda qiymat saqlanishini kutish."),

"ESP32 xatolarini topish (boot muammolari)": T(
 "Turli yuklash xatolarini modellashtirib, tuzatish tartibini ishlab chiqish",
 ["Boot xabari Serial monitorda ko'rinadi. Undagi ma'lumot xato sababini aniqlashga yordam beradi.",
  "Ko'p uchraydigan muammolar: boot pinlariga (GPIO 0, 2, 12, 15) komponent ulangan; quvvat yetarli emas; kabel yomon.",
  "Brownout detector xabari — quvvat cho'kkanini bildiradi. Sababi odatda kuchsiz USB port yoki ko'p tok oladigan modul.",
  "Guru Meditation Error — dasturdagi jiddiy xato (masalan bo'sh ko'rsatkichga murojaat). Xabardagi manzil xato joyini topishga yordam beradi."],
 "Brownout xatosini ko'rsating (motor ulab): bu ESP32 loyihalarida eng ko'p uchraydigan va sababi eng kam tushuniladigan muammo.",
 [("Brownout xatosi nimani bildiradi?", "Quvvat cho'kkanini."),
  ("Qaysi pinlarga komponent ulash yuklashni buzadi?", "GPIO 0, 2, 12, 15.")],
 "Boot xabarini o'qimasdan platani nosoz deb hisoblash."),

# ==================================================== 2-CHORAK: WiFi, veb va IoT
"WiFi tarmog'iga ulanish": T(
 "ESP32 ni WiFi ga ulab, signal kuchini va IP manzilni o'lchash",
 ["#include <WiFi.h>, WiFi.begin(ssid, parol), keyin WiFi.status() bilan kutish.",
  "Ulanish 2-10 sekund davom etadi. IP manzil: WiFi.localIP().",
  "MUHIM: ESP32 faqat 2.4 GHz tarmoqni qo'llab-quvvatlaydi, 5 GHz ga ulanmaydi.",
  "Signal kuchi: WiFi.RSSI(). -50 dBm yaxshi, -70 chegara, -80 dan past ishonchsiz."],
 "Sinf routerining 2.4 GHz tarmog'i borligini oldindan tekshiring — 5 GHz muammosi butun darsni to'xtatib qo'yishi mumkin.",
 [("ESP32 qaysi WiFi diapazonini qo'llab-quvvatlaydi?", "Faqat 2.4 GHz."),
  ("RSSI -80 dBm nimani bildiradi?", "Signal juda kuchsiz.")],
 "5 GHz tarmoqqa ulanmoqchi bo'lish."),

"IP manzil, port va tarmoq asoslari": T(
 "Tarmoq xaritasini chizib, qurilmalarning manzillarini aniqlash",
 ["IP manzil qurilmani tarmoqda belgilaydi. Mahalliy tarmoqda odatda 192.168.x.x.",
  "Router DHCP orqali manzil beradi — u qayta yoqilganda o'zgarishi mumkin.",
  "Statik IP: WiFi.config(ip, gateway, subnet) — manzil doim bir xil qoladi.",
  "Port — bitta qurilmadagi turli xizmatlar uchun raqam. Veb-server 80, MQTT 1883, HTTPS 443."],
 "Statik IP ni loyihalarda tavsiya qiling — o'zgarib turadigan manzil har safar qayta izlashni talab qiladi.",
 [("Veb-server odatda qaysi portda ishlaydi?", "80-portda."),
  ("Statik IP nima beradi?", "Manzil doim bir xil qoladi.")],
 "IP o'zgarganini bilmay, eski manzilga murojaat qilish."),

"Veb-server yaratish": T(
 "ESP32 da veb-server ishga tushirib, brauzerdan ochish",
 ["WiFiServer server(80); setup ichida server.begin();",
  "loop ichida mijoz tekshiriladi, so'rov o'qiladi va javob yuboriladi.",
  "HTTP javobi tuzilishi: status qatori, sarlavhalar, BO'SH QATOR, keyin HTML.",
  "Bo'sh qator majburiy — usiz brauzer sahifani ko'rsatmaydi."],
 "Bo'sh qator qoidasini ta'kidlang — bu ko'rinmaydigan detal va uni unutish sahifa ochilmasligining eng ko'p sababi.",
 [("HTTP javobida sarlavhalardan keyin nima kerak?", "Bo'sh qator."),
  ("Veb-server qaysi portda ochiladi?", "Odatda 80-portda.")],
 "Bo'sh qatorni unutish."),

"HTML sahifani platadan yuborish": T(
 "To'liq HTML sahifani stil bilan birga yuborish",
 ["HTML client.println() bilan qatorlab yuboriladi.",
  "Uzun HTML uchun R\"rawliteral(...)rawliteral\" konstruksiyasi qulay — qo'shtirnoqlarni ekranlash kerak bo'lmaydi.",
  "meta viewport tegi bo'lishi kerak, aks holda telefonda sahifa juda kichik ko'rinadi.",
  "Xotira cheklovi: katta sahifa xotirani to'ldiradi. Yechim — SPIFFS fayl tizimida saqlash."],
 "rawliteral usulini ko'rsating — usiz har qo'shtirnoqni ekranlash kerak va kod o'qib bo'lmas holga keladi.",
 [("Telefonda to'g'ri ko'rinish uchun nima kerak?", "meta viewport tegi."),
  ("Katta sahifalar qayerda saqlanadi?", "SPIFFS fayl tizimida.")],
 "Har qo'shtirnoqni qo'lda ekranlashga urinish."),

"Brauzerdan qurilmani boshqarish": T(
 "Veb-sahifadagi tugmalar orqali bir necha qurilmani boshqarish",
 ["Brauzer so'rovi matn sifatida keladi: GET /LEDON HTTP/1.1.",
  "So'rovdagi yo'l tekshiriladi: if (sorov.indexOf(\"GET /LEDON\") >= 0).",
  "Tugmalar oddiy havolalar bo'lishi mumkin, lekin har bosishda sahifa qayta yuklanadi.",
  "Silliqroq yechim — JavaScript bilan fon so'rovi (AJAX), bu keyingi dars mavzusi."],
 "Sahifaning qayta yuklanishi muammosini his qildiring — keyingi darsdagi AJAX yechimi mantiqiy davom bo'lib ko'rinadi.",
 [("Brauzer so'rovi qanday keladi?", "Matn sifatida, GET /yo'l ko'rinishida."),
  ("Havolali tugmaning kamchiligi nima?", "Har bosishda sahifa qayta yuklanadi.")],
 "So'rovni to'liq o'qimasdan javob yuborish."),

"Sensor qiymatini sahifada ko'rsatish": T(
 "Sensor ma'lumotini veb-sahifada ko'rsatib, yangilanishni tashkil qilish",
 ["Eng oddiy usul — meta refresh: sahifa har N sekundda o'zi qayta yuklanadi.",
  "Kamchiligi: butun sahifa yuklanadi, miltillaydi va ortiqcha trafik sarflanadi.",
  "Yaxshiroq usul — alohida manzil (masalan /qiymat) faqat raqamni qaytarsin.",
  "Sahifadagi JavaScript shu manzilga so'rov yuborib, faqat kerakli qismni yangilaydi."],
 "Ikki usulni ketma-ket sinatib ko'ring — AJAX ning afzalligi darhol ko'rinadi va JavaScript ga qiziqish uyg'otadi.",
 [("meta refresh ning kamchiligi nima?", "Butun sahifa qayta yuklanadi."),
  ("Yaxshiroq yechim nima?", "Alohida manzildan faqat qiymatni olish.")],
 "Har sekundda butun sahifani qayta yuklash."),

"Sahifani avtomatik yangilash (AJAX g'oyasi)": T(
 "JavaScript bilan sahifaning bir qismini fon rejimida yangilash",
 ["AJAX — sahifani qayta yuklamasdan serverdan ma'lumot olish usuli.",
  "JavaScript kodi: fetch('/qiymat').then(javob => javob.text()).then(matn => elementni yangilash).",
  "setInterval bilan bu so'rov muntazam takrorlanadi (masalan har sekundda).",
  "ESP32 tomonida alohida manzil bo'lishi kerak — u faqat raqam qaytaradi, HTML emas."],
 "JavaScript kodini tayyor bering, lekin har qatorini tushuntiring. Maqsad — JavaScript o'rgatish emas, g'oyani tushuntirish.",
 [("AJAX nima qiladi?", "Sahifani qayta yuklamasdan ma'lumot oladi."),
  ("So'rovni takrorlash uchun nima ishlatiladi?", "setInterval.")],
 "AJAX manzilidan to'liq HTML qaytarish — u faqat qiymat qaytarishi kerak."),

"CSS bilan sahifani chiroyli qilish": T(
 "Veb-sahifaga CSS qo'shib, telefonda ham qulay ko'rinishini ta'minlash",
 ["CSS sahifaning ko'rinishini belgilaydi: rang, o'lcham, joylashuv.",
  "CSS ni HTML ichida <style> tegida yozish qulay — alohida fayl kerak bo'lmaydi.",
  "Telefon uchun: meta viewport, katta tugmalar (kamida 44x44 piksel), yetarli kontrast.",
  "Sodda va kam CSS afzal: ESP32 xotirasi cheklangan va katta stil fayli joy egallaydi."],
 "Tugma o'lchami (44 piksel) qoidasini ayting — bu barmoq bilan bosish uchun sanoat standarti va foydalanish qulayligining aniq mezoni.",
 [("CSS qayerda yoziladi?", "HTML ichidagi <style> tegida."),
  ("Telefon uchun tugma o'lchami qanday bo'lishi kerak?", "Kamida 44x44 piksel.")],
 "Katta CSS fayli yozib, ESP32 xotirasini to'ldirish."),

"HTTP so'rov yuborish (client)": T(
 "ESP32 dan tashqi serverga so'rov yuborib, javobni qayta ishlash",
 ["HTTPClient kutubxonasi: http.begin(url); int kod = http.GET(); String javob = http.getString(); http.end();",
  "Javob kodlari: 200 — muvaffaqiyat, 404 — topilmadi, 500 — server xatosi, manfiy — ulanish xatosi.",
  "http.end() majburiy — aks holda xotira asta-sekin to'ladi va qurilma soatlar o'tgach qotib qoladi.",
  "HTTPS uchun WiFiClientSecure kerak. setInsecure() sertifikat tekshiruvini o'chiradi — sinov uchun mumkin, ishlab chiqarishda emas."],
 "Xotira sizib ketishi (memory leak) tushunchasini kiriting: http.end() ni unutish qurilmani bir necha soatdan keyin ishdan chiqaradi.",
 [("Javob kodi 200 nimani bildiradi?", "So'rov muvaffaqiyatli."),
  ("http.end() nima uchun kerak?", "Xotirani bo'shatish uchun.")],
 "http.end() ni unutish."),

"Bulut xizmatiga ma'lumot yuborish": T(
 "Bulut platformasiga sensor ma'lumotini muntazam yuborish",
 ["Hisob ochiladi, kanal yaratiladi va API kalit olinadi.",
  "Yuborish HTTP GET yoki POST so'rovi orqali: api.thingspeak.com/update?api_key=KALIT&field1=QIYMAT.",
  "Bepul rejada cheklov bor — odatda 15 sekundda bir marta. Tez-tez yuborilsa so'rov rad etiladi.",
  "API kalit maxfiy ma'lumot — uni ochiq joyga qo'yish mumkin emas."],
 "API kalitning maxfiyligini ta'kidlang — bu raqamli xavfsizlik madaniyatining amaliy darsi.",
 [("API kalit nima?", "Xizmatga murojaat uchun maxfiy kalit."),
  ("Bepul rejada qanday cheklov bo'ladi?", "Yuborish chastotasi cheklanadi.")],
 "API kalitni ochiq joyda saqlash."),

"Bulutda grafik va tahlil": T(
 "To'plangan ma'lumotni bulutda tahlil qilib, xulosalar chiqarish",
 ["Bulut xizmatlari ma'lumotni avtomatik grafikka aylantiradi.",
  "Grafikdan ko'rinadigan narsalar: kunlik sikl, anomaliyalar, sensor nosozligi (to'satdan tekis chiziq).",
  "Ma'lumotni CSV qilib yuklab, jadval dasturida chuqurroq tahlil qilish mumkin.",
  "Tahlil savollari: o'rtacha qancha? Maksimal qachon? Qanday qonuniyat bor? Nima uchun shunday?"],
 "Bir necha kunlik ma'lumot to'plab, birgalikda tahlil qiling. Real ma'lumotdagi kunlik siklni ko'rish kuchli taassurot qoldiradi.",
 [("Grafikda to'satdan tekis chiziq nimani bildiradi?", "Sensor nosozligini yoki uzilganini."),
  ("Chuqurroq tahlil uchun nima qilinadi?", "CSV yuklab, jadval dasturida ishlash.")],
 "Ma'lumotni faqat to'plab, tahlil qilmaslik."),

"Telegram bot yaratish": T(
 "BotFather orqali bot yaratib, ESP32 bilan bog'lash",
 ["@BotFather ga /newbot yuboriladi, nom tanlanadi va TOKEN olinadi.",
  "Token — botni boshqarish uchun parol. Uni hech kimga bermaslik kerak.",
  "Kutubxona: UniversalTelegramBot. WiFiClientSecure va Telegram sertifikati kerak.",
  "Chat ID ham kerak — bot kimga xabar yuborishini belgilaydi. @userinfobot orqali bilib olinadi."],
 "Token maxfiyligini yana ta'kidlang — token o'g'irlansa botni boshqa odam to'liq boshqara oladi.",
 [("Bot yaratish uchun kimga murojaat qilinadi?", "@BotFather ga."),
  ("Chat ID nima uchun kerak?", "Bot kimga xabar yuborishini belgilash uchun.")],
 "Tokenni ochiq kodda qoldirish."),

"Telegram orqali xabar va ogohlantirish": T(
 "Chegara oshganda ogohlantirish yuboradigan tizim yozish",
 ["bot.sendMessage(chat_id, matn, \"\") bilan xabar yuboriladi.",
  "Bayroq (flag) kerak: xabar bir marta yuborilsin, har siklda emas.",
  "Bayroq holat normal holatga qaytgach tiklanadi.",
  "Xabar mazmuni foydali bo'lishi kerak: nima, qachon, qanday qiymat."],
 "Xabar mazmuni haqidagi talabni qo'ying — foydali xabar yozish texnik yozuv madaniyatining bir qismi.",
 [("Nega bayroq kerak?", "Xabar bir marta yuborilishi uchun."),
  ("Xabarda nima bo'lishi kerak?", "Nima bo'lgani, qachon va qanday qiymat.")],
 "Bayroqsiz ogohlantirish — bot yuzlab xabar yuboradi."),

"Telegram orqali boshqarish": T(
 "Telegram buyruqlari bilan qurilmani xavfsiz boshqarish",
 ["Bot kelgan xabarlarni davriy so'raydi: bot.getUpdates().",
  "Buyruqlar / bilan boshlanadi: /yoq, /ochir, /holat.",
  "XAVFSIZLIK: faqat ruxsat berilgan chat ID lardan kelgan buyruqlar bajarilishi kerak.",
  "Klaviatura (keyboard) qo'shish foydalanuvchiga tugmalar ko'rsatadi va buyruqni qo'lda yozish kerak bo'lmaydi."],
 "Chat ID tekshiruvini MAJBURIY qiling — bu xavfsizlik tushunchasining eng aniq va amaliy misoli.",
 [("Nega chat ID tekshiriladi?", "Faqat ruxsat berilgan odam boshqarishi uchun."),
  ("Klaviatura nima beradi?", "Foydalanuvchiga tayyor tugmalar.")],
 "Chat ID ni tekshirmaslik."),

"MQTT protokoli": T(
 "MQTT broker orqali xabar almashib, mavzular tuzilmasini loyihalash",
 ["MQTT uch element: broker (markaz), publisher (yuboruvchi), subscriber (obunachi).",
  "Xabarlar mavzu (topic) bo'yicha: uy/oshxona/harorat. Mavzular daraxt ko'rinishida.",
  "Qurilmalar bir-birini bilmaydi — broker vositachi. Bu tizimni kengaytirishni osonlashtiradi.",
  "HTTP dan afzalligi: kam trafik, tez javob, ikki tomonlama aloqa (server ham xabar yubora oladi)."],
 "Mavzu nomlarini tizimli tanlash bo'yicha qoida bering (joy/qurilma/parametr). Tartibsiz nomlar tizim kengayganda boshqarib bo'lmas holga keltiradi.",
 [("MQTT ning uch elementi qaysi?", "Broker, publisher, subscriber."),
  ("Mavzular qanday tuziladi?", "Daraxt ko'rinishida, masalan uy/oshxona/harorat.")],
 "Mavzu nomlarini tartibsiz tanlash."),

"Ikki qurilma o'rtasida aloqa": T(
 "Ikki ESP32 ni bog'lab, ma'lumot almashish tizimini qurish",
 ["Uch usul: MQTT (broker orqali), to'g'ridan-to'g'ri HTTP (biri server), ESP-NOW.",
  "ESP-NOW — Espressif protokoli: routersiz, to'g'ridan-to'g'ri, juda tez va kam quvvat sarflaydi.",
  "ESP-NOW uchun qabul qiluvchining MAC manzili kerak: WiFi.macAddress().",
  "Tanlov: internet kerak bo'lsa MQTT, faqat mahalliy va tez aloqa kerak bo'lsa ESP-NOW."],
 "ESP-NOW ni ko'rsating — routersiz ishlaydigan aloqa o'quvchilar uchun kutilmagan va juda qiziq bo'ladi.",
 [("ESP-NOW ning afzalligi nima?", "Routersiz, tez va kam quvvat."),
  ("ESP-NOW uchun nima kerak?", "Qabul qiluvchining MAC manzili.")],
 "MAC manzilni noto'g'ri kiritish — xabar yetib bormaydi va xato ham chiqmaydi."),

"BLE (Bluetooth Low Energy) asoslari": T(
 "ESP32 ni BLE orqali telefonga ulab, ma'lumot uzatish",
 ["BLE kam quvvat sarflaydigan simsiz aloqa. Klassik Bluetooth'dan farq qiladi.",
  "Tuzilma: Service ichida Characteristic. Har biriga UUID beriladi.",
  "Telefonda nRF Connect ilovasi bilan sinash mumkin.",
  "Masofa 10-30 metr, tezlik past. Sensor qiymatlari uchun ideal, katta ma'lumot uchun mos emas."],
 "BLE va WiFi ni solishtiring: qachon qaysi biri mos? Bu texnologiya tanlash bo'yicha muhandislik qarorining yaxshi misoli.",
 [("BLE ning asosiy afzalligi nima?", "Juda kam quvvat sarflaydi."),
  ("BLE da ma'lumot qanday tashkil qilinadi?", "Service ichida Characteristic.")],
 "BLE orqali katta hajmdagi ma'lumot uzatishga urinish."),

"Tarmoq xavfsizligi asoslari": T(
 "Loyihadagi xavfsizlik zaifliklarini aniqlab, himoya choralarini qo'llash",
 ["Asosiy zaifliklar: kodda ochiq saqlangan parol va token; autentifikatsiyasiz veb-server; shifrlanmagan aloqa.",
  "Minimal himoya: veb-serverga parol qo'yish, Telegram'da chat ID tekshiruvi, HTTPS ishlatish.",
  "Parollarni kodda saqlash o'rniga alohida faylda (secrets.h) saqlash va uni ochiq joyga qo'ymaslik.",
  "IoT qurilmalari real xavf: himoyasiz kameralar va routerlar orqali uy tarmog'iga kirish holatlari ko'p."],
 "Real hodisalarni misol qiling (himoyasiz kameralar orqali kirish). Bu xavfsizlikni mavhum talab emas, real ehtiyoj sifatida ko'rsatadi.",
 [("Kodda parol saqlash nima uchun xavfli?", "Kod boshqalarga o'tsa parol ham o'tadi."),
  ("Minimal himoya nimalardan iborat?", "Parol, autentifikatsiya va shifrlangan aloqa.")],
 "Loyihani \"kichik, hech kimga kerak emas\" deb himoyasiz qoldirish."),

# ==================================================== 3-CHORAK: Sun'iy intellekt asoslari
"Sun'iy intellekt, mashinaviy o'rganish, TinyML": T(
 "Uch tushunchani ajratib, misollar bilan jadval to'ldirish",
 ["Sun'iy intellekt (SI) — eng keng tushuncha: inson aqliy vazifalarini bajaruvchi tizimlar sohasi.",
  "Mashinaviy o'rganish (ML) — SI ning bir qismi: qoidalar qo'lda yozilmaydi, ma'lumotdan o'rganiladi.",
  "Chuqur o'rganish (DL) — ML ning bir qismi: ko'p qatlamli neyron tarmoqlar.",
  "TinyML — ML modellarini mikrokontrollerda ishlatish. Model kichkina bo'lishi kerak: kilobaytlar tartibida."],
 "Uch doira sxemasini chizing (SI ichida ML, ML ichida DL). Bu tushunchalarning munosabatini bir qarashda ochadi.",
 [("ML SI ning bir qismimi yoki aksincha?", "ML — SI ning bir qismi."),
  ("TinyML nima?", "Mikrokontrollerda ishlaydigan kichik ML modellari.")],
 "SI va ML ni sinonim deb ishlatish."),

"An'anaviy dastur va o'rganuvchi model farqi": T(
 "Bir vazifani ikki usulda hal qilib (qoida va model), farqni aniqlash",
 ["An'anaviy dasturda qoidalarni DASTURCHI yozadi: agar harorat > 30 bo'lsa shamollatgichni yoq.",
  "Mashinaviy o'rganishda qoidalar MA'LUMOTDAN topiladi: modelga ko'p misol ko'rsatiladi va u qonuniyatni o'zi topadi.",
  "Qachon ML kerak: qoidalarni yozib bo'lmaydigan vazifalarda. Masalan \"bu rasmda mushuk bormi?\" savolini qoidalar bilan hal qilish deyarli imkonsiz.",
  "Qachon an'anaviy dastur afzal: qoida aniq va sodda bo'lsa. Termostat uchun ML kerak emas — u ortiqcha murakkablik."],
 "\"Qachon ML kerak EMAS\" savoliga alohida vaqt bering. Bu muhandislik yetukligining belgisi va ML ni hamma joyga tiqishtirishning oldini oladi.",
 [("An'anaviy dasturda qoidalarni kim yozadi?", "Dasturchi."),
  ("ML qachon kerak?", "Qoidalarni qo'lda yozib bo'lmaydigan vazifalarda.")],
 "Har vazifaga ML qo'llashga urinish — ko'p holatda oddiy shart yetarli."),

"Ma'lumot (dataset) nima va nega muhim": T(
 "Kichik dataset yig'ib, uning sifatini baholash",
 ["Dataset — modelni o'rgatish uchun yig'ilgan misollar to'plami. Har misolda kirish ma'lumoti va to'g'ri javob bor.",
  "Model faqat ko'rgan narsasidan o'rganadi. Datasetda bo'lmagan holatni u to'g'ri tanimaydi.",
  "Sifat mezonlari: yetarli miqdor, xilma-xillik, muvozanat (har sinfdan taxminan teng), to'g'ri belgilash.",
  "\"Axlat kirsa, axlat chiqadi\" — sifatsiz ma'lumotdan yaxshi model chiqmaydi, model qanchalik murakkab bo'lmasin."],
 "Datasetning ahamiyatini ta'kidlang: amalda ML loyihasining vaqtining 70-80% i ma'lumot yig'ish va tozalashga ketadi, model o'rgatishga emas.",
 [("Dataset nima?", "Modelni o'rgatish uchun yig'ilgan misollar to'plami."),
  ("ML loyihasining vaqtining ko'p qismi nimaga ketadi?", "Ma'lumot yig'ish va tayyorlashga.")],
 "Kam va bir xil ma'lumot yig'ib, modeldan yaxshi natija kutish."),

"Belgi (feature) va sinf (class) tushunchasi": T(
 "Berilgan vazifalar uchun belgilar va sinflarni aniqlab, jadval tuzish",
 ["Belgi (feature) — ma'lumotdan ajratilgan va model uchun muhim xususiyat. Masalan tezlanish o'qlari bo'yicha qiymatlar.",
  "Sinf (class) — model ajratadigan toifalardan biri. Masalan \"yurish\", \"yugurish\", \"turish\".",
  "Yaxshi belgi tanlash model sifatini keskin oshiradi. Xom ma'lumot o'rniga undan hisoblangan qiymatlar (o'rtacha, tebranish, chastota) ko'pincha yaxshiroq ishlaydi.",
  "Edge Impulse belgi ajratishni avtomatik bajaradi, lekin qaysi usul tanlanishini foydalanuvchi belgilaydi."],
 "Belgi tanlash misolini beruvchi mashq qiling: \"yurish va yugurishni ajratish uchun qanday belgi kerak?\" Javob (tebranish chastotasi) intuitiv topiladi.",
 [("Belgi (feature) nima?", "Ma'lumotdan ajratilgan muhim xususiyat."),
  ("Sinf nima?", "Model ajratadigan toifalardan biri.")],
 "Xom ma'lumotni to'g'ridan-to'g'ri modelga berib, belgi ajratishni o'tkazib yuborish."),

"Model o'rgatish jarayoni: qadamlar": T(
 "To'liq ML ish oqimini qadamlar bo'yicha rejalashtirish",
 ["Qadamlar: 1) vazifani aniqlash, 2) ma'lumot yig'ish, 3) belgilash, 4) belgi ajratish, 5) o'rgatish, 6) baholash, 7) joylash, 8) kuzatish.",
  "Ma'lumot ikkiga bo'linadi: o'rgatish to'plami (80%) va tekshirish to'plami (20%).",
  "Model faqat o'rgatish to'plamini ko'radi. Tekshirish to'plami uning haqiqiy sifatini baholash uchun ishlatiladi.",
  "Bu sikl bir marta emas, bir necha marta takrorlanadi: natija yomon bo'lsa ma'lumot qo'shiladi yoki parametrlar o'zgartiriladi."],
 "Sikl ekanini ta'kidlang: birinchi urinishda yaxshi natija chiqmaydi va bu normal. Bu ML ishining tabiati.",
 [("Ma'lumot qanday bo'linadi?", "O'rgatish (80%) va tekshirish (20%) to'plamlariga."),
  ("Tekshirish to'plami nima uchun kerak?", "Modelning haqiqiy sifatini baholash uchun.")],
 "Butun ma'lumotni o'rgatishga berib, tekshirish uchun qoldirmaslik."),

"Edge Impulse platformasi bilan tanishuv": T(
 "Edge Impulse da hisob ochib, interfeys bilan tanishish",
 ["Edge Impulse — brauzerda ishlaydigan TinyML platformasi. Dastur o'rnatish kerak emas.",
  "Ish oqimi bosqichlari interfeysda ko'rinadi: Data acquisition, Impulse design, Training, Model testing, Deployment.",
  "Bepul rejada cheklovlar bor: o'rgatish vaqti va ma'lumot hajmi. Ta'lim loyihalari uchun yetarli.",
  "Natija tayyor Arduino kutubxonasi sifatida yuklab olinadi va oddiy #include bilan ishlatiladi."],
 "Interfeys bosqichlarini ML ish oqimi qadamlariga moslashtirib ko'rsating — bu platformani tushunishni ancha osonlashtiradi.",
 [("Edge Impulse qayerda ishlaydi?", "Brauzerda."),
  ("Natija qanday shaklda olinadi?", "Tayyor Arduino kutubxonasi sifatida.")],
 "Bepul reja cheklovlarini hisobga olmay, juda katta dataset yig'ish."),

"Loyiha yaratish va qurilmani ulash": T(
 "Edge Impulse da loyiha yaratib, ESP32 ni ulash",
 ["Loyiha yaratilgach, qurilmani ulash usullari: Edge Impulse CLI, telefon, yoki ma'lumotni qo'lda yuklash.",
  "CLI o'rnatish uchun Node.js kerak. Qurilma ulangach u brauzerda ko'rinadi.",
  "Telefon orqali ulash eng oson usul — telefondagi datchiklar bilan tez sinab ko'rish mumkin.",
  "Ma'lumotni CSV yoki JSON sifatida qo'lda yuklash ham mumkin — bu boshqa manbalardan olingan ma'lumot uchun qulay."],
 "Telefon orqali ulanish variantini ko'rsating — bu eng tez yo'l va o'quvchilar darhol natija ko'radi.",
 [("Qurilma qanday ulanadi?", "CLI, telefon yoki qo'lda yuklash orqali."),
  ("CLI uchun nima kerak?", "Node.js o'rnatilgan bo'lishi.")],
 "CLI o'rnatishga uzoq vaqt sarflab, dars vaqtini yo'qotish."),

"MPU6050: harakat ma'lumotini yig'ish": T(
 "MPU6050 ni ulab, uch o'q bo'yicha tezlanishni o'qish",
 ["MPU6050 — akselerometr (tezlanish) va giroskop (burilish tezligi) bir korpusda.",
  "I2C bilan ulanadi, manzil 0x68 (AD0 pini GND da) yoki 0x69.",
  "Akselerometr uch o'q bo'yicha tezlanishni beradi. Tinch holatda ham Yer tortishi (1g) seziladi — shuning uchun qiyalikni aniqlash mumkin.",
  "Namuna olish chastotasi muhim: harakatni tanish uchun odatda 50-100 Hz kerak."],
 "Tinch holatdagi 1g ni ko'rsating — bu kutilmagan va akselerometrning ishlash tamoyilini yaxshi ochadi.",
 [("MPU6050 nimalarni o'lchaydi?", "Tezlanish va burilish tezligini."),
  ("Tinch holatda akselerometr nima ko'rsatadi?", "Yer tortishini, ya'ni 1g.")],
 "Namuna olish chastotasini juda past qo'yish — tez harakatlar sezilmaydi."),

"Imo-ishora uchun ma'lumot to'plash": T(
 "Uch xil imo-ishora uchun namunalar to'plab, dataset tuzish",
 ["Har sinf uchun kamida 30-50 namuna kerak. Kamroq bo'lsa model ishonchsiz bo'ladi.",
  "Xilma-xillik muhim: turli odamlar, turli tezlik, turli kuch bilan bajarilgan namunalar.",
  "Namuna uzunligi bir xil bo'lishi kerak (masalan har biri 2 sekund).",
  "Muvozanat: har sinfdan taxminan teng miqdorda namuna. Nomutanosib datasetda model ko'p uchraydigan sinfni afzal ko'radi."],
 "Har o'quvchi o'z namunalarini bersin — bu datasetni xilma-xil qiladi va o'quvchilarni jarayonga jalb etadi.",
 [("Har sinf uchun kamida nechta namuna kerak?", "30-50 ta."),
  ("Nega xilma-xillik muhim?", "Model turli bajarilish usullarini tanishi uchun.")],
 "Faqat bitta odam, bir xil tezlikda namuna yig'ish — model boshqa odamda ishlamaydi."),

"Ma'lumotni belgilash (labeling)": T(
 "Yig'ilgan namunalarni to'g'ri sinflarga belgilab chiqish",
 ["Belgilash — har namunaga to'g'ri sinf nomini qo'yish. Bu nazorat ostidagi o'rganishning asosi.",
  "Noto'g'ri belgilangan ma'lumot modelni ataylab yanglishtiradi. Bir necha noto'g'ri yorliq butun natijani buzishi mumkin.",
  "Sinf nomlari izchil bo'lishi kerak: \"yurish\" va \"Yurish\" ikki xil sinf sifatida qabul qilinadi.",
  "Shubhali namunalarni tashlab yuborish belgilashga urinishdan yaxshiroq — noaniq ma'lumot zarar keltiradi."],
 "Noto'g'ri belgilashning ta'sirini tajribada ko'rsating: ataylab 20% namunani noto'g'ri belgilab, natijani solishtiring.",
 [("Belgilash nima?", "Har namunaga to'g'ri sinf nomini qo'yish."),
  ("Shubhali namuna bilan nima qilinadi?", "Tashlab yuborilgani ma'qul.")],
 "Sinf nomlarini turlicha yozish (yurish, Yurish, yurish2) — ular alohida sinf bo'lib qoladi."),

"O'rgatish va tekshirish to'plamlari": T(
 "Ma'lumotni to'g'ri bo'lib, har to'plamning vazifasini tushunish",
 ["O'rgatish to'plami (train) — model shundan o'rganadi. Odatda 80%.",
  "Tekshirish to'plami (test) — model uni HECH QACHON ko'rmaydi. U modelning haqiqiy sifatini baholash uchun.",
  "Bo'lish tasodifiy bo'lishi kerak, lekin har sinf ikkala to'plamda ham bo'lishi shart.",
  "Agar test to'plamidagi natija o'rgatish to'plamidagidan ancha yomon bo'lsa — model yodlab olgan, umumlashtira olmagan."],
 "\"Model test to'plamini ko'rmaydi\" qoidasini ta'kidlang — bu ML dagi eng muhim halollik tamoyili.",
 [("Test to'plami nima uchun kerak?", "Modelning haqiqiy sifatini baholash uchun."),
  ("Test natijasi ancha yomon bo'lsa nima demak?", "Model yodlab olgan, umumlashtira olmagan.")],
 "Test to'plamini ham o'rgatishga qo'shib yuborish — natija aldamchi yaxshi chiqadi."),

"Modelni o'rgatish va aniqlikni ko'rish": T(
 "Modelni o'rgatib, aniqlik ko'rsatkichlarini tahlil qilish",
 ["O'rgatish jarayonida model ma'lumotdan qonuniyat izlaydi. Bu bir necha daqiqa davom etadi.",
  "Natijada aniqlik (accuracy) foizi chiqadi: to'g'ri javoblar ulushi.",
  "90% aniqlik yaxshi eshitiladi, lekin kontekstga bog'liq: 10 ta harakatdan biri xato tanilsa, ba'zi vazifalar uchun bu yetarli, ba'zilari uchun emas.",
  "Aniqlik yolg'iz o'zi yetarli emas — chalkashlik matritsasi qaysi sinflar adashtirilayotganini ko'rsatadi."],
 "Aniqlikning aldamchi tomonini ayting: 95% sinf muvozanatsiz bo'lsa hech narsani bildirmasligi mumkin. Bu keyingi dars mavzusiga kirish.",
 [("Aniqlik nima?", "To'g'ri javoblar ulushi."),
  ("Nega aniqlik yolg'iz yetarli emas?", "U qaysi sinflar adashtirilayotganini ko'rsatmaydi.")],
 "Faqat aniqlik foiziga qarab modelni yaxshi deb baholash."),

"Chalkashlik matritsasi (confusion matrix)": T(
 "Chalkashlik matritsasini o'qib, modelning kuchsiz joyini aniqlash",
 ["Chalkashlik matritsasi — jadval: qatorlar haqiqiy sinf, ustunlar model bergan javob.",
  "Diagonaldagi qiymatlar to'g'ri javoblar. Diagonaldan tashqaridagilar xatolar.",
  "Matritsa qaysi sinf qaysi bilan adashtirilayotganini aniq ko'rsatadi: masalan \"yurish\" ko'pincha \"yugurish\" deb tanilsa, shu ikkisi bir-biriga o'xshash.",
  "Yechim: shu ikki sinf uchun ko'proq va aniqroq ma'lumot yig'ish yoki belgi ajratish usulini o'zgartirish."],
 "Matritsani birgalikda o'qib, aniq xulosa chiqaring: \"qaysi ikki sinf chalkashmoqda va nima qilish kerak?\" Bu tahlil ko'nikmasi juda qimmatli.",
 [("Matritsaning diagonalida nima turadi?", "To'g'ri javoblar soni."),
  ("Matritsa nima haqida ma'lumot beradi?", "Qaysi sinflar bir-biri bilan adashtirilayotgani haqida.")],
 "Matritsani o'qimasdan faqat umumiy aniqlikka qarash."),

"Modelni qurilmaga yuklash": T(
 "O'rgatilgan modelni ESP32 ga yuklab, ishga tushirish",
 ["Edge Impulse da Deployment bo'limidan Arduino kutubxonasi tanlanadi va yuklab olinadi.",
  "Kutubxona IDE ga qo'shiladi: Sketch > Include Library > Add .ZIP Library.",
  "Misol kod kutubxona bilan birga keladi — undan boshlash tavsiya etiladi.",
  "Xotira cheklovi: model ESP32 xotirasiga sig'ishi kerak. Sig'masa kvantlash yoki modelni kichraytirish kerak."],
 "Misoldan boshlashni majburiy qiling — kutubxonaning ishlash usulini tushunmasdan o'z kodini yozishga urinish uzoq vaqt yeydi.",
 [("Model qanday shaklda olinadi?", "Arduino kutubxonasi (ZIP) sifatida."),
  ("Model xotiraga sig'masa nima qilinadi?", "Kvantlash yoki modelni kichraytirish.")],
 "Misolni o'rganmasdan o'z kodini yozishga urinish."),

"Imo-ishorani real vaqtda tanish": T(
 "Modelni qurilmada sinab, real vaqtdagi aniqligini o'lchash",
 ["Real vaqtda model uzluksiz ma'lumot oladi va har oynada bashorat qiladi.",
  "Natija har sinf uchun ehtimollik sifatida keladi (masalan yurish 0.85, yugurish 0.10, turish 0.05).",
  "Chegara qo'yiladi: ehtimollik 0,7 dan past bo'lsa \"aniqlanmadi\" deb hisoblanadi. Bu yolg'on tanishlarni kamaytiradi.",
  "Real vaqtdagi aniqlik test to'plamidagidan pastroq bo'ladi — bu normal, chunki real sharoit datasetdan farq qiladi."],
 "Real aniqlikni sanab o'lchashni tashkil qiling: 20 marta bajarib, nechtasi to'g'ri tanilganini yozib chiqish. Bu haqiqiy baholash.",
 [("Model natijani qanday shaklda beradi?", "Har sinf uchun ehtimollik sifatida."),
  ("Chegara nima uchun qo'yiladi?", "Ishonchsiz bashoratlarni rad etish uchun.")],
 "Ehtimollik chegarasini qo'ymaslik — model har doim biror sinfni tanlaydi, hatto noaniq holatda ham."),

"Modelni yaxshilash: ko'proq ma'lumot": T(
 "Modelni yaxshilash uchun qo'shimcha ma'lumot yig'ib, natijani solishtirish",
 ["Modelni yaxshilashning eng ishonchli usuli — ko'proq va xilma-xilroq ma'lumot.",
  "Ayniqsa xato qilingan holatlar uchun ma'lumot qo'shish samarali: chalkashlik matritsasi qaysi sinflar muammoli ekanini ko'rsatadi.",
  "Ma'lumotni sun'iy ko'paytirish (augmentation) ham mumkin: shovqin qo'shish, siljitish, masshtablash.",
  "Har o'zgarishdan keyin natijani oldingisi bilan solishtirish kerak — aks holda yaxshilanish yoki yomonlashuvni bilib bo'lmaydi."],
 "Natijalarni jadvalga yozib borishni talab qiling: versiya, o'zgarish, aniqlik. Bu tajriba yuritishning ilmiy usuli.",
 [("Modelni yaxshilashning eng ishonchli usuli nima?", "Ko'proq va xilma-xil ma'lumot yig'ish."),
  ("Qaysi holatlar uchun ma'lumot qo'shish samarali?", "Model xato qiladigan holatlar uchun.")],
 "Bir vaqtda bir necha narsani o'zgartirib, qaysi biri yordam berganini bilmay qolish."),

"Ortiqcha moslashuv (overfitting) muammosi": T(
 "Overfitting'ni tajribada hosil qilib, uni aniqlash usullarini o'rganish",
 ["Overfitting — model o'rgatish ma'lumotini YODLAB oladi, lekin yangi ma'lumotda xato qiladi.",
  "Belgisi: o'rgatish to'plamida aniqlik 99%, test to'plamida esa 60%. Katta farq — aniq ishora.",
  "Sabablari: ma'lumot kam, model juda murakkab, o'rgatish juda uzoq davom etgan.",
  "Yechimlar: ko'proq ma'lumot, soddaroq model, o'rgatishni erta to'xtatish, regularizatsiya."],
 "Overfitting'ni ataylab hosil qiling: kam ma'lumot bilan uzoq o'rgatib, ikki aniqlik farqini ko'rsating. Bu tushunchani mustahkam ochadi.",
 [("Overfitting nima?", "Model o'rgatish ma'lumotini yodlab, yangisida xato qilishi."),
  ("Uning belgisi nima?", "O'rgatish va test aniqliklari orasidagi katta farq.")],
 "Faqat o'rgatish aniqligiga qarab modelni yaxshi deb hisoblash."),

"AI axloqi: ma'lumot va maxfiylik": T(
 "Loyihadagi axloqiy masalalarni aniqlab, muhokama qilish",
 ["Ma'lumot yig'ishda rozilik kerak: odamning ovozi, tasviri yoki harakati uning shaxsiy ma'lumoti.",
  "Maxfiylik: TinyML ning muhim afzalligi — ma'lumot qurilmada qayta ishlanadi va internetga yuborilmaydi.",
  "Xolislik (bias): dataset bir guruh odamdan yig'ilsa, model boshqalarda yomon ishlaydi. Bu real muammo — yuzni tanish tizimlarida ko'p uchragan.",
  "Mas'uliyat: model xato qilsa kim javobgar? Bu savolga oldindan javob bo'lishi kerak."],
 "Xolislik masalasini o'z datasetlari misolida ko'rsating: agar hamma namuna bir necha o'quvchidan olingan bo'lsa, model boshqalarda yomon ishlaydi. Bu tushunchani shaxsiy tajribaga bog'laydi.",
 [("TinyML ning maxfiylik bo'yicha afzalligi nima?", "Ma'lumot qurilmada qayta ishlanadi, internetga yuborilmaydi."),
  ("Xolislik (bias) qanday paydo bo'ladi?", "Dataset bir xil guruhdan yig'ilsa.")],
 "Ma'lumot yig'ishda rozilik masalasini e'tiborsiz qoldirish."),

# ==================================================== 4-CHORAK: AI qurilmasi — ovoz va tasvir
"XIAO ESP32S3 Sense bilan tanishuv": T(
 "XIAO platasini ulab, kamera va mikrofonini sinab ko'rish",
 ["XIAO ESP32S3 Sense — juda kichik (21x17,5 mm), lekin kamera va mikrofoni bor plata.",
  "ESP32-S3 protsessori: 240 MHz ikki yadro, 8 MB PSRAM, 8 MB flesh. AI hisoblari uchun maxsus buyruqlar bor.",
  "PSRAM muhim: kamera tasviri katta joy egallaydi va oddiy SRAM yetmaydi.",
  "Kamera va mikrofon kengaytirish platasida — u asosiy plataga ulanadi."],
 "Plataning o'lchamini ko'rsating — bunday kichik qurilmada AI ishlashi o'quvchilarni hayratlantiradi va texnologiya rivojini his qildiradi.",
 [("XIAO ESP32S3 Sense da nima bor?", "Kamera va mikrofon."),
  ("PSRAM nima uchun kerak?", "Kamera tasviri katta joy egallaydi.")],
 "Kengaytirish platasini noto'g'ri ulash — kamera ishlamaydi."),

"Mikrofondan ovoz ma'lumotini olish": T(
 "Mikrofondan ovoz yozib, to'lqin shaklini kuzatish",
 ["PDM mikrofon raqamli signal beradi. Kutubxona namunalarni buferga yig'adi.",
  "Namuna olish chastotasi: nutq uchun odatda 16 kHz yetarli (telefon sifati).",
  "Bir sekundlik yozuv 16000 namuna beradi — bu katta hajm, shuning uchun PSRAM kerak.",
  "Ovoz ma'lumoti to'g'ridan-to'g'ri modelga berilmaydi: undan spektrogramma (chastotalar taqsimoti) hisoblanadi."],
 "Spektrogramma tushunchasini oddiy tushuntiring: tovushni chastotalarga ajratib, vaqt bo'yicha rasm qilish. Bu belgi ajratishning eng aniq misoli.",
 [("Nutq uchun qanday namuna chastotasi yetarli?", "16 kHz."),
  ("Ovozdan qanday belgi ajratiladi?", "Spektrogramma — chastotalar taqsimoti.")],
 "Xom ovoz ma'lumotini to'g'ridan-to'g'ri modelga berish."),

"Ovoz buyruqlari uchun ma'lumot to'plash": T(
 "Uch ovozli buyruq uchun namunalar yig'ib, dataset tuzish",
 ["Har buyruq uchun kamida 50 namuna kerak. Ko'proq bo'lsa yaxshiroq.",
  "Turli odamlar aytishi shart: bir odamdan yig'ilgan dataset boshqalarda ishlamaydi.",
  "\"Boshqa\" (noise) sinfi ham kerak: fon shovqini, boshqa so'zlar, jimlik. Usiz model har tovushni buyruq deb taniydi.",
  "Namuna uzunligi bir xil (odatda 1 sekund) va buyruq o'rtada bo'lishi kerak."],
 "\"Boshqa\" sinfining zarurligini ta'kidlang — bu eng ko'p unutiladigan va eng muhim sinf. Usiz tizim amalda ishlamaydi.",
 [("Nega \"boshqa\" sinfi kerak?", "Model buyruq bo'lmagan tovushlarni ajratishi uchun."),
  ("Nega turli odamlardan yig'iladi?", "Model faqat bir ovozga moslashib qolmasligi uchun.")],
 "\"Boshqa\" sinfini yig'masdan model o'rgatish."),

"Ovoz modelini o'rgatish": T(
 "Ovoz tanish modelini o'rgatib, natijalarni tahlil qilish",
 ["Ovoz uchun Edge Impulse da MFCC yoki MFE belgi ajratish bloki tanlanadi — u spektrogramma hisoblaydi.",
  "Model turi: nutq uchun odatda 1D yoki 2D konvolyutsion tarmoq.",
  "O'rgatishdan keyin chalkashlik matritsasi ko'riladi: qaysi buyruqlar adashtirilmoqda.",
  "O'xshash tovushli buyruqlar (masalan \"yoq\" va \"och\") ko'p adashtiriladi — buyruqlarni bir-biridan farqli tanlash kerak."],
 "Buyruq tanlash bo'yicha maslahat bering: bo'g'inlar soni va tovushlari farqli bo'lsin. Bu model sifatini oshirishning eng arzon usuli.",
 [("Ovoz uchun qanday belgi ajratish ishlatiladi?", "MFCC yoki MFE — spektrogramma asosida."),
  ("Qanday buyruqlar tanlanishi kerak?", "Bir-biridan tovushi bilan aniq farq qiladigan.")],
 "O'xshash tovushli buyruqlarni tanlash — model ularni ajrata olmaydi."),

"Ovoz bilan boshqarish (keyword spotting)": T(
 "Ovoz buyruqlari bilan qurilmani boshqaruvchi tizim yasash",
 ["Keyword spotting — uzluksiz oqimdan belgilangan so'zni topish.",
  "Model uzluksiz ishlaydi va har oynada bashorat qiladi. Bu quvvat sarflaydi — batareyali qurilmada muhim masala.",
  "Ehtimollik chegarasi qo'yiladi (masalan 0,8): undan past bo'lsa buyruq qabul qilinmaydi.",
  "Tasdiqlash mexanizmi foydali: buyruq bajarilishidan oldin qurilma signal berib, tasdiqlashni kutadi."],
 "Ehtimollik chegarasini sozlash mashqini bering: past chegarada yolg'on ishga tushish ko'p, yuqorida esa buyruq tanilmaydi. Muvozanat topish — muhandislik qarori.",
 [("Keyword spotting nima?", "Uzluksiz oqimdan belgilangan so'zni topish."),
  ("Chegara past bo'lsa nima bo'ladi?", "Yolg'on ishga tushish ko'payadi.")],
 "Chegarani sozlamasdan qoldirish."),

"Kamera bilan tanishuv va rasm olish": T(
 "Kamerani ishga tushirib, rasm olib, sifatini baholash",
 ["Kamera moduli (OV2640) kengaytirish platasida. Ishga tushirish uchun konfiguratsiya sozlamalari kerak.",
  "Ruxsat (rezolyutsiya) tanlanadi: AI uchun odatda kichik o'lcham yetarli (96x96 yoki 160x120).",
  "Katta rasm ko'p xotira va vaqt talab qiladi. TinyML uchun kichik rasm ataylab tanlanadi.",
  "Yorug'lik sifatga juda ta'sir qiladi: yomon yorug'likda tasvir shovqinli bo'ladi va model xato qiladi."],
 "Kichik rasm (96x96) yetarli ekanini ko'rsating — o'quvchilar katta ruxsat kerak deb o'ylaydi, aslida AI uchun aksincha.",
 [("TinyML uchun qanday rasm o'lchami ishlatiladi?", "Kichik — masalan 96x96."),
  ("Nima tasvir sifatiga eng ko'p ta'sir qiladi?", "Yorug'lik.")],
 "Katta ruxsatli rasm olishga urinish — xotira yetmaydi."),

"Tasvir ma'lumotini to'plash": T(
 "Ikki-uch sinf uchun tasvir namunalarini to'plash",
 ["Har sinf uchun kamida 50-100 rasm kerak.",
  "Xilma-xillik: turli burchak, masofa, yorug'lik va fon. Bir xil sharoitda olingan rasmlar modelni cheklaydi.",
  "Fon muhim: agar bir sinf doim bir xil fonda suratga olinsa, model buyumni emas, fonni tanib qoladi.",
  "\"Boshqa\" sinfi (bo'sh fon, aloqasiz buyumlar) ham kerak."],
 "Fon muammosini ta'kidlang — bu klassik xato va uni ko'rsatish oson: model buyum o'rniga stol rangini tanib qoladi.",
 [("Har sinf uchun nechta rasm kerak?", "Kamida 50-100 ta."),
  ("Nega fon xilma-xil bo'lishi kerak?", "Model buyumni emas, fonni tanib qolmasligi uchun.")],
 "Har sinfni bir xil fonda suratga olish."),

"Tasvirni belgilash va tayyorlash": T(
 "To'plangan rasmlarni belgilab, o'rgatishga tayyorlash",
 ["Tasnif (classification) uchun har rasmga bitta sinf yorlig'i qo'yiladi.",
  "Obyekt aniqlash (object detection) uchun esa har buyumning joyi ham belgilanadi (ramka chiziladi).",
  "Rasmlar bir xil o'lchamga keltiriladi va rang formati tanlanadi: rangli (RGB) yoki oq-qora.",
  "Oq-qora kamroq ma'lumot va tezroq ishlaydi, lekin rang muhim bo'lsa (masalan meva pishganini aniqlash) rangli kerak."],
 "Rangli va oq-qora tanlovini vazifaga bog'lab tushuntiring — bu resurs va sifat orasidagi muhandislik kelishuvining aniq misoli.",
 [("Tasnif va obyekt aniqlash farqi nima?", "Tasnifda faqat sinf, obyekt aniqlashda joy ham belgilanadi."),
  ("Qachon oq-qora yetarli?", "Rang muhim bo'lmagan vazifalarda.")],
 "Rangni keraksiz joyda ishlatib, model hajmini oshirish."),

"Tasvir tanish modelini o'rgatish": T(
 "Tasvir tanish modelini o'rgatib, natijalarni baholash",
 ["Tasvir uchun konvolyutsion neyron tarmoq (CNN) ishlatiladi.",
  "Transfer learning usuli qulay: tayyor o'rgatilgan model asos qilib olinadi va faqat oxirgi qatlam qayta o'rgatiladi. Bu kam ma'lumot bilan yaxshi natija beradi.",
  "MobileNet — mobil qurilmalar uchun mo'ljallangan yengil model turi. Edge Impulse da mavjud.",
  "O'rgatish tasvir uchun ancha uzoq davom etadi — bir necha daqiqadan yarim soatgacha."],
 "Transfer learning g'oyasini oddiy tushuntiring: boshqa vazifada o'rgangan model \"ko'rish\" ni allaqachon biladi, unga faqat yangi sinflarni o'rgatish kerak.",
 [("Transfer learning nima?", "Tayyor o'rgatilgan modeldan foydalanib, faqat oxirgi qismini qayta o'rgatish."),
  ("Nega u foydali?", "Kam ma'lumot bilan yaxshi natija beradi.")],
 "Noldan model o'rgatishga urinish — kam ma'lumot bilan bu ishlamaydi."),

"Modelni qurilmaga yuklash va sinash": T(
 "Tasvir modelini XIAO ga yuklab, real sharoitda sinash",
 ["Model Arduino kutubxonasi sifatida yuklab olinadi va IDE ga qo'shiladi.",
  "Xotira cheklovi jiddiy: tasvir modeli katta bo'ladi. PSRAM yoqilgan bo'lishi kerak.",
  "Bir bashorat vaqti (inference time) o'lchanadi — u odatda 100-500 ms.",
  "Real sharoitdagi aniqlik test to'plamidagidan past bo'ladi. Buni sanab o'lchash kerak."],
 "Bashorat vaqtini o'lchatib ko'ring va sekundiga nechta kadr ishlashini hisoblang. Bu tizim imkoniyatlarini aniq baholashga o'rgatadi.",
 [("Bir bashorat qancha vaqt oladi?", "Odatda 100-500 millisekund."),
  ("Nega real aniqlik pastroq bo'ladi?", "Real sharoit datasetdan farq qiladi.")],
 "PSRAM ni yoqishni unutish — model yuklanmaydi."),

"Obyektni aniqlash (object detection) haqida": T(
 "Tasnif va obyekt aniqlash farqini misollarda tahlil qilish",
 ["Tasnif butun rasmga bitta yorliq beradi: \"bu rasmda olma bor\".",
  "Obyekt aniqlash esa buyumning JOYINI ham ko'rsatadi va bir necha buyumni bir vaqtda topadi.",
  "Obyekt aniqlash ancha ko'p resurs talab qiladi — mikrokontrollerda bu chegarada.",
  "FOMO (Faster Objects, More Objects) — Edge Impulse ning mikrokontroller uchun soddalashtirilgan usuli. U buyum markazini topadi, lekin aniq o'lchamini bermaydi."],
 "FOMO ning cheklovini (o'lcham berilmaydi) ochiq ayting — cheklovlarni bilish texnologiyani to'g'ri qo'llashning sharti.",
 [("Obyekt aniqlash tasnifdan nimasi bilan farq qiladi?", "Buyumning joyini ham ko'rsatadi."),
  ("FOMO nima beradi?", "Buyum markazini, lekin aniq o'lchamini emas.")],
 "Mikrokontrollerda to'liq obyekt aniqlash modelini ishlatishga urinish — resurs yetmaydi."),

"Modelni siqish (quantization) nima uchun kerak": T(
 "Kvantlangan va kvantlanmagan modelni solishtirib, hajm va tezlik farqini o'lchash",
 ["Kvantlash — model parametrlarini kamroq joy egallaydigan formatga o'tkazish: float32 dan int8 ga.",
  "Natijada model hajmi 4 marta kamayadi va hisoblash sezilarli tezlashadi.",
  "Aniqlik biroz pasayadi (odatda 1-2%), lekin mikrokontrollerda bu almashuv deyarli har doim foydali.",
  "Edge Impulse da ikkala variant ham ko'rsatiladi: hajm, tezlik va aniqlik bo'yicha solishtirish mumkin."],
 "Ikki variantni jadval qilib solishtiring: hajm, tezlik, aniqlik. Bu muhandislik kelishuvini raqamlar bilan ko'rsatadi.",
 [("Kvantlash nima qiladi?", "Model parametrlarini kamroq joy egallaydigan formatga o'tkazadi."),
  ("Hajm qancha kamayadi?", "Taxminan 4 marta.")],
 "Kvantlashsiz modelni mikrokontrollerga yuklashga urinish."),

"AI + IoT: natijani internetga yuborish": T(
 "AI natijasini bulutga yoki Telegram'ga yuboradigan tizim yasash",
 ["Arxitektura: qurilmada model ishlaydi, faqat NATIJA internetga yuboriladi.",
  "Bu TinyML ning asosiy afzalligi: xom ma'lumot (ovoz, tasvir) qurilmada qoladi va maxfiylik saqlanadi.",
  "Trafik ham keskin kamayadi: rasm o'rniga bir necha bayt natija yuboriladi.",
  "Yuborish faqat muhim hodisada bo'lishi kerak — har bashoratni yuborish tarmoqni va batareyani behuda sarflaydi."],
 "\"Xom ma'lumot emas, natija yuboriladi\" tamoyilini ta'kidlang — bu Edge AI ning butun mohiyati va uni tushunish muhim.",
 [("Nima internetga yuboriladi?", "Faqat model natijasi, xom ma'lumot emas."),
  ("Bu qanday afzallik beradi?", "Maxfiylik saqlanadi va trafik kamayadi.")],
 "Har bashoratni internetga yuborish — trafik va batareya behuda sarflanadi."),

"Loyiha g'oyasini tanlash va rejalashtirish": T(
 "Yakuniy loyiha uchun g'oya tanlab, texnik topshiriq yozish",
 ["G'oya tanlash mezonlari: real muammoni hal qiladimi, mavjud jihoz bilan bajarilamimi, vaqtga ulguriladimi.",
  "AI haqiqatan kerakmi degan savolga javob berish shart: agar oddiy shart bilan hal bo'lsa, AI ortiqcha murakkablik.",
  "Texnik topshiriqda o'lchanadigan talablar: aniqlik foizi, javob vaqti, ishlash muddati.",
  "Bosqichlarga bo'lish: har bosqich mustaqil sinaladigan bo'lsin."],
 "\"AI haqiqatan kerakmi?\" savolini har g'oya uchun so'rang. Bu muhandislik yetukligining belgisi va ortiqcha murakkablikning oldini oladi.",
 [("G'oya tanlashda qanday savol beriladi?", "AI haqiqatan kerakmi yoki oddiy shart yetarlimi."),
  ("Talablar qanday yozilishi kerak?", "O'lchanadigan raqamlar bilan.")],
 "AI ni ko'rsatish uchun uni kerak bo'lmagan joyga qo'shish."),

"Prototipni yig'ish": T(
 "Loyiha prototipini bosqichma-bosqich yig'ib, har bosqichni sinash",
 ["Yig'ish tartibi: avval sensor va kirish qismi, keyin AI model, oxirida chiqish va aloqa.",
  "Har bosqich alohida sinaladi. AI modelini qo'shishdan oldin ma'lumot to'g'ri kelayotganini tekshirish shart.",
  "Xotira va quvvat cheklovlari doim nazarda tutiladi: AI modeli ko'p xotira va quvvat talab qiladi.",
  "Har bosqichda kod nusxasi saqlanadi."],
 "AI qismini oxirida qo'shishni tavsiya qiling — avval ma'lumot oqimi ishlashiga ishonch hosil qilish kerak, aks holda xato qayerda ekani noma'lum bo'ladi.",
 [("Yig'ish qaysi tartibda olib boriladi?", "Kirish, keyin model, oxirida chiqish."),
  ("AI dan oldin nima tekshiriladi?", "Ma'lumot to'g'ri kelayotgani.")],
 "AI modelini birinchi qo'shib, ma'lumot oqimini tekshirmaslik."),

"Modelni o'rgatish va sozlash": T(
 "Loyiha uchun modelni o'rgatib, parametrlarni sozlash sikli",
 ["O'rgatish sikli: ma'lumot yig'ish, o'rgatish, baholash, kamchilikni aniqlash, ma'lumot yoki parametrni o'zgartirish, qayta o'rgatish.",
  "Har urinish natijasi jadvalga yoziladi: versiya, o'zgarish, aniqlik, model hajmi, bashorat vaqti.",
  "Bir vaqtda faqat bitta narsa o'zgartiriladi — aks holda nima yordam berganini bilib bo'lmaydi.",
  "To'xtash mezoni oldindan belgilanadi: masalan test aniqligi 85% dan oshsa yetarli."],
 "Tajriba jadvalini yuritishni majburiy qiling. Bu ilmiy usulning amaliy ko'rinishi va natijani takrorlanadigan qiladi.",
 [("Nega bir vaqtda bitta narsa o'zgartiriladi?", "Nima yordam berganini aniq bilish uchun."),
  ("Nega to'xtash mezoni oldindan belgilanadi?", "Cheksiz yaxshilashga urinmaslik uchun.")],
 "Tajribalarni yozib bormaslik — qaysi variant yaxshi bo'lganini eslab bo'lmaydi."),

"Tizimni sinash va o'lchash": T(
 "Tizimni real sharoitda sinab, ko'rsatkichlarni o'lchash",
 ["O'lchanadigan ko'rsatkichlar: real aniqlik, bashorat vaqti, quvvat iste'moli, uzluksiz ishlash muddati.",
  "Real aniqlik sanab o'lchanadi: 30-50 marta sinab, nechtasi to'g'ri bo'lganini yozish.",
  "Chetki holatlar sinaladi: yomon yorug'lik, shovqinli muhit, kutilmagan kirish.",
  "Uzoq muddatli sinov: xotira sizishi va barqarorlik muammolari faqat vaqt o'tgach ko'rinadi."],
 "Real aniqlikni sanab o'lchashni majburiy qiling — Edge Impulse dagi foiz real ishlashni ko'rsatmaydi va bu farqni bilish muhim.",
 [("Real aniqlik qanday o'lchanadi?", "Ko'p marta sinab, to'g'ri javoblarni sanab."),
  ("Nega uzoq muddatli sinov kerak?", "Ba'zi muammolar faqat vaqt o'tgach ko'rinadi.")],
 "Faqat platformadagi aniqlik foiziga tayanish."),

"Loyihani hujjatlashtirish": T(
 "AI loyihasi uchun to'liq texnik hujjat tayyorlash",
 ["AI loyihasi hujjatida qo'shimcha bo'limlar bor: dataset tavsifi, model arxitekturasi, o'rgatish parametrlari, baholash natijalari.",
  "Dataset tavsifi: nechta namuna, qanday sinflar, kim va qanday sharoitda yig'gan.",
  "Baholash: aniqlik, chalkashlik matritsasi, real sinov natijalari.",
  "Cheklovlar bo'limi majburiy: model qanday sharoitda ishlamaydi, qanday xatolar kutiladi."],
 "Cheklovlar bo'limini majburiy qiling — AI tizimlarining chegaralarini ochiq aytish professional va axloqiy talab.",
 [("AI hujjatida qanday qo'shimcha bo'limlar bor?", "Dataset tavsifi, model va baholash natijalari."),
  ("Nega cheklovlar yoziladi?", "Tizim chegaralarini ochiq ko'rsatish uchun.")],
 "Faqat yaxshi natijalarni yozib, cheklovlarni yashirish."),
}
