# -*- coding: utf-8 -*-
"""1-yil, 6-sinf — elektronika (chuqurroq). 72 mavzu uchun aniq kontent."""

from kb_5_8 import T

MAVZULAR = {

# ==================================================== 1-CHORAK: Elektr va sxema tili
"Atom, elektron va zaryad": T(
 "Atom modelini chizib, o'tkazgich va izolyatorda elektronlar holatini taqqoslash",
 ["Atom yadro (proton va neytron) va uning atrofidagi elektronlardan iborat. Proton musbat, elektron manfiy, neytron zaryadsiz.",
  "Neytral atomda proton va elektron soni teng. Elektron qo'shilsa manfiy ion, ajralsa musbat ion hosil bo'ladi.",
  "Metallda tashqi elektronlar atomga kuchsiz bog'langan — ular kristall panjara ichida erkin harakatlanadi. Bu \"elektron gaz\" deb ataladi.",
  "Zaryad birligi — kulon (Kl). Bitta elektronning zaryadi 1,6 x 10 daraja -19 Kl, ya'ni 1 kulonda 6 kvintillion elektron bor."],
 "Kimyo darsidagi atom tuzilishi bilan bevosita bog'lang. Elektronika fizika va kimyoning davomi ekanini o'quvchilar shu darsda ko'rishi kerak.",
 [("Neytral atomda nima teng bo'ladi?", "Proton va elektron soni."),
  ("Metallda elektronlar nima uchun erkin?", "Tashqi elektronlar atomga kuchsiz bog'langan.")],
 "Zaryadni \"modda\" deb tasavvur qilish — zaryad moddaning xossasi, alohida modda emas."),

"Elektr toki: zaryadning yo'naltirilgan harakati": T(
 "Turli kesimdagi simlarda bir xil kuchlanishda tokni o'lchab solishtirish",
 ["Quvvat berilmagan metallda elektronlar tartibsiz harakatlanadi — umumiy siljish nolga teng.",
  "Kuchlanish berilganda ular tartibsiz harakatni saqlagan holda bir tomonga sekin siljiydi. Bu siljish tezligi juda kichik — soatiga bir necha santimetr.",
  "Lekin chiroq darhol yonadi, chunki elektr maydoni deyarli yorug'lik tezligida tarqaladi va hamma elektronlar bir vaqtda siljiy boshlaydi.",
  "Tok kuchi I = q / t: bir sekundda kesim orqali o'tgan zaryad miqdori. 1 A = 1 sekundda 1 kulon."],
 "\"Elektron sekin, signal tez\" paradoksini albatta ayting — quvurdagi suv o'xshatishi bilan tushuntirsa bo'ladi: kranni ochsangiz suv darhol chiqadi, garchi quvur boshidagi tomchi hali yetib kelmagan bo'lsa ham.",
 [("Elektronlarning siljish tezligi qanaqa?", "Juda kichik, soatiga bir necha santimetr."),
  ("Nega chiroq darhol yonadi?", "Elektr maydoni deyarli yorug'lik tezligida tarqaladi.")],
 "Elektronlar simda yorug'lik tezligida uchadi deb o'ylash."),

"Kuchlanish: zaryadni harakatlantiruvchi kuch": T(
 "Bir necha manbaning kuchlanishini o'lchab, zanjirdagi kuchlanish taqsimotini kuzatish",
 ["Kuchlanish — bir kulon zaryadni bir nuqtadan ikkinchisiga ko'chirishda bajarilgan ish: U = A / q. Birligi volt.",
  "Kuchlanish har doim IKKI nuqta orasida. \"Shu nuqtada 5 V\" degani aslida \"shu nuqta bilan GND orasida 5 V\" degani.",
  "Manba kuchlanishi (EYuK) va zanjirdagi kuchlanish farq qiladi: manbaning ichki qarshiligida ham bir qismi yo'qoladi.",
  "Kuchlanishning boshqa nomlari: potensiallar farqi, taranglik. Sxemada V yoki U harfi bilan belgilanadi."],
 "\"Nuqtadagi kuchlanish\" iborasi noto'g'ri ekanini bir necha marta takrorlang. Bu tushuncha 5-sinfda ham berilgan, 6-sinfda uni formula darajasida mustahkamlash kerak.",
 [("Kuchlanish formulasi qanday?", "U = A / q, ya'ni ish bo'linadi zaryadga."),
  ("\"Shu nuqtada 5 V\" iborasi to'liq qanday aytiladi?", "Shu nuqta bilan GND orasida 5 V.")],
 "Kuchlanishni tok bilan chalkashtirish: \"5 voltlik tok\" degan ifoda noto'g'ri."),

"Tok manbalari: batareya, akkumulyator, adapter": T(
 "Uch xil manbaning kuchlanishi va yuklamadagi cho'kishini o'lchab, jadval tuzish",
 ["Batareya (bir marta ishlatiladigan) — kimyoviy reaksiya qaytmas, tugagach tashlanadi. AA, AAA, krona.",
  "Akkumulyator qayta zaryadlanadi: Li-ion 3,7 V, NiMH 1,2 V. Zaryadlash uchun maxsus kontroller kerak, aks holda yong'in xavfi bor.",
  "Adapter (blok pitaniya) 220 V ni past kuchlanishga aylantiradi. Uning quvvati amper bilan yozilgan: 5V 2A = 10 vatt.",
  "Har manbaning ichki qarshiligi bor: batareyada katta (bir necha om), adapterda juda kichik. Shuning uchun motorli qurilmalar adapterdan barqarorroq ishlaydi."],
 "Li-ion akkumulyatorlarni sinfda o'quvchilarga bermang — noto'g'ri ishlatilsa yonish xavfi bor. Ular haqida faqat gapiring va tayyor korpusdagi power bankni ko'rsating.",
 [("Li-ion akkumulyatorning nominal kuchlanishi qancha?", "3,7 V."),
  ("Adapterdagi 5V 2A nimani bildiradi?", "5 volt kuchlanish, 2 ampergacha tok bera oladi.")],
 "Akkumulyatorni oddiy batareya deb hisoblab, uni to'g'ridan-to'g'ri manbaga ulash."),

"Zanjir elementlari va ularning shartli belgilari": T(
 "15 ta shartli belgini yod olib, tanish testini bajarish",
 ["Har bir komponentning xalqaro standart belgisi bor (IEC 60617). Bu belgilar tilga bog'liq emas.",
  "Asosiylari: rezistor — to'rtburchak; kondensator — ikki parallel chiziq (qutbli bo'lsa biri egri); diod — uchburchak va chiziq; tranzistor — doira ichida uch chiziq; kalit — uzilgan chiziq.",
  "Manba: uzun va kalta chiziq (uzun = musbat). Yer (GND) — uch pog'onali qisqaruvchi chiziqlar.",
  "Belgilarni yodlash shart, chunki sxemani o'qish kurs davomida har darsda kerak bo'ladi."],
 "Belgilar kartochkasini tayyorlang va har darsning boshida 2 daqiqalik tez so'rov o'tkazing. Yodlash bir necha takrorlash bilan avtomatlashadi.",
 [("Sxemada uzun chiziq manbaning qaysi qutbi?", "Musbat."),
  ("Nega belgilar xalqaro standartlashtirilgan?", "Har mamlakat muhandisi bir-birining sxemasini tarjimasiz o'qishi uchun.")],
 "Belgilarni o'zicha o'ylab chiqarish yoki kitobdagidan boshqacha chizish."),

"Printsipial sxemani o'qish": T(
 "Berilgan uch sxemani og'zaki tavsiflab, qanday ishlashini tushuntirish",
 ["Sxemani o'qish tartibi: 1) manbani topish, 2) tokning yo'lini kuzatish, 3) har tarmoqni alohida ko'rib chiqish, 4) boshqaruv elementlarini aniqlash.",
  "Sxemada tok yo'nalishi odatda yuqoridan pastga, chapdan o'ngga chiziladi. Bu o'qishni osonlashtiradigan kelishuv.",
  "Nuqta bilan kesishgan simlar ulangan, nuqtasiz kesishganlari ulanmagan. Zamonaviy sxemalarda ulanmagan simlar ko'pincha umuman kesishtirilmaydi.",
  "Sxemani \"gapirib\" o'qish foydali: \"manbadan tok R1 orqali tranzistor bazasiga boradi...\""],
 "Har bir o'quvchi sxemani OVOZ CHIQARIB o'qib bersin. Ovoz chiqarib o'qish tushunmagan joyni darhol ochib beradi.",
 [("Sxema o'qishni nimadan boshlash kerak?", "Manbani topishdan."),
  ("Kesishgan simlarda nuqta bo'lsa nima degani?", "Ular o'zaro ulangan.")],
 "Sxemani rasm sifatida ko'rib, joylashuvni ulanish deb tushunish."),

"Sxemani chizish: o'z zanjiringni qog'ozda": T(
 "Breadboardda yig'ilgan zanjirni sxemaga aylantirib chizish",
 ["Yig'ilgan zanjirdan sxema chizish tartibi: har bir ulanishni topib, komponentlar orasidagi bog'lanishlar ro'yxatini tuzish, keyin uni tartibli chizmaga aylantirish.",
  "Chizmada joylashuv erkin: komponentni istalgan joyga qo'yish mumkin, faqat ulanishlar to'g'ri bo'lsin.",
  "Yaxshi sxemada simlar kam kesishadi va o'qish yo'nalishi (chapdan o'ngga) saqlanadi.",
  "Har komponentga belgi va nominal yoziladi: R1 220 Om, D1 LED qizil, Q1 BC547."],
 "Bir xil zanjirni ikki o'quvchi chizib, sxemalarini solishtirsin. Turli ko'rinishdagi ikki sxema bir xil zanjirni ifodalashi mumkinligi muhim kashfiyot bo'ladi.",
 [("Sxemada komponentlar joylashuvi muhimmi?", "Yo'q, faqat ulanishlar to'g'ri bo'lishi kerak."),
  ("Q1 belgisi odatda nimani bildiradi?", "Tranzistorni.")],
 "Sxemani breadboarddagi joylashuvni aynan takrorlab chizish."),

"Breadboard: ichki ulanishlar xaritasi": T(
 "Multimetr bilan breadboardni to'liq tekshirib, ichki ulanishlar xaritasini chizish",
 ["Standart breadboardda 830 teshik bor: o'rta qismda 63 ustun x 2 tomon x 5 teshik, chetlarda 4 ta quvvat shinasi.",
  "Ba'zi breadboardlarda quvvat shinasi o'rtasidan uzilgan bo'ladi — buni albatta tekshirish kerak, aks holda taxtaning yarmiga quvvat bormaydi.",
  "Kontaktlar cheklangan resursga ega: qalin oyoqli komponentlar (masalan yo'g'on simlar) ularni kengaytirib, keyingi komponent uchun kontakt yomonlashadi.",
  "Breadboard yuqori chastota va katta tok uchun mos emas: kontaktlarning qarshiligi bor va 1-2 A dan yuqori tok kontaktni qizdiradi."],
 "Quvvat shinasi uzilgan-uzilmaganini har bir taxtada tekshirtiring. Bu sinfdagi eng ko'p vaqt yo'qotadigan \"sirli nosozlik\" ning asosiy sababi.",
 [("Breadboard quvvat shinasi doim uzluksizmi?", "Yo'q, ba'zilarida o'rtadan uzilgan bo'ladi."),
  ("Nega breadboard katta tok uchun mos emas?", "Kontaktlarning qarshiligi bor, ular qiziydi.")],
 "Yo'g'on simlarni breadboardga tiqish — kontaktlar kengayib, taxta ishdan chiqadi."),

"Rezistor: vazifasi va rangli kodi": T(
 "4 va 5 halqali rezistorlarni o'qib, o'lchov bilan tekshirish",
 ["Rezistorning uch vazifasi: tokni cheklash, kuchlanishni bo'lish va pin holatini aniq ushlab turish (tortuvchi rezistor).",
  "5 halqali rezistorda uchta raqam halqasi bor — u aniqroq (odatda 1%). Masalan jigarrang-qora-qora-jigarrang = 100 va bitta nol = 1000 Om.",
  "Rezistorlar standart qatorda ishlab chiqariladi (E12, E24): 10, 12, 15, 18, 22, 27, 33, 39, 47, 56, 68, 82 va ularning o'nlik ko'paytmalari.",
  "Shuning uchun hisobda 193 Om chiqsa, sotuvda 180 yoki 220 Om bor — yaqinini tanlashga to'g'ri keladi."],
 "E12 qatorini doskaga yozib qo'ying va hisoblangan qiymatlarni doim shu qatorga moslashni odat qiling. Bu haqiqiy muhandislik ko'nikmasi.",
 [("5 halqali rezistorda nechta raqam halqasi bor?", "Uchta."),
  ("Hisobda 193 Om chiqsa qaysi rezistor olinadi?", "220 Om — eng yaqin standart qiymat, tokni kamaytirish tomoniga.")],
 "Standart qator borligini bilmay, aniq hisoblangan qiymatni izlashga urinish."),

"Rezistor nominalini hisoblash mashqlari": T(
 "20 ta rangli kodni o'qib, teskarisini ham bajarish: berilgan qiymatga rang tanlash",
 ["Teskari masala ham muhim: 4,7 kOm ni rangda yozish uchun 4-7-uchta nol = sariq-binafsha-qizil.",
  "kOm va MOm ni Om ga aylantirish: 1 kOm = 1000 Om, 1 MOm = 1 000 000 Om.",
  "Qisqartma yozuv: 4k7 = 4,7 kOm, 1M2 = 1,2 MOm. Harf vergul o'rnida turadi — bu chizmada vergul ko'rinmay qolishining oldini oladi.",
  "Rezistor qiymatini ko'z bilan taxminlash ko'nikmasi ham foydali: uchinchi halqa qizil bo'lsa yuzlar, to'q sariq bo'lsa minglar tartibida."],
 "Teskari masalani (qiymatdan rangga) albatta bering — bu tushunganini tekshirishning eng ishonchli usuli.",
 [("4,7 kOm rangda qanday yoziladi?", "Sariq-binafsha-qizil."),
  ("1M2 nimani bildiradi?", "1,2 MOm.")],
 "kOm ni Om ga aylantirishda nolni kam yoki ko'p qo'yish."),

"LED: yarimo'tkazgichli yorug'lik manbai": T(
 "Turli rangli LEDlarning tushish kuchlanishini o'lchab, rang bilan bog'liqligini aniqlash",
 ["LED ichida p-n o'tish bor. Elektron teshik bilan birlashganda energiya ajraladi va u FOTON ko'rinishida chiqadi.",
  "Ajraladigan energiya yarimo'tkazgich materialiga bog'liq, energiya esa rangni belgilaydi. Shuning uchun har rang uchun boshqa material ishlatiladi.",
  "Energiya katta bo'lsa (ko'k, binafsha) tushish kuchlanishi ham katta (3-3,4 V), kichik bo'lsa (qizil, infraqizil) kichik (1,6-2 V).",
  "Oq LED aslida ko'k LED — uning ustiga sariq lyuminofor qoplanadi, ko'k va sariq qo'shilib oq hosil qiladi."],
 "Oq LEDning \"siri\" (ko'k + lyuminofor) o'quvchilarni har doim hayratlantiradi. Buni ayting va ko'k rangni lyuminofor orqali ko'rsatishga urinib ko'ring.",
 [("LEDda yorug'lik qanday hosil bo'ladi?", "Elektron teshik bilan birlashganda foton ajraladi."),
  ("Oq LED aslida qanday ishlaydi?", "Ko'k LED ustiga sariq lyuminofor qoplanadi.")],
 "Barcha LEDlarga bir xil rezistor tanlash — ranglarga qarab kuchlanish farq qiladi."),

"LED uchun rezistorni hisoblash": T(
 "Uch xil manba kuchlanishi uchun bir xil LEDga rezistor hisoblab, jadval tuzish",
 ["Formula: R = (U manba - U led) / I led. Natija omda chiqadi.",
  "Manba o'zgarsa rezistor ham o'zgaradi: 5 V da qizil LED uchun 200 Om, 9 V da (9-2)/0,015 = 467 Om, 12 V da 667 Om.",
  "Rezistorda ajraladigan quvvatni ham tekshirish kerak: P = U x I = 7 V x 0,015 A = 0,105 Vt. Odatiy 0,25 Vt rezistor bunga chidaydi.",
  "Agar quvvat 0,25 Vt dan oshsa, kuchliroq rezistor (0,5 yoki 1 Vt) olish yoki sxemani o'zgartirish kerak."],
 "Quvvat tekshiruvini shu darsda kiriting — 5-sinfda faqat tok hisoblangan edi, 6-sinfda quvvat qo'shilishi mavzuni bir pog'ona yuqoriga ko'taradi.",
 [("12 V da qizil LED (2 V, 15 mA) uchun rezistor?", "(12-2)/0,015 = 667 Om, ya'ni 680 Om."),
  ("Rezistorda ajraladigan quvvat qanday hisoblanadi?", "P = U x I, bunda U — rezistordagi kuchlanish.")],
 "Quvvatni tekshirmaslik — yuqori kuchlanishli zanjirda rezistor qizib ketadi."),

"Ketma-ket ulanish qonuniyatlari": T(
 "Uch rezistorli ketma-ket zanjirda barcha kattaliklarni hisoblab, o'lchov bilan solishtirish",
 ["Uch qonuniyat: I bir xil; U qo'shiladi (U = U1 + U2 + U3); R qo'shiladi (R = R1 + R2 + R3).",
  "Undan kelib chiqadi: eng katta rezistorga eng katta kuchlanish tushadi. Bu tekshirishning tez usuli.",
  "Ketma-ket zanjirning kamchiligi: bitta element uzilsa hammasi to'xtaydi. Eski yangi yil girlyandalari shuning uchun noqulay edi.",
  "Afzalligi: tokni cheklash oson va kuchlanishni kerakli nisbatda bo'lish mumkin."],
 "Hisoblangan va o'lchangan qiymatlarni yonma-yon jadvalga yozdiring. Ikki ustunning mos kelishi nazariyaga ishonch hosil qiladi.",
 [("Ketma-ket zanjirda umumiy qarshilik qanday topiladi?", "Qarshiliklar qo'shiladi."),
  ("Qaysi rezistorga eng katta kuchlanish tushadi?", "Eng katta qarshilikka ega bo'lganiga.")],
 "Kuchlanishlar yig'indisini tekshirmaslik — bu hisobdagi xatoni topishning eng oson usuli."),

"Parallel ulanish qonuniyatlari": T(
 "Uch tarmoqli parallel zanjirni hisoblab, umumiy qarshilikni o'lchov bilan tekshirish",
 ["Uch qonuniyat: U bir xil; I qo'shiladi (I = I1 + I2 + I3); qarshilik uchun 1/R = 1/R1 + 1/R2 + 1/R3.",
  "Ikki rezistor uchun qulay formula: R = (R1 x R2) / (R1 + R2).",
  "Umumiy qarshilik har doim eng KICHIK tarmoq qarshiligidan ham kichik bo'ladi — bu javobni tekshirishning tez usuli.",
  "N ta bir xil rezistor parallel bo'lsa: R = R1 / N. Uchta 300 Om = 100 Om."],
 "\"Javob eng kichik rezistordan kichik bo'lishi kerak\" qoidasini har hisobdan keyin tekshirtiring — ko'p xatolar shu tekshiruvda topiladi.",
 [("100 va 100 Om parallel bo'lsa qancha?", "50 Om."),
  ("Umumiy qarshilik eng kichik tarmoqdan katta chiqsa nima demak?", "Hisobda xato bor.")],
 "Parallel qarshilikni ham qo'shib yuborish — bu eng ko'p uchraydigan xato."),

"Aralash (ketma-ket + parallel) ulanish": T(
 "To'rt rezistorli aralash zanjirni bosqichma-bosqich soddalashtirib hisoblash",
 ["Aralash zanjir bosqichma-bosqich soddalashtiriladi: avval parallel guruhlar bitta ekvivalent qarshilikka aylantiriladi, keyin ketma-ket qo'shiladi.",
  "Misol: R1 ketma-ket, keyin R2 va R3 parallel. Avval R23 = R2xR3/(R2+R3), keyin R umumiy = R1 + R23.",
  "Har bosqichda soddalashtirilgan sxemani qayta chizib borish kerak — bu chalkashishning oldini oladi.",
  "Toklar va kuchlanishlarni topish teskari yo'nalishda: umumiy tokdan boshlab, orqaga qarab har bir tarmoqqa taqsimlanadi."],
 "Har bosqichda sxemani qayta chizishni MAJBURIY qiling. Faqat boshda qiyin ko'rinadi, keyin bu usul har qanday murakkab zanjirni yechish kalitiga aylanadi.",
 [("Aralash zanjirni yechish nimadan boshlanadi?", "Parallel guruhlarni ekvivalent qarshilikka aylantirishdan."),
  ("200 va 200 Om parallel, ularga 100 Om ketma-ket. Umumiy?", "100 + 100 = 200 Om.")],
 "Barcha qarshiliklarni bir yo'la qo'shib yuborish, tuzilmani hisobga olmaslik."),

"Tugma, kalit va jamper: zanjirni boshqarish": T(
 "Uch xil boshqarish elementini bir zanjirda ishlatib, farqlarini jadvalga yozish",
 ["Tugma — momentiy kontakt, faqat bosilganda ulanadi. Kalit — holat saqlaydi. Jamper — qo'lda o'rnatiladigan doimiy ulanish.",
  "Jamper konfiguratsiya uchun ishlatiladi: qurilma yig'ilgach bir marta qo'yiladi va odatda o'zgartirilmaydi (masalan manzil tanlash).",
  "Kalit turlari belgilanadi: SPST (bir tomonlama oddiy), SPDT (bir tomonlama ikki holatli), DPDT (ikki tomonlama ikki holatli).",
  "DPDT kalit bilan motorning yo'nalishini almashtirish mumkin, chunki u bir vaqtda ikkala simni almashtira oladi."],
 "SPST/SPDT/DPDT belgilarini kartochkaga yozib bering. Bu qisqartmalar katalog o'qishda doim uchraydi.",
 [("Jamper nima uchun ishlatiladi?", "Bir marta o'rnatiladigan konfiguratsiya uchun."),
  ("Motor yo'nalishini almashtirish uchun qanday kalit kerak?", "DPDT.")],
 "SPDT kalitni motor yo'nalishini almashtirishga ishlatishga urinish — u faqat bitta simni almashtiradi, yetmaydi."),

"Montaj madaniyati: toza va tushunarli yig'ish": T(
 "Chalkash yig'ilgan zanjirni qayta, toza qoidalar bo'yicha yig'ish va vaqtni solishtirish",
 ["Beshta qoida: simlar qisqa; ranglar mantiqli (qizil = +, qora = GND, boshqa ranglar = signal); simlar taxta ustidan o'tmaydi; komponentlar bir yo'nalishda; ulanmagan oyoqlar kesilgan.",
  "Toza montaj vaqt tejaydi: nosozlik izlash bir necha barobar tezlashadi.",
  "Sim uzunligi kerakli masofadan 5-10 mm ortiq bo'lsin — juda tarang sim kontaktni tortadi, juda uzun sim chalkashadi.",
  "Sanoatda bu jiddiy talab: aviatsiya va tibbiy texnikada montaj sifati alohida tekshiriladi va hujjatlashtiriladi."],
 "Ikki zanjirni (chalkash va toza) yonma-yon qo'yib, ikkalasiga bir xil xato kiriting. Xatoni topish vaqtini o'lchang — farq o'zi hamma narsani aytadi.",
 [("Qaysi rang odatda GND uchun ishlatiladi?", "Qora."),
  ("Toza montaj nimani tezlashtiradi?", "Nosozlik izlashni.")],
 "Bir xil rangdagi simlar bilan butun zanjirni yig'ish — keyin qaysi sim qayerga borishini aniqlab bo'lmaydi."),

"Nosozlik topish usullari: bosqichma-bosqich tekshirish": T(
 "Uch xatoli zanjirni tizimli usul bilan tuzatib, har qadamni protokolga yozish",
 ["Tizimli tekshiruvning to'rt bosqichi: 1) ko'z bilan ko'rish, 2) quvvatni o'lchash, 3) zumlash bilan ulanishni tekshirish, 4) signalni bosqichma-bosqich kuzatish.",
  "Ko'z bilan ko'rish bosqichida topiladigan xatolar: teskari qutb, kuygan komponent, tegib turgan oyoqlar, chala kirgan sim. Bu eng tez bosqich.",
  "Protokol yuritish shart: nima tekshirildi, natija qanday. Aks holda bir joyni ikki marta tekshirish va boshqasini umuman unutish yuz beradi.",
  "\"O'zgartirish - sinash\" siklida bir vaqtda FAQAT BITTA narsa o'zgartiriladi, aks holda nima yordam berganini bilib bo'lmaydi."],
 "Protokol shaklini tayyorlab tarqating (nima tekshirildi / natija / xulosa ustunlari bilan). Yozib borish odati muhandislik madaniyatining asosi.",
 [("Tekshiruvning birinchi bosqichi nima?", "Ko'z bilan ko'rish."),
  ("Nega bir vaqtda bitta narsa o'zgartiriladi?", "Aks holda nima yordam berganini aniqlab bo'lmaydi.")],
 "Protokolsiz ishlash — bir joy ikki marta tekshiriladi, boshqasi umuman tushib qoladi."),

# ==================================================== 2-CHORAK: Om qonuni, quvvat va energiya
"Multimetr tuzilishi va xavfsizlik qoidalari": T(
 "Multimetrni ochib (o'qituvchi namoyishida) ichki tuzilishini ko'rish va predoxranitelni topish",
 ["Multimetr ichida ADC (analog-raqamli aylantirgich), rejim tanlagich va o'lchov rezistorlari bor.",
  "Kuchlanish o'lchashda kirish qarshiligi 10 MOm — asbob zanjirdan deyarli tok olmaydi.",
  "Tok o'lchashda esa kirish qarshiligi juda kichik (shunt rezistor). Shuning uchun tok teshigidagi shchup bilan kuchlanish o'lchash qisqa tutashuvga olib keladi.",
  "Ichida ikki predoxranitel bor: 200 mA va 10 A uchun. Ular aynan shu xatodan himoya qiladi va kuysa almashtiriladi."],
 "Kuygan predoxranitelni ko'rsating va uni almashtirishni namoyish qiling. O'quvchilar xato oqibatini ko'rgach ehtiyotkorroq bo'ladi.",
 [("Kuchlanish rejimida multimetrning kirish qarshiligi qancha?", "Taxminan 10 MOm."),
  ("Tok teshigidagi shchup bilan kuchlanish o'lchansa nima bo'ladi?", "Qisqa tutashuv, predoxranitel kuyadi.")],
 "O'lchagandan keyin shchupni tok teshigida qoldirish — keyingi o'lchov asbobni kuydiradi."),

"Kuchlanishni o'lchash amaliyoti": T(
 "Aralash zanjirning 6 nuqtasida kuchlanishni o'lchab, sxemaga yozib chiqish",
 ["O'lchashda umumiy nuqta (GND) tanlanadi va qora shchup unda qoldiriladi. Qizil shchup bilan boshqa nuqtalar tekshiriladi.",
  "Bunda olingan qiymatlar POTENSIALLAR deyiladi — har bir nuqtaning GND ga nisbatan kuchlanishi.",
  "Komponentdagi kuchlanish — uning ikki uchidagi potensiallar farqi. Masalan A nuqtada 5 V, B da 3 V bo'lsa, ular orasidagi komponentda 2 V.",
  "Sxemaga o'lchangan qiymatlarni yozib borish — bu haqiqiy muhandislik odati, shunday sxema keyinchalik hujjat bo'lib qoladi."],
 "Bir GND nuqtasini tanlab, undan qimirlamaslikni qoida qiling. Har o'lchovda qora shchupni ko'chirish eng ko'p chalkashlik sababi.",
 [("Potensial nima?", "Nuqtaning GND ga nisbatan kuchlanishi."),
  ("A da 5 V, B da 3 V. Orasidagi komponentda qancha?", "2 V.")],
 "Har o'lchovda qora shchupni ham ko'chirish — natijalar bir-biriga bog'lanmaydi."),

"Qarshilikni o'lchash amaliyoti": T(
 "10 ta komponentning qarshiligini o'lchab, qaysilari rezistor emasligini aniqlash",
 ["Qarshilik faqat quvvatsiz va zanjirdan uzilgan komponentda aniq o'lchanadi.",
  "Ba'zi komponentlarning qarshiligi yo'nalishga bog'liq: diodni ikki tomondan o'lchasa turli natija chiqadi. Bu ularni tanib olish usuli.",
  "Motorning g'altak qarshiligi kichik (5-50 Om), rele g'altagi kattaroq (70-400 Om), lampochka soviq holatda kichik, qizib turganda katta.",
  "Kondensator o'lchanganda qiymat asta-sekin o'sib boradi va OL ga yetadi — bu uning zaryadlanayotganini bildiradi, nosozlik emas."],
 "Kondensatorni ommetrda o'lchab ko'rsating: raqamning sekin o'sishi va OL ga yetishi o'quvchilarga kondensatorning ishlashini yana bir tomondan ko'rsatadi.",
 [("Diodni ikki tomondan o'lchasa nima chiqadi?", "Bir tomonda kichik qarshilik, ikkinchisida OL."),
  ("Kondensatorni ommetrda o'lchasa raqam nega o'zgaradi?", "U asbob bergan tok bilan zaryadlanadi.")],
 "Zanjirdan uzmasdan o'lchash — yondosh komponentlar natijaga qo'shilib ketadi."),

"Tokni o'lchash amaliyoti": T(
 "Ketma-ket va parallel zanjirlarning har bir tarmog'ida tokni o'lchab, qonuniyatlarni tasdiqlash",
 ["Har o'lchash uchun zanjir uzilishi kerak — bu tokni o'lchashning asosiy noqulayligi.",
  "Shuning uchun amalda ko'pincha bilvosita usul ishlatiladi: ma'lum qarshilikdagi kuchlanish o'lchanadi va I = U / R bilan hisoblanadi.",
  "Parallel zanjirda umumiy tokni o'lchash uchun manba yonidan, tarmoq tokini o'lchash uchun tarmoqning ichidan uzish kerak.",
  "O'lchov chegarasini to'g'ri tanlash muhim: kutilgan qiymat noma'lum bo'lsa, eng katta chegaradan boshlab pastga tushiladi."],
 "Bilvosita usulni albatta ko'rsating — bu 7-8-sinfda tok o'lchash modullari (INA219) bilan ishlashning asosi.",
 [("Tokni bilvosita qanday o'lchash mumkin?", "Ma'lum rezistordagi kuchlanishni o'lchab, I = U/R bilan hisoblab."),
  ("Chegara noma'lum bo'lsa qaysi chegaradan boshlanadi?", "Eng kattasidan.")],
 "Kichik chegarada katta tokni o'lchashga urinish — predoxranitel kuyadi."),

"Om qonuni: formula va ma'nosi": T(
 "Doimiy kuchlanishda qarshilikni o'zgartirib, tokni o'lchash va grafik chizish",
 ["Om qonuni tajriba yo'li bilan topilgan: Georg Om 1827-yilda simning uzunligi va kesimi tokka qanday ta'sir qilishini o'rgangan.",
  "U = I x R munosabati o'tkazgichlar uchun to'g'ri, lekin hamma element uchun emas: diod, lampochka va tranzistor Om qonuniga bo'ysunmaydi (chiziqsiz elementlar).",
  "Grafikda: rezistor uchun U-I bog'liqligi to'g'ri chiziq, uning qiyaligi qarshilikni beradi. Lampochka uchun esa egri chiziq chiqadi.",
  "Chiziqsizlikning sababi: lampochka qizigan sari qarshiligi ortadi, chunki metallning qarshiligi haroratga bog'liq."],
 "Rezistor va lampochka uchun ikkita grafik chizdiring. Bir to'g'ri, bir egri chiziq — Om qonunining chegarasi shu bilan ko'rsatiladi.",
 [("Om qonuni hamma komponent uchun to'g'rimi?", "Yo'q, diod va lampochka kabi chiziqsiz elementlar bo'ysunmaydi."),
  ("Nega lampochka grafigi egri?", "Qizigan sari uning qarshiligi ortadi.")],
 "Om qonunini universal deb hisoblab, diod uchun ham qo'llashga urinish."),

"Om qonuni masalalari yechish": T(
 "15 ta masalani yechib, murakkabroq besh masalani sxema bilan tekshirish",
 ["Masalani yechish tartibi: 1) berilganlarni yozish, 2) birliklarni bir tizimga keltirish, 3) formula tanlash, 4) hisoblash, 5) javobni tekshirish.",
  "Ko'p bosqichli masalalarda oraliq javob yozib boriladi. Bir yo'la hisoblashga urinish xatoga olib keladi.",
  "Javobni tekshirishning uch usuli: birlik to'g'rimi; qiymat mantiqan real mi; teskari hisob mos keladimi.",
  "Misol: 5 V, ikki rezistor ketma-ket 1 kOm va 4 kOm. I = 5/5000 = 1 mA. U1 = 1 V, U2 = 4 V. Tekshiruv: 1 + 4 = 5 V — to'g'ri."],
 "Javobni tekshirishning uch usulini har masalada talab qiling. O'zini tekshirish ko'nikmasi imtihon va olimpiadada eng ko'p ball qo'shadigan odat.",
 [("Masala yechishning birinchi qadami nima?", "Berilganlarni yozib, birliklarni keltirish."),
  ("Ketma-ket zanjirda javobni qanday tekshirish mumkin?", "Kuchlanishlar yig'indisi manbaga teng bo'lishi kerak.")],
 "Oraliq natijalarni yozmay, kalkulyatorda ketma-ket hisoblash — xato topilmaydi."),

"Kuchlanish bo'luvchi: nazariya": T(
 "Turli nisbatdagi bo'luvchilarni hisoblab, chiqish kuchlanishlari jadvalini tuzish",
 ["Formula: U chiqish = U kirish x R2 / (R1 + R2), R2 — GND ga ulangan pastki rezistor.",
  "Chiqish kuchlanishi rezistorlarning NISBATIGA bog'liq, absolyut qiymatiga emas: 1k/1k ham, 10k/10k ham yarmini beradi.",
  "Lekin absolyut qiymat tok iste'moliga ta'sir qiladi: 100 Om/100 Om bo'luvchi 5 V da 25 mA yeydi, 10k/10k esa 0,25 mA.",
  "Shuning uchun kompromis: juda kichik qiymat energiya isrof qiladi, juda katta qiymat esa shovqinga sezgir bo'ladi. Odatda 1-100 kOm oralig'i tanlanadi."],
 "Nisbat va absolyut qiymat farqini alohida ta'kidlang. Bu 5-sinfda berilmagan yangi qatlam va aynan shu 6-sinf darajasini belgilaydi.",
 [("1k/1k va 10k/10k bo'luvchilar bir xil chiqish beradimi?", "Ha, chunki nisbat bir xil."),
  ("Ular nimasi bilan farq qiladi?", "Tok iste'moli bilan.")],
 "Faqat nisbatni hisoblab, tok iste'molini umuman hisobga olmaslik."),

"Kuchlanish bo'luvchi: amaliy o'lchov": T(
 "Bo'luvchi chiqishiga turli yuklamalar ulab, kuchlanishning qanday cho'kishini o'lchash",
 ["Yuklamasiz bo'luvchi hisoblangan qiymatni beradi. Yuklama ulanishi bilan chiqish kuchlanishi pasayadi.",
  "Sababi: yuklama pastki rezistor bilan parallel bo'lib qoladi va ekvivalent qarshilik kamayadi.",
  "Qoida: yuklama qarshiligi pastki rezistordan kamida 10 marta katta bo'lishi kerak — shunda cho'kish 10% dan oshmaydi.",
  "Shuning uchun bo'luvchi faqat kam tok oladigan kirishlarga (sensor o'qish, mikrokontroller kirishi) ulanadi."],
 "Uch xil yuklama (1 kOm, 10 kOm, 100 kOm) bilan o'lchatib, jadval tuzdiring. \"10 marta qoidasi\" o'lchov natijalaridan o'zi kelib chiqadi.",
 [("Nega yuklama ulanganda chiqish kuchlanishi pasayadi?", "Yuklama pastki rezistor bilan parallel bo'ladi."),
  ("Yuklama qanchalik katta bo'lishi kerak?", "Pastki rezistordan kamida 10 marta.")],
 "Bo'luvchidan motor yoki LED quvvatlantirishga urinish."),

"Potensiometr — sozlanadigan bo'luvchi": T(
 "Potensiometrni reostat va bo'luvchi rejimlarida ulab, farqni o'lchash",
 ["Potensiometr ikki xil ulanadi: uch oyoqli (bo'luvchi rejimi) va ikki oyoqli (reostat rejimi).",
  "Bo'luvchi rejimida chiqish kuchlanishi 0 dan manba kuchlanishigacha silliq o'zgaradi, yuklamadan qat'i nazar nisbatan barqaror.",
  "Reostat rejimida esa faqat qarshilik o'zgaradi — chiqish yuklamaga juda bog'liq bo'ladi.",
  "Potensiometrlar chiziqli (B) va logarifmik (A) bo'ladi. Ovoz balandligi uchun logarifmik ishlatiladi, chunki quloq tovushni logarifmik sezadi."],
 "Logarifmik potensiometr misolini radio yoki kolonka ovoz regulyatori bilan bog'lang — bu inson sezgisi va texnika o'rtasidagi bog'liqlikning yaxshi misoli.",
 [("Bo'luvchi rejimida nechta oyoq ishlatiladi?", "Uchtasi ham."),
  ("Ovoz balandligi uchun qaysi tur ishlatiladi?", "Logarifmik (A turi).")],
 "Reostat rejimida ulab, chiqish kuchlanishi barqaror bo'lishini kutish."),

"Elektr quvvati: P = U x I": T(
 "Turli komponentlarda ajraladigan quvvatni hisoblab, qizishini qo'l bilan tekshirish",
 ["Quvvat — birlik vaqtda sarflanadigan energiya: P = U x I. Birligi vatt (Vt).",
  "Om qonuni bilan birlashtirilsa boshqa ko'rinishlar chiqadi: P = I daraja 2 x R va P = U daraja 2 / R.",
  "Misol: 220 Om rezistorda 3 V tushsa, P = 9 / 220 = 0,041 Vt. Bu 0,25 Vt rezistor uchun xavfsiz.",
  "Ajraladigan quvvat issiqlikka aylanadi. Rezistor maksimal quvvatining 50% idan oshmasligi kerak — bu ishonchlilik zaxirasi."],
 "Rezistorlarni turli quvvatda ishlatib, qo'l bilan (ehtiyotkorlik bilan) qizishini sezdiring. Formula bilan sezgi bog'lanishi tushunchani mustahkamlaydi.",
 [("P = U x I dan boshqa qanday ko'rinishlar bor?", "P = I kvadrat x R va P = U kvadrat / R."),
  ("100 Om da 5 V bo'lsa quvvat qancha?", "25/100 = 0,25 Vt — chegarada, kuchliroq rezistor kerak.")],
 "Rezistorning quvvatini tekshirmaslik — u qiziydi, rangi o'zgaradi va nominal siljiydi."),

"Quvvatni hisoblab rezistor tanlash": T(
 "Berilgan besh zanjir uchun rezistorning nominalini va quvvatini tanlash",
 ["Rezistor ikki parametr bilan tanlanadi: nominal (Om) va maksimal quvvat (Vt).",
  "Standart quvvatlar: 0,125, 0,25, 0,5, 1, 2, 5 Vt. Katta quvvatlilar jismonan ham kattaroq bo'ladi.",
  "Hisob: kerakli quvvat topiladi, keyin undan kamida ikki barobar katta rezistor olinadi. 0,4 Vt kerak bo'lsa — 1 Vt li olinadi.",
  "Yopiq korpusda va yomon shamollatishda zaxira kattaroq bo'lishi kerak, chunki issiqlik chiqib ketolmaydi."],
 "\"Ikki barobar zaxira\" qoidasining sababini so'rang: harorat, korpus, uzoq muddat ishlash. Bu muhandislikdagi ishonchlilik tushunchasining kirishi.",
 [("0,4 Vt kerak bo'lsa qanday rezistor olinadi?", "Kamida 1 Vt li."),
  ("Nima uchun zaxira qoldiriladi?", "Isish, korpus va uzoq ishlash sharoitlarini hisobga olish uchun.")],
 "Faqat nominalga qarab tanlash va quvvatni hisobga olmaslik."),

"Energiya va iste'mol: kilovatt-soat": T(
 "Uy jihozlarining quvvatini yozib olib, oylik iste'mol va to'lovni hisoblash",
 ["Energiya = quvvat x vaqt: E = P x t. Elektr hisoblagichi kilovatt-soatda (kVt·s) o'lchaydi.",
  "1 kVt·s — 1000 vattlik qurilmaning 1 soatdagi iste'moli. Masalan 100 Vt lampa 10 soatda 1 kVt·s sarflaydi.",
  "Misol: 2000 Vt li elektr chaynik kuniga 15 daqiqa ishlasa: 2 kVt x 0,25 soat = 0,5 kVt·s kuniga, oyiga 15 kVt·s.",
  "LED lampa (10 Vt) va cho'g'lanma lampa (100 Vt) bir xil yorug'lik beradi, lekin ikkinchisi 10 barobar ko'p energiya sarflaydi."],
 "O'quvchilar uydagi hisoblagichni o'qib kelsin va sinfda hisoblasin. Elektronika darsi shu bilan real oilaviy byudjetga bog'lanadi.",
 [("1 kVt·s nima?", "1000 vattlik qurilmaning 1 soatlik iste'moli."),
  ("2 kVt li qurilma 30 daqiqada qancha sarflaydi?", "1 kVt·s.")],
 "Vattni kilovattga aylantirishni unutish — natija 1000 marta xato chiqadi."),

"Ketma-ket zanjirni o'lchab tekshirish": T(
 "Hisoblangan va o'lchangan qiymatlarni jadvalga yozib, farqni foizda hisoblash",
 ["Nazariy hisob ideal komponentlarni ko'zda tutadi. Amalda rezistor 5% chetlangan, simda qarshilik bor, batareya cho'kadi.",
  "Shuning uchun 5-10% farq NORMAL. 30% farq esa xato borligini bildiradi.",
  "Farqni foizda hisoblash: (o'lchangan - hisoblangan) / hisoblangan x 100%.",
  "Katta farq sabablari: batareya kuchlanishi hisobdagidan past; rezistor nominali chetlangan; kontakt qarshiligi katta."],
 "Nazariya va amaliyot orasidagi farqni \"xato\" emas, \"real sharoit\" deb tushuntirish muhim. Bu ilmiy dunyoqarashning muhim qismi.",
 [("5-10% farq nimani bildiradi?", "Bu normal, komponent chetlanishi va o'lchov xatoligi."),
  ("30% farqning sababi nima bo'lishi mumkin?", "Batareya cho'kkan, kontakt yomon yoki hisobda xato bor.")],
 "Farq chiqqach, hisobni o'lchovga moslashtirib \"tuzatib\" qo'yish."),

"Parallel zanjirni o'lchab tekshirish": T(
 "Parallel zanjirning umumiy va tarmoq toklarini o'lchab, qonuniyatni tasdiqlash",
 ["Tarmoq toklarining yig'indisi umumiy tokka teng bo'lishi kerak — bu Kirxgofning birinchi qonuni.",
  "Amalda kichik farq bo'ladi (1-3%), chunki ampermetrning o'zi ham zanjirga qarshilik qo'shadi.",
  "Tarmoq tokini o'lchash uchun aynan shu tarmoqni uzish kerak. Boshqa joydan uzilsa umumiy tok o'lchanadi.",
  "Qiziqarli tekshiruv: bitta tarmoqni uzib qo'yib, qolganlarining toki o'zgaradimi yoki yo'q — javob \"o'zgarmaydi\", chunki ular mustaqil."],
 "Bir tarmoqni uzib, qolganlarining o'zgarmasligini o'lchab ko'rsating. Bu parallel ulanishning eng muhim amaliy xossasi.",
 [("Kirxgofning birinchi qonuni nima deydi?", "Tugunga kirgan toklar yig'indisi chiqqan toklar yig'indisiga teng."),
  ("Bir tarmoq uzilsa qolganlarining toki o'zgaradimi?", "Yo'q.")],
 "Tarmoq tokini o'lchash uchun noto'g'ri joydan uzish."),

"Batareyaning ichki qarshiligi: nega kuchlanish cho'kadi": T(
 "Batareyaning bo'sh va yuklamali kuchlanishini o'lchab, ichki qarshilikni hisoblash",
 ["Har manbaning ichida qarshilik bor. Tok o'tganda unda ham kuchlanish tushadi va tashqariga kamroq qoladi.",
  "Hisoblash: r = (U bo'sh - U yuklama) / I. Masalan 1,55 V bo'sh, 1,35 V yuklamada, tok 0,2 A. r = 0,2 / 0,2 = 1 Om.",
  "Yangi AA batareyada ichki qarshilik 0,15-0,3 Om, eskisida bir necha om bo'lishi mumkin.",
  "Shuning uchun eski batareya bo'sh holda normal ko'rsatib, motor ulanishi bilan kuchlanishi keskin tushadi."],
 "Ichki qarshilikni har bir juftlik o'z batareyasi uchun hisoblasin va sinf bo'yicha solishtirilsin. Raqamlar batareyalarning holatini aniq ko'rsatadi.",
 [("Ichki qarshilik qanday hisoblanadi?", "Bo'sh va yuklamali kuchlanish farqini tokka bo'lib."),
  ("Eski batareyada ichki qarshilik qanday bo'ladi?", "Kattalashadi.")],
 "Bo'sh kuchlanishga qarab batareyani yaroqli deb hisoblash."),

"Qisqa tutashuv va himoya (predoxranitel)": T(
 "Predoxranitelli zanjir yig'ib, ataylab ortiqcha tok berib, uni kuydirish (nazorat ostida)",
 ["Predoxranitel ichida ma'lum tokda eriydigan sim bor. Tok nominaldan oshsa u uzilib, zanjirni ochadi.",
  "Nominal tanlash: ishchi tokdan 1,5-2 barobar katta. 1 A iste'mol qiladigan qurilmaga 2 A predoxranitel qo'yiladi.",
  "Tez va sekin turlari bor: sekin (T) qisqa muddatli start tokiga chidaydi, tez (F) darhol uziladi. Motorli qurilmalarga sekin turi qo'yiladi.",
  "Zamonaviy himoya — qayta tiklanadigan predoxranitel (PTC, polifuze): u qizib qarshiligini oshiradi, soviganidan keyin o'z holiga qaytadi."],
 "PTC predoxranitelni sinab ko'rsating: ortiqcha tokda zanjir uziladi, bir necha sekunddan keyin o'zi tiklanadi. Bu o'quvchilarga juda qiziq ko'rinadi.",
 [("1 A iste'mol uchun qanday predoxranitel olinadi?", "1,5-2 A li."),
  ("Motorli qurilmaga qaysi tur qo'yiladi?", "Sekin (T) turi, start tokiga chidashi uchun.")],
 "Predoxranitelni ishchi tokka teng qilib tanlash — u normal ishda ham uzilib turadi."),

"O'lchov aniqligi va xatolik": T(
 "Bir kattalikni uch xil usulda o'lchab, natijalarni solishtirish va sabab tahlil qilish",
 ["Xatolik ikki turli: tasodifiy (har o'lchovda har xil) va tizimli (doim bir tomonga siljigan).",
  "Tasodifiy xatolik ko'p marta o'lchab o'rtachasini olish bilan kamayadi. Tizimli xatolik esa faqat asbobni kalibrlash bilan tuzatiladi.",
  "Asbobning ta'siri ham xatolik manbai: ampermetr zanjirga qarshilik qo'shadi, voltmetr esa oz bo'lsa-da tok oladi.",
  "Natija yozilishi: 4,72 ± 0,05 V. Ikkinchi son — noaniqlik chegarasi, u o'lchov natijasining ajralmas qismi."],
 "± belgisi bilan yozishni talab qiling. Bu fizika laboratoriya ishlarida ham xuddi shu talab bo'ladi va o'quvchi tayyor keladi.",
 [("Tasodifiy va tizimli xatolik farqi nima?", "Tasodifiy har o'lchovda har xil, tizimli doim bir tomonga siljigan."),
  ("Tizimli xatolik qanday tuzatiladi?", "Asbobni kalibrlash bilan.")],
 "Natijani noaniqliksiz yozish va uni mutlaq aniq deb hisoblash."),

"Murakkab zanjirni tahlil qilish": T(
 "6 komponentli aralash zanjirni to'liq hisoblab, barcha nuqtalarda o'lchov bilan tekshirish",
 ["Tahlil tartibi: 1) zanjirni soddalashtirib umumiy qarshilikni topish, 2) umumiy tokni hisoblash, 3) orqaga qaytib har bir elementdagi U va I ni topish.",
  "Har bosqichda oraliq sxema chiziladi va topilgan qiymatlar unga yoziladi.",
  "Tekshiruv usullari: ketma-ket qismlarda kuchlanishlar yig'indisi; tugunlarda toklar yig'indisi; umumiy quvvat elementlar quvvati yig'indisiga teng.",
  "Quvvat balansi eng ishonchli tekshiruv: manba bergan quvvat barcha elementlarda ajralgan quvvatlar yig'indisiga teng bo'lishi shart."],
 "Quvvat balansini oxirgi tekshiruv sifatida kiriting. Bu energiyaning saqlanish qonunining elektrotexnikadagi ko'rinishi va fizika bilan bevosita bog'lanadi.",
 [("Tahlil qaysi tartibda olib boriladi?", "Soddalashtirish, umumiy tok, keyin orqaga qaytib har element."),
  ("Quvvat balansi nimani tekshiradi?", "Manba quvvati elementlar quvvatlari yig'indisiga tengligini.")],
 "Bir yo'la hisoblashga urinish — murakkab zanjirda bu deyarli doim xatoga olib keladi."),

# ==================================================== 3-CHORAK: Yarimo'tkazgichlar va komponentlar
"Kondensator: tuzilishi va sig'imi": T(
 "Turli sig'im va kuchlanishdagi kondensatorlarni saralab, belgilarini jadvalga yozish",
 ["Kondensator ikki plastina va ular orasidagi dielektrikdan iborat. Sig'im C = e x S / d: yuza katta va oraliq kichik bo'lsa sig'im katta.",
  "Elektrolitikda dielektrik juda yupqa oksid qatlami — shuning uchun katta sig'im kichik korpusga sig'adi, lekin u qutbli.",
  "Keramik kondensator qutbsiz, kichik sig'imli (pF-nF), lekin yuqori chastotada yaxshi ishlaydi.",
  "Har kondensatorda maksimal kuchlanish yozilgan. Undan oshsa dielektrik teshiladi va kondensator ishdan chiqadi."],
 "Kondensatorni ochib ko'rsating (elektrolitikni ehtiyotkorlik bilan): ichidagi o'ralgan folga qatlamlari sig'im formulasini ko'z bilan tushuntiradi.",
 [("Sig'im nimaga bog'liq?", "Plastinalar yuzasiga, oraliq masofasiga va dielektrikga."),
  ("Nega elektrolitik kondensator katta sig'imli?", "Uning dielektrik qatlami juda yupqa.")],
 "Maksimal kuchlanishga e'tibor bermay, 5 V zanjirga 6,3 V kondensator qo'yish — zaxira qolmaydi."),

"Kondensatorni zaryadlash va bo'shatish": T(
 "Turli sig'imlarni zaryadlab, kuchlanishning vaqt bo'yicha o'zgarishini jadvalga yozish",
 ["Zaryadlanish eksponensial: boshida tez, keyin sekinlashadi. Kuchlanish manba qiymatiga asimptotik yaqinlashadi.",
  "Bir T (vaqt doimiysi) da 63%, ikki T da 86%, uch T da 95%, besh T da 99% ga yetadi.",
  "Bo'shatish ham eksponensial: bir T da 37% qoladi.",
  "Zaryadlash toki boshida maksimal, oxirida nolga intiladi. Shuning uchun bo'sh kondensator qisqa tutashuvga o'xshab ko'rinadi."],
 "Kuchlanishni har 5 sekundda yozib borishni tashkil qiling va grafik chizdiring. Eksponensial egri chiziqni o'z ma'lumotidan olish kuchli tajriba.",
 [("Bir vaqt doimiysida kondensator necha foizga zaryadlanadi?", "63%."),
  ("Bo'sh kondensator ulangan lahzada nimaga o'xshaydi?", "Qisqa tutashuvga — tok maksimal.")],
 "Zaryadlanish chiziqli deb o'ylab, grafikni to'g'ri chiziq qilib chizish."),

"RC zanjir va vaqt doimiysi": T(
 "R va C ni almashtirib, T ni hisoblab va o'lchab, jadval bilan solishtirish",
 ["T = R x C. Om va faradda hisoblansa natija sekundda chiqadi.",
  "Amaliy hisob uchun qulay: kOm x uF = millisekund. 10 kOm x 100 uF = 1000 ms = 1 s.",
  "RC zanjir taymer, filtr va debounce sxemalarida ishlatiladi.",
  "Kuchlanish 63% ga yetgan vaqtni o'lchash orqali T ni tajribada aniqlash mumkin — bu noma'lum kondensator sig'imini topish usuli."],
 "kOm x uF = ms qoidasini doskaga yozib qo'ying. Bu hisobni bir necha barobar tezlashtiradi va nol xatolarini yo'q qiladi.",
 [("47 kOm va 10 uF uchun T qancha?", "470 ms."),
  ("Noma'lum sig'imni qanday topish mumkin?", "63% ga yetish vaqtini o'lchab, C = T/R bilan.")],
 "Om va mikrofaradni to'g'ridan-to'g'ri ko'paytirish — birlik aylantirilmasa natija xato."),

"Kondensator turlari va tanlash": T(
 "Berilgan besh vazifa uchun mos kondensator turini tanlab, tanlovini asoslash",
 ["Elektrolitik: katta sig'im (1-10000 uF), qutbli, quvvat filtri uchun. Kamchiligi — qurib qoladi va yuqori chastotada yomon ishlaydi.",
  "Keramik: kichik sig'im (pF-uF), qutbsiz, arzon, yuqori chastotada yaxshi. Mikrosxema yonidagi shovqin filtri uchun (100 nF).",
  "Plyonkali: o'rta sig'im, aniq va barqaror, audio va o'lchov sxemalarida.",
  "Tantal: kichik korpusda katta sig'im, lekin teskari ulanishga juda sezgir — yonib ketishi mumkin."],
 "\"Har mikrosxema yonida 100 nF\" qoidasini eslatib qo'ying — bu keyingi yillarda Arduino va ESP32 platalarida uchraydigan detal.",
 [("Quvvat filtri uchun qaysi tur ishlatiladi?", "Elektrolitik."),
  ("Mikrosxema yonidagi shovqin filtri uchun-chi?", "100 nF keramik.")],
 "Keramik va elektrolitikni o'zaro almashtirib qo'yish — sig'im tartibi mos kelmaydi."),

"Diod: p-n o'tish": T(
 "Diodning to'g'ri va teskari yo'nalishdagi xarakteristikasini o'lchab, grafik chizish",
 ["p-turdagi yarimo'tkazgichda teshiklar, n-turdagida elektronlar ko'p. Ular tutashgan joyda p-n o'tish hosil bo'ladi.",
  "Chegarada zaryadlar bir-biriga o'tib, to'siq (bariyer) hosil qiladi. Uni yengish uchun kremniyda 0,7 V, germaniyda 0,3 V kerak.",
  "To'g'ri yo'nalishda kuchlanish 0,7 V dan oshsa tok keskin o'sadi — grafik tik ko'tariladi.",
  "Teskari yo'nalishda faqat juda kichik oqim toki o'tadi. Kuchlanish teshilish chegarasidan oshsa, diod ishdan chiqadi."],
 "Volt-amper xarakteristikasini nuqta-nuqta o'lchab, grafik chizdiring. Chiziqsiz element grafigi — Om qonuni chegarasining ko'rgazmali isboti.",
 [("Kremniyli diodning ochilish kuchlanishi qancha?", "0,7 V."),
  ("Teskari yo'nalishda diod nima qiladi?", "Deyarli tok o'tkazmaydi.")],
 "Diodda kuchlanish tushishi doim 0,7 V deb hisoblash — u tokka biroz bog'liq."),

"Diodni tekshirish va to'g'ri qutblash": T(
 "10 ta diodni multimetr bilan tekshirib, sog'lom va nosozlarini ajratish",
 ["Diod rejimida to'g'ri yo'nalishda 0,5-0,7 ko'rsatadi (Shottki diodda 0,2-0,3), teskarisida OL.",
  "Ikkala tomonda OL — diod uzilgan. Ikkala tomonda 0 yoki juda kichik qiymat — diod teshilgan (qisqa tutashgan).",
  "Katod tomoni korpusdagi halqa bilan belgilanadi. LEDda esa kalta oyoq va tekis chekka.",
  "Diodni zanjirda tekshirish noto'g'ri natija berishi mumkin — parallel yo'llar bo'lsa, kamida bir oyog'ini uzish kerak."],
 "Ataylab nosoz diodlar tayyorlab bering (bittasi uzilgan, bittasi teshilgan). Nosozlikni multimetr bilan aniqlash ko'nikmasi shu tarzda mustahkamlanadi.",
 [("Ikkala tomonda ham OL chiqsa nima demak?", "Diod uzilgan."),
  ("Shottki diodda tushish kuchlanishi qancha?", "0,2-0,3 V.")],
 "Diodni zanjirdan uzmasdan tekshirish."),

"Diod ko'prigi: o'zgaruvchan tokni to'g'rilash": T(
 "To'rt diodli ko'prik yig'ib, kirish va chiqish signallarini kuzatish",
 ["O'zgaruvchan tokda yo'nalish davriy almashadi. Ko'p qurilma esa doimiy tok talab qiladi.",
  "Bir diodli to'g'rilash faqat yarim davrni o'tkazadi — energiyaning yarmi yo'qoladi.",
  "To'rt diodli ko'prik ikkala yarim davrni ham ishlatadi: qaysi yo'nalishda bo'lmasin, yuklamadan tok bir tomonga o'tadi.",
  "Ko'prik chiqishida pulsatsiyalanuvchi doimiy tok bo'ladi. Uni silliqlash uchun katta elektrolitik kondensator qo'yiladi."],
 "Ko'prikdagi tok yo'lini ikki yo'nalish uchun alohida rangda chizdiring. Bu sxemani \"ko'rish\" ning yagona ishonchli usuli.",
 [("Ko'prikda nechta diod bor?", "To'rtta."),
  ("Ko'prik chiqishidagi kondensator nima qiladi?", "Pulsatsiyani silliqlaydi.")],
 "Ko'prikdagi diodlarning birortasini teskari ulash — chiqishda kuchlanish bo'lmaydi yoki qisqa tutashuv bo'ladi."),

"Stabilitron: kuchlanishni ushlab turish": T(
 "Stabilitronli sxema yig'ib, kirish kuchlanishini o'zgartirganda chiqish barqarorligini o'lchash",
 ["Stabilitron TESKARI yo'nalishda ishlatiladi. Teskari kuchlanish stabillash qiymatiga yetganda u tok o'tkaza boshlaydi va kuchlanishni shu darajada ushlab turadi.",
  "Sxemada u yuklamaga parallel, manbaga esa ketma-ket rezistor orqali ulanadi. Rezistor ortiqcha tokni cheklaydi.",
  "Rezistorni hisoblash: R = (U kirish - U stab) / (I yuklama + I stab min). Stabilitron uchun kamida 5 mA qoldiriladi.",
  "Kamchiligi: doimiy tok sarflaydi va issiqlik ajratadi. Shuning uchun kuchli yuklamalar uchun stabilizator mikrosxemasi (7805) ishlatiladi."],
 "Kirish kuchlanishini 8 dan 15 V gacha o'zgartirib, chiqish 5,1 V da qolishini o'lchab ko'rsating. Bu \"stabilizatsiya\" so'zining ma'nosini bir zumda ochadi.",
 [("Stabilitron qaysi yo'nalishda ulanadi?", "Teskari."),
  ("Ketma-ket rezistor nima uchun kerak?", "Stabilitrondan o'tadigan tokni cheklash uchun.")],
 "Stabilitronni oddiy diod kabi to'g'ri yo'nalishda ulash — u shunchaki diod bo'lib ishlaydi."),

"Tranzistor tuzilishi va oyoqlari": T(
 "Turli korpusdagi tranzistorlarning oyoqlarini datasheet va multimetr bilan aniqlash",
 ["Bipolyar tranzistor uch qatlamdan iborat: NPN yoki PNP. Oyoqlar — baza, kollektor, emitter.",
  "TO-92 korpusda oyoq tartibi turga qarab har xil: BC547 da tekis tomondan qaraganda E-B-C, 2N2222 da esa E-B-C boshqa tartibda bo'lishi mumkin. Datasheet SHART.",
  "Multimetrning diod rejimida baza topiladi: bazadan ikkala oyoqqa ham o'tish ko'rinadi (NPN da qizil shchup bazada).",
  "Emitter va kollektorni ajratish: emitter-baza o'tishining kuchlanishi kollektor-baza o'tishinikidan biroz katta bo'ladi."],
 "Datasheetni ochib, oyoq chizmasini (pinout) topishni birgalikda bajaring. \"Oyoqlarni taxmin qilmaslik\" qoidasi tranzistorlar bilan ishlashning birinchi shartidir.",
 [("Bipolyar tranzistorning uch oyog'i nima?", "Baza, kollektor, emitter."),
  ("Oyoq tartibini qayerdan bilish kerak?", "Datasheetdan — turlar orasida farq qiladi.")],
 "Bir tranzistorning oyoq tartibini boshqasiga ko'chirish — natijada tranzistor ishlamaydi yoki kuyadi."),

"Tranzistor kalit rejimida": T(
 "Tranzistorli kalit yig'ib, baza rezistorini o'zgartirib to'yinish holatini topish",
 ["Kalit rejimida tranzistor to'liq ochiq (to'yingan) yoki to'liq yopiq bo'ladi. Oraliq holat quvvat isrof qiladi va tranzistorni qizdiradi.",
  "To'yinish uchun baza toki yetarli bo'lishi kerak: I baza = I kollektor / beta, lekin ishonchlilik uchun 5-10 barobar ko'proq beriladi.",
  "Baza rezistorini hisoblash: R = (U boshqaruv - 0,7) / I baza. 5 V va 5 mA uchun R = 4,3/0,005 = 860 Om, ya'ni 820 Om olinadi.",
  "To'yingan tranzistorda kollektor-emitter kuchlanishi 0,2 V ga tushadi — bu holat multimetr bilan tekshiriladi."],
 "To'yinish holatini kuchlanish o'lchash bilan tekshirtiring: 0,2 V bo'lsa to'yingan, 2-3 V bo'lsa oraliq holatda va tranzistor qiziydi.",
 [("To'yingan tranzistorda kollektor-emitter kuchlanishi qancha?", "Taxminan 0,2 V."),
  ("Nega baza tokini zaxira bilan beriladi?", "To'yinish kafolatlangan bo'lishi va tranzistor qizimasligi uchun.")],
 "Baza rezistorini juda katta olish — tranzistor to'liq ochilmaydi, qiziydi va yuklama to'liq ishlamaydi."),

"Tranzistor bilan motorni yoqish": T(
 "Tranzistor va flyback diod bilan motorni yoqadigan zanjir yig'ish",
 ["Motor katta tok oladi, shuning uchun kuchli tranzistor kerak: TIP122 yoki MOSFET (IRF540, IRLZ44N).",
  "Motorga parallel FLYBACK diod majburiy: motor o'chganda g'altakda 100 V dan ortiq teskari impuls hosil bo'ladi.",
  "Diod motorga TESKARI ulanadi: katod musbat tomonga. To'g'ri ulansa qisqa tutashuv bo'ladi.",
  "Motor va boshqaruv sxemasi uchun quvvat ALOHIDA bo'lishi ma'qul, lekin GND umumiy bo'lishi shart."],
 "\"Umumiy GND\" qoidasini alohida ta'kidlang — ikki manba ishlatilganda GND ulanmasa sxema tasodifiy ishlaydi va bu topish qiyin nosozlik.",
 [("Flyback diod qanday ulanadi?", "Motorga parallel va teskari yo'nalishda."),
  ("Ikki alohida manba ishlatilsa nima umumiy bo'lishi kerak?", "GND.")],
 "Flyback diodni unutish yoki uni to'g'ri yo'nalishda ulash."),

"NPN va PNP tranzistorlar farqi": T(
 "NPN va PNP bilan bir xil vazifani bajaruvchi ikki sxema yig'ib solishtirish",
 ["NPN da yuklama kollektorda, emitter GND ga ulanadi. Boshqarish uchun bazaga MUSBAT signal beriladi.",
  "PNP da emitter musbat shinaga ulanadi, yuklama kollektorda. Boshqarish uchun bazaga PAST daraja beriladi.",
  "NPN sxemasi \"pastdan kalit\" (low-side), PNP esa \"yuqoridan kalit\" (high-side) deb ataladi.",
  "Amalda NPN ko'proq ishlatiladi — u soddaroq va mikrokontroller bilan bevosita mos keladi."],
 "Ikkala sxemani yonma-yon chizib, strelka yo'nalishini solishtiring: NPN da strelka emitterdan tashqariga, PNP da ichkariga qaragan. Bu belgini yodlashning kaliti.",
 [("NPN ni boshqarish uchun bazaga qanday signal beriladi?", "Musbat."),
  ("Qaysi turi mikrokontroller bilan sodda ishlaydi?", "NPN.")],
 "PNP ni NPN sxemasiga qo'yish — u boshqarilmaydi yoki doim ochiq turadi."),

"Rele: elektromagnit kalit": T(
 "Rele g'altagi qarshiligini o'lchab, ishga tushish kuchlanishini aniqlash",
 ["Rele g'altagida odatda 70-400 Om qarshilik bo'ladi. 5 V rele uchun tok = 5/120 = ~40 mA.",
  "Bu tok mikrokontroller pini uchun ko'p — shuning uchun rele doim tranzistor orqali boshqariladi.",
  "Ishga tushish kuchlanishi nominalning 70-80% i atrofida. Qo'yib yuborish esa ancha pastroqda sodir bo'ladi — bu gisterezis deb ataladi.",
  "Kontakt reytingi korpusda yozilgan: 10A 250VAC / 10A 30VDC. O'zgaruvchan tok uchun ko'rsatkich kattaroq bo'ladi."],
 "Gisterezis tushunchasini shu yerda kiriting — u keyinchalik sensor chegaralarini sozlashda ham kerak bo'ladi.",
 [("Nega rele tranzistorsiz boshqarilmaydi?", "G'altagi 40 mA atrofida tok oladi, bu plata pini uchun ko'p."),
  ("Gisterezis nima?", "Ishga tushish va qo'yib yuborish kuchlanishlari orasidagi farq.")],
 "Releni to'g'ridan-to'g'ri plata pinidan yurgizishga urinish."),

"Rele bilan kuchli yuklamani ulash": T(
 "Rele orqali alohida manbadan quvvat oladigan lampa yoki motorni boshqarish",
 ["Rele ikki zanjirni to'liq ajratadi: boshqaruv (5 V) va yuklama (12 V, 220 V). Ular orasida elektr aloqasi yo'q.",
  "Ulash: yuklama zanjiri COM va NO kontaktlariga ulanadi. Rele yoqilganda kontakt tutashadi.",
  "220 V bilan ishlash MUMKIN EMAS o'quvchilar uchun. Sinfda faqat 12 V gacha yuklama ishlatiladi.",
  "Rele modullarida odatda optopara ham bor — u qo'shimcha himoya qatlami beradi va mikrokontrollerni to'liq ajratadi."],
 "220 V ni faqat gapiring, sinfda ishlatmang. Yuqori kuchlanish bilan ishlash — kasbiy tayyorgarlik talab qiladigan alohida soha.",
 [("Rele boshqaruv va yuklama zanjirlarini ajratadimi?", "Ha, ular orasida elektr aloqasi yo'q."),
  ("Sinfda maksimal qanday yuklama ishlatiladi?", "12 V gacha.")],
 "220 V bilan mustaqil tajriba qilishga urinish — bu qat'iy taqiqlanadi."),

"Optopara va IK juftlik": T(
 "Optopara bilan ikki zanjirni ajratib, IK juftlik bilan to'siqni sezuvchi zanjir yig'ish",
 ["Optopara ichida IK LED va fototranzistor bir korpusda, yorug'lik orqali bog'langan. Elektr aloqasi yo'q.",
  "Bu galvanik ajratish deb ataladi: bir tomondagi yuqori kuchlanish ikkinchi tomonga o'tmaydi.",
  "IK juftlik (alohida LED va qabul qiluvchi) to'siqni sezish uchun ishlatiladi: nur to'silsa fototranzistor yopiladi.",
  "Ikki joylashuv: qarama-qarshi (barrier) — orasidan o'tgan buyum seziladi; yonma-yon (reflective) — qaytgan nur bo'yicha, chiziq bo'ylab yuruvchi robotlarda ishlatiladi."],
 "Chiziq bo'ylab yuruvchi robot (line follower) misolini keltiring — bu o'quvchilar ko'rgan robotlarning eng keng tarqalgani va aynan shu juftlik bilan ishlaydi.",
 [("Optopara ikki zanjirni nima orqali bog'laydi?", "Yorug'lik orqali, elektr aloqasisiz."),
  ("Chiziq bo'ylab yuruvchi robotda qaysi joylashuv ishlatiladi?", "Qaytaruvchi (reflective).")],
 "IK nurni ko'z bilan ko'rmoqchi bo'lish — u ko'rinmaydi, telefon kamerasi orqali ko'rish mumkin."),

"RGB LED va rang aralashtirish": T(
 "RGB LED bilan 8 ta asosiy rangni hosil qilib, jadval tuzish",
 ["Uch rang yoqilgan/o'chirilgan holatda 2 daraja 3 = 8 kombinatsiya beradi: o'chiq, R, G, B, sariq, magenta, siyan, oq.",
  "Oraliq ranglar uchun har rangning YORQINLIGINI o'zgartirish kerak. Buni potensiometr yoki PWM bilan qilinadi.",
  "PWM bilan har rangga 256 daraja berilsa, 256 daraja 3 = 16,7 million rang chiqadi — bu ekranlardagi \"true color\".",
  "Ko'z ranglarni bir xil sezmaydi: yashilni yorqinroq, ko'kni xiraroq ko'radi. Shuning uchun teng qiymatlarda oq emas, ko'kish-yashil chiqishi mumkin."],
 "16,7 million rang raqami o'quvchilarni hayratga soladi va uni oddiy hisobdan (256 uchinchi darajada) chiqarish matematikani texnikaga bog'laydi.",
 [("Uch rang yoqiq/o'chiq holatda nechta kombinatsiya beradi?", "Sakkizta."),
  ("16,7 million rang qanday hosil bo'ladi?", "Har rangga 256 daraja: 256 ni uchinchi darajaga ko'tarish.")],
 "Teng PWM qiymatlarida aniq oq rang chiqishini kutish — ko'z sezgisi tufayli tuzatish kerak bo'ladi."),

"7-segment indikator bilan ishlash": T(
 "Ikki razryadli indikatorni ulab, raqamlarni qo'lda hosil qilish",
 ["Ko'p razryadli indikatorda segment oyoqlari UMUMIY, faqat COM oyoqlari alohida bo'ladi. Bu pinlar sonini kamaytiradi.",
  "Shuning uchun razryadlar bir vaqtda turli raqam ko'rsata olmaydi — ular NAVBAT BILAN yoqiladi (dinamik indikatsiya).",
  "Almashish tezligi 50 Hz dan yuqori bo'lsa ko'z buni sezmaydi va ikkala razryad bir vaqtda yonayotgandek ko'rinadi.",
  "Bu 2-yildagi dasturlash mavzusi. Hozircha faqat tamoyilni tushunish va bitta razryadni qo'lda boshqarish yetarli."],
 "Dinamik indikatsiyani qo'lda sekin almashtirib ko'rsating, keyin tez almashtiring. Ko'zning inersiyasi tushunchasi shu yerda ochiladi.",
 [("Nega ko'p razryadli indikatorda segment oyoqlari umumiy?", "Pinlar sonini kamaytirish uchun."),
  ("Dinamik indikatsiya nima?", "Razryadlarni juda tez navbat bilan yoqish.")],
 "Ikki razryadni bir vaqtda yoqishga urinish — ikkalasida bir xil raqam chiqadi."),

"Komponentni katalog (datasheet) bo'yicha tanlash": T(
 "Uch komponentning datasheetini o'qib, asosiy parametrlarini jadvalga chiqarish",
 ["Datasheetning tuzilishi: 1) qisqacha tavsif, 2) mutlaq maksimal qiymatlar, 3) elektr xarakteristikalar, 4) grafiklar, 5) korpus o'lchamlari.",
  "Eng muhim bo'lim — Absolute Maximum Ratings. Undagi qiymatlardan oshish komponentni darhol ishdan chiqaradi.",
  "Elektr xarakteristikalar jadvalida min/typ/max ustunlari bor. Loyihalashda TYP emas, eng yomon holat (min yoki max) hisobga olinadi.",
  "Grafiklar ko'pincha eng foydali qism: masalan tranzistorning beta koeffitsienti tok va haroratga qanday bog'liqligini ko'rsatadi."],
 "\"Typ emas, eng yomon holat bo'yicha loyihalash\" qoidasini kiriting — bu haqiqiy muhandislik yondashuvi va o'quvchilarni havaskorlikdan ajratadi.",
 [("Datasheetning eng muhim bo'limi qaysi?", "Absolute Maximum Ratings."),
  ("Loyihalashda min/typ/max dan qaysi biri olinadi?", "Eng yomon holat — vazifaga qarab min yoki max.")],
 "Faqat typ qiymatlarga tayanib hisoblash — real qurilma chegaraviy sharoitda ishlamay qoladi."),

# ==================================================== 4-CHORAK: Sensorlar va elektromexanika
"Sensor tushunchasi va turlari": T(
 "To'plamdagi barcha sensorlarni turlarga ajratib, tasnif jadvali tuzish",
 ["Sensor fizik kattalikni elektr signalga aylantiradi. Tasniflash mumkin: sezadigan kattaligi bo'yicha, chiqish turi bo'yicha, quvvat talabi bo'yicha.",
  "Kattalik bo'yicha: mexanik (bosim, qiyalik), issiqlik (harorat), optik (yorug'lik, masofa), magnit (Hall), kimyoviy (gaz, namlik).",
  "Chiqish bo'yicha: qarshilikli (fotorezistor, termistor), kuchlanishli, tokli, raqamli (DHT22, protokol orqali).",
  "Passiv sensor o'zi quvvat talab qilmaydi (termopara), aktiv sensor esa talab qiladi (ko'p modullar)."],
 "Tasnif jadvalini o'quvchilar o'zi to'ldirsin — tayyor jadval berish emas, o'zi tasniflash tushunchani mustahkam qiladi.",
 [("Sensor nima qiladi?", "Fizik kattalikni elektr signalga aylantiradi."),
  ("Fotorezistor qaysi chiqish turiga kiradi?", "Qarshilikli.")],
 "Modulni sensor bilan chalkashtirish: modul — sensor va yordamchi sxemaning birgalikdagi platasi."),

"Fotorezistor: yorug'lik-qarshilik bog'liqligi": T(
 "Yorug'lik manbaidan turli masofada qarshilikni o'lchab, grafik chizish",
 ["Fotorezistorda yorug'lik fotonlari elektronlarni erkin holatga o'tkazadi — o'tkazuvchanlik oshadi, qarshilik kamayadi.",
  "Bog'liqlik logarifmik: yorug'lik 10 barobar oshsa, qarshilik taxminan 10 barobar kamayadi. Shuning uchun grafik logarifmik o'qda to'g'ri chiziq bo'ladi.",
  "Javob tezligi sekin: yorug'likdan qorong'iga o'tishda qarshilik to'liq tiklanishiga bir necha soniya ketadi.",
  "Materiali kadmiy sulfid (CdS) — kadmiy zaharli, shuning uchun Yevropada ular cheklangan va fotodiod bilan almashtirilmoqda."],
 "Masofa ikki barobar oshganda yorug'lik to'rt barobar kamayishini (teskari kvadrat qonuni) fizika bilan bog'lab tushuntiring.",
 [("Yorug'lik oshsa fotorezistor qarshiligi qanday o'zgaradi?", "Kamayadi."),
  ("Uning javob tezligi qanday?", "Sekin — bir necha soniyagacha.")],
 "Fotorezistorni tez o'zgaruvchan yorug'likni o'lchashga ishlatish — u ulgurmaydi."),

"Fotorezistorli avtomat zanjiri": T(
 "Sezgirligi sozlanadigan tungi chiroq avtomatini yig'ib, chegarani sozlash",
 ["Sxema: fotorezistor + potensiometr bo'luvchi -> tranzistor bazasi -> LED yoki rele.",
  "Potensiometr chegara nuqtasini belgilaydi: qaysi yorug'likda tranzistor ochilishini sozlaydi.",
  "Muammo: chegara atrofida chiroq miltillay boshlaydi (chiroq yonsa yorug' bo'ladi, sensor o'chiradi, qorong'i bo'ladi, yana yonadi).",
  "Yechim: gisterezis qo'shish (musbat teskari bog'lanish rezistori) yoki sensorni chiroq nuridan uzoqroq joylashtirish."],
 "Miltillash muammosini ataylab yuzaga keltiring va o'quvchilar yechim taklif qilsin. Bu haqiqiy muhandislik masalasi va yechimi ham amaliy.",
 [("Nega chiroq chegara atrofida miltillaydi?", "Chiroq yorug'ligi sensorga tushib, uni qayta o'chiradi."),
  ("Bu qanday hal qilinadi?", "Gisterezis qo'shish yoki sensorni chiroqdan uzoqlashtirish.")],
 "Sensorni chiroq yoniga qo'yish — qurilma doim miltillab turadi."),

"Termistor va harorat o'lchash": T(
 "Termistor qarshiligini turli haroratlarda o'lchab, kalibrlash jadvalini tuzish",
 ["NTC termistorning qarshiligi harorat bilan chiziqsiz bog'langan — Shteynxart-Xart tenglamasi bilan tavsiflanadi.",
  "Amaliy hisob uchun soddalashtirilgan B-parametr formulasi ishlatiladi. B qiymati datasheetda beriladi (odatda 3950).",
  "Kalibrlash: muzli suv (0 daraja) va qaynagan suv (100 daraja) — ikkita ma'lum nuqta. Ular orasidagi qiymatlar interpolyatsiya qilinadi.",
  "Aniqlik 1-2 daraja atrofida. Aniqroq o'lchov uchun raqamli sensor (DS18B20, DHT22) ishlatiladi."],
 "Muzli suv va qaynagan suv bilan kalibrlashni amalda bajaring — bu o'lchov texnikasining klassik usuli va boshqa fanlarda ham qo'llaniladi.",
 [("Termistorni kalibrlash uchun qaysi ikki nuqta ishlatiladi?", "Muzli suv (0) va qaynagan suv (100 daraja)."),
  ("Termistorning aniqligi qanday?", "1-2 daraja atrofida.")],
 "Termistorni suvga to'g'ridan-to'g'ri botirish — oyoqlari tutashib, natija xato chiqadi. Izolyatsiya kerak."),

"Haroratli signalizatsiya": T(
 "Belgilangan haroratdan oshganda tovush beradigan qurilma yig'ish",
 ["Sxema: termistorli bo'luvchi -> komparator yoki tranzistor -> zummer.",
  "Chegarani aniq belgilash uchun avval kerakli haroratda bo'luvchi chiqishidagi kuchlanish o'lchanadi, keyin potensiometr shu qiymatga sozlanadi.",
  "Termistor o'lchanadigan joyga yaxshi tegib turishi kerak. Havodagi harorat va yuza harorati farq qiladi.",
  "Amaliy qo'llanish: server xonasi, akkumulyator zaryadlagichi, issiqxona — hamma joyda ortiqcha qizishdan ogohlantirish kerak."],
 "Qurilmani real vaziyatda sinatib ko'ring: issiq suvli stakanni yaqinlashtirib, javob vaqtini o'lchang. Javob tezligi ham muhandislik parametri.",
 [("Chegarani qanday aniq sozlash mumkin?", "Kerakli haroratdagi kuchlanishni o'lchab, potensiometrni shunga sozlab."),
  ("Termistor qayerga joylashtiriladi?", "O'lchanadigan yuzaga tegib turadigan joyga.")],
 "Chegarani ko'z bilan taxminan sozlash — qurilma noto'g'ri haroratda ishga tushadi."),

"Reed va Hall datchiklari": T(
 "Ikki datchikni bir zanjirda sinab, javob tezligi va masofasini solishtirish",
 ["Reed — mexanik: kontaktlar magnitdan tortilib tutashadi. Hall — elektron: magnit maydonida kuchlanish hosil bo'ladi.",
  "Reed sekin (millisekundlar), cheklangan resursli (million marta), lekin quvvat talab qilmaydi va oddiy.",
  "Hall tez (mikrosekundlar), cheksiz resursli, lekin doimiy quvvat oladi va uch oyoqli.",
  "Tanlov: eshik ochilishi kabi kam takrorlanadigan hodisa uchun reed, aylanish sanash uchun Hall."],
 "Tanlov mezonini o'quvchilar o'zi ayta olsin: \"tez-tez takrorlanadimi?\" degan savol javobni beradi. Bu komponent tanlash mantiqining sodda misoli.",
 [("Qaysi datchik tez javob beradi?", "Hall."),
  ("Eshik ochilishini sezish uchun qaysi biri mos?", "Reed — kam takrorlanadi, quvvat talab qilmaydi.")],
 "Reed datchikni yuqori chastotali aylanish sanashga ishlatish — kontaktlar tez yeyiladi."),

"Tovush datchigi": T(
 "Mikrofon modulining analog chiqishini kuzatib, turli tovushlarga javobini yozib olish",
 ["Modulda elektret mikrofon, LM393 komparator va kuchaytirgich bor.",
  "Analog chiqish (A0) tovush kuchiga proporsional o'zgaradi, lekin u tez tebranadi — o'rtacha qiymat olish kerak.",
  "Raqamli chiqish (D0) faqat chegaradan oshganda ishlaydi. Potensiometr shu chegarani belgilaydi.",
  "Mikrofon TOVUSH KUCHINI o'lchaydi, uning mazmunini emas. Nutqni tanish uchun butunlay boshqa texnologiya kerak — bu 7-8-sinf AI mavzusi."],
 "\"Kuch\" va \"mazmun\" farqini aniq ajrating. O'quvchilar mikrofon modulidan ovozni tanishni kutadi va bu tushunmovchilikni oldindan bartaraf qilish kerak.",
 [("Mikrofon moduli nimani o'lchaydi?", "Tovush kuchini."),
  ("Nutqni tanish uchun bu yetarlimi?", "Yo'q, buning uchun boshqa texnologiya kerak.")],
 "Modulda ovoz mazmunini tanishni kutish."),

"Suv sathi va tuproq namligi datchiklari": T(
 "Ikki datchikni kalibrlab, sug'orish tizimi uchun chegara qiymatlarini aniqlash",
 ["Ikkala datchik ham qarshilik tamoyilida ishlaydi: o'tkazuvchanlik o'lchanadi.",
  "Kalibrlash zarur: har suv va tuproq turi uchun qiymatlar farq qiladi. Ikki nuqta olinadi — mutlaqo quruq va to'liq nam.",
  "Elektroliz muammosi ikkalasida ham bor. Yechim: doimiy emas, davriy o'lchash (masalan har 10 daqiqada bir sekund).",
  "Sig'imli tuproq datchigi bu muammodan xoli va uzoq muddatli loyihalar uchun afzal."],
 "Davriy o'lchash g'oyasini kiriting — bu quvvat tejash va uzoq xizmat qilishning muhim usuli, ESP32 darslarida (deep sleep) qayta uchraydi.",
 [("Nega datchiklar davriy o'lchashi kerak?", "Elektrolizni kamaytirish va quvvat tejash uchun."),
  ("Kalibrlashda qaysi ikki nuqta olinadi?", "Mutlaqo quruq va to'liq nam holat.")],
 "Kalibrlashsiz tayyor chegarani ishlatish — boshqa tuproqda tizim noto'g'ri ishlaydi."),

"Qiyalik va tebranish datchiklari": T(
 "Tilt va tebranish datchiklarini sinab, javob xarakterini solishtirish",
 ["Tilt datchik statik holatga javob beradi: qiyshaygan holatda kontakt tutashib turadi.",
  "Tebranish (vibration) datchigi esa dinamik hodisaga javob beradi: ichidagi prujina zarbadan tebranib, qisqa impuls beradi.",
  "Tebranish datchigining signali juda qisqa (millisekundlar) — uni ushlab qolish uchun kondensatorli sxema yoki dasturiy ushlash kerak.",
  "Amaliy qo'llanish: signalizatsiya, paket tashish nazorati, o'yinchoqlar, zilzila sensori (soddalashtirilgan)."],
 "Signal qisqaligi muammosini ko'rsating: datchik ishlayapti, lekin LED yonmagandek ko'rinadi. Yechim kondensator bilan impulsni cho'zish.",
 [("Tebranish datchigi qanday signal beradi?", "Juda qisqa impuls."),
  ("Uni qanday ushlab qolish mumkin?", "Kondensatorli sxema yoki dasturiy usul bilan.")],
 "Tebranish datchigidan uzun signal kutish — u faqat zarba lahzasida ishlaydi."),

"DC motor tuzilishi va ishlashi": T(
 "Motorni qismlarga ajratib ko'rish (o'qituvchi namoyishi) va parametrlarini o'lchash",
 ["Ichida: doimiy magnitlar (stator), g'altakli yakor (rotor), kollektor va grafit cho'tkalar.",
  "Cho'tkalar har yarim aylanishda g'altakdagi tok yo'nalishini almashtiradi — shu tufayli aylanish uzluksiz davom etadi.",
  "Bo'sh yurish toki kichik (50-100 mA), yuklama ortgan sari tok oshadi. To'liq to'xtatilganda (stall) tok maksimal bo'ladi va motor qiziydi.",
  "Cho'tkalar yeyiladigan qism — motorning xizmat muddatini shular belgilaydi. Cho'tkasiz (BLDC) motorlar uzoqroq ishlaydi, lekin elektron boshqaruv talab qiladi."],
 "Eski motorni ochib ko'rsating: kollektor va cho'tkalarni ko'rish tushuntirishdan ancha samarali. Har sinfda bitta \"qurbon\" motor bo'lsin.",
 [("Cho'tkalar nima vazifasini bajaradi?", "G'altakdagi tok yo'nalishini davriy almashtiradi."),
  ("Motor to'xtatilganda tok qanday o'zgaradi?", "Maksimal darajaga ko'tariladi.")],
 "Motorni valdan ushlab uzoq to'xtatib turish — u qiziydi va g'altak kuyishi mumkin."),

"Motor tezligini o'zgartirish": T(
 "Rezistor va PWM (qo'lda tugma bilan) usullarini solishtirib, tezlik va kuchni o'lchash",
 ["Birinchi usul — ketma-ket rezistor: kuchlanish kamayadi, motor sekinlashadi. Kamchiligi: rezistorda energiya issiqlikka aylanib isrof bo'ladi va motorning kuchi keskin kamayadi.",
  "Ikkinchi usul — PWM: kuchlanish to'liq beriladi, lekin qisqa impulslar bilan. O'rtacha quvvat impuls kengligiga bog'liq.",
  "PWM da motor kuchini yo'qotmaydi, chunki impuls paytida to'liq kuchlanish keladi. Energiya ham isrof bo'lmaydi.",
  "Shuning uchun barcha zamonaviy tezlik regulyatorlari PWM asosida ishlaydi. Buni mikrokontroller yoki maxsus mikrosxema bajaradi."],
 "Rezistorli usulda motor kuchining yo'qolishini qo'l bilan valini ushlab sezdiring. Ikki usul farqi shu bilan yaqqol ko'rinadi.",
 [("Rezistor bilan tezlikni kamaytirishning kamchiligi nima?", "Energiya isrof bo'ladi va motor kuchi kamayadi."),
  ("PWM da motor nega kuchini yo'qotmaydi?", "Impuls paytida unga to'liq kuchlanish beriladi.")],
 "PWM chastotasini juda past qilish — motor silkinib, tovush chiqarib ishlaydi."),

"Motor yo'nalishini o'zgartirish: H-ko'prik g'oyasi": T(
 "To'rt kalitli H-ko'prik maketini yig'ib, ikki yo'nalishda aylantirish",
 ["H-ko'prik to'rt kalitdan iborat: S1, S2 yuqorida, S3, S4 pastda. Motor o'rtada.",
  "Oldinga: S1 va S4 yoqiladi. Orqaga: S2 va S3 yoqiladi. Tormoz: S3 va S4 birga yoqiladi (motor qisqa tutashadi).",
  "TAQIQLANGAN holat: S1 va S3 (yoki S2 va S4) birga yoqilishi — bu manbani to'g'ridan-to'g'ri qisqa tutashtiradi (shoot-through).",
  "Tayyor mikrosxemalarda (L298N, DRV8833) bu himoya ichida bajarilgan, lekin dasturda ham ikki yo'nalishni bir vaqtda yoqmaslik kerak."],
 "Taqiqlangan holatni doskada qizil bilan belgilang. Bu 7-8-sinfda L298N bilan ishlashda dasturiy xatoning eng qimmat turi.",
 [("Oldinga yurish uchun qaysi kalitlar yoqiladi?", "S1 va S4."),
  ("Qaysi kombinatsiya taqiqlangan?", "Bir ustundagi ikki kalit — S1 va S3.")],
 "Bir ustundagi ikki kalitni birga yoqib, manbani qisqa tutashtirish."),

"Servo motor: burchakli harakat": T(
 "Servoni qo'lda signal generatori bilan boshqarib, burchak-impuls bog'liqligini aniqlash",
 ["Servo ichida: DC motor, reduktor, potensiometr (holat datchigi) va boshqaruv sxemasi.",
  "U berilgan BURCHAKDA turadi: potensiometr joriy burchakni o'lchaydi, sxema uni kerakli qiymat bilan solishtiradi va farq yo'qolgunicha motorni yurgizadi. Bu teskari bog'lanishli tizim.",
  "Boshqaruv signali — har 20 ms da beriladigan impuls. 1 ms = 0 daraja, 1,5 ms = 90 daraja, 2 ms = 180 daraja.",
  "Servo alohida quvvat talab qiladi: harakat paytida 500 mA gacha tok oladi, bu plata pini uchun juda ko'p."],
 "Teskari bog'lanish (feedback) tushunchasini shu yerda kiriting — bu robototexnikaning asosiy g'oyalaridan biri va servoda uni ko'rish oson.",
 [("Servoda holatni nima o'lchaydi?", "Ichidagi potensiometr."),
  ("90 daraja uchun impuls uzunligi qancha?", "1,5 ms.")],
 "Servoni plata pinidan quvvatlantirish — plata qayta yuklanadi yoki ishdan chiqadi."),

"Qadamli motor haqida tushuncha": T(
 "28BYJ-48 qadamli motorni qo'lda ketma-ket faza berish orqali aylantirish",
 ["Qadamli motor aniq burchak qadamlari bilan aylanadi. Fazalarga ma'lum tartibda tok berilsa, rotor har safar bir qadamga siljiydi.",
  "28BYJ-48 da reduktor ham bor: motor o'zi 11,25 daraja qadam qiladi, reduktordan keyin chiqishda 5,625/64 daraja bo'ladi. To'liq aylanish uchun 2048 qadam kerak.",
  "Afzalligi: datchiksiz aniq holatni bilish mumkin — qadamlar sanaladi. 3D printer va skanerlarda shuning uchun ishlatiladi.",
  "Kamchiligi: sekin, ko'p quvvat sarflaydi va qadam \"o'tkazib yuborilsa\" (yuklama ko'p bo'lsa) holat haqidagi ma'lumot yo'qoladi."],
 "Fazalarni qo'lda navbat bilan ulab, motorning qadamma-qadam siljishini ko'rsating. Bu dasturlashsiz ham tamoyilni to'liq tushuntiradi.",
 [("Qadamli motorda holat qanday aniqlanadi?", "Berilgan qadamlar sanab boriladi."),
  ("28BYJ-48 uchun to'liq aylanish necha qadam?", "Taxminan 2048.")],
 "Yuklamani oshirib, qadam o'tkazib yuborilishiga yo'l qo'yish — bunda holat hisobi buziladi."),

"Motorni himoyalash: diod va kondensator": T(
 "Himoyasiz va himoyali motor zanjirlarini solishtirib, shovqin ta'sirini kuzatish",
 ["Motor ikki xil muammo yaratadi: o'chganda induktiv impuls va ishlaganda cho'tkalardan chiqadigan yuqori chastotali shovqin.",
  "Induktiv impulsdan flyback diod himoya qiladi (motorga parallel, teskari yo'nalishda).",
  "Shovqindan keramik kondensator himoya qiladi: 100 nF motor klemmalariga parallel, ba'zan har klemmadan korpusga ham qo'shimcha qo'yiladi.",
  "Shovqin sezilarli: himoyasiz motor yonidagi sensor noto'g'ri qiymat berishi, mikrokontroller esa qayta yuklanishi mumkin."],
 "Himoyasiz motorni ishlatib, yonidagi sensorning \"aqldan ozishini\" ko'rsating. Bu shovqin muammosining eng ishonarli namoyishi.",
 [("Induktiv impulsdan nima himoya qiladi?", "Flyback diod."),
  ("Cho'tka shovqinidan-chi?", "Motor klemmalariga parallel 100 nF keramik kondensator.")],
 "Faqat diod qo'yib, kondensatorni unutish — shovqin muammosi qolaveradi."),

"Sensor + ijro qurilmasi: avtomat qurish": T(
 "Sensor, boshqaruv va ijro qismlarini birlashtirib, to'liq avtomatik qurilma yig'ish",
 ["Har qanday avtomat uch bo'g'indan iborat: SEZISH (sensor) - QAROR (boshqaruv sxemasi) - IJRO (motor, LED, rele).",
  "Har bo'g'in alohida sinalishi kerak: avval sensor chiqishi o'lchanadi, keyin boshqaruv, oxirida ijro. Birdan yig'ib sinash xatoni topishni qiyinlashtiradi.",
  "Bo'g'inlar orasidagi moslik muhim: sensor chiqishi boshqaruv kirishiga mos kuchlanishda bo'lishi, boshqaruv esa ijro qurilmasining tokini ko'tara olishi kerak.",
  "Teskari bog'lanish qo'shilsa tizim yanada aqlli bo'ladi: masalan sug'orish tizimi suv berganidan keyin namlikni qayta o'lchaydi."],
 "Uch bo'g'inni alohida sinash usulini majburiy qiling. Bu modul-modul sinash tamoyili keyingi yillarda dastur yozishda ham xuddi shunday ishlaydi.",
 [("Avtomatning uch bo'g'ini qaysilar?", "Sezish, qaror, ijro."),
  ("Nega har bo'g'in alohida sinaladi?", "Xatoni tez topish uchun.")],
 "Butun qurilmani birdan yig'ib, ishlamasa qayerdan izlashni bilmay qolish."),

"Qurilmani loyihalash bosqichlari": T(
 "O'z qurilmasi uchun texnik topshiriq va blok-sxema tayyorlash",
 ["Loyihalash bosqichlari: 1) vazifani aniqlash, 2) talablarni yozish, 3) blok-sxema, 4) komponent tanlash, 5) sxema, 6) prototip, 7) sinov, 8) yaxshilash.",
  "Texnik topshiriqda aniq raqamlar bo'lishi kerak: \"tez ishlasin\" emas, \"1 sekunddan kam vaqtda javob bersin\".",
  "Blok-sxema — qurilmaning qismlari va ular orasidagi bog'lanishlar chizmasi. Detallarsiz, faqat tuzilma.",
  "Eng ko'p uchraydigan xato — bosqichlarni tashlab, darhol yig'ishga kirishish. Natijada qurilma yarim yo'lda qayta boshlanadi."],
 "Texnik topshiriqda o'lchanadigan talablarni yozishni majburiy qiling. \"Yaxshi ishlasin\" ni tekshirib bo'lmaydi, \"3 sekundda javob bersin\" ni esa mumkin.",
 [("Texnik topshiriqda talablar qanday yozilishi kerak?", "Aniq va o'lchanadigan raqamlar bilan."),
  ("Blok-sxema nimani ko'rsatadi?", "Qurilma qismlari va ular orasidagi bog'lanishlarni.")],
 "Rejalashtirmasdan darhol yig'ishga kirishish — vaqt behuda sarflanadi."),

"Prototipdan korpusli qurilmaga": T(
 "Breadboarddagi zanjirni ko'chma korpusga ko'chirish va mustahkam ulash",
 ["Prototip (breadboard) tez o'zgartirish uchun, tayyor qurilma esa ishonchlilik uchun mo'ljallangan. Ular boshqa talablarga javob beradi.",
  "Ko'chirishda ulanishlar mustahkamlanadi: burab ulash, klemma yoki kavsharlash. Breadboard uzoq muddatli qurilma uchun mos emas.",
  "Simlar uzunligini oldindan o'lchash va tartibli tortish kerak. Har simga belgi (birka) qo'yish keyinchalik ta'mirlashni osonlashtiradi.",
  "Tayyor qurilma sinovdan o'tkaziladi: silkitish, qizib ketishini tekshirish, uzoq muddat uzluksiz ishlatish."],
 "Silkitish sinovini albatta o'tkazing — bu chala ulanishlarni topishning eng tez usuli va o'quvchilar uchun qiziqarli bo'ladi.",
 [("Nega breadboard tayyor qurilma uchun mos emas?", "Kontaktlari ishonchsiz, tebranishdan uziladi."),
  ("Simlarga birka qo'yish nima uchun kerak?", "Keyinchalik ta'mirlash va o'zgartirish oson bo'lishi uchun.")],
 "Breadboardni korpusga solib, tayyor qurilma deb hisoblash — u tashishda ishdan chiqadi."),
}
