# -*- coding: utf-8 -*-
"""1-yil, 8-sinf — Arduino (2 chorak) + ESP32. 72 mavzu uchun aniq kontent."""

from kb_5_8 import T

MAVZULAR = {

# ==================================================== 1-CHORAK: Elektronika va Arduino asoslari (jadal)
"Tok, kuchlanish, qarshilik va Om qonuni": T(
 "Zanjir yig'ib, uch kattalikni o'lchash va Om qonuni bilan tekshirish",
 ["I (amper) — zaryad oqimi, U (volt) — zaryadni harakatlantiruvchi bosim, R (om) — oqimga to'sqinlik.",
  "U = I x R. Quvvat: P = U x I = I kvadrat x R = U kvadrat / R.",
  "Amaliy qisqartma: V / kOm = mA. 5 V / 1 kOm = 5 mA.",
  "Odatiy qiymatlar: LED 15 mA, Arduino 50 mA, servo 500 mA, motor 200-1000 mA. Bu raqamlar quvvat manbai tanlashda hal qiluvchi."],
 "8-sinf 1-chorakda elektronika va Arduino bir chorakda beriladi. Nazariyani minimal qoldirib, har tushunchani darhol o'lchov bilan mustahkamlang.",
 [("9 V va 3 kOm: tok qancha?", "3 mA."),
  ("Servo qancha tok oladi?", "500 mA gacha.")],
 "Birliklarni aylantirmaslik — mA va A ni aralashtirish."),

"Multimetr bilan o'lchash amaliyoti": T(
 "Kuchlanish, qarshilik va tokni o'lchab, protokol jadvalini to'ldirish",
 ["Kuchlanish — parallel, qarshilik — quvvatsiz va uzilgan holda, tok — ketma-ket.",
  "Tok o'lchashda qizil shchup A/mA teshigiga ko'chiriladi. Uni qaytarib qo'ymaslik — eng qimmat xato.",
  "Zumlash rejimi ulanishni tez tekshiradi va uzilgan simni topishning eng samarali usuli.",
  "Amalda tok ko'pincha bilvosita hisoblanadi: ma'lum rezistordagi kuchlanish o'lchanib I = U/R qo'llaniladi."],
 "Multimetrni ishlatish 8-sinfda tez o'zlashtiriladi. Ko'proq vaqtni nosozlik topishga sarflang — bu chorak davomida eng ko'p kerak bo'ladigan ko'nikma.",
 [("Tok o'lchashda shchup qayerga ko'chiriladi?", "A yoki mA teshigiga."),
  ("Zumlash nima uchun ishlatiladi?", "Ulanish bor-yo'qligini tez tekshirish uchun.")],
 "Shchupni tok teshigida qoldirib, keyin kuchlanish o'lchash."),

"Breadboard, rezistor, LED": T(
 "Breadboardni tekshirib, hisoblangan rezistor bilan LED zanjirini yig'ish",
 ["Breadboard ustunlari (5 teshik) o'zaro ulangan, o'rta tirqishdan o'tmaydi. Chetdagi shinalar quvvat uchun.",
  "Rezistorning rangli kodi: raqam, raqam, nollar soni, aniqlik. Asosiy qiymatlar: 220 Om (LED), 1 kOm (baza), 10 kOm (pull-up).",
  "LED rezistori: R = (U manba - U led) / I led. 5 V, qizil LED, 15 mA uchun 220 Om.",
  "Toza montaj: qisqa simlar, rang bo'yicha tartib, komponentlar bir yo'nalishda."],
 "Uch \"ish beruvchi\" qiymatni (220, 1k, 10k) yodlashni talab qiling — chorak davomidagi ishlarning aksariyati shular bilan bajariladi.",
 [("5 V uchun LED rezistori qancha?", "220 Om."),
  ("Pull-up rezistor uchun qaysi qiymat olinadi?", "10 kOm.")],
 "Rezistorsiz LED ulash — u bir necha sekundda kuyadi."),

"Ketma-ket, parallel va kuchlanish bo'luvchi": T(
 "Uch turdagi ulanishni yig'ib, hisob va o'lchov natijalarini solishtirish",
 ["Ketma-ket: I bir xil, U qo'shiladi, R qo'shiladi. Parallel: U bir xil, I qo'shiladi, R kamayadi.",
  "Bo'luvchi: U chiqish = U kirish x R2 / (R1 + R2), R2 — GND ga ulangan pastki rezistor.",
  "Bo'luvchi barcha analog sensorlarning asosi: fotorezistor, termistor, tuproq sensori shu sxemada ulanadi.",
  "Yuklama qoidasi: yuklama qarshiligi R2 dan kamida 10 marta katta bo'lishi kerak."],
 "Bo'luvchiga alohida urg'u bering — 8-sinf 2-chorakda har bir analog sensor darsi shu formulaga qaytadi.",
 [("Bo'luvchi formulasida R2 qaysi?", "GND ga ulangan pastki rezistor."),
  ("Parallel ulanishda umumiy qarshilik qanday bo'ladi?", "Eng kichik tarmoqdan ham kichik.")],
 "Bo'luvchidan yuklama quvvatlantirishga urinish."),

"Kondensator, diod, tranzistor": T(
 "Uch komponentni sinab, har biriga xos xususiyatni o'lchov bilan tasdiqlash",
 ["Kondensator zaryad to'playdi. Vaqt doimiysi T = R x C (kOm x uF = ms). Elektrolitik qutbli, keramik qutbsiz.",
  "Diod tokni bir yo'nalishda o'tkazadi, 0,7 V tushadi. Flyback diod g'altakli yuklamaga parallel va teskari ulanadi — bu MAJBURIY.",
  "Tranzistor kalit rejimida: baza rezistori R = (U boshqaruv - 0,7) / (I kollektor / 10).",
  "To'yingan tranzistorda kollektor-emitter kuchlanishi 0,2 V. 2-3 V bo'lsa u oraliq holatda va qiziydi."],
 "Uch komponentning har biri chorak davomida kerak bo'ladi: kondensator filtr uchun, diod motor uchun, tranzistor kuchli yuklama uchun. Ularni amaliy vazifa bilan bog'lab tushuntiring.",
 [("Flyback diod qanday ulanadi?", "Yuklamaga parallel va teskari yo'nalishda."),
  ("To'yingan tranzistorda kollektor-emitter kuchlanishi qancha?", "Taxminan 0,2 V.")],
 "Flyback diodni unutish yoki to'g'ri yo'nalishda ulash."),

"Arduino platasi va IDE": T(
 "IDE'ni sozlab, plata pinlar xaritasini chizib, birinchi dasturni yuklash",
 ["Arduino Uno: ATmega328P, 32 KB flesh, 2 KB SRAM, 16 MHz. Raqamli pinlar D0-D13, analog A0-A5.",
  "PWM pinlari ~ belgili: 3, 5, 6, 9, 10, 11. A4 va A5 I2C uchun (SDA, SCL) band bo'lishi mumkin.",
  "Pin toki: xavfsiz 20 mA, mutlaq chegara 40 mA. Butun plata 200 mA gacha.",
  "IDE sozlamalari: Tools > Board (Arduino Uno) va Tools > Port. Klon platalar uchun CH340 drayveri kerak."],
 "Pin cheklovlarini (20 mA / 200 mA) doskaga yozib, chorak oxirigacha o'chirmang. Bu raqamlar har komponent ulashda hisobga olinadi.",
 [("Arduino pinidan xavfsiz qancha tok olinadi?", "20 mA."),
  ("A4 va A5 pinlari qaysi protokol uchun band?", "I2C — SDA va SCL.")],
 "Motor yoki servoni to'g'ridan-to'g'ri pinga ulash."),

"Blink va dastur tuzilishi": T(
 "Blink dasturini yuklab, miltillash naqshini o'zgartirish",
 ["Har Arduino dasturi ikki funksiyadan iborat: setup() bir marta, loop() cheksiz takrorlanadi.",
  "setup ichida: pinMode, Serial.begin, boshlang'ich sozlamalar. loop ichida: asosiy mantiq.",
  "Blink: pinMode(13, OUTPUT); loop ichida digitalWrite(13, HIGH), delay(1000), digitalWrite(13, LOW), delay(1000).",
  "D13 pinda plataning o'z LEDi bor — tashqi komponentsiz ham natija ko'rinadi."],
 "Birinchi muvaffaqiyatli yuklashni tezda ta'minlang. Kodni tayyor bering, o'quvchilar faqat qiymatlarni o'zgartirsin — muvaffaqiyat hissi motivatsiya beradi.",
 [("setup() necha marta bajariladi?", "Bir marta."),
  ("delay(250) qancha vaqt?", "Chorak sekund.")],
 "Serial.begin ni loop ichiga yozish."),

"pinMode, digitalWrite, delay": T(
 "Beshta LED bilan turli miltillash naqshlarini yaratish",
 ["pinMode(pin, OUTPUT/INPUT) pin vazifasini belgilaydi, odatda setup ichida.",
  "digitalWrite(pin, HIGH/LOW) chiqishga 5 V yoki 0 V beradi.",
  "delay(ms) dasturni to'xtatib turadi. Muhim kamchilik: bu vaqtda plata boshqa hech narsa qila olmaydi.",
  "Shuning uchun murakkab dasturlarda delay o'rniga millis() ishlatiladi — u vaqtni sanaydi, lekin dasturni to'xtatmaydi."],
 "delay ning kamchiligini shu darsda ayting va 2-chorakda millis() bilan yechimni bering. Muammoni oldin his qilish yechimni yaxshi o'zlashtiradi.",
 [("delay paytida tugma o'qiladimi?", "Yo'q, dastur to'liq to'xtaydi."),
  ("pinMode unutilsa nima bo'ladi?", "LED xira yonadi yoki umuman yonmaydi.")],
 "pinMode ni unutish."),

"O'zgaruvchi va ma'lumot turlari": T(
 "Turli turdagi o'zgaruvchilar bilan hisoblash qilib, xotira sarfini solishtirish",
 ["int — butun son (2 bayt, -32768..32767), long — katta butun (4 bayt), float — kasrli (4 bayt), bool — true/false (1 bayt), byte — 0..255 (1 bayt).",
  "Arduino Uno da faqat 2 KB SRAM bor. Katta massivlar va String'lar xotirani tez to'ldiradi.",
  "float hisoblash int dan ancha sekin — mikrokontrollerda apparat float qo'llab-quvvatlanmaydi. Kerak bo'lmasa ishlatilmaydi.",
  "millis() long qaytaradi va u ~50 kundan keyin to'lib ketadi (overflow). Uzoq ishlaydigan qurilmada buni hisobga olish kerak."],
 "2 KB SRAM cheklovi 8-sinf uchun muhim tushuncha: bu kompyuter dasturlashdan asosiy farq. Xotira haqida o'ylash ko'nikmasi shu yerda boshlanadi.",
 [("Arduino Uno da qancha SRAM bor?", "2 kilobayt."),
  ("Nega float dan iloji boricha qochiladi?", "Hisoblash sekin va ko'p xotira oladi.")],
 "Hamma joyda float va String ishlatish — xotira tugaydi va dastur beqaror ishlaydi."),

"for va while sikllari": T(
 "Ikki sikl bilan bir xil vazifani bajarib, qaysi holatda qaysi biri qulayligini aniqlash",
 ["for (boshlang'ich; shart; qadam) — takrorlanish soni ma'lum bo'lganda.",
  "while (shart) — shartga bog'liq takrorlanish uchun. do...while esa kamida bir marta bajaradi.",
  "Ichma-ich sikllar (nested) matritsa va murakkab naqshlar uchun: tashqi sikl qatorlar, ichki sikl ustunlar.",
  "break sikldan chiqadi, continue esa joriy iteratsiyani tashlab, keyingisiga o'tadi."],
 "break va continue ni oddiy misolda ko'rsating. 8-sinf darajasida bular kerak bo'ladi va ularni bilmaslik kodni murakkablashtiradi.",
 [("break nima qiladi?", "Sikldan butunlay chiqadi."),
  ("continue-chi?", "Joriy iteratsiyani tashlab, keyingisiga o'tadi.")],
 "Cheksiz sikl yozish — while ichida shartga ta'sir qiladigan amalni unutish."),

"digitalRead va tugma bilan ishlash": T(
 "INPUT_PULLUP bilan tugmani o'qib, holat almashtiruvchi (toggle) dastur yozish",
 ["digitalRead(pin) pinning holatini HIGH yoki LOW deb qaytaradi.",
  "INPUT_PULLUP ichki tortuvchi rezistorni yoqadi — tashqi rezistor kerak emas. Mantiq teskari: bosilganda LOW.",
  "Toggle (holat almashtirish) uchun tugmaning BOSILISH LAHZASINI aniqlash kerak, holatini emas: oldingi va joriy holat solishtiriladi.",
  "Kod: agar oldingiHolat == HIGH va joriyHolat == LOW bo'lsa — tugma yangi bosildi."],
 "\"Holat\" va \"o'zgarish lahzasi\" farqini alohida tushuntiring. Bu tushunchani bilmaslik toggle dasturlarining ishlamasligiga olib keladi.",
 [("INPUT_PULLUP da bosilgan tugma qanday o'qiladi?", "LOW."),
  ("Toggle uchun nima aniqlanadi?", "Tugmaning bosilish lahzasi, holati emas.")],
 "Tugma holatini tekshirib toggle qilishga urinish — LED tinimsiz almashadi."),

"if / else if / else": T(
 "Sensor qiymatiga qarab uch xil javob beradigan dastur yozish",
 ["if (shart) — rost bo'lsa bajariladi. else — aks holda. else if — bir necha shartni ketma-ket tekshirish.",
  "Solishtirish belgilari: == (teng), != , > , < , >= , <=. Bitta = qiymat berish, ikki == solishtirish.",
  "Shartlar TARTIBI muhim: kengroq shart oldin yozilsa, torroq shart hech qachon bajarilmaydi.",
  "switch...case bir o'zgaruvchining aniq qiymatlarini tekshirish uchun qulay va else if zanjiridan tushunarliroq."],
 "switch...case ni 8-sinfda kiriting — u pult tugmalari va menyu dasturlarida keyinchalik juda foydali bo'ladi.",
 [("Shartlar tartibi nega muhim?", "Kengroq shart oldin bo'lsa, torroq shart bajarilmaydi."),
  ("switch qachon qulay?", "Bir o'zgaruvchining aniq qiymatlarini tekshirishda.")],
 "if ichida bitta teng belgisi (=) yozish."),

"Mantiqiy amallar: VA, YOKI, EMAS": T(
 "Ikki sensorli shartlarni turli mantiqiy amallar bilan birlashtirib sinash",
 ["&& (VA) — ikkala shart ham rost bo'lishi kerak. || (YOKI) — kamida bittasi. ! (EMAS) — natijani teskarilaydi.",
  "Rostlik jadvali: 1&&1=1, qolganlari 0. 0||0=0, qolganlari 1.",
  "Qisqa tutashuvli hisoblash: && da birinchi shart yolg'on bo'lsa, ikkinchisi umuman tekshirilmaydi. Bu tezlik beradi.",
  "Amaliy misol: if (harorat > 30 && namlik < 40) — shamollatgichni faqat issiq VA quruq bo'lsa yoqish."],
 "5-sinfdagi ikki tugmali VA/YOKI zanjirlariga havola qiling: bir xil mantiq, endi apparat emas, dasturiy shaklda.",
 [("&& qachon rost beradi?", "Ikkala shart ham rost bo'lganda."),
  ("! amali nima qiladi?", "Natijani teskarilaydi.")],
 "&& o'rniga & (bitli amal) yozish — natija boshqacha chiqadi."),

"Serial monitor va nosozlik topish": T(
 "Serial orqali dasturning bajarilish yo'lini kuzatib, xatoni topish",
 ["Serial.begin(9600) setup ichida. Serial.print / println bilan qiymat yuboriladi.",
  "Nosozlik topishning asosiy usuli: shubhali joylarga Serial.println(\"1-nuqta\") qo'yib, dastur qayergacha yetayotganini ko'rish.",
  "O'zgaruvchi qiymatlarini chiqarish taxminni tekshiradi: sensor haqiqatan kutilgan qiymat beryaptimi?",
  "Serial Plotter grafik chizadi — shovqin va o'zgarish xarakterini ko'rish uchun jadvaldan ancha samarali."],
 "\"Taxmin qilma, o'lchab ko'r\" tamoyilini o'rnating. Ko'r-ko'rona kod o'zgartirish — 8-sinfda eng ko'p vaqt yo'qotadigan odat.",
 [("Dastur qayergacha yetganini qanday bilish mumkin?", "Serial.println bilan nuqtalar qo'yib."),
  ("Serial Plotter nimani ko'rsatadi?", "Qiymatlarning grafigini.")],
 "Kompilyatsiya xatosi xabarini o'qimay, kodni tasodifan o'zgartirish."),

"analogRead va analog signal": T(
 "Turli analog manbalarni o'qib, qiymatlar oralig'ini aniqlash",
 ["analogRead(pin) 0-1023 oralig'ida qiymat qaytaradi (10 razryadli ADC).",
  "Bitta darajaning qiymati: 5 V / 1024 = 4,9 mV. Undan kichik farq sezilmaydi.",
  "O'lchash vaqti ~100 mikrosekund, ya'ni sekundiga ~10000 marta o'qish mumkin.",
  "Shovqinni kamaytirish uchun bir necha o'lchov o'rtachasi olinadi: 10 marta o'qib, yig'indini 10 ga bo'lish."],
 "O'rtacha olish usulini shu darsda kiriting va shovqinning kamayishini Serial Plotter'da ko'rsating. Farq juda yaqqol ko'rinadi.",
 [("analogRead qanday oraliq beradi?", "0 dan 1023 gacha."),
  ("Shovqinni qanday kamaytirish mumkin?", "Bir necha o'lchov o'rtachasini olib.")],
 "Bitta o'lchovga tayanib qaror qabul qilish — shovqin tufayli tizim beqaror ishlaydi."),

"PWM va analogWrite": T(
 "PWM bilan LED yorqinligi va motor tezligini boshqarish",
 ["PWM — impuls kengligi modulyatsiyasi: pin tez yoqilib-o'chiriladi, o'rtacha quvvat yoqiq vaqt ulushiga bog'liq.",
  "analogWrite(pin, 0-255). Faqat ~ belgili pinlarda: 3, 5, 6, 9, 10, 11.",
  "Arduino Uno da PWM chastotasi 490 Hz (5 va 6-pinlarda 980 Hz). LED va motor uchun yetarli.",
  "PWM analog signal EMAS — u tez o'zgaruvchi raqamli signal. Haqiqiy analog chiqish uchun DAC kerak, Uno da u yo'q."],
 "\"PWM analog emas\" fikrini ta'kidlang. analogWrite nomi chalg'itadi va bu tushunmovchilik ESP32 dagi DAC mavzusida yana yuzaga chiqadi.",
 [("analogWrite qanday oraliqda ishlaydi?", "0 dan 255 gacha."),
  ("Uno da haqiqiy analog chiqish bormi?", "Yo'q, DAC yo'q.")],
 "PWM'siz pinda analogWrite ishlatish."),

"map() va qiymatlarni moslash": T(
 "Sensor qiymatlarini turli chiqish oraliqlariga moslash",
 ["map(qiymat, eskiMin, eskiMax, yangiMin, yangiMax) proporsional o'tkazadi.",
  "Odatiy ishlatilishi: map(analogRead(A0), 0, 1023, 0, 255) — ADC dan PWM ga.",
  "Faqat butun sonlar bilan ishlaydi. Kasrli aniqlik kerak bo'lsa qo'lda hisoblash yoki oldin 100 ga ko'paytirish kerak.",
  "constrain(qiymat, min, maks) qiymatni chegaralar ichida ushlaydi — map dan keyin doim ishlatish tavsiya etiladi."],
 "map va constrain ni juftlik sifatida o'rgating. constrain'siz map kutilmagan qiymatlar berishi mumkin va bu topish qiyin xato.",
 [("map faqat qanday sonlar bilan ishlaydi?", "Butun sonlar bilan."),
  ("constrain nima qiladi?", "Qiymatni belgilangan chegaralarda ushlaydi.")],
 "map natijasini cheklamaslik."),

"Kodni toza yozish: nom berish va izoh": T(
 "Chalkash yozilgan kodni qayta nomlab, izohlar qo'shib, tushunarli holga keltirish",
 ["Nomlash qoidalari: o'zgaruvchi nomi nima saqlashini bildirsin (haroratChegara, sensorPin), funksiya nomi nima qilishini (miltillaSvetofor).",
  "Sehrli raqamlar taqiqlanadi: kodda 220 emas, const int LED_PIN = 9; deb nomlangan doimiy ishlatiladi.",
  "Izoh NEGA shunday qilinganini tushuntirishi kerak, nima qilinayotganini emas. Kod o'zi nima qilishini ko'rsatib turadi.",
  "Bo'sh qatorlar bilan kodni mantiqiy bo'laklarga ajratish o'qishni sezilarli osonlashtiradi."],
 "O'quvchilar kodini almashtirib, bir-birinikini o'qisin. \"Tushunmadim\" degan javob toza kod yozishning zarurligini eng yaxshi isbotlaydi.",
 [("Izohda nima yozilishi kerak?", "Nega shunday qilingani."),
  ("Sehrli raqam nima?", "Kodda to'g'ridan-to'g'ri yozilgan, nomlanmagan son.")],
 "Bir harfli o'zgaruvchi nomlari ishlatish."),

# ==================================================== 2-CHORAK: Arduino — sensorlar va ijro (yakun)
"O'z funksiyangni yozish va qayta ishlatish": T(
 "Takrorlanadigan kodni parametrli funksiyalarga chiqarib, dasturni qayta tuzish",
 ["Funksiya e'loni: qaytaruvchiTuri nom(parametrlar) { ... }. void — qiymat qaytarmaydi.",
  "Parametr funksiyaga ma'lumot uzatadi, return esa natijani qaytaradi.",
  "Funksiya bitta aniq vazifani bajarishi kerak. \"Sensorni o'qib, ekranga chiqarib, releni yoqadigan\" funksiya juda ko'p ish qiladi — uni bo'lish kerak.",
  "Funksiyalarga bo'lingan kodni sinash osonroq: har funksiyani alohida tekshirish mumkin."],
 "\"Bitta funksiya — bitta vazifa\" tamoyilini o'rnating. Bu keyingi choraklardagi ESP32 loyihalarida kodni boshqarib bo'ladigan holda saqlaydi.",
 [("Funksiya nechta vazifani bajarishi kerak?", "Bitta aniq vazifani."),
  ("return nima qiladi?", "Natijani chaqiruvchi joyga qaytaradi.")],
 "Bitta funksiyaga hamma ishni yuklash — uni sinash va tuzatish qiyinlashadi."),

"Massiv va sikl bilan ishlash": T(
 "Sensor qiymatlarini massivga yig'ib, o'rtacha va maksimal qiymatni hisoblash",
 ["Massiv: int qiymatlar[10]; — 10 ta int uchun joy. Indekslar 0 dan 9 gacha.",
  "Aylanma bufer (circular buffer): oxirgi N ta qiymatni saqlash uchun indeks massiv oxiriga yetganda 0 ga qaytariladi.",
  "O'rtacha hisoblash: sikl bilan yig'indi topiladi va elementlar soniga bo'linadi.",
  "Massiv chegarasidan chiqish Arduino'da xato bermaydi — u boshqa o'zgaruvchining xotirasini buzadi va dastur tushunarsiz ishlaydi."],
 "Massiv chegarasidan chiqish xavfini alohida ta'kidlang: Arduino ogohlantirmaydi va bu xato eng qiyin topiladiganlardan biri.",
 [("10 elementli massivda indekslar qanday?", "0 dan 9 gacha."),
  ("Chegaradan chiqilsa nima bo'ladi?", "Boshqa o'zgaruvchining xotirasi buziladi.")],
 "Massiv chegarasidan chiqish."),

"Fotorezistor va termistor": T(
 "Ikki analog sensorni bo'luvchiga ulab, kalibrlash jadvalini tuzish",
 ["Ikkalasi ham qarshilikli sensor — bo'luvchi sxemasida ulanadi va analogRead bilan o'qiladi.",
  "Fotorezistor: yorug'da qarshilik kichik. Termistor (NTC): issiqda qarshilik kichik.",
  "Kalibrlash ikki nuqtada: fotorezistor uchun qorong'i va yorug'; termistor uchun muzli va issiq suv.",
  "Har sensor va sharoit uchun qiymatlar farq qiladi — tayyor chegara ishlatib bo'lmaydi."],
 "Kalibrlashni har juftlik o'z sensori uchun bajarsin. Tayyor raqamlarni bermang: kalibrlash ko'nikmasi sensor bilan ishlashning asosi.",
 [("NTC termistorda issiqda qarshilik qanday bo'ladi?", "Kichik."),
  ("Kalibrlash uchun nechta nuqta kerak?", "Kamida ikkita ma'lum nuqta.")],
 "Boshqa guruhning kalibrlash qiymatlarini ko'chirib olish."),

"DHT22 va kutubxona ishlatish": T(
 "DHT22 dan harorat va namlikni o'qib, ekranga chiqarish",
 ["DHT22 raqamli sensor: o'zi o'lchab, natijani bitta sim orqali raqam sifatida yuboradi.",
  "Kutubxona: DHT sensor library (Adafruit). Kodda #include <DHT.h>, DHT dht(2, DHT22);",
  "O'qish: dht.readTemperature() va dht.readHumidity(). Natija float qaytadi.",
  "Cheklovlar: sekundiga bir marta o'qish; ma'lumot pini VCC bilan 10 kOm rezistor orqali tortilishi kerak. Aks holda \"nan\" qaytadi."],
 "\"nan\" natijasi eng ko'p uchraydigan muammo. Uning ikki sababini (tez o'qish va tortuvchi rezistor yo'qligi) oldindan aytib qo'ying.",
 [("DHT22 dan qanchalik tez-tez o'qish mumkin?", "Sekundiga bir marta."),
  ("nan qaytsa nima tekshiriladi?", "O'qish tezligi va tortuvchi rezistor.")],
 "isnan() bilan tekshirmasdan natijani ishlatish — hisoblar buziladi."),

"HC-SR04 masofa o'lchagich": T(
 "Ultratovush sensori bilan masofani o'lchab, o'rtacha qiymat bilan barqarorlashtirish",
 ["TRIG ga 10 mkrs impuls, ECHO da qaytish vaqti o'lchanadi. Masofa = vaqt x 0,034 / 2.",
  "0,034 koeffitsienti tovush tezligidan (340 m/s) kelib chiqadi. Tovush tezligi haroratga bog'liq — aniq o'lchovda tuzatish kerak.",
  "Diapazon 2-400 sm. Yumshoq, qiya va juda kichik yuzalar tovushni yaxshi qaytarmaydi.",
  "Barqarorlik uchun 5 ta o'lchov olinadi va ularning MEDIANASI (o'rtadagisi) ishlatiladi — bu tasodifiy chetlanishlarni yo'q qiladi."],
 "Mediana va o'rtachaning farqini tushuntiring: bitta juda katta xato o'rtachani buzadi, medianaga esa ta'sir qilmaydi. Bu statistikaning amaliy misoli.",
 [("Nega o'lchangan vaqt ikkiga bo'linadi?", "Tovush borib qaytadi."),
  ("Nega mediana o'rtachadan afzal?", "Bitta katta xato natijaga ta'sir qilmaydi.")],
 "Bitta o'lchovga tayanib qaror qabul qilish."),

"PIR harakat datchigi": T(
 "PIR bilan harakatni sezib, vaqt bilan yozib boruvchi qurilma yig'ish",
 ["PIR passiv sensor: issiq jismlardan kelayotgan IK nurlanish O'ZGARISHINI sezadi, qimirlamay turgan odamni sezmaydi.",
  "Ikki potensiometr: sezgirlik va ushlab turish vaqti. Yoqilgandan keyin 30-60 sekund isinish kerak.",
  "Chiqish raqamli: harakat sezilganda HIGH bo'ladi va sozlangan vaqt davomida shunday qoladi.",
  "Yolg'on ishga tushish sabablari: issiq havo oqimi, quyosh nuri, uy hayvonlari. Ikkinchi sensor bilan tasdiqlash ishonchlilikni oshiradi."],
 "Isinish vaqtini aytmasangiz, o'quvchilar dastlabki yolg'on signallarni nosozlik deb o'ylab sozlamalarni behuda o'zgartiradi.",
 [("PIR qimirlamay turgan odamni sezadimi?", "Yo'q."),
  ("Yoqilgandan keyin qancha kutish kerak?", "30-60 sekund.")],
 "Isinish vaqtini kutmasdan sozlamalarni o'zgartirishga kirishish."),

"Tuproq, suv va olov datchiklari": T(
 "Uch datchikni kalibrlab, xavfsizlik va sug'orish tizimi maketini yig'ish",
 ["Tuproq va suv datchiklari qarshilik tamoyilida ishlaydi, olov datchigi IK nurlanishni sezadi.",
  "Qarshilikli datchiklarda elektroliz muammosi bor: doimiy quvvat elektrodlarni yemiradi. Yechim — faqat o'lchash paytida quvvat berish.",
  "Olov datchigi quyosh va lampa nuridan yolg'on ishga tushadi. Ko'rish burchagi 60 daraja, masofa 20-100 sm.",
  "Ishonchli tizimda ikki sensor tasdig'i talab qilinadi — bu yolg'on signallarni keskin kamaytiradi."],
 "Sensorni pin orqali quvvatlantirish usulini ko'rsating (digitalWrite bilan yoqib-o'chirish). Bu oddiy yechim sensor umrini bir necha barobar uzaytiradi.",
 [("Elektroliz muammosi qanday hal qilinadi?", "Faqat o'lchash paytida quvvat berib."),
  ("Olov datchigi nimadan yolg'on ishga tushadi?", "Quyosh va lampa nuridan.")],
 "Datchikni doimiy quvvatga ulab qoldirish."),

"Ovoz datchigi va qarsakli boshqaruv": T(
 "Qarsak bilan chiroqni yoqib-o'chiruvchi qurilma yozish",
 ["Mikrofon moduli tovush kuchini o'lchaydi. A0 — analog qiymat, D0 — chegaradan oshganini bildiradi.",
  "Qarsak qisqa va kuchli tovush — uni fon shovqinidan ajratish uchun chegara to'g'ri sozlanishi kerak.",
  "Ikki qarsakni tanish uchun vaqt oynasi ishlatiladi: birinchi qarsakdan keyin 500 ms ichida ikkinchisi kelsa — buyruq deb qabul qilinadi.",
  "Yolg'on ishga tushishni kamaytirish: bitta qarsak emas, ikki qarsak talab qilinadi."],
 "Ikki qarsakli mantiqni millis() bilan qurishni birgalikda tahlil qiling. Bu vaqt bilan ishlashning amaliy va qiziqarli misoli.",
 [("Nega bitta emas, ikki qarsak talab qilinadi?", "Yolg'on ishga tushishni kamaytirish uchun."),
  ("Ikki qarsak orasidagi vaqt qanday tekshiriladi?", "millis() bilan vaqt oynasi orqali.")],
 "Sezgirlikni maksimalga qo'yish — qurilma har shovqindan ishlaydi."),

"Servo motorni boshqarish": T(
 "Servo bilan aniq burchakli mexanizm (shlagbaum yoki qo'l) yasash",
 ["Servo kutubxonasi: #include <Servo.h>, Servo s; s.attach(9); s.write(burchak);",
  "Burchak 0-180 daraja. Burilish tezligi cheklangan: 60 daraja uchun 0,1-0,2 sekund.",
  "Silliq harakat uchun burchak birdan emas, bosqichma-bosqich o'zgartiriladi: sikl bilan 1 gradusdan, orasida kichik delay.",
  "Servo 500 mA gacha tok oladi — alohida 5 V manba kerak, GND umumiy bo'lishi shart."],
 "Silliq harakat kodini yozdiring — birdan burilish va bosqichma-bosqich burilish farqi mexanizmning ko'rinishini butunlay o'zgartiradi.",
 [("Servo qancha tok oladi?", "500 mA gacha."),
  ("Silliq harakat qanday qilinadi?", "Burchakni bosqichma-bosqich, kichik kechikish bilan o'zgartirib.")],
 "Servoni Arduino 5V pinidan quvvatlantirish."),

"DC motor va L298N": T(
 "L298N bilan motorni ikki yo'nalishda va tezlik bilan boshqarish",
 ["L298N ikki kanalli H-ko'prik: har kanalga IN1, IN2 (yo'nalish) va ENA (PWM tezlik).",
  "IN1=HIGH, IN2=LOW — oldinga; teskarisi — orqaga; ikkalasi teng — to'xtash.",
  "ENA jamperi olinmasa PWM ishlamaydi — motor doim to'liq tezlikda aylanadi.",
  "L298N da 1,5-2 V yo'qoladi va u qiziydi. 12 V berilsa motorga ~10 V yetadi. Zamonaviy alternativa — DRV8833 yoki TB6612FNG."],
 "Kuchlanish yo'qotishini o'lchatib ko'rsating. Bu \"komponent tanlash oqibatlari bor\" degan muhandislik tushunchasining aniq misoli.",
 [("ENA pini nima uchun?", "PWM bilan tezlikni boshqarish uchun."),
  ("L298N da qancha kuchlanish yo'qoladi?", "1,5-2 V.")],
 "ENA jamperini olmasdan tezlikni boshqarmoqchi bo'lish."),

"Qadamli motor": T(
 "28BYJ-48 bilan aniq burchakli aylantirish mexanizmini yasash",
 ["28BYJ-48 + ULN2003 drayveri. To'rt pin (IN1-IN4) Arduino'ga ulanadi.",
  "Stepper kutubxonasi: Stepper motor(2048, 8, 10, 9, 11); — pinlar tartibi ataylab shunday.",
  "To'liq aylanish 2048 qadam. 90 daraja = 512 qadam. Aniqlik yuqori, tezlik past (~15 aylanish/daqiqa).",
  "Motor to'xtaganda ham fazalarga tok berilib turadi va u qiziydi. Kerak bo'lmaganda fazalarni o'chirish quvvat tejaydi."],
 "To'xtagan motorning qizishini sezdiring va fazalarni o'chirish yechimini bering. Bu quvvat boshqaruvining sodda va amaliy misoli.",
 [("28BYJ-48 uchun to'liq aylanish necha qadam?", "2048."),
  ("Nega to'xtagan motor qiziydi?", "Fazalarga tok berilib turadi.")],
 "Stepper kutubxonasidagi pinlar tartibini \"tuzatish\"."),

"Rele bilan kuchli yuklama": T(
 "Rele moduli bilan 12 V yuklamani dasturdan boshqarish",
 ["Rele moduli: VCC, GND, IN. Ichida tranzistor, flyback diod va ko'pincha optopara bor.",
  "Ko'p modullar teskari mantiqda: IN ga LOW berilganda rele yoqiladi.",
  "Yuklama COM va NO kontaktlariga ulanadi. Modulning kontakt reytingi korpusda yozilgan.",
  "Sinfda maksimal 12 V yuklama ishlatiladi. 220 V — faqat o'qituvchi namoyishi, o'quvchilar mustaqil ishlamaydi."],
 "Teskari mantiqni oldindan sinab, sinfga aytib qo'ying. Bu bilmasdan yozilgan to'g'ri kod ham teskari natija beradi.",
 [("Ko'p rele modullarida rele qachon yoqiladi?", "IN ga LOW berilganda."),
  ("Sinfda maksimal qanday yuklama ruxsat etiladi?", "12 V.")],
 "220 V bilan mustaqil ishlashga urinish — qat'iy taqiqlanadi."),

"Zummer va melodiya": T(
 "Massiv bilan melodiya chalib, tugmalar bilan boshqariladigan \"pianino\" yasash",
 ["tone(pin, chastota, davomiylik) va noTone(pin). Passiv zummer kerak.",
  "Melodiya ikki massivda: notalar va davomiyliklar. Sikl bilan navbat bilan chalinadi.",
  "Notalar orasida pauza kerak — odatda davomiylikning 30% i, aks holda notalar qo'shilib ketadi.",
  "Cheklov: tone() Timer2 ni ishlatadi va 3, 11-pinlardagi PWM bilan to'qnashadi."],
 "Timer to'qnashuvini eslatib turing — servo (Timer1) va tone (Timer2) birga ishlatilganda muammo chiqadi va sababini bilish kerak.",
 [("Melodiya uchun nechta massiv kerak?", "Ikkita."),
  ("tone() qaysi pinlardagi PWM bilan to'qnashadi?", "3 va 11-pinlarda.")],
 "Aktiv zummer bilan melodiya chalishga urinish."),

"LCD 1602 va I2C": T(
 "I2C LCD ni ulab, ikki qatorli ma'lumot paneli yasash",
 ["I2C moduli bilan 4 sim: VCC, GND, SDA (A4), SCL (A5). Kutubxona: LiquidCrystal_I2C.",
  "Manzil odatda 0x27 yoki 0x3F — I2C skaner bilan aniqlanadi.",
  "lcd.setCursor(ustun, qator), lcd.print(matn), lcd.clear().",
  "Eski matn qoldig'i muammosi: qisqaroq matn yozilganda oldingi belgilar ko'rinib qoladi. Yechim — orqasidan bo'sh joy yozish."],
 "16x2 ekran maketini qog'ozda rejalashtirishni talab qiling. Joy juda kam va rejasiz ma'lumot sig'maydi.",
 [("I2C LCD uchun nechta sim kerak?", "To'rtta."),
  ("Matn ko'rinmasa birinchi nima tekshiriladi?", "Kontrast potensiometri va I2C manzili.")],
 "I2C manzilini tekshirmasdan tayyor kodni ishlatish."),

"7-segment va 74HC595": T(
 "Siljish registri orqali ikki razryadli indikatorda son ko'rsatish",
 ["74HC595 uch pin bilan 8 chiqish beradi: DS (ma'lumot), SHCP (takt), STCP (chiqishga o'tkazish).",
  "shiftOut(dataPin, clockPin, MSBFIRST, qiymat) bitta baytni yuboradi, keyin STCP ga impuls beriladi.",
  "Raqamlar segment kodlari massivida saqlanadi: har raqam uchun bitta bayt.",
  "Ikki razryad uchun dinamik indikatsiya: razryadlar navbat bilan, 50 Hz dan tez almashtiriladi — ko'z buni sezmaydi."],
 "Dinamik indikatsiyani sekin almashtirib ko'rsating, keyin tezlashtiring. Ko'z inersiyasi tushunchasi shunda yaqqol ochiladi.",
 [("74HC595 uchun nechta pin kerak?", "Uchta."),
  ("Dinamik indikatsiyada almashish chastotasi qancha bo'lishi kerak?", "50 Hz dan yuqori.")],
 "STCP ga impuls berishni unutish — chiqishlar yangilanmaydi."),

"IR pult bilan boshqarish": T(
 "Pult tugmalarini tanib, bir necha qurilmani boshqaruvchi tizim yozish",
 ["IRremote kutubxonasi. Avval har tugmaning kodi Serial monitorda o'qib olinadi va jadval tuziladi.",
  "Kodlar pultga bog'liq — har pultda o'ziga xos.",
  "switch...case bilan tugma kodlariga qarab turli amallar bajariladi — bu else if zanjiridan tushunarliroq.",
  "Ba'zi pultlar tugma bosib turilganda takrorlash kodi (0xFFFFFFFF) yuboradi. Uni alohida qayta ishlash kerak."],
 "Takrorlash kodini oldindan aytib qo'ying — u kutilmagan xatti-harakatga sabab bo'ladi va o'quvchilar sababini topa olmaydi.",
 [("Pult kodlari universalmi?", "Yo'q, har pultda o'ziga xos."),
  ("Tugma bosib turilganda nima yuboriladi?", "Takrorlash kodi.")],
 "Takrorlash kodini hisobga olmaslik — buyruq bir necha marta bajariladi."),

"RFID RC522: identifikatsiya": T(
 "RC522 bilan kartalarni o'qib, ruxsat berilgan kartalar ro'yxatini tuzish",
 ["RC522 radio to'lqin orqali kartaning UID (noyob raqam) ini o'qiydi. SPI protokoli bilan ulanadi.",
  "MUHIM: RC522 faqat 3.3V bilan ishlaydi. 5V ga ulash modulni butunlay ishdan chiqaradi.",
  "Kutubxona: MFRC522. Avval kartalarning UID lari o'qib olinadi va kodga ro'yxat sifatida yoziladi.",
  "Xavfsizlik cheklovi: UID nusxalanishi mumkin, shuning uchun bu jiddiy xavfsizlik tizimi emas. Haqiqiy tizimlarda kartadagi shifrlangan ma'lumot ishlatiladi."],
 "3.3V cheklovini qizil bilan yozib qo'ying — bu darsda eng ko'p modul kuyadigan xato. Ulashni har juftlikda o'zingiz tekshiring.",
 [("RC522 qanday kuchlanishda ishlaydi?", "Faqat 3.3 V."),
  ("UID nusxalanishi mumkinmi?", "Ha, shuning uchun bu jiddiy xavfsizlik yechimi emas.")],
 "RC522 ni 5V ga ulash — modul darhol ishdan chiqadi."),

"Loyihani hujjatlashtirish": T(
 "Chorak loyihasi uchun to'liq texnik hujjat tayyorlash",
 ["Hujjat tarkibi: qisqacha tavsif, blok-sxema, printsipial sxema, komponentlar ro'yxati (BOM), izohli kod, foydalanish qo'llanmasi.",
  "BOM jadvali: nomi, nominali, soni, taxminiy narx. Bu bilan qurilmani boshqa odam takrorlay oladi.",
  "Kodda izoh NEGA shunday qilinganini tushuntirsin. Muhim qarorlarga alohida izoh yoziladi.",
  "Sinov natijalari ham hujjatning bir qismi: nima sinaldi, qanday natija chiqdi, qanday cheklovlar aniqlandi."],
 "Sinov natijalari bo'limini majburiy qiling. \"Ishladi\" degan javob yetarli emas — qanday sharoitda, qanday aniqlik bilan ishlagani yozilishi kerak.",
 [("BOM nima?", "Komponentlar ro'yxati jadvali."),
  ("Hujjatda sinov natijalari nima uchun kerak?", "Qurilmaning chegaralarini va ishonchliligini ko'rsatish uchun.")],
 "Faqat kod va sxemani hujjat deb hisoblash — sinov va cheklovlar tushib qoladi."),

# ==================================================== 3-CHORAK: ESP32 va WiFi
"ESP32 pinlari va 3.3V mantiq darajasi": T(
 "ESP32 pin xaritasini chizib, ishlatib bo'lmaydigan pinlarni belgilash",
 ["ESP32 — 240 MHz ikki yadroli, 520 KB SRAM, 4 MB flesh, WiFi va Bluetooth o'rnatilgan.",
  "MANTIQ DARAJASI 3.3 V. 5 V signalni to'g'ridan-to'g'ri kirishga berish pinni shikastlaydi.",
  "Ba'zi pinlar cheklangan: GPIO 6-11 ichki fleshga ulangan, ishlatilmaydi. GPIO 34-39 faqat kirish (chiqish bo'la olmaydi va ichki tortuvchi rezistori yo'q).",
  "GPIO 0, 2, 12, 15 yuklash (boot) jarayoniga ta'sir qiladi — ularga komponent ulansa plata yuklanmasligi mumkin."],
 "\"Xavfsiz pinlar\" ro'yxatini tuzib tarqating (masalan 4, 5, 13, 14, 16-19, 21-23, 25-27, 32, 33). Bu chorak davomida eng ko'p ishlatiladigan qog'oz bo'ladi.",
 [("ESP32 ning mantiq darajasi qancha?", "3.3 V."),
  ("Qaysi pinlar faqat kirish uchun?", "GPIO 34-39.")],
 "GPIO 34-39 ni chiqish sifatida ishlatishga urinish yoki 5V signalni to'g'ridan-to'g'ri ulash."),

"IDE'ga ESP32 platasini qo'shish": T(
 "Board Manager orqali ESP32 ni qo'shib, birinchi dasturni yuklash",
 ["File > Preferences > Additional Board Manager URLs ga ESP32 paketining manzili qo'shiladi.",
  "Keyin Tools > Board > Boards Manager da \"esp32\" qidirilib o'rnatiladi. Paket katta (~200 MB), internet kerak.",
  "Plata turi tanlanadi (odatda ESP32 Dev Module) va port belgilanadi.",
  "Ko'p ESP32 platalarida CP2102 yoki CH340 drayveri kerak. Port ko'rinmasa avval shu tekshiriladi."],
 "Paketni oldindan barcha kompyuterlarga o'rnatib qo'ying. 200 MB yuklash sinf internetida butun darsni yeb qo'yishi mumkin.",
 [("ESP32 ni IDE ga qanday qo'shiladi?", "Board Manager URL qo'shib, keyin Boards Manager orqali o'rnatib."),
  ("Port ko'rinmasa nima tekshiriladi?", "Drayver (CP2102 yoki CH340) va kabel.")],
 "Paketni dars vaqtida yuklashga urinish — internet yetmaydi."),

"Birinchi dastur va Serial aloqa": T(
 "ESP32 da Blink va Serial dasturini ishga tushirib, Arduino bilan farqni ko'rish",
 ["ESP32 da o'rnatilgan LED odatda GPIO2 da (plata turiga bog'liq).",
  "Serial tezligi odatda 115200 — Arduino'dagi 9600 dan tezroq. Monitor oynasida ham shu tezlik tanlanadi.",
  "Yuklashda ba'zi platalarda BOOT tugmasini bosib turish kerak. \"Connecting...\" yozuvi uzoq tursa shu bajariladi.",
  "Yuklashdan keyin plata avtomatik qayta yuklanadi va dastur ishga tushadi."],
 "BOOT tugmasi masalasini oldindan ayting — bu ESP32 bilan ishlashda eng ko'p uchraydigan birinchi to'siq.",
 [("ESP32 da odatiy Serial tezligi qancha?", "115200."),
  ("Yuklash boshlanmasa nima qilinadi?", "BOOT tugmasi bosib turiladi.")],
 "Serial monitorda 9600 qoldirib, ekranda tushunarsiz belgilarni ko'rish."),

"3.3V va 5V mos kelmasligi: nima qilish kerak": T(
 "5V sensorni ESP32 ga kuchlanish bo'luvchi orqali xavfsiz ulash",
 ["ESP32 kirishiga maksimal 3.3 V berilishi mumkin. 5 V signal pinni sekin-asta yoki darhol ishdan chiqaradi.",
  "Yechim 1 — kuchlanish bo'luvchi: 1 kOm va 2 kOm rezistorlar. 5 V x 2/3 = 3,3 V. Faqat sekin signallar uchun mos.",
  "Yechim 2 — daraja o'tkazgich moduli (level shifter). Tez signallar va ikki tomonlama aloqa uchun kerak.",
  "Teskari yo'nalish (ESP32 dan 5 V qurilmaga) odatda muammosiz: ko'p 5 V kirishlar 3,3 V ni HIGH deb qabul qiladi."],
 "HC-SR04 ning ECHO pini aynan shu muammoning klassik misoli. Uni namunali holat sifatida ko'rsating va bo'luvchini birgalikda hisoblang.",
 [("ESP32 kirishiga maksimal qancha berilishi mumkin?", "3.3 V."),
  ("5 V dan 3,3 V olish uchun qanday rezistorlar olinadi?", "Masalan 1 kOm va 2 kOm bo'luvchi.")],
 "5V sensorni to'g'ridan-to'g'ri ESP32 ga ulash."),

"ESP32'da raqamli kirish va chiqish": T(
 "ESP32 da LED va tugma bilan ishlab, Arduino'dan farqlarni aniqlash",
 ["pinMode, digitalWrite, digitalRead buyruqlari Arduino bilan bir xil ishlaydi.",
  "Farq: chiqish kuchlanishi 3.3 V. LED uchun rezistor kichikroq bo'ladi: (3,3-2)/0,015 = 87 Om, ya'ni 100 Om.",
  "Ko'k va oq LED (3,2 V) 3.3 V da juda xira yonadi — bu normal, kuchlanish deyarli yetmaydi.",
  "Pin toki: xavfsiz 12 mA, mutlaq chegara 40 mA. Arduino'dagidan kamroq — buni hisobga olish kerak."],
 "3.3 V da ko'k LED muammosini ko'rsating. Bu 7-sinfdagi tushish kuchlanishi mavzusining amaliy oqibati va bog'lanishni ko'rsatadi.",
 [("ESP32 chiqishi qancha kuchlanish beradi?", "3.3 V."),
  ("ESP32 pinidan xavfsiz qancha tok olinadi?", "Taxminan 12 mA.")],
 "Arduino uchun hisoblangan rezistorlarni ESP32 da o'zgartirmasdan ishlatish."),

"ESP32'da analog o'qish (ADC)": T(
 "ESP32 ADC ni potensiometr bilan sinab, chiziqsizligini o'lchash",
 ["ESP32 ADC 12 razryadli: 0-4095 oralig'ida qiymat qaytaradi (Arduino'da 0-1023).",
  "Kirish diapazoni 0-3.3 V. Standart sozlamada esa aniq o'lchash 0,15-2,45 V oralig'ida ishonchli.",
  "MUHIM kamchilik: ESP32 ning ADC si CHIZIQSIZ, ayniqsa chekka qiymatlarda. Aniq o'lchov uchun kalibrlash kerak.",
  "ADC2 kanallari (GPIO 0, 2, 4, 12-15, 25-27) WiFi yoqilganda ISHLAMAYDI. WiFi bilan birga faqat ADC1 (GPIO 32-39) ishlatiladi."],
 "ADC2 va WiFi to'qnashuvi — bu chorakning eng ko'p vaqt yeydigan sirli nosozligi. Uni oldindan aytib, xavfsiz pinlar ro'yxatiga yozib qo'ying.",
 [("ESP32 ADC qanday oraliq beradi?", "0 dan 4095 gacha."),
  ("WiFi yoqilganda qaysi ADC kanallari ishlamaydi?", "ADC2 kanallari.")],
 "WiFi bilan birga ADC2 pinini ishlatish — qiymat doim 0 yoki tasodifiy chiqadi."),

"PWM (LEDC) va yorqinlik boshqaruvi": T(
 "LEDC kanallari bilan bir necha LEDning yorqinligini mustaqil boshqarish",
 ["ESP32 da analogWrite yo'q (eski versiyalarda). O'rniga LEDC tizimi ishlatiladi.",
  "Sozlash: ledcSetup(kanal, chastota, razryad); ledcAttachPin(pin, kanal); ledcWrite(kanal, qiymat);",
  "16 ta mustaqil kanal bor va har biriga o'z chastotasi va razryadi berilishi mumkin.",
  "Razryad 8 bo'lsa qiymat 0-255, 10 bo'lsa 0-1023, 12 bo'lsa 0-4095. Yuqori razryad silliqroq boshqaruv beradi."],
 "Arduino'ning yagona 8 razryadli PWM va ESP32 ning sozlanadigan tizimi farqini ko'rsating — bu platformalar orasidagi bosqichni yaxshi ifodalaydi.",
 [("ESP32 da nechta PWM kanali bor?", "16 ta."),
  ("10 razryadli PWM da qiymat oralig'i qanday?", "0 dan 1023 gacha.")],
 "Bir kanalni bir necha pinga bog'lab, ularni mustaqil boshqarmoqchi bo'lish."),

"Sensorlarni ESP32'ga ulash": T(
 "3.3V va 5V sensorlarni to'g'ri usulda ulab, o'qish natijalarini solishtirish",
 ["3.3 V sensorlar (DHT22, BMP280, MPU6050) to'g'ridan-to'g'ri ulanadi.",
  "5 V sensorlar uchun: chiqish signaliga bo'luvchi yoki daraja o'tkazgich kerak.",
  "Quvvat: ko'p sensorlar 3.3 V dan ham ishlaydi. Datasheetda ish kuchlanishi diapazoni tekshiriladi.",
  "Analog sensorlarda diapazon farqi: 5 V bo'luvchining chiqishi 3.3 V dan oshmasligi uchun rezistorlar qayta hisoblanadi."],
 "Har sensorni ulashdan oldin datasheetdagi kuchlanish diapazonini tekshirish odatini o'rnating. Bu chorak davomida bir necha modulni saqlab qoladi.",
 [("5V sensor chiqishi qanday ulanadi?", "Bo'luvchi yoki daraja o'tkazgich orqali."),
  ("Sensorni ulashdan oldin nima tekshiriladi?", "Datasheetdagi ish kuchlanishi diapazoni.")],
 "Arduino sxemasini o'zgartirmasdan ESP32 ga ko'chirish."),

"OLED ekranni I2C orqali ulash": T(
 "SSD1306 OLED ni ulab, birinchi matnni chiqarish",
 ["SSD1306 OLED I2C bilan ulanadi: VCC (3.3V), GND, SDA (GPIO21), SCL (GPIO22).",
  "Kutubxona: Adafruit SSD1306 va Adafruit GFX. Manzil odatda 0x3C.",
  "O'lcham 128x64 yoki 128x32 piksel. Kodda to'g'ri o'lcham ko'rsatilishi kerak.",
  "MUHIM: har o'zgarishdan keyin display.display() chaqirilishi shart — usiz ekran yangilanmaydi. Bu eng ko'p uchraydigan xato."],
 "display.display() ni unutish muammosini oldindan aytib qo'ying. Kod to'g'ri, ekran bo'sh — sababi topilmaydi va ko'p vaqt ketadi.",
 [("OLED ekran yangilanishi uchun nima chaqiriladi?", "display.display()."),
  ("SSD1306 ning odatiy I2C manzili qanday?", "0x3C.")],
 "display.display() ni unutish."),

"OLED'da matn va raqam chiqarish": T(
 "Turli o'lcham va joylashuvdagi matn bilan ma'lumot paneli yasash",
 ["setTextSize(1-3) — matn o'lchami. 1-o'lchamda 21x8 belgi, 2-o'lchamda 10x4 sig'adi.",
  "setCursor(x, y) — piksel koordinatalari (LCD dagi kabi belgi emas). setTextColor(SSD1306_WHITE).",
  "Ekranni yangilash tartibi: clearDisplay(), keyin chizish, oxirida display().",
  "Yangilash tezligi cheklangan (I2C da ~20-30 kadr/sekund). Har loop siklida yangilash keraksiz — 200-500 ms yetarli."],
 "Piksel koordinatalari va belgi koordinatalari farqini ta'kidlang — LCD dan kelgan o'quvchilar buni chalkashtiradi.",
 [("setCursor qanday koordinata oladi?", "Piksel koordinatalarini."),
  ("Ekran yangilash tartibi qanday?", "clearDisplay, chizish, display.")],
 "Har loop siklida ekranni to'liq yangilash — dastur sekinlashadi."),

"OLED'da grafik va chizma": T(
 "Sensor qiymatlarining real vaqtli grafigini OLED ekranda chizish",
 ["GFX kutubxonasi chizish funksiyalarini beradi: drawPixel, drawLine, drawRect, fillRect, drawCircle.",
  "Grafik chizish uchun oxirgi N ta qiymat massivda saqlanadi va har yangilanishda qayta chiziladi.",
  "Qiymatlarni ekran balandligiga moslash: y = map(qiymat, min, maks, 63, 0). Ekranda y noldan boshlanadi — shuning uchun teskari moslash.",
  "Aylanma bufer ishlatiladi: yangi qiymat eng eskisining o'rniga yoziladi va indeks aylanadi."],
 "Y o'qining teskari ekanini (yuqorida 0) alohida ayting — bu barcha ekran grafikasida uchraydigan va ko'p chalkashtiradigan detal.",
 [("Ekranda y = 0 qayerda?", "Yuqorida."),
  ("Grafik uchun qiymatlar qayerda saqlanadi?", "Aylanma buferli massivda.")],
 "Y o'qini teskari moslashni unutish — grafik ag'darilib chiqadi."),

"WiFi tarmog'iga ulanish": T(
 "ESP32 ni WiFi ga ulab, IP manzilni Serial monitorda ko'rish",
 ["#include <WiFi.h>, keyin WiFi.begin(ssid, parol). Ulanishni kutish: while (WiFi.status() != WL_CONNECTED).",
  "Ulanish 2-10 sekund davom etadi. Kutish siklida nuqta chiqarib borish foydali — jarayon ko'rinib turadi.",
  "IP manzil: WiFi.localIP(). Bu manzil orqali brauzerdan qurilmaga murojaat qilinadi.",
  "MUHIM: ESP32 faqat 2.4 GHz tarmoqni qo'llab-quvvatlaydi. 5 GHz tarmoqqa ulanmaydi — bu ko'p uchraydigan muammo."],
 "Sinf routerining 2.4 GHz tarmog'i borligini oldindan tekshiring. 5 GHz muammosi butun darsni to'xtatib qo'yishi mumkin.",
 [("ESP32 qaysi WiFi diapazonini qo'llab-quvvatlaydi?", "Faqat 2.4 GHz."),
  ("IP manzil qanday olinadi?", "WiFi.localIP() bilan.")],
 "5 GHz tarmoqqa ulanmoqchi bo'lish."),

"IP manzil va tarmoq asoslari": T(
 "Tarmoqdagi qurilmalarning IP manzillarini aniqlab, tarmoq xaritasini chizish",
 ["IP manzil — tarmoqdagi qurilmaning manzili. Mahalliy tarmoqda odatda 192.168.x.x ko'rinishida.",
  "Router har qurilmaga DHCP orqali manzil beradi. Manzil qayta yoqilganda o'zgarishi mumkin.",
  "Statik IP belgilash mumkin: WiFi.config(ip, gateway, subnet) — bunda manzil doim bir xil qoladi.",
  "Port — bitta qurilmadagi turli xizmatlar uchun raqam. Veb-server odatda 80-portda ishlaydi."],
 "Statik IP ni loyihalarda tavsiya qiling — o'zgarib turadigan manzil qurilmaga har safar qaytadan murojaat qilishni talab qiladi va bu noqulay.",
 [("Mahalliy tarmoqda IP odatda qanday ko'rinishda bo'ladi?", "192.168.x.x."),
  ("Veb-server odatda qaysi portda ishlaydi?", "80-portda.")],
 "IP o'zgarganini bilmay, eski manzilga murojaat qilishda davom etish."),

"Veb-server yaratish": T(
 "ESP32 da oddiy veb-server ishga tushirib, brauzerdan ochish",
 ["WiFiServer server(80); setup ichida server.begin();",
  "loop ichida: WiFiClient client = server.available(); agar mijoz bo'lsa, so'rovni o'qib javob yuborish.",
  "HTTP javobi ma'lum tuzilishda: HTTP/1.1 200 OK, Content-type: text/html, bo'sh qator, keyin HTML.",
  "Bo'sh qator MAJBURIY — u sarlavhalar tugaganini bildiradi. Usiz brauzer sahifani ko'rsatmaydi."],
 "Bo'sh qator qoidasini alohida ta'kidlang. Bu ko'rinmaydigan detal va uni unutish sahifa ochilmasligining eng ko'p sababi.",
 [("HTTP javobida sarlavhalardan keyin nima kerak?", "Bo'sh qator."),
  ("Veb-server qaysi portda ochiladi?", "Odatda 80-portda.")],
 "Bo'sh qatorni unutish — brauzer sahifani ko'rsatmaydi."),

"Brauzerdan LED yoqish va o'chirish": T(
 "Veb-sahifadagi tugmalar orqali LEDni boshqarish",
 ["Brauzer so'rovi matn sifatida keladi: GET /LEDON HTTP/1.1. Undagi yo'lni tekshirib, amal bajariladi.",
  "Tekshirish: if (sorov.indexOf(\"GET /LEDON\") >= 0) { digitalWrite(LED, HIGH); }",
  "Sahifada tugmalar oddiy havolalar bo'lishi mumkin: <a href=\"/LEDON\"><button>Yoqish</button></a>",
  "Har bosishda sahifa qayta yuklanadi — bu oddiy, lekin qo'pol usul. Silliqroq yechim keyingi darsda (AJAX)."],
 "Sahifaning qayta yuklanishi muammosini his qildiring — keyingi darsdagi AJAX yechimi shunda mantiqiy davom bo'lib ko'rinadi.",
 [("Brauzer so'rovi qanday keladi?", "Matn sifatida, GET /yo'l ko'rinishida."),
  ("Havolali tugmaning kamchiligi nima?", "Har bosishda sahifa qayta yuklanadi.")],
 "So'rovni to'liq o'qimasdan javob yuborish — brauzer xato ko'rsatadi."),

"HTML sahifani platadan yuborish": T(
 "To'liq HTML sahifani (stil bilan) ESP32 dan yuborish",
 ["HTML sahifa qatorlar ketma-ketligi sifatida client.println() bilan yuboriladi.",
  "Uzun HTML ni kodda saqlash uchun R\"rawliteral(...)rawliteral\" konstruksiyasi qulay — unda qo'shtirnoq va yangi qatorlar to'g'ridan-to'g'ri yoziladi.",
  "Sahifada meta viewport bo'lishi kerak, aks holda telefonda juda kichik ko'rinadi.",
  "Xotira cheklovi: juda katta sahifa ESP32 xotirasini to'ldiradi. Katta sahifalar SPIFFS fayl tizimida saqlanadi."],
 "rawliteral usulini ko'rsating — usiz har qo'shtirnoqni ekranlash kerak bo'ladi va kod o'qib bo'lmas holga keladi.",
 [("Telefonda to'g'ri ko'rinishi uchun nima kerak?", "meta viewport tegi."),
  ("Katta sahifalar qayerda saqlanadi?", "SPIFFS fayl tizimida.")],
 "Har qo'shtirnoqni qo'lda ekranlashga urinish — kod tushunarsiz bo'ladi."),

"Sensor qiymatini veb-sahifada ko'rsatish": T(
 "Sensor ma'lumotini veb-sahifada avtomatik yangilanadigan qilib ko'rsatish",
 ["Eng oddiy usul — sahifaga meta refresh qo'yish: har N sekundda sahifa o'zi qayta yuklanadi.",
  "Kamchiligi: butun sahifa qayta yuklanadi, miltillaydi va ortiqcha trafik sarflanadi.",
  "Yaxshiroq usul — AJAX: JavaScript faqat qiymatni so'raydi va sahifaning bir qismini yangilaydi.",
  "Buning uchun ESP32 da ikkinchi manzil (masalan /qiymat) bo'lishi kerak — u faqat raqamni qaytaradi."],
 "Ikki usulni ketma-ket sinatib ko'ring. AJAX ning afzalligi (miltillamaslik) darhol ko'rinadi va JavaScript ga qiziqish uyg'otadi.",
 [("meta refresh ning kamchiligi nima?", "Butun sahifa qayta yuklanadi va miltillaydi."),
  ("AJAX nima qiladi?", "Faqat kerakli qiymatni so'rab, sahifaning bir qismini yangilaydi.")],
 "Har sekundda butun sahifani qayta yuklash — tarmoq va xotira behuda sarflanadi."),

"WiFi xatolarini topish va tuzatish": T(
 "Turli WiFi nosozliklarini modellashtirib, tuzatish tartibini ishlab chiqish",
 ["Eng ko'p uchraydigan sabablar: 5 GHz tarmoq, parol xato, signal kuchsiz, router mijozlar sonini cheklagan.",
  "WiFi.status() turli kodlar qaytaradi: WL_NO_SSID_AVAIL (tarmoq topilmadi), WL_CONNECT_FAILED (parol xato), WL_DISCONNECTED.",
  "Signal kuchi: WiFi.RSSI() — -50 dBm yaxshi, -70 dBm chegara, -80 dBm dan past ishonchsiz.",
  "Avtomatik qayta ulanish kerak: aloqa uzilsa dastur o'zi qayta urinishi lozim, aks holda qurilma \"o'lik\" qoladi."],
 "Avtomatik qayta ulanishni har WiFi loyihasida majburiy qiling. Uzoq ishlaydigan qurilmalarda aloqa albatta uziladi va tiklanish bo'lishi shart.",
 [("RSSI -80 dBm nimani bildiradi?", "Signal juda kuchsiz, aloqa ishonchsiz."),
  ("Aloqa uzilsa dastur nima qilishi kerak?", "Avtomatik qayta ulanishga urinishi.")],
 "Qayta ulanish mantiqini yozmaslik — qurilma bir marta uzilgach boshqa ishlamaydi."),

# ==================================================== 4-CHORAK: IoT — internetga ulangan qurilma
"Ma'lumotni saqlash: microSD kart moduli": T(
 "SD kartga fayl yozib, uni kompyuterda ochib tekshirish",
 ["SD kart moduli SPI bilan ulanadi: MOSI, MISO, SCK va CS pinlari.",
  "Kutubxona: SD.h. Ishga tushirish SD.begin(CS_PIN) bilan, muvaffaqiyatni tekshirish shart.",
  "Fayl ochish: File f = SD.open(\"/log.txt\", FILE_APPEND); yozish f.println(...); YOPISH f.close() — MAJBURIY.",
  "Fayl yopilmasa ma'lumot kartaga yozilmaydi va quvvat uzilganda yo'qoladi."],
 "close() ni unutish muammosini alohida ta'kidlang: dastur ishlagandek ko'rinadi, lekin kartada hech narsa bo'lmaydi.",
 [("SD kart qaysi protokol bilan ulanadi?", "SPI."),
  ("Yozgandan keyin nima qilish shart?", "Faylni close() bilan yopish.")],
 "Faylni yopmaslik — ma'lumot yozilmaydi."),

"Data logging: qiymatlarni vaqt bilan yozish": T(
 "Sensor qiymatlarini vaqt belgisi bilan CSV faylga yozib borish",
 ["CSV formati — vergul bilan ajratilgan qiymatlar. Excel va Google Sheets uni to'g'ridan-to'g'ri ochadi.",
  "Har qator: vaqt, qiymat1, qiymat2. Birinchi qatorga sarlavha yoziladi.",
  "Yozish chastotasi vazifaga qarab tanlanadi: harorat uchun daqiqada bir marta yetadi, tebranish uchun sekundiga o'nlab marta kerak.",
  "Fayl hajmini hisoblash: har qator ~30 bayt, daqiqada 1 qator = kuniga 43 KB. Bir yilda ~16 MB."],
 "Fayl hajmini oldindan hisoblash odatini o'rgating. Bu ma'lumot to'plash tizimlarini loyihalashning muhim qismi.",
 [("CSV nima?", "Vergul bilan ajratilgan qiymatlar formati."),
  ("Yozish chastotasi nimaga qarab tanlanadi?", "O'lchanayotgan hodisaning o'zgarish tezligiga.")],
 "Juda tez-tez yozish — kart tez to'ladi va ma'lumot tahlil qilib bo'lmas darajada ko'payadi."),

"RTC DS3231: real vaqt soati": T(
 "DS3231 ni sozlab, aniq vaqt bilan yozuv olib borish",
 ["DS3231 — quvvat o'chsa ham vaqtni saqlaydigan aniq soat. Ichida termokompensatsiyalangan kvars bor.",
  "I2C bilan ulanadi, manzil 0x68. Batareya (CR2032) quvvat o'chganda vaqtni saqlaydi.",
  "Aniqligi juda yuqori: yiliga ±2 daqiqa chetlanish (oddiy RTC da bu bir necha soat bo'ladi).",
  "Vaqtni sozlash bir marta bajariladi. Sozlash kodi keyin izohga olinishi kerak — aks holda har yuklashda vaqt qayta o'rnatiladi."],
 "Sozlash kodini izohga olishni albatta ayting. Aks holda har dasturni yuklaganda vaqt kompilyatsiya paytiga qaytadi va o'quvchilar sababini topa olmaydi.",
 [("DS3231 ning aniqligi qanday?", "Yiliga ±2 daqiqa atrofida."),
  ("Sozlashdan keyin kod bilan nima qilinadi?", "Izohga olinadi.")],
 "Sozlash kodini qoldirib, vaqtning har yuklashda qayta o'rnatilishiga yo'l qo'yish."),

"Vaqt bo'yicha avtomatlashtirish": T(
 "Belgilangan vaqtda ishga tushadigan sug'orish yoki yoritish tizimi yozish",
 ["Vaqt bo'yicha vazifa: joriy soat va daqiqa tekshirilib, kerakli vaqtga to'g'ri kelsa amal bajariladi.",
  "Muammo: shart bir daqiqa davomida rost bo'lib turadi va amal ko'p marta bajariladi. Yechim — bayroq (flag) o'zgaruvchisi.",
  "Bayroq: amal bajarilgach true qilinadi, vaqt o'tgach false ga qaytariladi.",
  "Alternativa — millis() bilan interval: har N daqiqada bir marta bajarish. Bu aniq vaqt kerak bo'lmaganda soddaroq."],
 "Bayroq muammosini amalda ko'rsating: bayroqsiz kod nasosni bir daqiqa davomida yuzlab marta yoqadi. Bu klassik xato.",
 [("Nega bayroq o'zgaruvchisi kerak?", "Amal bir marta bajarilishi uchun."),
  ("Aniq vaqt kerak bo'lmasa qanday usul soddaroq?", "millis() bilan interval.")],
 "Bayroqsiz vaqt sharti yozish — amal ko'p marta takrorlanadi."),

"HTTP so'rov yuborish": T(
 "ESP32 dan tashqi serverga HTTP so'rov yuborib, javobni o'qish",
 ["HTTPClient kutubxonasi: http.begin(url); int kod = http.GET(); String javob = http.getString(); http.end();",
  "Javob kodi natijani bildiradi: 200 — muvaffaqiyat, 404 — topilmadi, 500 — server xatosi, manfiy — ulanish xatosi.",
  "http.end() ni chaqirish majburiy — aks holda xotira asta-sekin to'ladi va qurilma bir necha soatdan keyin qotib qoladi.",
  "HTTPS uchun WiFiClientSecure kerak. Oddiy holatda sertifikat tekshiruvini o'chirib qo'yish mumkin (setInsecure), lekin bu xavfsiz emas."],
 "Xotira sizib ketishi (memory leak) tushunchasini shu yerda kiriting: http.end() ni unutish qurilmani bir necha soatdan keyin ishdan chiqaradi.",
 [("HTTP javob kodi 200 nimani bildiradi?", "So'rov muvaffaqiyatli bajarilgan."),
  ("http.end() nima uchun kerak?", "Xotirani bo'shatish uchun.")],
 "http.end() ni unutish — qurilma bir necha soatdan keyin qotib qoladi."),

"Bulut xizmatiga ma'lumot yuborish": T(
 "ThingSpeak yoki shunga o'xshash xizmatga sensor ma'lumotini yuborish",
 ["Bulut xizmatida hisob ochiladi, kanal yaratiladi va API kalit olinadi.",
  "Yuborish oddiy HTTP GET so'rovi orqali: api.thingspeak.com/update?api_key=KALIT&field1=QIYMAT.",
  "Cheklovlar bor: bepul rejada odatda 15 sekundda bir marta yuborish mumkin. Tez-tez yuborilsa so'rov rad etiladi.",
  "API kalit — parol kabi maxfiy ma'lumot. Uni ochiq joyga (masalan GitHub'ga) qo'yish mumkin emas."],
 "API kalitning maxfiyligini alohida ta'kidlang — bu raqamli xavfsizlik madaniyatining amaliy darsi.",
 [("API kalit nima?", "Xizmatga murojaat qilish uchun maxfiy kalit."),
  ("Bepul rejada odatda qanday cheklov bo'ladi?", "Yuborish chastotasi cheklanadi, masalan 15 sekundda bir marta.")],
 "API kalitni ochiq joyda saqlash yoki juda tez-tez so'rov yuborish."),

"Bulutda grafik ko'rish va tahlil qilish": T(
 "To'plangan ma'lumotni bulutda grafik ko'rinishida tahlil qilish",
 ["Bulut xizmatlari ma'lumotni avtomatik grafikka aylantiradi va vaqt bo'yicha ko'rsatadi.",
  "Grafikdan ko'rinadigan narsalar: kunlik sikl (harorat kunduzi yuqori), anomaliyalar, sensor nosozligi (to'satdan tekis chiziq).",
  "Ma'lumotni yuklab olish (CSV) va Excel yoki Google Sheets da chuqurroq tahlil qilish mumkin.",
  "Tahlil savollari: o'rtacha qancha? Maksimal va minimal qachon? Qanday qonuniyat ko'rinadi?"],
 "Bir necha kunlik ma'lumot to'plab, uni birgalikda tahlil qiling. Haqiqiy ma'lumotdagi kunlik siklni ko'rish o'quvchilarga kuchli taassurot qoldiradi.",
 [("Grafikda to'satdan tekis chiziq nimani bildirishi mumkin?", "Sensor nosozligini yoki uzilganini."),
  ("Ma'lumotni chuqurroq tahlil qilish uchun nima qilinadi?", "CSV qilib yuklab olib, jadval dasturida ishlash.")],
 "Ma'lumotni faqat to'plab, tahlil qilmaslik."),

"Telegram bot bilan tanishuv": T(
 "BotFather orqali bot yaratib, token olish va birinchi xabarni yuborish",
 ["Telegram'da @BotFather ga /newbot buyrug'i yuboriladi, nom va foydalanuvchi nomi tanlanadi.",
  "Natijada TOKEN beriladi — bu botni boshqarish uchun parol. Uni hech kimga bermaslik kerak.",
  "Kutubxona: UniversalTelegramBot. Ishlash uchun WiFiClientSecure va Telegram sertifikati kerak.",
  "Chat ID ham kerak — bu botning kimga xabar yuborishini belgilaydi. Uni @userinfobot orqali bilib olish mumkin."],
 "Token maxfiyligini yana ta'kidlang. Token o'g'irlansa botni boshqa odam to'liq boshqara oladi.",
 [("Bot yaratish uchun kimga murojaat qilinadi?", "@BotFather ga."),
  ("Token nima?", "Botni boshqarish uchun maxfiy kalit.")],
 "Tokenni ochiq kodda qoldirish yoki boshqalarga ko'rsatish."),

"Telegram orqali xabar yuborish": T(
 "Sensor chegaradan oshganda Telegram'ga ogohlantirish yuborish",
 ["Xabar yuborish: bot.sendMessage(chat_id, matn, \"\").",
  "Ogohlantirish mantiqida bayroq kerak: xabar bir marta yuborilsin, har sekundda emas.",
  "Bayroq holat o'zgarganda qayta tiklanadi: qiymat normal holatga qaytgach, keyingi oshishda yana xabar yuboriladi.",
  "Xabar mazmuni foydali bo'lishi kerak: nima, qachon, qanday qiymat. \"Ogohlantirish!\" degan xabar hech narsa bermaydi."],
 "Xabar mazmuni haqidagi talabni qo'ying — foydali xabar yozish ko'nikmasi texnik yozuv madaniyatining bir qismi.",
 [("Nega bayroq kerak?", "Xabar bir marta yuborilishi uchun."),
  ("Xabarda nima bo'lishi kerak?", "Nima bo'lgani, qachon va qanday qiymat.")],
 "Bayroqsiz ogohlantirish — bot yuzlab xabar yuborib, spam qiladi."),

"Telegram orqali qurilmani boshqarish": T(
 "Telegram buyruqlari bilan qurilmani boshqaradigan tizim yozish",
 ["Bot kelgan xabarlarni davriy so'raydi: bot.getUpdates(). Odatda 1 sekundda bir marta.",
  "Buyruqlar / bilan boshlanadi: /yoq, /ochir, /holat. Ular matn sifatida kelib, tekshiriladi.",
  "Xavfsizlik: faqat ruxsat berilgan chat ID lardan kelgan buyruqlar bajarilishi kerak. Aks holda botni topgan istalgan odam qurilmani boshqara oladi.",
  "Klaviatura (keyboard) qo'shish mumkin — bu foydalanuvchiga tugmalar ko'rsatadi va buyruqni qo'lda yozish kerak bo'lmaydi."],
 "Chat ID tekshiruvini MAJBURIY qiling. Bu xavfsizlik tushunchasining eng aniq va amaliy misoli.",
 [("Nega chat ID tekshiriladi?", "Faqat ruxsat berilgan odam qurilmani boshqarishi uchun."),
  ("Buyruqlar qanday belgilanadi?", "/ belgisi bilan boshlanadi.")],
 "Chat ID ni tekshirmaslik — istalgan odam qurilmani boshqara oladi."),

"MQTT protokoli haqida tushuncha": T(
 "MQTT broker orqali ikki qurilma o'rtasida xabar almashish",
 ["MQTT — IoT uchun yengil xabar protokoli. Uch element: broker (markaz), publisher (yuboruvchi), subscriber (obunachi).",
  "Xabarlar MAVZU (topic) bo'yicha tashkil qilinadi: uy/oshxona/harorat. Mavzular daraxt ko'rinishida bo'ladi.",
  "Qurilma mavzuga xabar yuboradi (publish) yoki mavzuga obuna bo'ladi (subscribe). Ular bir-birini bilmaydi — broker vositachi.",
  "HTTP dan afzalligi: kam trafik, tez javob, ikki tomonlama aloqa. Shuning uchun IoT da keng ishlatiladi."],
 "\"Qurilmalar bir-birini bilmaydi\" g'oyasini ta'kidlang — bu tizim arxitekturasining muhim tamoyili va kengaytirish imkonini beradi.",
 [("MQTT ning uch elementi qaysi?", "Broker, publisher, subscriber."),
  ("Xabarlar nima bo'yicha tashkil qilinadi?", "Mavzu (topic) bo'yicha.")],
 "Mavzu nomlarini tartibsiz tanlash — tizim kengayganda boshqarib bo'lmas holga keladi."),

"Ikki ESP32 o'rtasida aloqa": T(
 "Ikki ESP32 ni MQTT yoki ESP-NOW orqali bog'lab, ma'lumot almashish",
 ["Uch usul bor: MQTT (broker orqali), to'g'ridan-to'g'ri HTTP (biri server, ikkinchisi mijoz) va ESP-NOW.",
  "ESP-NOW — Espressif'ning o'z protokoli: routersiz, to'g'ridan-to'g'ri, juda tez (millisekundlar) va kam quvvat sarflaydi.",
  "ESP-NOW uchun qurilmaning MAC manzili kerak. Uni WiFi.macAddress() bilan bilib olinadi.",
  "Tanlov: internet kerak bo'lsa MQTT, faqat mahalliy va tez aloqa kerak bo'lsa ESP-NOW."],
 "ESP-NOW ni ko'rsating — routersiz ishlaydigan aloqa o'quvchilar uchun kutilmagan va juda qiziq bo'ladi.",
 [("ESP-NOW ning afzalligi nima?", "Routersiz, tez va kam quvvat sarflaydi."),
  ("ESP-NOW uchun nima kerak?", "Qabul qiluvchining MAC manzili.")],
 "MAC manzilni noto'g'ri kiritish — xabar yetib bormaydi va xato ham chiqmaydi."),

"Bluetooth (BLE) orqali boshqarish": T(
 "ESP32 ni BLE orqali telefonga ulab, ma'lumot almashish",
 ["BLE (Bluetooth Low Energy) — kam quvvat sarflaydigan simsiz aloqa. Klassik Bluetooth'dan farq qiladi.",
  "BLE tuzilmasi: Service (xizmat) ichida Characteristic (xususiyat). Har biriga UUID beriladi.",
  "Telefonda nRF Connect yoki shunga o'xshash ilova bilan sinash mumkin.",
  "Masofa 10-30 metr, tezlik past (kilobaytlar). Katta ma'lumot uzatish uchun mos emas, lekin sensor qiymatlari uchun ideal."],
 "BLE va WiFi ni solishtirib chiqing: qachon qaysi biri mos? Bu texnologiya tanlash bo'yicha muhandislik qarorining yaxshi misoli.",
 [("BLE ning asosiy afzalligi nima?", "Juda kam quvvat sarflaydi."),
  ("BLE da ma'lumot qanday tashkil qilinadi?", "Service ichida Characteristic.")],
 "BLE orqali katta hajmdagi ma'lumot uzatishga urinish — u buning uchun mo'ljallanmagan."),

"Quvvat tejash: deep sleep rejimi": T(
 "Deep sleep bilan qurilmaning tok iste'molini o'lchab, batareya muddatini hisoblash",
 ["Deep sleep da ESP32 deyarli hamma qismini o'chiradi: iste'mol 150 mA dan 10 mikroamperga tushadi.",
  "Uyg'onish taymer bilan: esp_sleep_enable_timer_wakeup(mikrosekund), keyin esp_deep_sleep_start().",
  "Uyg'ongandan keyin dastur BOSHIDAN boshlanadi (setup dan). Oddiy o'zgaruvchilar qiymati saqlanmaydi.",
  "Saqlash kerak bo'lsa RTC xotira ishlatiladi: RTC_DATA_ATTR int sanoq = 0;"],
 "Iste'molni multimetr bilan o'lchab, batareya muddatini hisoblang: 2000 mAh batareya 150 mA da 13 soat, deep sleep bilan esa oylab ishlaydi. Bu raqamlar juda ta'sirchan.",
 [("Deep sleep da iste'mol qancha bo'ladi?", "Taxminan 10 mikroamper."),
  ("Uyg'ongandan keyin dastur qayerdan boshlanadi?", "setup() dan.")],
 "Oddiy o'zgaruvchilarda qiymat saqlanishini kutish — RTC_DATA_ATTR kerak."),

"Batareyada mustaqil ishlaydigan qurilma": T(
 "Batareyali qurilma yig'ib, uning ish muddatini hisoblab, o'lchov bilan tekshirish",
 ["Batareya muddati: sig'im (mAh) / o'rtacha iste'mol (mA) = soat.",
  "O'rtacha iste'mol hisoblanadi: masalan har 10 daqiqada 5 sekund ishlasa (150 mA), qolgan vaqtda uxlasa (0,01 mA): o'rtacha = (150 x 5 + 0,01 x 595) / 600 = 1,26 mA.",
  "2000 mAh batareya bilan: 2000 / 1,26 = 1587 soat = 66 kun.",
  "Amalda kamroq chiqadi: batareyaning o'z-o'zidan razryadlanishi, harorat va stabilizatorning yo'qotishlari hisobga olinadi. Zaxira sifatida 30% kamaytiriladi."],
 "Hisobni real o'lchov bilan solishtirish uchun qurilmani bir hafta ishlatib ko'ring. Nazariya va amaliyot farqini ko'rish qimmatli tajriba.",
 [("2000 mAh va 2 mA iste'mol bilan qancha ishlaydi?", "1000 soat, ya'ni ~41 kun."),
  ("Nega amalda kamroq chiqadi?", "O'z-o'zidan razryadlanish, harorat va stabilizator yo'qotishlari.")],
 "Faqat ishlash paytidagi iste'molni hisoblash — o'rtacha iste'mol olinishi kerak."),

"Qurilma korpusi va yakuniy montaj": T(
 "Loyihani mustahkam korpusga joylashtirib, yakuniy montajni bajarish",
 ["Korpus talablari: himoya, xavfsizlik, foydalanish qulayligi, isishni chiqarish.",
  "Joylashtirish tartibi: boshqaruv elementlari va ekran joyi belgilanadi, keyin plata, oxirida simlar.",
  "Antenna joylashuvi WiFi qurilmalarida muhim: metall korpus signalni to'sadi. Plastik korpus yoki tashqi antenna kerak.",
  "Batareya va zaryadlash portiga qulay kirish qoldiriladi. Simlar tebranishdan uzilmasligi uchun mahkamlanadi."],
 "Metall korpus va WiFi masalasini ayting — bu kutilmagan va amalda ko'p uchraydigan muammo.",
 [("Metall korpus WiFi ga qanday ta'sir qiladi?", "Signalni to'sadi."),
  ("Simlar nima uchun mahkamlanadi?", "Tebranishdan uzilib qolmasligi uchun.")],
 "Antennani metall qismlar orasiga joylashtirish — aloqa masofasi keskin kamayadi."),

"Tizimni sinash va nosozliklarni yo'qotish": T(
 "Tizimni uzoq muddat va turli sharoitlarda sinab, nosozliklar ro'yxatini tuzish",
 ["Sinov turlari: funksional (hamma imkoniyat ishlaydimi), yuklamali (uzoq muddat), chegaraviy (eng yomon sharoit), tiklanish (uzilishdan keyin).",
  "Uzoq muddatli sinov IoT qurilmalarida majburiy: xotira sizishi va aloqa uzilishi faqat soatlar o'tgach ko'rinadi.",
  "Nosozliklar ro'yxati (bug list) yuritiladi: tavsif, takrorlash qadamlari, muhimlik darajasi, holati.",
  "Har tuzatishdan keyin oldingi sinovlar qayta bajariladi — tuzatish boshqa joyni buzmaganini tekshirish uchun."],
 "24 soatlik uzluksiz sinovni tashkil qiling. Bir kecha ishlagan qurilma o'quvchilarga tizim ishonchliligi haqida ko'p narsa o'rgatadi.",
 [("Nega uzoq muddatli sinov kerak?", "Xotira sizishi va aloqa uzilishi faqat vaqt o'tib ko'rinadi."),
  ("Tuzatishdan keyin nima qilinadi?", "Oldingi sinovlar qayta bajariladi.")],
 "Faqat qisqa muddatli sinov o'tkazib, tizimni tayyor deb hisoblash."),

"Loyihani taqdim etish va himoya qilish": T(
 "Loyihani texnik taqdimot ko'rinishida himoya qilish",
 ["Taqdimot tuzilishi: muammo, yechim g'oyasi, tizim arxitekturasi, namoyish, sinov natijalari, cheklovlar va rivojlantirish yo'llari.",
  "Namoyish oldindan sinaladi va zaxira varianti tayyorlanadi (video yozib qo'yish).",
  "Sinov natijalari raqamlar bilan beriladi: aniqlik, javob vaqti, batareya muddati.",
  "Cheklovlarni ochiq aytish kuchsizlik emas — bu muallif o'z ishini tanqidiy baholay olishini ko'rsatadi va savollarga tayyorligini bildiradi."],
 "Namoyish uchun zaxira video tayyorlashni majburiy qiling. Jonli namoyish taqdimotda buzilishi juda ko'p uchraydi va zaxira ishni saqlab qoladi.",
 [("Taqdimotda sinov natijalari qanday beriladi?", "Aniq raqamlar bilan."),
  ("Nega zaxira video kerak?", "Jonli namoyish buzilib qolishi mumkin.")],
 "Faqat \"biz nima yasadik\" ni gapirib, natija va cheklovlarni aytmaslik."),
}
