# -*- coding: utf-8 -*-
"""1-yil, 7-sinf — elektronika (jadal) + Arduino. 72 mavzu uchun aniq kontent."""

from kb_5_8 import T

MAVZULAR = {

# ==================================================== 1-CHORAK: Elektronika asoslari (jadal kurs)
"Tok, kuchlanish, qarshilik: asosiy kattaliklar": T(
 "Uch kattalikni bitta zanjirda o'lchab, o'zaro bog'liqligini jadvalga tushirish",
 ["Uch asosiy kattalik: tok I (amper) — zaryad oqimi; kuchlanish U (volt) — zaryadni harakatlantiruvchi bosim; qarshilik R (om) — oqimga to'sqinlik.",
  "Suv tizimi bilan solishtirish: kuchlanish = nasos bosimi, tok = sekundiga oqadigan suv, qarshilik = quvurning torligi.",
  "Kattaliklarning prefikslari: mA = 0,001 A, uA = 0,000001 A, kOm = 1000 Om, MOm = 1 000 000 Om.",
  "Odatiy qiymatlar: LED 15 mA, Arduino platasi 50 mA, motor 200-1000 mA, telefon zaryadlagichi 1-2 A."],
 "7-sinf uchun bu jadal takrorlash — 5-6-sinf materialini bir darsda beradi. Shuning uchun suv o'xshatishiga ko'p vaqt sarflamang, darhol raqamlar va o'lchovga o'ting.",
 [("mA ni A ga qanday aylantiriladi?", "1000 ga bo'linadi."),
  ("Motor odatda qancha tok oladi?", "200-1000 mA.")],
 "Prefikslarni aralashtirish — hisobda 1000 marta xatoga olib keladi."),

"Zanjir va sxema tili": T(
 "12 ta shartli belgini o'rganib, berilgan sxemani zanjirga aylantirish",
 ["Sxema — muhandislarning xalqaro tili. Belgilar IEC standarti bo'yicha bir xil.",
  "Asosiy belgilar: rezistor (to'rtburchak), kondensator (ikki chiziq), diod (uchburchak), tranzistor (doira), kalit (uzuq chiziq), GND (qisqaruvchi chiziqlar).",
  "Yozuv qoidalari: har komponentga belgi (R1, C2, Q1) va nominal (220 Om, 100 nF) yoziladi.",
  "Sxemani zanjirga aylantirish tartibi: quvvat shinalari, keyin asosiy tarmoq, keyin qo'shimcha ulanishlar."],
 "Belgilarni tez o'rgatish uchun kartochka o'yini tashkil qiling. 7-sinfda jadal kurs bo'lgani uchun mexanik yodlashga vaqt yo'q — o'yin tezroq ishlaydi.",
 [("R1, C2, Q1 belgilari nimani bildiradi?", "Rezistor, kondensator va tranzistorning tartib raqami."),
  ("Sxemani yig'ish nimadan boshlanadi?", "Quvvat shinalarini ulashdan.")],
 "Nominalsiz sxema chizish — komponent tanlab bo'lmaydi."),

"Breadboard va montaj qoidalari": T(
 "Breadboardni tekshirib, toza montaj qoidalari bilan test zanjiri yig'ish",
 ["Breadboardda o'rta qism ustunlari (5 teshik) va chetdagi quvvat shinalari bor. Ustunlar o'rta tirqishdan o'tmaydi.",
  "Montaj qoidalari: qisqa simlar, ranglar bo'yicha tartib (qizil +, qora GND), komponentlar bir yo'nalishda, simlar taxta ustidan o'tmaydi.",
  "Quvvat shinasi ba'zi taxtalarda o'rtadan uzilgan — buni har yangi taxtada tekshirish kerak.",
  "Breadboard 1 A gacha tokka mo'ljallangan. Motor va rele uchun alohida quvvat va mustahkam ulanish kerak."],
 "Toza montajni birinchi darsdan talab qiling. 7-sinf 2-chorakda darhol Arduino boshlanadi va o'sha yerda chalkash montaj ish tezligini keskin pasaytiradi.",
 [("Breadboard ustunidagi nechta teshik o'zaro ulangan?", "Beshta."),
  ("Breadboard qancha tokka mo'ljallangan?", "Taxminan 1 A gacha.")],
 "Motor tokini breadboard orqali o'tkazish — kontaktlar qiziydi va taxta shikastlanadi."),

"Rezistor va rangli kod": T(
 "Rangli kodni o'qish va teskarisini bajarish, o'lchov bilan tekshirish",
 ["To'rt halqa: raqam, raqam, nollar soni, aniqlik. Rang-raqam: qora 0, jigarrang 1, qizil 2, to'q sariq 3, sariq 4, yashil 5, ko'k 6, binafsha 7, kulrang 8, oq 9.",
  "Standart E12 qatori: 10, 12, 15, 18, 22, 27, 33, 39, 47, 56, 68, 82 va o'nlik ko'paytmalari. Hisobda chiqqan qiymat shu qatorga moslanadi.",
  "Rezistorda quvvat ham muhim: odatiy 0,25 Vt. P = I kvadrat x R bilan tekshiriladi.",
  "Eng ko'p ishlatiladigan qiymatlar: 220 Om (LED), 1 kOm (tranzistor bazasi), 10 kOm (tortuvchi rezistor)."],
 "Uch \"ish beruvchi\" qiymatni (220, 1k, 10k) alohida yodlashni tavsiya qiling — amaliy ishlarning 80% i shular bilan bajariladi.",
 [("LED uchun standart rezistor qancha?", "220 Om (5 V zanjirda)."),
  ("Tortuvchi rezistor uchun odatda qaysi qiymat olinadi?", "10 kOm.")],
 "Rangli kodni teskari tomondan o'qish."),

"LED va qutblanish": T(
 "LEDlarning tushish kuchlanishini o'lchab, har rang uchun rezistor hisoblash",
 ["LED diod — faqat bir yo'nalishda tok o'tkazadi. Uzun oyoq anod (+), kalta oyoq katod (-).",
  "Tushish kuchlanishi rangga bog'liq: qizil 1,8-2 V, yashil/sariq 2-2,2 V, ko'k/oq 3-3,2 V.",
  "Rezistor: R = (U manba - U led) / I led. 5 V, qizil, 15 mA uchun: (5-2)/0,015 = 200 Om, ya'ni 220 Om.",
  "3,3 V zanjirda (ESP32) ko'k LED uchun rezistor juda kichik chiqadi — bu keyingi chorakdagi 3,3 V mantiq mavzusiga bog'lanadi."],
 "3,3 V va ko'k LED muammosini oldindan aytib qo'ying — bu 8-sinfdagi ESP32 darslariga ko'prik va o'quvchilarni tayyorlaydi.",
 [("Ko'k LEDning tushish kuchlanishi qancha?", "Taxminan 3-3,2 V."),
  ("5 V da yashil LED (2,1 V, 15 mA) uchun rezistor?", "Taxminan 200 Om, ya'ni 220 Om.")],
 "Barcha ranglarga bir xil rezistor tanlash."),

"Multimetr: kuchlanishni o'lchash": T(
 "Zanjirning har bir nuqtasida potensialni o'lchab, sxemaga yozib chiqish",
 ["Voltmetr parallel ulanadi, kirish qarshiligi 10 MOm — zanjirga deyarli ta'sir qilmaydi.",
  "GND ni umumiy nuqta qilib tanlab, qora shchupni unda qoldirish kerak. Shunda barcha o'lchovlar solishtirsa bo'ladigan bo'ladi.",
  "Manfiy qiymat shchuplarning teskari qo'yilganini bildiradi, xato emas.",
  "O'lchangan qiymatlarni sxemaga yozib borish — bu qurilma hujjatining bir qismi va nosozlik izlashda juda qimmatli."],
 "Sxemaga o'lchov yozish odatini shu darsda o'rnating. 7-sinf bir yilda Arduino'ni tugatadi, shuning uchun ish madaniyati birinchi chorakda shakllanishi kerak.",
 [("Voltmetr qanday ulanadi?", "Parallel."),
  ("Nega qora shchup bir joyda qoldiriladi?", "O'lchovlar bir-biriga solishtiriladigan bo'lishi uchun.")],
 "Har o'lchovda ikkala shchupni ham ko'chirish."),

"Multimetr: qarshilik va tokni o'lchash": T(
 "Qarshilik va tokni o'lchab, Om qonuni bilan tekshirish",
 ["Qarshilik faqat quvvatsiz zanjirda va komponent kamida bir tomondan uzilgan holda o'lchanadi.",
  "Tok ketma-ket o'lchanadi — zanjir uzilib, ampermetr uzilgan joyga qo'yiladi. Qizil shchup A yoki mA teshigiga ko'chiriladi.",
  "Eng qimmat xato: tok teshigidagi shchup bilan kuchlanish o'lchash — bu qisqa tutashuv va predoxranitel kuyadi.",
  "Amalda tok ko'pincha bilvosita hisoblanadi: ma'lum rezistordagi kuchlanish o'lchanib, I = U/R qo'llaniladi."],
 "Tok o'lchashda har bir juftlik ulanishini SIZ tekshiring. Bir sinf uchun bir necha predoxranitel zaxirada bo'lsin.",
 [("Tok qanday ulanish bilan o'lchanadi?", "Ketma-ket."),
  ("Bilvosita tok o'lchash usuli qanday?", "Ma'lum rezistordagi kuchlanishni o'lchab, I = U/R bilan hisoblab.")],
 "O'lchovdan keyin shchupni tok teshigida qoldirish."),

"Om qonuni va hisoblash": T(
 "10 ta masalani yechib, uchtasini zanjirda o'lchov bilan tekshirish",
 ["U = I x R. Uch ko'rinish: U = I x R, I = U / R, R = U / I.",
  "Quvvat: P = U x I = I kvadrat x R = U kvadrat / R.",
  "Amaliy qisqartma: V / kOm = mA. 5 V / 1 kOm = 5 mA — nollar bilan ovora bo'lmaydi.",
  "Har javob tekshiriladi: birlik to'g'rimi, qiymat realmi, teskari hisob mos keladimi."],
 "V/kOm = mA qisqartmasini doskaga yozib qo'ying. Jadal kursda vaqt tejash muhim va bu usul hisobni ikki barobar tezlashtiradi.",
 [("9 V va 3 kOm: tok qancha?", "3 mA."),
  ("P = U x I dan boshqa ko'rinishlar qaysi?", "P = I kvadrat x R va P = U kvadrat / R.")],
 "Birliklarni aylantirmaslik."),

"Ketma-ket va parallel ulanish": T(
 "Ikki turdagi zanjirni yig'ib, barcha kattaliklarni o'lchab jadval tuzish",
 ["Ketma-ket: I bir xil, U qo'shiladi, R qo'shiladi.",
  "Parallel: U bir xil, I qo'shiladi, 1/R = 1/R1 + 1/R2. Ikki rezistor uchun R = R1xR2/(R1+R2).",
  "Tekshirish qoidasi: parallel ulanishning umumiy qarshiligi eng kichik tarmoqdan ham kichik bo'ladi.",
  "Amalda ko'p zanjirlar aralash: ular bosqichma-bosqich soddalashtiriladi."],
 "Ikki turdagi zanjirni yonma-yon yig'dirib, jadvalni bitta varaqda solishtiring. Farq shu tarzda eng aniq ko'rinadi.",
 [("Parallel ulanishda umumiy qarshilik qanday bo'ladi?", "Eng kichik tarmoq qarshiligidan ham kichik."),
  ("Ketma-ket zanjirda tok qanday taqsimlanadi?", "Taqsimlanmaydi — hamma joyda bir xil.")],
 "Parallel qarshiliklarni qo'shib yuborish."),

"Kuchlanish bo'luvchi va potensiometr": T(
 "Bo'luvchi hisoblab yig'ish va potensiometr bilan silliq sozlashni sinash",
 ["Bo'luvchi: U chiqish = U kirish x R2 / (R1 + R2). R2 — pastki (GND ga ulangan) rezistor.",
  "Chiqish nisbatga bog'liq, absolyut qiymatga emas. Lekin absolyut qiymat tok iste'moliga ta'sir qiladi.",
  "Yuklama ulanganda chiqish pasayadi. Qoida: yuklama R2 dan kamida 10 marta katta bo'lsin.",
  "Potensiometr — sozlanadigan bo'luvchi. Barcha analog sensorlar (fotorezistor, termistor) shu sxemada ulanadi."],
 "Bo'luvchi keyingi chorakda analogRead bilan har bir sensorda uchraydi — buni aniq ayting, o'quvchilar bog'lanishni ko'rsin.",
 [("Bo'luvchi formulasida R2 qaysi rezistor?", "GND ga ulangan pastki rezistor."),
  ("Yuklama qanchalik katta bo'lishi kerak?", "R2 dan kamida 10 marta.")],
 "Bo'luvchidan LED yoki motor quvvatlantirishga urinish."),

"Tugma va kalitlar, tortuvchi rezistor": T(
 "Tortuvchi rezistorli va rezistorsiz tugma zanjirini solishtirib, kirish holatini o'lchash",
 ["Tugma bosilmaganda uning ulanmagan uchi \"osilgan\" (floating) holatda bo'ladi — kuchlanish noaniq va tasodifiy o'zgaradi.",
  "Tortuvchi rezistor (pull-up) kirishni VCC ga tortadi: bosilmaganda 5 V, bosilganda 0 V.",
  "Pastga tortuvchi (pull-down) esa GND ga tortadi: bosilmaganda 0 V, bosilganda 5 V.",
  "Odatiy qiymat 10 kOm. Juda kichik bo'lsa ortiqcha tok, juda katta bo'lsa shovqinga sezgir bo'ladi."],
 "Rezistorsiz tugmaning \"osilgan\" holatini voltmetr bilan ko'rsating — qiymat qo'l yaqinlashganda ham o'zgaradi. Bu juda ta'sirchan namoyish.",
 [("Pull-up rezistorli tugma bosilmaganda kirishda qancha bo'ladi?", "VCC, ya'ni 5 V."),
  ("Odatiy tortuvchi rezistor qiymati qancha?", "10 kOm.")],
 "Tortuvchi rezistorsiz tugma ulash — kirish tasodifiy qiymat beradi va dastur beqaror ishlaydi."),

"Kondensator va RC zanjir": T(
 "RC zanjirning vaqt doimiysini hisoblab, LEDning so'nish vaqtini o'lchash",
 ["Kondensator zaryad to'playdi. Sig'im faradda, amalda uF, nF, pF ishlatiladi.",
  "Vaqt doimiysi T = R x C. Qulay shakl: kOm x uF = ms.",
  "Bir T da 63%, besh T da 99% ga zaryadlanadi.",
  "Elektrolitik qutbli — teskari ulash mumkin emas. Keramik qutbsiz va yuqori chastotali shovqin filtri sifatida mikrosxemalar yoniga qo'yiladi."],
 "\"Har mikrosxema yonida 100 nF\" qoidasini eslatib qo'ying — Arduino platasida ham shunday kondensatorlar bor, buni ko'rsatib bering.",
 [("10 kOm va 47 uF uchun T qancha?", "470 ms."),
  ("Mikrosxema yonidagi kondensator nima uchun?", "Yuqori chastotali shovqinni filtrlash uchun.")],
 "Elektrolitikni teskari ulash."),

"Diod va himoya": T(
 "Flyback diodli va diodsiz rele zanjirini solishtirish",
 ["Diod tokni bir yo'nalishda o'tkazadi, to'g'ri yo'nalishda 0,7 V tushadi.",
  "Ketma-ket diod teskari qutblanishdan himoya qiladi.",
  "Flyback diod — g'altakli yuklamaga (motor, rele) PARALLEL va TESKARI ulanadi. G'altak o'chganda hosil bo'ladigan yuqori kuchlanish impulsini yo'q qiladi.",
  "Bu impuls 100 V dan oshishi mumkin va boshqaruvchi tranzistor yoki mikrokontrollerni darhol ishdan chiqaradi."],
 "Flyback diod 2-chorakdan boshlab har bir motorli va releli sxemada kerak bo'ladi. Uni \"majburiy komponent\" sifatida ro'yxatga kiritib qo'ying.",
 [("Flyback diod qanday ulanadi?", "Yuklamaga parallel va teskari yo'nalishda."),
  ("U nimadan himoya qiladi?", "G'altak o'chganda hosil bo'ladigan yuqori kuchlanish impulsidan.")],
 "Flyback diodni to'g'ri yo'nalishda ulash — qisqa tutashuv."),

"Tranzistor kalit sifatida": T(
 "Tranzistorli kalit yig'ib, baza rezistorini hisoblash va to'yinishni tekshirish",
 ["Kalit rejimida tranzistor to'liq ochiq yoki to'liq yopiq bo'ladi.",
  "Baza rezistori: R = (U boshqaruv - 0,7) / I baza, bunda I baza = I kollektor / 10 (zaxira bilan).",
  "5 V boshqaruv va 100 mA yuklama uchun: I baza = 10 mA, R = 4,3/0,01 = 430 Om, ya'ni 470 Om.",
  "To'yinganini tekshirish: kollektor-emitter kuchlanishi 0,2 V bo'lishi kerak. 2-3 V bo'lsa tranzistor oraliq holatda va qiziydi."],
 "Bu sxema 2-chorakdan boshlab Arduino bilan motor, rele va kuchli LEDni boshqarishda ishlatiladi. Hisobni yaxshi o'zlashtirish shart.",
 [("To'yingan tranzistorda kollektor-emitter kuchlanishi qancha?", "Taxminan 0,2 V."),
  ("100 mA yuklama uchun baza toki qancha olinadi?", "Taxminan 10 mA.")],
 "Baza rezistorini qo'ymaslik yoki juda katta olish."),

"Zummer va tovush hosil qilish": T(
 "Aktiv va passiv zummerni solishtirib, passivga turli chastota berib nota hosil qilish",
 ["Aktiv zummer ichida generator bor — doimiy kuchlanishda o'z tonida tovush chiqaradi.",
  "Passiv zummerga chastota berish kerak. U bilan istalgan nota va melodiya chalinadi.",
  "Nota chastotalari: DO 262 Hz, RE 294, MI 330, FA 349, SOL 392, LYA 440, SI 494 Hz.",
  "Oktava — chastotaning ikki barobarlanishi. LYA 440, keyingi oktavada 880 Hz."],
 "Nota chastotalari jadvalini tarqating — 4-chorakdagi melodiya darsida u massiv sifatida kodga kiritiladi.",
 [("Melodiya uchun qaysi zummer kerak?", "Passiv."),
  ("LYA notasining chastotasi qancha?", "440 Hz.")],
 "Passiv zummerga doimiy kuchlanish berib, uni buzuq deb hisoblash."),

"DC motor va rele": T(
 "Tranzistor orqali motorni, rele orqali alohida manbali yuklamani boshqarish",
 ["Motor katta tok oladi (bo'sh yurishda 100 mA, to'xtatilganda 1 A gacha) va shovqin chiqaradi.",
  "Boshqarish: tranzistor (TIP122 yoki MOSFET) + flyback diod + motor klemmalariga 100 nF kondensator.",
  "Rele boshqaruv va yuklama zanjirlarini to'liq ajratadi. G'altagi 40 mA atrofida tok oladi — u ham tranzistor orqali boshqariladi.",
  "Motor va boshqaruv sxemasiga alohida quvvat berish ma'qul, lekin GND umumiy bo'lishi SHART."],
 "\"Umumiy GND\" qoidasini alohida yozib qo'ying — ikki manbali sxemalarda bu eng ko'p uchraydigan va topish qiyin xato.",
 [("Motorli sxemada qanday uch himoya elementi kerak?", "Tranzistor (yoki drayver), flyback diod, shovqin kondensatori."),
  ("Ikki manba ishlatilganda nima umumiy bo'lishi kerak?", "GND.")],
 "GND ni umumiylashtirishni unutish — sxema tasodifiy va tushunarsiz ishlaydi."),

"Quvvat manbalari va xavfsizlik": T(
 "Turli manbalarning kuchlanishi va yuklamadagi holatini o'lchab, jadval tuzish",
 ["Manba tanlashda uch parametr: kuchlanish (V), maksimal tok (A) va barqarorlik.",
  "USB porti 5 V va 0,5 A gacha beradi. Motorli loyihalar uchun bu yetmaydi — alohida adapter kerak.",
  "Adapterning quvvati: 5V 2A = 10 Vt. Iste'mol undan kam bo'lishi kerak, zaxira bilan.",
  "Xavfsizlik: 220 V bilan faqat o'qituvchi ishlaydi; Li-ion akkumulyator maxsus kontrollersiz zaryadlanmaydi; qizigan komponentga tegilmaydi."],
 "USB portining 0,5 A cheklovini alohida ayting — o'quvchilar Arduino'ni USB'dan quvvatlantirib, motor ulaganda kompyuter portini ishdan chiqarishi mumkin.",
 [("USB port qancha tok bera oladi?", "Odatda 0,5 A gacha."),
  ("5V 2A adapterning quvvati qancha?", "10 vatt.")],
 "Motorni Arduino'ning USB quvvatidan yurgizish — plata qayta yuklanadi yoki port shikastlanadi."),

"Nosozlik topish: tizimli yondashuv": T(
 "Uch xatoli zanjirni tizimli usul bilan tuzatib, protokol yuritish",
 ["Tartib: 1) ko'z bilan ko'rish, 2) quvvatni o'lchash, 3) zumlash bilan ulanishlarni tekshirish, 4) signalni bosqichma-bosqich kuzatish.",
  "Yarmiga bo'lish usuli: zanjirni ikkiga bo'lib, qaysi yarmida muammo borligini aniqlash. Bu qadamlar sonini keskin kamaytiradi.",
  "Bir vaqtda faqat BITTA narsa o'zgartiriladi, aks holda nima yordam berganini bilib bo'lmaydi.",
  "Protokol yuritish shart: nima tekshirildi, natija qanday, keyingi qadam nima."],
 "Protokol shaklini tarqating. 7-sinf keyingi chorakda dasturlashga o'tadi va u yerda ham xuddi shu tizimli yondashuv (bitta o'zgartirish - sinash) ishlaydi.",
 [("Yarmiga bo'lish usuli nima beradi?", "Xatoni ancha kam tekshiruvda topish imkonini."),
  ("Nega bir vaqtda bitta narsa o'zgartiriladi?", "Nima yordam berganini aniq bilish uchun.")],
 "Bir necha narsani birdan o'zgartirib, tasodifan ishlab ketishiga umid qilish."),

# ==================================================== 2-CHORAK: Arduino — birinchi qadamlar
"Arduino Uno platasi: pinlar xaritasi": T(
 "Plataning barcha pinlarini xaritaga chizib, har birining vazifasini yozish",
 ["Arduino Uno da ATmega328P mikrokontrolleri bor: 32 KB flesh xotira, 2 KB operativ xotira, 16 MHz chastota.",
  "Raqamli pinlar D0-D13: kirish yoki chiqish bo'la oladi. Ulardan D3, D5, D6, D9, D10, D11 (~ belgili) PWM ham bera oladi.",
  "Analog pinlar A0-A5: 0-5 V oralig'idagi kuchlanishni 0-1023 qiymatga aylantiradi. Ular raqamli pin sifatida ham ishlashi mumkin.",
  "Quvvat pinlari: 5V, 3.3V, GND (uchta), VIN. Har pin maksimal 20 mA (mutlaq chegara 40 mA), butun plata esa 200 mA gacha bera oladi."],
 "Pin cheklovlarini (20 mA pinga, 200 mA plataga) doskaga yozib qo'ying. Bu raqamlar butun yil davomida komponent ulashda hal qiluvchi bo'ladi.",
 [("Arduino Uno pinidan maksimal qancha tok olish mumkin?", "Xavfsiz 20 mA, mutlaq chegara 40 mA."),
  ("Qaysi pinlar PWM bera oladi?", "~ belgili pinlar: 3, 5, 6, 9, 10, 11.")],
 "Bir necha LEDni bir pinga ulash yoki motor ulash — pin ishdan chiqadi."),

"Arduino IDE va platani ulash": T(
 "IDE'ni sozlab, platani ulash va Blink misolini yuklash",
 ["Arduino IDE — kod yozib, uni kompilyatsiya qilib, plataga yuklaydigan muhit.",
  "Ulashdan keyin ikkita sozlama shart: Tools > Board (Arduino Uno) va Tools > Port (COM raqami).",
  "Port ko'rinmasa: USB kabel faqat quvvat uchunmi (ma'lumot simlarisiz), drayver o'rnatilmaganmi yoki plata klonimi (CH340 drayveri kerak) tekshiriladi.",
  "Yuklashda plata RX/TX diodlari miltillaydi. Miltillamasa — aloqa yo'q."],
 "Klon platalar uchun CH340 drayverini oldindan barcha kompyuterlarga o'rnatib qo'ying. Aks holda birinchi dars drayver o'rnatish bilan o'tib ketadi.",
 [("Yuklashdan oldin qaysi ikki sozlama tekshiriladi?", "Board va Port."),
  ("Port ko'rinmasa nima tekshiriladi?", "Kabel, drayver va plata turi.")],
 "Ma'lumot simlari yo'q (faqat zaryadlash uchun) USB kabelni ishlatish."),

"Blink: birinchi dastur": T(
 "Blink dasturini yuklab, kechikish qiymatini o'zgartirib natijani kuzatish",
 ["Blink — eng oddiy dastur: LEDni yoqadi, kutadi, o'chiradi, kutadi va takrorlaydi.",
  "Kod: pinMode(13, OUTPUT) sozlashda; loop ichida digitalWrite(13, HIGH), delay(1000), digitalWrite(13, LOW), delay(1000).",
  "D13 pinga plataning o'zida LED ulangan — tashqi komponentsiz ham natija ko'rinadi.",
  "delay(1000) — 1000 millisekund, ya'ni 1 sekund. Qiymatni 100 qilsa LED 10 marta tez miltillaydi."],
 "Birinchi yuklash muvaffaqiyatli bo'lishi psixologik jihatdan juda muhim. Kodni tayyor bering, o'quvchilar faqat delay qiymatini o'zgartirsin.",
 [("delay(500) qancha vaqt kutadi?", "Yarim sekund."),
  ("D13 pinda nima ulangan?", "Plataning o'z LEDi.")],
 "Kodni to'liq o'zi yozishga urinish va nuqta-vergul unutib, birinchi darsdanoq xatoga duch kelish."),

"Dastur tuzilishi: setup() va loop()": T(
 "setup va loop ichiga har xil kod qo'yib, farqni kuzatish",
 ["Har bir Arduino dasturi ikki majburiy funksiyadan iborat: setup() va loop().",
  "setup() plata yoqilganda YOKI reset bosilganda faqat BIR MARTA bajariladi. Unda pin rejimlari, Serial aloqa va boshlang'ich sozlamalar yoziladi.",
  "loop() esa setup tugagach cheksiz takrorlanadi. Plata o'chirilmaguncha to'xtamaydi.",
  "Bu ikkisining farqini tushunish eng muhim: pinMode ni loop ichiga yozish xato emas, lekin keraksiz — u har sikl qayta bajariladi."],
 "setup ichiga miltillash kodini qo'yib ko'rsating: LED bir marta miltillaydi va to'xtaydi. Farq shu tajriba bilan bir zumda tushunarli bo'ladi.",
 [("setup() necha marta bajariladi?", "Bir marta — plata yoqilganda yoki reset bosilganda."),
  ("loop() qachon to'xtaydi?", "Plata o'chirilmaguncha to'xtamaydi.")],
 "Serial.begin() ni loop ichiga yozish — aloqa har sikl qayta ochiladi va ishlamaydi."),

"pinMode va digitalWrite": T(
 "Uch LEDni turli pinlarga ulab, mustaqil boshqarish",
 ["pinMode(pin, rejim) — pinning vazifasini belgilaydi: OUTPUT (chiqish) yoki INPUT (kirish).",
  "digitalWrite(pin, qiymat) — chiqish pinga HIGH (5 V) yoki LOW (0 V) beradi.",
  "pinMode odatda setup() ichida bir marta yoziladi, digitalWrite esa loop ichida kerakli joyda.",
  "Pin OUTPUT qilinmasa, digitalWrite ishlamaydi (aniqrog'i, ichki tortuvchi rezistorni yoqadi). Bu eng ko'p uchraydigan \"nega ishlamayapti\" sababi."],
 "pinMode ni ataylab unutib, natijani ko'rsating: LED xira yonadi yoki umuman yonmaydi. Sabab — ichki tortuvchi rezistor orqali juda kichik tok o'tishi.",
 [("pinMode qayerda yoziladi?", "Odatda setup() ichida."),
  ("digitalWrite(pin, HIGH) pinga qancha kuchlanish beradi?", "5 V.")],
 "pinMode ni unutish — LED xira yonadi va sabab tushunarsiz bo'ladi."),

"delay() va vaqt boshqaruvi": T(
 "Har xil delay qiymatlari bilan miltillash naqshlarini yaratish",
 ["delay(ms) dasturni belgilangan millisekundga to'xtatib turadi.",
  "Muhim kamchilik: delay paytida plata BOSHQA HECH NARSA QILA OLMAYDI — tugmani ham o'qimaydi, sensorni ham tekshirmaydi.",
  "Shuning uchun delay faqat oddiy dasturlarda ishlatiladi. Murakkab dasturlarda millis() bilan vaqt hisoblanadi.",
  "delayMicroseconds() ham bor — mikrosekundlik kechikish uchun, masalan ultratovush sensorini boshqarishda."],
 "delay ning kamchiligini shu darsda ayting, lekin millis ga hozircha o'tmang. O'quvchilar avval muammoni his qilsin, keyin yechim berilsin.",
 [("delay paytida plata tugmani o'qiy oladimi?", "Yo'q, dastur to'liq to'xtaydi."),
  ("delay(2500) qancha vaqt?", "2,5 sekund.")],
 "Uzun delay qo'yib, tugma javob bermasligidan hayron bo'lish."),

"Bir nechta LED bilan ishlash": T(
 "Beshta LEDni ketma-ket yoqadigan \"yuguruvchi olov\" dasturini yozish",
 ["Har LED o'z piniga va o'z rezistoriga ulanadi. Beshta LED uchun D2-D6 pinlari qulay.",
  "Har biri uchun pinMode setup ichida yoziladi. Kod uzun bo'lib ketadi — bu keyingi darsdagi sikl mavzusiga tabiiy ehtiyoj yaratadi.",
  "\"Yuguruvchi olov\" — bir LEDni yoqib, oldingisini o'chirish va bu jarayonni surib borish.",
  "Umumiy tok hisobga olinadi: beshta LED birga yonsa 5 x 15 = 75 mA. Bu Arduino uchun xavfsiz, lekin yigirmata LED uchun tashqi quvvat kerak bo'lardi."],
 "Kodning uzunligidan o'quvchilar bezovta bo'lsin — keyingi darsdagi for sikli \"qutqaruvchi\" bo'lib ko'rinadi va yaxshi o'zlashtiriladi.",
 [("Beshta LED birga yonsa qancha tok kerak?", "Taxminan 75 mA."),
  ("Har LEDga alohida rezistor kerakmi?", "Ha.")],
 "Barcha LEDlarni bitta pinga ulash — pin cheklovidan oshadi."),

"Svetofor dasturi": T(
 "Uch rangli LED bilan haqiqiy svetofor sikli dasturini yozish",
 ["Svetofor sikli: yashil (5 s) -> sariq (2 s) -> qizil (5 s) -> qizil+sariq (1 s) -> yashil.",
  "Bu ketma-ketlik ALGORITM: aniq belgilangan qadamlar tartibi. Uni avval qog'ozda yozib, keyin kodga aylantirish kerak.",
  "Har holatda qaysi LED yonishi jadval qilib yoziladi — bu keyinchalik kodni tekshirishda ishlatiladi.",
  "Real svetoforda vaqtlar yo'l harakati zichligiga qarab o'zgaradi va piyodalar tugmasi ham bo'ladi. Buni keyingi bosqichda qo'shish mumkin."],
 "Algoritmni avval QOG'OZDA yozdirish odatini o'rnating. Kodni to'g'ridan-to'g'ri yozishga urinish 7-sinfda eng ko'p vaqt yo'qotadigan xato.",
 [("Svetofor sikli nechta holatdan iborat?", "To'rtta asosiy holat."),
  ("Algoritm nima?", "Masalani yechish qadamlarining aniq ketma-ketligi.")],
 "Kodni qog'ozdagi rejasiz yozishga kirishish."),

"O'zgaruvchi (variable) tushunchasi": T(
 "Kechikish vaqtini o'zgaruvchiga chiqarib, bir joydan butun dasturni sozlash",
 ["O'zgaruvchi — nomlangan xotira katagi. Unga qiymat yoziladi va keyin nom orqali ishlatiladi.",
  "E'lon qilish: int kechikish = 500; — bunda int turi, kechikish nomi, 500 boshlang'ich qiymat.",
  "Afzalligi: qiymat bir joyda o'zgartirilsa, u ishlatilgan hamma joyda o'zgaradi. 10 ta delay(500) o'rniga bitta o'zgaruvchi.",
  "Nom ma'noli bo'lishi kerak: kechikish yaxshi, x yomon. Kod bir oydan keyin o'qilganda nom o'zi tushuntirib turadi."],
 "\"Sehrli raqamlar\" (kodda to'g'ridan-to'g'ri yozilgan sonlar) muammosini ko'rsating: 500 ni 10 joyda o'zgartirish kerak bo'lsa nima bo'ladi?",
 [("O'zgaruvchining afzalligi nima?", "Qiymat bir joyda o'zgartirilsa hamma joyda o'zgaradi."),
  ("O'zgaruvchi nomi qanday bo'lishi kerak?", "Ma'noli, nima saqlashini bildiradigan.")],
 "Bir harfli nomlar berish — kod bir haftadan keyin tushunarsiz bo'ladi."),

"Ma'lumot turlari: int, float, bool": T(
 "Turli turdagi o'zgaruvchilar bilan hisoblash qilib, natijalarni Serial monitorda ko'rish",
 ["int — butun son, -32768 dan 32767 gacha, 2 bayt xotira egallaydi.",
  "float — kasrli son, 6-7 raqam aniqlikda, 4 bayt. Sekin hisoblanadi, faqat kerak bo'lganda ishlatiladi.",
  "bool — faqat true yoki false, 1 bayt. Holat saqlash uchun ideal.",
  "long — katta butun son (2 mlrd gacha), millis() natijasini saqlash uchun kerak. byte — 0-255, kam xotira talab qiladi."],
 "int ning chegarasini (32767) ko'rsating: undan oshsa qiymat manfiyga aylanadi. Bu \"to'lib ketish\" (overflow) hodisasi va uni bir marta ko'rish kerak.",
 [("int qanday chegaraga ega?", "-32768 dan 32767 gacha."),
  ("Holat saqlash uchun qaysi tur qulay?", "bool.")],
 "Hamma joyda float ishlatish — xotira va vaqt behuda sarflanadi."),

"for sikli": T(
 "for sikli bilan yuguruvchi olovni qayta yozib, kod uzunligini solishtirish",
 ["for sikli takrorlanadigan amallarni qisqartiradi. Tuzilishi: for (boshlang'ich; shart; qadam) { ... }",
  "Misol: for (int i = 2; i <= 6; i++) — i 2 dan boshlanadi, 6 gacha davom etadi, har safar 1 ga oshadi.",
  "Beshta LED uchun 15 qator kod bitta sikl bilan 3 qatorga tushadi.",
  "Teskari sikl ham mumkin: for (int i = 6; i >= 2; i--) — bu yuguruvchi olovni orqaga qaytaradi."],
 "Sikldan oldingi va keyingi kodni yonma-yon ko'rsating. Kod uzunligining farqi siklning foydasini gapirmasdan tushuntiradi.",
 [("for (int i = 0; i < 5; i++) necha marta bajariladi?", "Besh marta — i 0, 1, 2, 3, 4."),
  ("i-- nima qiladi?", "Har siklda i ni bittaga kamaytiradi.")],
 "Shart belgisini noto'g'ri qo'yish (< o'rniga <=) — sikl bir marta ortiq yoki kam bajariladi."),

"while sikli": T(
 "while bilan shartga bog'liq takrorlanish yozish va for bilan solishtirish",
 ["while (shart) { ... } — shart rost bo'lguncha takrorlanadi.",
  "for takrorlanish soni MA'LUM bo'lganda ishlatiladi, while esa shartga bog'liq bo'lganda: \"tugma bosilguncha kut\".",
  "Xavf: shart hech qachon yolg'on bo'lmasa, dastur cheksiz siklga tushib qoladi va boshqa hech narsa qilmaydi.",
  "Shuning uchun while ichida shartga ta'sir qiladigan amal albatta bo'lishi kerak."],
 "Cheksiz siklni ataylab yozdirib, plataning \"osilib qolishini\" ko'rsating. Reset tugmasi bilan chiqishni ham ko'rsatib qo'ying.",
 [("for va while qachon ishlatiladi?", "for — takrorlanish soni ma'lum bo'lganda, while — shartga bog'liq bo'lganda."),
  ("Cheksiz sikldan qanday chiqiladi?", "Reset tugmasi bilan yoki shartni o'zgartirib.")],
 "while ichida shartga ta'sir qiladigan amalni unutish — cheksiz sikl."),

"digitalRead: tugmani o'qish": T(
 "Tugmani o'qib, holatini Serial monitorda ko'rsatish",
 ["digitalRead(pin) pinning holatini o'qiydi va HIGH yoki LOW qaytaradi.",
  "Pin INPUT rejimida bo'lishi kerak: pinMode(pin, INPUT) yoki INPUT_PULLUP.",
  "INPUT_PULLUP ichki tortuvchi rezistorni yoqadi — tashqi 10 kOm rezistor kerak bo'lmaydi. Bunda tugma bosilmaganda HIGH, bosilganda LOW bo'ladi (mantiq teskari).",
  "Tugmani GND ga ulash odatiy usul: bir oyog'i pinga, ikkinchisi GND ga."],
 "INPUT_PULLUP ni asosiy usul sifatida o'rgating — u kamroq komponent talab qiladi va xato imkoniyati kam. Teskari mantiqni esa aniq tushuntiring.",
 [("INPUT_PULLUP da tugma bosilganda qanday qiymat o'qiladi?", "LOW."),
  ("Nega INPUT_PULLUP qulay?", "Tashqi tortuvchi rezistor kerak bo'lmaydi.")],
 "INPUT_PULLUP da mantiqni to'g'ri deb o'ylash — u teskari ishlaydi."),

"if sharti": T(
 "Tugma bosilganda LED yonadigan dastur yozish",
 ["if (shart) { ... } — shart rost bo'lsa qavs ichidagi kod bajariladi.",
  "Solishtirish belgilari: == (teng), != (teng emas), > , < , >= , <=.",
  "MUHIM: tenglikni tekshirish uchun IKKI teng belgisi (==) ishlatiladi. Bitta teng (=) qiymat berish degani va bu eng ko'p uchraydigan xato.",
  "Misol: if (digitalRead(2) == LOW) { digitalWrite(13, HIGH); }"],
 "== va = farqini alohida, katta harflar bilan doskaga yozing. Bu xato kompilyatsiya xatosi bermasligi mumkin va topish juda qiyin.",
 [("Tenglikni tekshirish uchun qaysi belgi ishlatiladi?", "== (ikki teng belgisi)."),
  ("if (x = 5) nima qiladi?", "x ga 5 beradi va shart har doim rost bo'ladi — bu xato.")],
 "if ichida bitta teng belgisi (=) yozish."),

"else va else if": T(
 "Tugma bosilgan va bosilmagan holatlar uchun turli javob beruvchi dastur yozish",
 ["else — shart yolg'on bo'lganda bajariladigan qism. if bilan birga to'liq tanlovni beradi.",
  "else if — bir necha shartni ketma-ket tekshirish uchun. Birinchi rost chiqqan shart bajariladi va qolganlari tekshirilmaydi.",
  "Tartib muhim: kengroq shart oldin yozilsa, torroq shart hech qachon bajarilmaydi.",
  "Misol: agar qiymat > 700 bo'lsa yorug'; aks holda agar > 300 bo'lsa o'rtacha; aks holda qorong'i."],
 "Shartlar tartibi masalasini misol bilan ko'rsating: if (x > 100) ni if (x > 500) dan oldin yozsa, ikkinchisi hech qachon ishlamaydi.",
 [("else if larda qaysi shart bajariladi?", "Birinchi rost chiqqani, qolganlari tekshirilmaydi."),
  ("Shartlar tartibi muhimmi?", "Ha, torroq shart oldin yozilishi kerak.")],
 "Shartlarni noto'g'ri tartibda yozish — ba'zi shoxlar hech qachon bajarilmaydi."),

"Tugma sakrashi (debounce) muammosi": T(
 "Tugma bosishlarini sanab, debounce'siz va debounce bilan natijani solishtirish",
 ["Mexanik tugma bosilganda kontaktlar bir necha marta ochilib-yopiladi — bu 5-50 millisekund davom etadi.",
  "Dastur juda tez ishlaganligi uchun bitta bosishni bir necha marta deb qabul qiladi. Sanoq 1 o'rniga 5 chiqadi.",
  "Dasturiy yechim: holat o'zgargach 20-50 ms kutish, keyin qayta tekshirish. Yoki millis() bilan oxirgi o'zgarish vaqtini eslab qolish.",
  "Apparat yechimi: tugmaga parallel 100 nF kondensator — u sakrashlarni silliqlaydi."],
 "Debounce'siz sanoqni ko'rsating: bir marta bosilganda 3-7 chiqadi. O'quvchilar muammoni o'z ko'zi bilan ko'rmaguncha yechimning qadrini bilmaydi.",
 [("Tugma sakrashi qancha davom etadi?", "5-50 millisekund."),
  ("Dasturiy yechim nima?", "Holat o'zgargach 20-50 ms kutib, qayta tekshirish.")],
 "Debounce'ni umuman hisobga olmaslik — sanoq va menyu dasturlari noto'g'ri ishlaydi."),

"Serial monitor: plata bilan gaplashish": T(
 "Sensor va o'zgaruvchi qiymatlarini Serial monitorda kuzatish",
 ["Serial.begin(9600) — setup ichida aloqani ochadi. 9600 — tezlik (bod), monitor oynasida ham shu tezlik tanlanishi kerak.",
  "Serial.print(qiymat) qiymatni yuboradi, Serial.println() esa yuborib, yangi qatorga o'tadi.",
  "Serial monitor — nosozlik topishning asosiy quroli: dasturning qaysi qismi bajarilayotganini va o'zgaruvchilar qiymatini ko'rsatadi.",
  "Serial Plotter esa qiymatlarni grafik qilib chizadi — sensor ma'lumotini kuzatishda juda qulay."],
 "Serial'ni \"dasturning ko'zi\" deb tanishtiring. Kodni ko'r-ko'rona tuzatish o'rniga qiymatlarni ko'rish odati 7-sinfda mustahkamlanishi kerak.",
 [("Serial.begin() qayerda yoziladi?", "setup() ichida."),
  ("Serial monitor asosan nima uchun ishlatiladi?", "Nosozlik topish va qiymatlarni kuzatish uchun.")],
 "Monitor oynasidagi tezlikni kodda ko'rsatilganidan boshqa qo'yish — ekranda tushunarsiz belgilar chiqadi."),

"Nosozlik topish: kod va sxemani birga tekshirish": T(
 "Xatolari bor loyihani tizimli usul bilan tuzatish",
 ["Arduino loyihasida xato ikki joyda bo'lishi mumkin: sxemada yoki kodda. Ularni ajratish birinchi qadam.",
  "Ajratish usuli: sxemani tekshirish uchun eng oddiy kod (Blink) yuklanadi. Ishlasa — sxema joyida, xato kodda.",
  "Kodda xato izlash: Serial.println() ni asosiy nuqtalarga qo'yib, dastur qayergacha yetayotganini ko'rish.",
  "Kompilyatsiya xatosi (yozuvda xato) va mantiqiy xato (dastur ishlaydi, lekin noto'g'ri) — bular butunlay boshqa turlar va boshqacha izlanadi."],
 "\"Sxemami, kodmi?\" savolini birinchi qadam qilib o'rnating. Bu ikkiga bo'lish usulining Arduino'dagi ko'rinishi va vaqtni juda tejaydi.",
 [("Sxema va koddagi xatoni qanday ajratish mumkin?", "Sxemaga eng oddiy tekshiruv kodini yuklab ko'rish."),
  ("Serial.println nosozlik topishda qanday yordam beradi?", "Dastur qayergacha yetganini va qiymatlarni ko'rsatadi.")],
 "Kompilyatsiya xatosi xabarini o'qimasdan kodni tasodifiy o'zgartirishga urinish."),

# ==================================================== 3-CHORAK: Analog signal va sensorlar
"analogRead: potensiometrni o'qish": T(
 "Potensiometrni A0 ga ulab, qiymatlarni Serial monitorda kuzatish",
 ["analogRead(pin) analog pindagi kuchlanishni o'qib, 0 dan 1023 gacha butun son qaytaradi.",
  "Bu 10 razryadli ADC: 2 daraja 10 = 1024 daraja. 0 = 0 V, 1023 = 5 V.",
  "Bitta darajaning qiymati: 5 V / 1024 = 4,9 mV. Ya'ni ADC 5 millivoltdan kichik farqni sezmaydi.",
  "Kuchlanishga aylantirish: U = qiymat x 5.0 / 1023."],
 "1024 raqamining kelib chiqishini (2 ning 10-darajasi) so'rang. Bu ikkilik sanoq tizimini eslatadi va informatika bilan bog'laydi.",
 [("analogRead qanday oraliqda qiymat qaytaradi?", "0 dan 1023 gacha."),
  ("512 qiymati qanday kuchlanishga to'g'ri keladi?", "Taxminan 2,5 V.")],
 "analogRead ni raqamli pinda ishlatishga urinish."),

"Qiymatlarni Serial monitorda kuzatish": T(
 "Sensor qiymatlarini Serial Plotter'da grafik ko'rinishida kuzatish",
 ["Serial monitor matnli, Serial Plotter esa grafik ko'rinishda ko'rsatadi. Ikkalasi ham Tools menyusida.",
  "Plotter uchun faqat raqam yuborilishi kerak: Serial.println(qiymat). Matn bilan yuborilsa grafik chizilmaydi.",
  "Bir necha qiymatni bir vaqtda chizish mumkin: Serial.print(a); Serial.print(\",\"); Serial.println(b);",
  "Grafik shovqinni, sensorning javob tezligini va qiymatlar oralig'ini bir qarashda ko'rsatadi — jadvaldan ancha samarali."],
 "Sensorga qo'l tekkizib, grafikning real vaqtda o'zgarishini ko'rsating. Bu o'quvchilar uchun eng qiziqarli lahzalardan biri.",
 [("Serial Plotter uchun nima yuborilishi kerak?", "Faqat raqam."),
  ("Grafik nimani ko'rsatadi?", "Shovqin, javob tezligi va qiymatlar oralig'ini.")],
 "Plotter'ga matn bilan aralash yuborish — grafik chizilmaydi."),

"map() funksiyasi: qiymatni moslash": T(
 "Potensiometr qiymatini turli oraliqlarga moslab, natijani kuzatish",
 ["map(qiymat, eskiMin, eskiMax, yangiMin, yangiMax) qiymatni bir oraliqdan boshqasiga proporsional o'tkazadi.",
  "Misol: map(qiymat, 0, 1023, 0, 255) — analogRead natijasini PWM oralig'iga o'tkazadi.",
  "Servo uchun: map(qiymat, 0, 1023, 0, 180) — burchak oralig'iga.",
  "map() faqat butun sonlar bilan ishlaydi va yaxlitlash tufayli kichik xatolik bo'lishi mumkin. Teskari moslash ham mumkin: map(x, 0, 1023, 255, 0)."],
 "Teskari moslashni ko'rsating — bu \"potensiometrni o'ngga bursak yorqinlik kamaysin\" kabi vazifalarda kerak bo'ladi va o'quvchilarga kutilmagan bo'ladi.",
 [("map(512, 0, 1023, 0, 255) taxminan qancha beradi?", "Taxminan 128."),
  ("Teskari moslash qanday yoziladi?", "Yangi min va maks joyini almashtirib.")],
 "map ning parametrlar tartibini chalkashtirish."),

"PWM va analogWrite": T(
 "LED yorqinligini PWM bilan bosqichma-bosqich o'zgartirish",
 ["PWM — impuls kengligi modulyatsiyasi. Pin tez yoqilib-o'chiriladi, o'rtacha quvvat esa yoqiq vaqt ulushiga bog'liq.",
  "analogWrite(pin, qiymat) — qiymat 0 dan 255 gacha. 0 = doim o'chiq, 255 = doim yoqiq, 128 = yarim.",
  "Faqat ~ belgili pinlarda ishlaydi: 3, 5, 6, 9, 10, 11. Boshqa pinlarda buyruq xato bermaydi, lekin PWM ham chiqmaydi.",
  "Arduino Uno da PWM chastotasi 490 Hz (ba'zi pinlarda 980 Hz). Bu LED va motor uchun yetarli, lekin audio uchun emas."],
 "\"Analog chiqish emas, tez o'zgaruvchi raqamli\" ekanini ta'kidlang. analogWrite nomi chalg'itadi va bu tushunmovchilik ko'p uchraydi.",
 [("analogWrite qanday oraliqda qiymat qabul qiladi?", "0 dan 255 gacha."),
  ("PWM aslida analog signalmi?", "Yo'q, u tez yoqilib-o'chadigan raqamli signal.")],
 "PWM'siz pinda analogWrite ishlatish — natija faqat yoqiq/o'chiq bo'ladi."),

"LED yorqinligini boshqarish": T(
 "Potensiometr bilan LED yorqinligini silliq boshqarish",
 ["Kod: qiymat = analogRead(A0); yorqinlik = map(qiymat, 0, 1023, 0, 255); analogWrite(9, yorqinlik);",
  "Ko'z yorqinlikni CHIZIQSIZ sezadi: PWM 0 dan 50 gacha o'zgarish 200 dan 250 gacha o'zgarishdan ancha ko'proq seziladi.",
  "Shuning uchun tabiiy ko'rinishi uchun kvadratik moslash ishlatiladi: yorqinlik = (qiymat x qiymat) / 4096.",
  "Bu Weber-Fexner qonuni deb ataladi va u tovushga ham tegishli — shuning uchun ovoz regulyatori logarifmik bo'ladi."],
 "Chiziqli va kvadratik moslashni yonma-yon sinatib ko'ring. Farq ko'rinadi va inson sezgisining chiziqsizligi haqidagi fikr esda qoladi.",
 [("Ko'z yorqinlikni chiziqli sezadimi?", "Yo'q, chiziqsiz — past darajalardagi o'zgarish ko'proq seziladi."),
  ("Bu qanday qonun bilan tushuntiriladi?", "Weber-Fexner qonuni.")],
 "Chiziqli moslashdan tabiiy ko'rinish kutish."),

"RGB LED va rang boshqaruvi": T(
 "Uch PWM pin bilan RGB LEDda 10 ta aniq rang hosil qilib, jadval tuzish",
 ["RGB LEDning uch oyog'i uchta PWM pinga ulanadi (masalan 9, 10, 11), umumiy oyoq GND yoki 5V ga.",
  "Har rangga 0-255 qiymat berilib, 16,7 million tus hosil qilinadi.",
  "Aniq ranglar: sariq (255,255,0), siyan (0,255,255), magenta (255,0,255), to'q sariq (255,128,0), binafsha (128,0,255).",
  "Ranglarni silliq o'zgartirish uchun sikl ishlatiladi: bir rangdan ikkinchisiga har qadamda qiymatlar bosqichma-bosqich yaqinlashadi."],
 "Rang jadvalini o'quvchilar o'zi to'ldirsin — RGB qiymatlarini tanlash grafika va dizayn bilan bog'lanadi va qizg'in ishtiyoq uyg'otadi.",
 [("Sariq rang uchun RGB qiymatlari qanday?", "255, 255, 0."),
  ("RGB LED uchun qanday pinlar kerak?", "Uchta PWM pin.")],
 "Umumiy anod LEDda qiymatlarni teskari qilishni unutish."),

"Fotorezistor bilan yorug'lik o'lchash": T(
 "Fotorezistorli bo'luvchini o'qib, yorug'lik darajalarini o'lchash",
 ["Fotorezistor 10 kOm rezistor bilan bo'luvchiga ulanadi, o'rta nuqta A0 ga boradi.",
  "Fotorezistor yuqorida bo'lsa: yorug'da qiymat katta, qorong'ida kichik. Joyi almashtirilsa aksincha.",
  "Odatiy qiymatlar: to'liq qorong'ida 50-150, xonaki yorug'likda 300-600, chiroq nurida 800-1000.",
  "Bu qiymatlar sinf va sensorga bog'liq — har safar o'lchab, o'z chegarangizni belgilash kerak."],
 "Har juftlik o'z sensori uchun uch nuqtani o'lchab yozsin. Tayyor raqam bermang — kalibrlash ko'nikmasi shu bilan shakllanadi.",
 [("Fotorezistor yuqorida bo'lsa qorong'ida qiymat qanday bo'ladi?", "Kichik."),
  ("Nega tayyor chegara ishlatilmaydi?", "Har sensor va sharoit uchun qiymatlar farq qiladi.")],
 "Boshqa guruhning chegarasini ko'chirib olish."),

"Tungi chiroq avtomati": T(
 "Qorong'ida avtomatik yonadigan, gisterezisli chiroq dasturini yozish",
 ["Oddiy variant: if (yoruglik < 300) LED yoq; else o'chir.",
  "Muammo: chegara atrofida qiymat tebranib, LED miltillay boshlaydi.",
  "Yechim — gisterezis: yoqish uchun bir chegara (300), o'chirish uchun boshqasi (400). Oraliqda holat o'zgarmaydi.",
  "Kod: if (holat == 0 && yoruglik < 300) yoq; if (holat == 1 && yoruglik > 400) o'chir;"],
 "Gisterezissiz variantni avval yozdiring va miltillashni ko'rsating. Muammoni ko'rgandan keyin yechim mantiqiy va yodda qoladi.",
 [("Gisterezis nima uchun kerak?", "Chegara atrofidagi miltillashni yo'q qilish uchun."),
  ("Ikki chegara qanday tanlanadi?", "Yoqish chegarasi o'chirishdan past bo'ladi.")],
 "Bitta chegara ishlatib, miltillashni sensorning nosozligi deb o'ylash."),

"Termistor va harorat hisoblash": T(
 "Termistordan haroratni hisoblab, Serial monitorda gradusda ko'rsatish",
 ["Termistor 10 kOm rezistor bilan bo'luvchiga ulanadi. analogRead qiymatidan qarshilik hisoblanadi.",
  "Qarshilik: R = 10000 x (1023 - qiymat) / qiymat (termistor yuqorida bo'lganda).",
  "Haroratni topish uchun B-parametr formulasi ishlatiladi. Kodda logarifm funksiyasi (log) kerak bo'ladi.",
  "Soddaroq yo'l — kalibrlash jadvali: bir necha ma'lum haroratda qiymat yozib olinadi va oraliq qiymatlar interpolyatsiya qilinadi."],
 "Formula murakkab bo'lgani uchun tayyor kod bering, lekin har qatorini tushuntiring. Maqsad — formulani yodlash emas, qadamlarni tushunish.",
 [("Termistordan haroratga o'tish uchun avval nima hisoblanadi?", "Uning qarshiligi."),
  ("Soddaroq usul qanday?", "Kalibrlash jadvali tuzib, oraliq qiymatlarni interpolyatsiya qilish.")],
 "analogRead qiymatini to'g'ridan-to'g'ri gradus deb qabul qilish."),

"DHT22: raqamli sensor protokoli": T(
 "DHT22 dan harorat va namlikni o'qib, Serial monitorda ko'rsatish",
 ["DHT22 analog emas, RAQAMLI sensor: u o'zi o'lchab, natijani bitta sim orqali raqam sifatida yuboradi.",
  "Bitta ma'lumot pini ishlatiladi va u ikki tomonlama: plata so'rov yuboradi, sensor javob qaytaradi.",
  "Protokol murakkab (impuls uzunligi bilan bit uzatiladi), shuning uchun kutubxona ishlatiladi.",
  "Cheklovi: sekundiga faqat bir marta o'qish mumkin. Tez-tez so'ralsa \"nan\" (raqam emas) qaytaradi."],
 "Analog va raqamli sensor farqini shu misolda mustahkamlang: analogda plata hisoblaydi, raqamlida sensorning o'zi hisoblab beradi.",
 [("DHT22 dan qanchalik tez-tez o'qish mumkin?", "Sekundiga bir marta."),
  ("Nima uchun kutubxona kerak?", "Uzatish protokoli murakkab — impuls uzunligi bilan bit uzatiladi.")],
 "Loop ichida delay'siz o'qishga urinish — natija doim nan chiqadi."),

"Kutubxona (library) ishlatish": T(
 "Ikki kutubxonani o'rnatib, ularning misollari bilan ishlash",
 ["Kutubxona — boshqa dasturchilar yozgan tayyor funksiyalar to'plami. U murakkab ishni bir necha buyruqqa qisqartiradi.",
  "O'rnatish: Sketch > Include Library > Manage Libraries, nom bo'yicha qidirish va Install.",
  "Kodda ulash: #include <DHT.h> — bu qator sketchning eng boshida turadi.",
  "Har kutubxonada misollar bor: File > Examples. Yangi kutubxona bilan ishlashni doim misoldan boshlash kerak."],
 "\"Misoldan boshlash\" qoidasini o'rnating. Hujjatni o'qishdan ko'ra ishlaydigan misolni o'zgartirib borish tezroq va ishonchliroq usul.",
 [("Kutubxona nima?", "Tayyor funksiyalar to'plami."),
  ("Yangi kutubxona bilan ishlashni nimadan boshlash kerak?", "Uning misollaridan.")],
 "#include qatorini funksiya ichiga yozish — u faylning eng boshida bo'lishi kerak."),

"HC-SR04: masofa o'lchash": T(
 "Ultratovush sensori bilan masofani o'lchab, santimetrda ko'rsatish",
 ["HC-SR04 ultratovush impulsi yuboradi va uning qaytishini kutadi. O'tgan vaqtdan masofa hisoblanadi.",
  "Ishlash tartibi: TRIG pinga 10 mikrosekundlik impuls beriladi, keyin ECHO pindagi yuqori darajaning davomiyligi o'lchanadi.",
  "Hisob: masofa (sm) = vaqt (mkrs) x 0,034 / 2. Ikkiga bo'linadi, chunki tovush borib-qaytadi.",
  "Diapazon 2-400 sm. Yumshoq va qiya yuzalar tovushni yaxshi qaytarmaydi — bunda natija noto'g'ri chiqadi."],
 "0,034 koeffitsienti tovush tezligidan (340 m/s) kelib chiqishini ko'rsating. Fizika bilan bog'lanish shu yerda juda tabiiy.",
 [("Nega o'lchangan vaqt ikkiga bo'linadi?", "Tovush nishonagacha borib qaytadi."),
  ("HC-SR04 ning ish diapazoni qanday?", "2 dan 400 santimetrgacha.")],
 "Yumshoq yuzalarda (mato, ko'rpa) o'lchab, sensorni nosoz deb hisoblash."),

"Masofa bo'yicha ogohlantirish tizimi": T(
 "Masofa kamaygan sari tez-tez signal beradigan parkovka radari yozish",
 ["Vazifa: masofa kamaysa, signal chastotasi oshsin. Bu avtomobil parkovka radarining aynan ishlash tamoyili.",
  "Kechikish masofaga proporsional qilinadi: kechikish = map(masofa, 5, 100, 50, 1000).",
  "Juda yaqin masofada (5 sm dan kam) uzluksiz signal beriladi — bu \"to'xta\" degan aniq ishora.",
  "constrain() funksiyasi qiymatni chegaralar ichida ushlab turadi va kutilmagan qiymatlardan himoya qiladi."],
 "Real parkovka radari bilan solishtiring. O'quvchilar mashinada eshitgan tovushni o'zi yaratishi — kuchli motivatsiya.",
 [("Masofa kamayganda signal qanday o'zgaradi?", "Tez-tez beriladi."),
  ("constrain() nima qiladi?", "Qiymatni belgilangan chegaralar ichida ushlaydi.")],
 "map dan chiqqan qiymatni cheklamaslik — masofa diapazondan chiqsa kutilmagan natija bo'ladi."),

"PIR: harakatni aniqlash": T(
 "PIR sensori bilan harakat sezilganda yonadigan chiroq dasturini yozish",
 ["PIR (Passive Infrared) — passiv sensor: u nur chiqarmaydi, faqat issiq jismlardan kelayotgan IK nurlanish O'ZGARISHINI sezadi.",
  "Shuning uchun qimirlamay turgan odamni sezmaydi — faqat harakatga javob beradi.",
  "Modulda ikki potensiometr bor: sezgirlik va ushlab turish vaqti (signal qancha davom etishi).",
  "Yoqilgandan keyin 30-60 sekund \"isinish\" kerak — bu vaqtda yolg'on signallar bo'ladi."],
 "Isinish vaqtini albatta ayting — aks holda o'quvchilar dastlabki yolg'on signallarni nosozlik deb o'ylab, sozlamalarni behuda o'zgartiradi.",
 [("PIR qimirlamay turgan odamni sezadimi?", "Yo'q, u faqat harakatga javob beradi."),
  ("Yoqilgandan keyin qancha vaqt kutish kerak?", "30-60 sekund.")],
 "Modulning ikki potensiometrini bilmasdan burash — sozlamalar chalkashib ketadi."),

"Tuproq namligi sensori": T(
 "Sensorni kalibrlab, sug'orish kerakligini aniqlaydigan dastur yozish",
 ["Sensor tuproq qarshiligini o'lchaydi: nam tuproqda qarshilik kichik, analogRead qiymati past.",
  "Kalibrlash: quruq havoda qiymat (masalan 1023) va suvda qiymat (masalan 300) o'lchanadi. Foizga aylantirish: map(qiymat, 1023, 300, 0, 100).",
  "Har tuproq turi uchun kalibrlash qayta bajariladi.",
  "Sensorga doimiy quvvat berilmaydi: elektroliz elektrodlarni yemiradi. O'lchash paytida quvvat beruvchi pin ishlatiladi."],
 "Quvvatni pin orqali berish g'oyasini ko'rsating: digitalWrite(quvvatPin, HIGH), o'lchash, LOW. Bu oddiy usul sensor umrini bir necha barobar uzaytiradi.",
 [("Nam tuproqda analogRead qiymati qanday bo'ladi?", "Past."),
  ("Sensor umrini qanday uzaytirish mumkin?", "Faqat o'lchash paytida quvvat berib.")],
 "Sensorni doimiy 5 V ga ulab qoldirish — bir necha haftada korroziyadan ishdan chiqadi."),

"Suv va olov datchiklari": T(
 "Ikki datchikni sinab, xavfsizlik tizimi maketini yig'ish",
 ["Suv datchigi qarshilik tamoyilida: suv yo'laklarni tutashtirgan sari qiymat o'zgaradi.",
  "Olov datchigi IK nurlanishni sezadi. Ko'rish burchagi 60 daraja, masofa 20-100 sm.",
  "Ikkalasi ham yolg'on ishga tushishi mumkin: suv datchigi namlikdan, olov datchigi quyosh yoki lampadan.",
  "Ishonchli tizimda ikki sensor birga ishlatiladi va faqat ikkalasi tasdiqlasa signal beriladi — bu yolg'on signalni keskin kamaytiradi."],
 "Ikki sensorni birga ishlatish g'oyasi (sensor fusion) muhim — buni sodda shaklda hozir kiritsangiz, 8-sinfdagi AI mavzularida tayyor tushuncha bo'ladi.",
 [("Nega ikki sensor birga ishlatiladi?", "Yolg'on signallarni kamaytirish uchun."),
  ("Olov datchigi nimadan yolg'on ishga tushadi?", "Quyosh va lampa nuridan.")],
 "Bitta sensorga to'liq ishonib, xavfsizlik tizimini shunga qurish."),

"O'z funksiyangni yozish": T(
 "Takrorlanadigan kodni funksiyaga chiqarib, dasturni qisqartirish",
 ["Funksiya — nom berilgan kod bo'lagi. U bir marta yoziladi va kerakli joyda nomi bilan chaqiriladi.",
  "E'lon: void miltilla(int pin, int vaqt) { ... } — void qaytaruvchi qiymat yo'qligini bildiradi.",
  "Parametrlar funksiyaga ma'lumot uzatadi. Chaqirish: miltilla(9, 500);",
  "Qiymat qaytaruvchi funksiya: int yigindi(int a, int b) { return a + b; }"],
 "Funksiyaga chiqarishdan oldin va keyingi kodni solishtiring. Takrorlanishning yo'qolishi — dasturlashning asosiy tamoyillaridan biri (DRY).",
 [("void nimani bildiradi?", "Funksiya qiymat qaytarmasligini."),
  ("Parametr nima uchun kerak?", "Funksiyaga ma'lumot uzatish uchun.")],
 "Funksiyani loop ichida e'lon qilishga urinish — u loop dan tashqarida yozilishi kerak."),

"Massiv (array) bilan ishlash": T(
 "LED pinlarini massivga yig'ib, sikl bilan boshqarish",
 ["Massiv — bir turdagi qiymatlar to'plami, bitta nom ostida saqlanadi.",
  "E'lon: int pinlar[5] = {2, 3, 4, 5, 6};",
  "Elementga murojaat indeks bilan: pinlar[0] birinchi element (2), pinlar[4] beshinchi (6). Indeks NOLDAN boshlanadi.",
  "Massiv va sikl birga juda kuchli: for (int i = 0; i < 5; i++) digitalWrite(pinlar[i], HIGH);"],
 "Indeksning noldan boshlanishi eng ko'p xato manbai. \"Beshta element bo'lsa indekslar 0 dan 4 gacha\" ni doskaga yozib qo'ying.",
 [("5 elementli massivda indekslar qanday?", "0 dan 4 gacha."),
  ("pinlar[2] qaysi elementni beradi?", "Uchinchisini.")],
 "Massiv chegarasidan chiqish (pinlar[5]) — bu kutilmagan qiymat beradi va dastur beqaror ishlaydi."),

# ==================================================== 4-CHORAK: Ijro qurilmalari va ekran
"Servo motorni boshqarish": T(
 "Servoni Servo kutubxonasi bilan turli burchaklarga burish",
 ["Servo kutubxonasi ishlatiladi: #include <Servo.h>, keyin Servo s; va setup ichida s.attach(9);",
  "Burish: s.write(burchak) — burchak 0 dan 180 gacha.",
  "Servo burilishga vaqt kerak: 60 daraja uchun 0,1-0,2 sekund. Shuning uchun buyruqdan keyin delay qo'yiladi.",
  "Servo alohida 5 V manbadan quvvatlantiriladi (500 mA gacha oladi), GND esa Arduino bilan umumiy bo'lishi shart."],
 "Alohida quvvat va umumiy GND qoidasini har servo darsida takrorlang. Arduino'dan quvvatlantirilgan servo platani qayta yuklashga majbur qiladi.",
 [("Servo qanday burchak oralig'ida ishlaydi?", "0 dan 180 gradusgacha."),
  ("Servo quvvatini qayerdan olish kerak?", "Alohida 5 V manbadan, GND umumiy bo'lgan holda.")],
 "Servoni Arduino 5V pinidan quvvatlantirish — plata qayta yuklanadi."),

"Servo va potensiometr birgalikda": T(
 "Potensiometr bilan servoni real vaqtda boshqarish",
 ["Kod: qiymat = analogRead(A0); burchak = map(qiymat, 0, 1023, 0, 180); s.write(burchak);",
  "Bu \"ochiq halqali boshqaruv\" — plata servo haqiqatan burilganini bilmaydi, faqat buyruq beradi.",
  "Servo o'z ichida esa yopiq halqali boshqaruv ishlatadi: potensiometri holatni o'lchab, xatoni tuzatadi.",
  "Silkinishni kamaytirish uchun kichik o'zgarishlarni e'tiborsiz qoldirish mumkin: agar yangi burchak eskisidan 2 darajadan kam farq qilsa, buyruq bermaslik."],
 "Ochiq va yopiq halqali boshqaruv farqini shu misolda ko'rsating — bu robototexnikaning asosiy tushunchalaridan biri.",
 [("Servo ichida qanday boshqaruv ishlatiladi?", "Yopiq halqali — holatni o'lchab, xatoni tuzatadi."),
  ("Silkinishni qanday kamaytirish mumkin?", "Juda kichik o'zgarishlarga buyruq bermaslik bilan.")],
 "Har loop siklida yangi burchak berish — servo tinimsiz silkinadi."),

"DC motorni tranzistor orqali yurgizish": T(
 "MOSFET yoki tranzistor bilan motor tezligini PWM orqali boshqarish",
 ["Sxema: Arduino pini -> baza rezistori -> tranzistor bazasi; motor kollektor va manba orasida; flyback diod motorga parallel.",
  "PWM bilan tezlik boshqariladi: analogWrite(pin, 0-255).",
  "Past PWM qiymatlarida motor aylanmasligi mumkin — start uchun ma'lum minimal kuchlanish kerak. Bu \"o'lik zona\" deb ataladi.",
  "Yechim: start uchun qisqa vaqtga to'liq quvvat berib, keyin kerakli darajaga tushirish."],
 "O'lik zonani o'lchatib toping: PWM ni 0 dan asta oshirib, motor qaysi qiymatda aylana boshlashini yozib oling. Har motorda bu qiymat har xil.",
 [("Nega past PWM da motor aylanmaydi?", "Start uchun minimal kuchlanish kerak."),
  ("Motorli sxemada qaysi himoya elementi majburiy?", "Flyback diod.")],
 "Motorni pinning o'ziga ulash — pin darhol kuyadi."),

"L298N bilan motor boshqaruvi": T(
 "L298N drayveri bilan motorni ikki yo'nalishda va tezlik bilan boshqarish",
 ["L298N — ikki kanalli H-ko'prik drayveri. Har kanal uchun uch pin: IN1, IN2 (yo'nalish) va ENA (tezlik, PWM).",
  "Yo'nalish: IN1 HIGH, IN2 LOW — oldinga; teskarisi — orqaga; ikkalasi bir xil — to'xtash (tormoz).",
  "ENA piniga analogWrite bilan tezlik beriladi. Jamper qo'yilgan bo'lsa u doim to'liq tezlikda ishlaydi — tezlik boshqarish uchun jamper olinadi.",
  "L298N eskirgan texnologiya: unda 1,5-2 V yo'qoladi va u qiziydi. Zamonaviy alternativa — DRV8833 yoki TB6612FNG."],
 "L298N ning kuchlanish yo'qotishini o'lchab ko'rsating: 12 V bersa motorga 10 V yetadi. Bu komponent tanlashning amaliy oqibati.",
 [("L298N da yo'nalish qanday belgilanadi?", "IN1 va IN2 pinlarining holati bilan."),
  ("ENA pini nima uchun?", "PWM bilan tezlikni boshqarish uchun.")],
 "ENA jamperini olib tashlamay, tezlikni boshqarmoqchi bo'lish."),

"Ikki motorli shassi: oldinga, orqaga, burilish": T(
 "Ikki motorli aravachani to'rt yo'nalishda harakatlantiruvchi dastur yozish",
 ["Ikki motorli (differensial) shassida burilish motorlarning turli tezligi hisobiga bo'ladi.",
  "Oldinga: ikkala motor bir xil tezlikda oldinga. Orqaga: ikkalasi orqaga.",
  "O'ngga burilish: chap motor tez, o'ng sekin. Joyida burilish: motorlar qarama-qarshi yo'nalishda.",
  "Amalda motorlar bir xil bo'lmaydi: bir xil PWM da biri tezroq aylanadi va aravacha qiyshayadi. Buni tuzatish uchun koeffitsient kiritiladi."],
 "Motorlarning tabiiy farqini o'lchatib toping va tuzatish koeffitsientini har guruh o'zi tanlasin. Bu real muhandislik masalasi.",
 [("Differensial shassida burilish qanday bo'ladi?", "Motorlarning turli tezligi hisobiga."),
  ("Nega aravacha to'g'ri yurmaydi?", "Motorlar bir xil emas, tuzatish koeffitsienti kerak.")],
 "Ikki motorga bir xil PWM berib, to'g'ri yurishni kutish."),

"Qadamli motor 28BYJ-48": T(
 "ULN2003 drayveri bilan qadamli motorni aniq burchaklarga burish",
 ["28BYJ-48 ULN2003 drayveri bilan ishlaydi: to'rt pin (IN1-IN4) Arduino'ga ulanadi.",
  "Stepper kutubxonasi ishlatiladi: #include <Stepper.h>, Stepper motor(2048, 8, 10, 9, 11);",
  "Diqqat: pinlar tartibi 8, 10, 9, 11 — bu ataylab shunday, chunki motorning fazalar tartibi shunday.",
  "Bir to'liq aylanish 2048 qadam. 90 daraja uchun 512 qadam. Aniqlik yuqori, lekin tezlik past."],
 "Pinlar tartibining g'alati ekanini ta'kidlang — o'quvchilar buni xato deb o'ylab \"tuzatib\" qo'yadi va motor ishlamay qoladi.",
 [("28BYJ-48 uchun to'liq aylanish necha qadam?", "2048."),
  ("Qadamli motorning asosiy afzalligi nima?", "Datchiksiz aniq holatni bilish mumkin.")],
 "Stepper kutubxonasida pinlar tartibini o'zgartirish — motor silkinadi, lekin aylanmaydi."),

"Passiv zummer va nota chastotalari": T(
 "tone() funksiyasi bilan notalarni chalish va gamma yaratish",
 ["tone(pin, chastota) — belgilangan chastotada tovush chiqaradi. noTone(pin) to'xtatadi.",
  "tone(pin, chastota, davomiylik) — uchinchi parametr bilan davomiylik millisekundda beriladi.",
  "Nota chastotalari: DO 262, RE 294, MI 330, FA 349, SOL 392, LYA 440, SI 494, yuqori DO 523 Hz.",
  "Cheklov: tone() Timer2 ni ishlatadi, shuning uchun 3 va 11-pinlarda PWM bilan to'qnashadi."],
 "Timer to'qnashuvi haqidagi cheklovni ayting — bu keyinchalik zummer va servo birga ishlatilganda muammo yaratadi va sababini bilish kerak.",
 [("tone() ning uchinchi parametri nima?", "Tovush davomiyligi millisekundda."),
  ("LYA notasi qaysi chastotada?", "440 Hz.")],
 "tone() bilan 3 yoki 11-pinda PWM ishlatishga urinish — ular bir-biriga xalaqit qiladi."),

"Melodiya chalish (massiv bilan)": T(
 "Nota va davomiyliklar massivi bilan qisqa melodiya chalish",
 ["Melodiya ikki massivda saqlanadi: notalar (chastotalar) va davomiyliklar.",
  "Chalish sikli: for bilan har notani navbat bilan tone() ga berish, davomiylikcha kutish, keyin qisqa pauza.",
  "Nota orasidagi pauza muhim: pauzasiz notalar bir-biriga qo'shilib ketadi. Odatda davomiylikning 30% i qo'shiladi.",
  "Pauza (jimlik) uchun chastota 0 beriladi yoki noTone() ishlatiladi."],
 "Tanish melodiyani (masalan \"Bahor keldi\" yoki maktab qo'ng'irog'i) tanlang. Tanish ohangni o'zi chalgan qurilma o'quvchi uchun katta yutuq.",
 [("Melodiya uchun nechta massiv kerak?", "Ikkita — notalar va davomiyliklar."),
  ("Notalar orasida pauza nima uchun kerak?", "Ular bir-biriga qo'shilib ketmasligi uchun.")],
 "Ikki massivning uzunligini teng qilmaslik — dastur massiv chegarasidan chiqadi."),

"LCD 1602 ni ulash": T(
 "LCD 1602 ni I2C moduli bilan ulab, birinchi matnni chiqarish",
 ["LCD 1602 — 2 qator, har qatorda 16 belgi. To'g'ridan-to'g'ri ulanish 6-7 pin talab qiladi.",
  "I2C moduli (PCF8574) bilan faqat 4 sim yetadi: VCC, GND, SDA, SCL. Arduino Uno da SDA = A4, SCL = A5.",
  "Kutubxona: LiquidCrystal_I2C. Manzil odatda 0x27 yoki 0x3F — I2C skaner dasturi bilan aniqlanadi.",
  "Kontrast potensiometr bilan sozlanadi. Ekran yonib turgan, lekin matn ko'rinmasa — birinchi navbatda kontrastni buraش kerak."],
 "Kontrast muammosini oldindan ayting: yangi ekranda matn ko'rinmasligi juda ko'p uchraydi va o'quvchilar ekranni nosoz deb o'ylaydi.",
 [("I2C ulanishida nechta sim kerak?", "To'rtta: VCC, GND, SDA, SCL."),
  ("Matn ko'rinmasa birinchi nima tekshiriladi?", "Kontrast potensiometri.")],
 "I2C manzilini tekshirmasdan tayyor kodni ishlatish — ekran hech narsa ko'rsatmaydi."),

"LCD ekranga matn chiqarish": T(
 "Ekranga o'zgaruvchan matn va raqamlarni chiqarish, kursor bilan ishlash",
 ["lcd.setCursor(ustun, qator) — kursorni belgilangan joyga qo'yadi. Ustun 0-15, qator 0-1.",
  "lcd.print(matn) — kursor turgan joydan boshlab yozadi. lcd.clear() ekranni tozalaydi.",
  "Muammo: eski matn ustiga qisqaroq yangi matn yozilsa, eski matnning qolgan qismi ko'rinib turadi (masalan 100 dan 99 ga o'tganda \"990\").",
  "Yechim: yangi qiymatdan keyin bo'sh joy yozish (lcd.print(\"  \")) yoki har safar clear() qilish."],
 "\"990\" muammosini ataylab ko'rsating — bu klassik xato va uni bir marta ko'rgan o'quvchi doim eslab qoladi.",
 [("lcd.setCursor(0, 1) kursorni qayerga qo'yadi?", "Ikkinchi qatorning boshiga."),
  ("Nega raqam noto'g'ri ko'rinadi?", "Eski matnning qolgan qismi tozalanmagan.")],
 "Har loop siklida clear() qilish — ekran miltillaydi."),

"I2C protokoli va 2 simli ulanish": T(
 "I2C skaner bilan shinadagi qurilmalarni topib, bir necha modulni birga ulash",
 ["I2C ikki sim ishlatadi: SDA (ma'lumot) va SCL (sinxronizatsiya). Ikkalasiga tortuvchi rezistor kerak (modullarda odatda o'rnatilgan).",
  "Har qurilmaning o'z MANZILI bor (7 bit, 0x00-0x7F). Bir shinada 100 dan ortiq qurilma bo'lishi mumkin.",
  "Bir xil manzilli ikki qurilmani bir shinaga ulash mumkin emas — konflikt bo'ladi. Ko'p modullarda manzilni jamper bilan o'zgartirish mumkin.",
  "I2C skaner dasturi shinadagi barcha qurilmalarni topib, manzillarini ko'rsatadi. Yangi modul bilan ishlashni doim shundan boshlash kerak."],
 "I2C skanerni har o'quvchining kompyuteriga saqlab qo'ying. Bu keyingi barcha I2C modullarida birinchi qadam bo'ladi.",
 [("I2C nechta sim ishlatadi?", "Ikkita: SDA va SCL."),
  ("Bir xil manzilli ikki qurilma ulansa nima bo'ladi?", "Konflikt — ikkalasi ham ishlamaydi.")],
 "Manzilni tekshirmasdan bir necha modulni birga ulash."),

"LCD + sensor: jonli ko'rsatkich": T(
 "Sensor qiymatini LCD ekranda real vaqtda ko'rsatuvchi qurilma yig'ish",
 ["Bu birinchi to'liq qurilma: sensor (kirish) + qayta ishlash + ekran (chiqish).",
  "Ekranni har loop siklida yangilash kerak emas — bu miltillash va keraksiz yuk beradi. 500 ms da bir marta yetarli.",
  "Yangilash vaqtini millis() bilan boshqarish: agar millis() - oxirgiVaqt > 500 bo'lsa yangilash.",
  "Ekran maketi oldindan qog'ozda chiziladi: qaysi ma'lumot qayerda turishi. 16x2 juda kichik va joyni rejalash kerak."],
 "Ekran maketini qog'ozda 16x2 katakcha chizib rejalashtiring. Bu foydalanuvchi interfeysi dizaynining eng sodda shakli.",
 [("Ekranni qanchalik tez-tez yangilash kerak?", "500 ms da bir marta yetarli."),
  ("Yangilash vaqtini nima bilan boshqariladi?", "millis() bilan.")],
 "Har loop siklida clear va print qilish — ekran miltillaydi va o'qib bo'lmaydi."),

"7-segment indikatorni boshqarish": T(
 "Bitta razryadli indikatorda 0-9 raqamlarini ko'rsatish",
 ["Har segment o'z piniga ulanadi (7 pin + rezistorlar). Raqamlar segment kombinatsiyalari bilan hosil qilinadi.",
  "Kombinatsiyalar massivda saqlanadi: har raqam uchun 7 ta 0/1 qiymat. Masalan 1 raqami uchun faqat b va c segmentlari.",
  "Kod: raqamni indeks sifatida ishlatib, massivdan segment holatlarini olib, sikl bilan pinlarga yozish.",
  "Ko'p pin talab qilishi asosiy kamchilik. Yechim — 74HC595 siljish registri, bu keyingi dars mavzusi."],
 "Pinlar yetishmasligi muammosini his qildiring — 7 pin ketgach, sensor uchun joy qolmaydi. Keyingi darsdagi 74HC595 shunda yechim bo'lib ko'rinadi.",
 [("Bir razryadli indikator uchun nechta pin kerak?", "Yettita (nuqta bilan sakkizta)."),
  ("Raqam kombinatsiyalari qayerda saqlanadi?", "Massivda.")],
 "Har segmentga rezistor qo'ymay, bitta umumiy rezistor ishlatish."),

"74HC595: 3 pin bilan 8 chiqish": T(
 "Siljish registri bilan 8 LEDni uch pin orqali boshqarish",
 ["74HC595 — siljish registri: ma'lumot ketma-ket kiritiladi, parallel chiqadi.",
  "Uch pin kerak: DS (ma'lumot), SHCP (siljish taktlari), STCP (chiqishga o'tkazish).",
  "shiftOut(dataPin, clockPin, MSBFIRST, qiymat) — bitta bayt (8 bit) yuboradi. Keyin STCP ga impuls berilib, natija chiqishlarga o'tadi.",
  "Registrlarni ketma-ket ulash mumkin: bittasining Q7' chiqishi keyingisining DS kirishiga. Shu bilan 3 pin bilan 16, 24 va undan ko'p chiqish olinadi."],
 "Ketma-ket ulash imkoniyatini ko'rsating — 3 pin bilan 100 ta LEDni boshqarish mumkinligi o'quvchilarni hayratlantiradi.",
 [("74HC595 uchun nechta pin kerak?", "Uchta."),
  ("Registrlarni ketma-ket ulash nima beradi?", "Bir xil 3 pin bilan ko'proq chiqish.")],
 "STCP ga impuls berishni unutish — chiqishlar yangilanmaydi."),

"IR pult bilan masofadan boshqarish": T(
 "IR qabul qiluvchi bilan pult tugmalarini tanib, qurilmani boshqarish",
 ["IR pult har tugma uchun o'z kodini infraqizil nur orqali yuboradi. Qabul qiluvchi (VS1838) uni raqamli signalga aylantiradi.",
  "IRremote kutubxonasi ishlatiladi. Avval har tugmaning kodi o'qib olinadi va Serial monitorda yozib olinadi.",
  "Kodlar pultga bog'liq — har pultning kodlari boshqacha. Shuning uchun avval o'z pultingizni \"o'rganish\" kerak.",
  "Uzatish masofasi 5-8 metr, lekin to'g'ridan-to'g'ri ko'rinish kerak. Quyosh nuri va lyuminessent lampalar xalaqit berishi mumkin."],
 "Kodlarni o'qish bosqichini alohida dars qismi qiling. Har juftlik o'z pultining kodlar jadvalini tuzsin — bu keyingi ishda kerak bo'ladi.",
 [("Pult kodlari barcha pultlarda bir xilmi?", "Yo'q, har pultda o'ziga xos."),
  ("Kodlarni qanday bilib olinadi?", "Serial monitorda o'qib, jadval tuzib.")],
 "Boshqa pultning kodlarini ishlatish — hech qanday tugma ishlamaydi."),

"Rele orqali qurilma yoqish": T(
 "Rele moduli bilan alohida manbali yuklamani dasturdan boshqarish",
 ["Rele moduli uch pinli: VCC, GND va IN (boshqaruv). Modulda tranzistor, diod va optopara allaqachon bor.",
  "Ko'p modullar TESKARI mantiqda ishlaydi: IN ga LOW berilganda rele yoqiladi. Buni sinab aniqlash kerak.",
  "Yuklama COM va NO kontaktlariga ulanadi. Rele yoqilganda ular tutashadi.",
  "Sinfda maksimal 12 V yuklama ishlatiladi. 220 V bilan ishlash faqat o'qituvchi namoyishida."],
 "Teskari mantiqni oldindan sinab, sinfga aytib qo'ying. Aks holda dastur to'g'ri yozilgan bo'lsa ham natija teskari bo'ladi va sabab uzoq izlanadi.",
 [("Ko'p rele modullarida rele qachon yoqiladi?", "IN ga LOW berilganda."),
  ("Yuklama qaysi kontaktlarga ulanadi?", "COM va NO ga.")],
 "Rele modulining teskari mantiqini hisobga olmaslik."),

"Loyihani rejalashtirish va bosqichlarga bo'lish": T(
 "Chorak loyihasi uchun texnik topshiriq, blok-sxema va bosqichlar rejasini tuzish",
 ["Loyihani bosqichlarga bo'lish — har bosqich MUSTAQIL sinaladigan bo'lishi kerak.",
  "Misol: aqlli uy maketi uchun bosqichlar — 1) sensor o'qish, 2) ekranga chiqarish, 3) rele boshqarish, 4) pult qo'shish, 5) korpus.",
  "Har bosqich tugagach kod saqlanadi (nusxa olinadi). Keyingi bosqichda muammo chiqsa, ishlaydigan versiyaga qaytish mumkin.",
  "Vaqt taqsimoti: rejalashtirishga 20%, yig'ish va dasturlashga 50%, sinash va tuzatishga 30%. Sinovga vaqt qoldirmaslik eng ko'p uchraydigan xato."],
 "Har bosqichda kod nusxasini saqlash odatini o'rnating (loyiha1_v1, loyiha1_v2). Bu versiya nazoratining eng sodda shakli va o'quvchilarni ko'p muammodan qutqaradi.",
 [("Bosqichlar qanday bo'lishi kerak?", "Har biri mustaqil sinaladigan."),
  ("Vaqtning qancha qismi sinovga ajratiladi?", "Taxminan 30%.")],
 "Hammasini birdan yig'ib, sinovga vaqt qoldirmaslik."),

"Sxema va kodni hujjatlashtirish": T(
 "Loyiha uchun to'liq hujjat tayyorlash: sxema, komponentlar ro'yxati, izohli kod",
 ["Hujjat uch qismdan iborat: sxema, komponentlar ro'yxati (BOM) va izohli kod.",
  "BOM (Bill of Materials) jadvali: nomi, nominali, soni, izoh. Bu ro'yxat bilan qurilmani boshqa odam takrorlay oladi.",
  "Kodda izoh yozish qoidasi: NIMA qilayotganini emas, NEGA shunday qilinganini yozish. \"i ni bittaga oshiradi\" foydasiz izoh.",
  "Yaxshi hujjatning mezoni: boshqa odam faqat hujjatga qarab qurilmani takrorlay olishi."],
 "\"Boshqa odam takrorlay oladimi?\" mezonini qo'ying va o'quvchilar hujjatlarini almashib, bir-birining qurilmasini yig'ishga urinsin. Bu sinov juda ta'sirchan.",
 [("BOM nima?", "Komponentlar ro'yxati jadvali."),
  ("Kodda izoh nimani yozishi kerak?", "Nima emas, NEGA shunday qilinganini.")],
 "Har qatorga foydasiz izoh yozish va muhim qarorlarni tushuntirmaslik."),
}
