# -*- coding: utf-8 -*-
"""2-yil, 5-sinf — elektronika takrorlash + blokli dasturlash (mBlock)."""

from kb_5_8 import T

MAVZULAR = {

# ==================================================== 1-CHORAK: Elektronikani eslash va kengaytirish
"Zanjir, tok, kuchlanish: takrorlash": T(
 "O'tgan yildagi uchta asosiy zanjirni xotiradan yig'ib, o'lchash",
 ["Zanjir uch qismdan iborat: manba, iste'molchi, ulovchi simlar. Tok faqat yopiq zanjirda yuradi.",
  "Tok (A) — zaryad oqimi, kuchlanish (V) — zaryadni harakatlantiruvchi bosim, qarshilik (Om) — oqimga to'sqinlik.",
  "Kuchlanish doim IKKI nuqta orasida o'lchanadi. Tok esa zanjirni uzib, ketma-ket o'lchanadi.",
  "LED har doim rezistor bilan ulanadi — 5 V uchun 220 Om."],
 "Bu takrorlash darsi, yangi material bermang. O'quvchilar o'tgan yildagi bilimni QO'LDAN chiqarmaganini tekshirish va bo'shliqlarni to'ldirish maqsad.",
 [("Tok qanday zanjirda yuradi?", "Faqat yopiq zanjirda."),
  ("5 V da LED uchun qanday rezistor olinadi?", "220 Om.")],
 "Yozgi tanaffusdan keyin rezistorni unutish — LED darhol kuyadi."),

"Multimetr bilan o'lchashni eslash": T(
 "Uch rejimda o'lchov o'tkazib, protokol jadvalini to'ldirish",
 ["Kuchlanish — parallel, komponentning ikki oyog'iga. Qarshilik — quvvatsiz va uzilgan holda. Tok — ketma-ket.",
  "Qora shchup doim COM da, qizil esa rejimga qarab V/Om yoki A teshigida.",
  "Zumlash rejimi ulanishni tekshiradi — uzilgan simni topishning eng tez usuli.",
  "Eng qimmat xato: tok teshigidagi shchup bilan kuchlanish o'lchash — predoxranitel kuyadi."],
 "O'lchov ko'nikmasi tanaffusdan keyin unutiladi. Har uch rejimni har bir o'quvchi bajarib ko'rsin, kuzatib turing.",
 [("Tok qanday ulanish bilan o'lchanadi?", "Ketma-ket."),
  ("Zumlash nima uchun ishlatiladi?", "Ulanish bor-yo'qligini tekshirish uchun.")],
 "Shchupni tok teshigida qoldirib, keyin kuchlanish o'lchash."),

"Om qonuni: mashqlar": T(
 "10 ta masalani yechib, uchtasini o'lchov bilan tekshirish",
 ["U = I x R, I = U / R, R = U / I. Quvvat: P = U x I.",
  "Amaliy qisqartma: V / kOm = mA. 5 V / 1 kOm = 5 mA.",
  "Birliklarni bir tizimga keltirish shart: mA ni A ga (1000 ga bo'lish), kOm ni Om ga (1000 ga ko'paytirish).",
  "Javob tekshiriladi: birlik to'g'rimi, qiymat realmi. 5 V zanjirda 3 A tok chiqsa — xato bor."],
 "Hisoblash mashqlarini matematika darsi bilan bog'lang — proporsiya va formuladan foydalanish shu yerda amaliy ma'no oladi.",
 [("6 V va 300 Om: tok qancha?", "20 mA."),
  ("V / kOm nima beradi?", "Milliamperni.")],
 "mA va A ni aralashtirish."),

"Kuchlanish bo'luvchi va potensiometr": T(
 "Bo'luvchi yig'ib hisoblash, keyin potensiometr bilan silliq sozlashni sinash",
 ["Bo'luvchi: U chiqish = U kirish x R2 / (R1 + R2), R2 — GND ga ulangan pastki rezistor.",
  "Potensiometr — sozlanadigan bo'luvchi. Uchala oyog'i ishlatiladi: chetkilari manba va GND ga, o'rtasi chiqish.",
  "Bo'luvchidan katta tok olinmaydi — u faqat signal berish uchun.",
  "Bu sxema chorakning ikkinchi yarmida analog kirish bilan ishlashda kerak bo'ladi."],
 "Potensiometr blokli dasturlashda birinchi analog kirish bo'ladi — buni oldindan aytib, bog'lanishni ko'rsating.",
 [("Bo'luvchi formulasida R2 qaysi rezistor?", "GND ga ulangan pastki rezistor."),
  ("Potensiometrning nechta oyog'i ishlatiladi?", "Uchtasi ham.")],
 "Faqat ikki oyoqni ulab, kuchlanish o'zgarmasligidan hayron bo'lish."),

"Tranzistor kalit: takrorlash va mustahkamlash": T(
 "Tranzistorli kalit yig'ib, baza rezistorini hisoblash va to'yinishni tekshirish",
 ["Tranzistorning uch oyog'i: baza, kollektor, emitter. Bazadagi kichik tok kollektor tokini boshqaradi.",
  "Baza rezistori majburiy — odatda 1 kOm. Usiz tranzistor kuyadi.",
  "To'yingan tranzistorda kollektor-emitter kuchlanishi 0,2 V. 2-3 V bo'lsa u oraliq holatda va qiziydi.",
  "Nima uchun kerak: mikrokontroller pini 20 mA beradi, motor esa 200 mA oladi. Tranzistor shu farqni to'ldiradi."],
 "\"Nima uchun kerak\" savoliga mikrokontroller pinining cheklovi orqali javob bering — bu chorakda Arduino kirganda darhol amaliy ma'no oladi.",
 [("Baza rezistori nima uchun kerak?", "Baza tokini cheklash va tranzistorni saqlash uchun."),
  ("To'yingan tranzistorda kollektor-emitter kuchlanishi qancha?", "0,2 V atrofida.")],
 "Baza rezistorini qo'ymaslik."),

"Kondensator va vaqt": T(
 "RC zanjir yig'ib, so'nish vaqtini o'lchab, T = R x C bilan solishtirish",
 ["Kondensator zaryad to'playdi. Vaqt doimiysi T = R x C.",
  "Qulay shakl: kOm x uF = ms. 10 kOm x 100 uF = 1000 ms = 1 sekund.",
  "Bir T da 63%, besh T da 99% ga zaryadlanadi.",
  "Elektrolitik kondensator qutbli: kalta oyoq manfiy. Teskari ulansa shishadi."],
 "kOm x uF = ms qoidasini doskaga yozing — bu hisobni juda tezlashtiradi va nol xatolarini yo'q qiladi.",
 [("10 kOm va 47 uF uchun T qancha?", "470 ms."),
  ("Elektrolitik kondensatorda kalta oyoq qaysi qutb?", "Manfiy.")],
 "Elektrolitikni teskari ulash."),

"Rele bilan boshqarish": T(
 "Rele orqali alohida manbali yuklamani tugma bilan boshqarish",
 ["Rele — elektromagnit kalit: g'altakdan tok o'tsa kontakt tutashadi.",
  "Asosiy afzalligi: boshqaruv (5 V) va yuklama (12 V) zanjirlari elektr jihatdan ajratilgan.",
  "Kontaktlar: COM (umumiy), NO (odatda ochiq), NC (odatda yopiq).",
  "G'altakka parallel flyback diod MAJBURIY — o'chganda hosil bo'ladigan yuqori kuchlanish impulsi tranzistorni kuydiradi."],
 "Rele modullarida diod va tranzistor allaqachon o'rnatilganini ko'rsating — modul va alohida komponent farqi shu yerda ko'rinadi.",
 [("Rele nimani ajratadi?", "Boshqaruv va yuklama zanjirlarini."),
  ("Flyback diod nima uchun kerak?", "G'altak o'chganda hosil bo'ladigan impulsni yo'q qilish uchun.")],
 "Flyback diodni unutish."),

"Ikki sensorli avtomat": T(
 "Yorug'lik va harorat sensorlarini birga ulab, ikki shartli avtomat yig'ish",
 ["Ikki sensor ketma-ket ulansa VA mantiqi, parallel ulansa YOKI mantiqi hosil bo'ladi.",
  "Har sensorning chegarasi ALOHIDA sozlanadi, aks holda biri ikkinchisining ta'sirini bekor qiladi.",
  "Sezish - qaror - ijro tuzilmasi: sensor sezadi, tranzistor qaror qabul qiladi, LED yoki rele bajaradi.",
  "Dasturlash bilan bu mantiqni o'zgartirish osonlashadi — sxemani qayta yig'ish kerak bo'lmaydi. Bu chorakning asosiy g'oyasi."],
 "Apparat mantiq va dasturiy mantiq farqiga urg'u bering: sxemada mantiqni o'zgartirish uchun simni qayta ulash kerak, dasturda esa bitta blokni almashtirish yetadi.",
 [("Ikki sensor ketma-ket ulansa qaysi mantiq hosil bo'ladi?", "VA."),
  ("Dasturiy mantiqning afzalligi nima?", "O'zgartirish uchun sxemani qayta yig'ish kerak emas.")],
 "Chegaralarni sozlamasdan qoldirish."),

"Mikrokontroller nima: yangi tushuncha": T(
 "Tranzistorli avtomat va mikrokontrollerli yechimni yonma-yon solishtirish",
 ["Mikrokontroller — bitta mikrosxemadagi kichik kompyuter: protsessor, xotira va kirish-chiqish pinlari.",
  "Farqi: oddiy zanjirda mantiq SIMLAR bilan belgilanadi, mikrokontrollerda esa DASTUR bilan.",
  "Shuning uchun bir xil apparat bilan butunlay boshqa vazifani bajarish mumkin — faqat dasturni almashtirish yetadi.",
  "Mikrokontroller uy jihozlarining deyarli hammasida bor: mikroto'lqinli pech, kir yuvish mashinasi, pult, o'yinchoq."],
 "Bitta apparat + turli dastur = turli qurilma g'oyasi bu chorakning asosiy kashfiyoti. Uni bitta plataga ikki xil dastur yuklab ko'rsatib bering.",
 [("Mikrokontrollerda mantiq nima bilan belgilanadi?", "Dastur bilan."),
  ("Oddiy zanjirda-chi?", "Simlar va komponentlarning ulanishi bilan.")],
 "Mikrokontrollerni oddiy komponent deb hisoblash — u dastursiz hech narsa qilmaydi."),

"Arduino platasi bilan tanishuv": T(
 "Platani ko'rib chiqib, qismlarini nomlab, xaritasini chizish",
 ["Arduino Uno platasidagi qismlar: mikrokontroller (katta mikrosxema), USB port, quvvat razyomi, reset tugmasi, pin razyomlari.",
  "Plata o'zi hech narsa qilmaydi — u faqat mikrokontrollerni qulay ishlatish uchun tayyorlangan asos.",
  "USB port ikki vazifani bajaradi: dastur yuklaydi va quvvat beradi.",
  "Reset tugmasi dasturni boshidan ishga tushiradi (setup dan)."],
 "Platani qo'lga olib ko'rish va qismlarni ko'rsatish uchun vaqt bering. Jismoniy tanishuv keyingi mavhum tushunchalarga asos bo'ladi.",
 [("USB port nechta vazifani bajaradi?", "Ikkita: dastur yuklash va quvvat berish."),
  ("Reset tugmasi nima qiladi?", "Dasturni boshidan ishga tushiradi.")],
 "Platani dastursiz ishlashini kutish."),

"Plataning pinlari va ularning vazifasi": T(
 "Pin xaritasini chizib, har guruhning vazifasini yozish",
 ["Raqamli pinlar D0-D13: faqat ikki holat — yoqiq (5 V) yoki o'chiq (0 V).",
  "Analog pinlar A0-A5: 0 dan 5 V gacha bo'lgan istalgan kuchlanishni o'qiy oladi.",
  "PWM pinlari (~ belgili: 3, 5, 6, 9, 10, 11): yorqinlik va tezlikni boshqarish uchun.",
  "Quvvat pinlari: 5V, 3.3V, GND. Har pindan maksimal 20 mA olinadi — LED uchun yetadi, motor uchun emas."],
 "20 mA cheklovini alohida yozib qo'ying. O'quvchilar motorni to'g'ridan-to'g'ri pinga ulashga urinishi eng ko'p uchraydigan va eng qimmat xato.",
 [("Analog pin nimasi bilan raqamlidan farq qiladi?", "U oraliq qiymatlarni ham o'qiy oladi."),
  ("Pindan maksimal qancha tok olinadi?", "20 mA.")],
 "Motorni to'g'ridan-to'g'ri pinga ulash."),

"Kompyuterga ulash va drayver": T(
 "Platani ulab, drayverni tekshirib, portni aniqlash",
 ["USB kabel ulanadi, kompyuter platani yangi qurilma sifatida taniydi.",
  "Drayver kerak bo'lishi mumkin: original platalarda odatda avtomatik, klonlarda CH340 drayveri qo'lda o'rnatiladi.",
  "Port raqami (COM3, COM5 va h.k.) dasturda tanlanadi. Har kompyuterda boshqacha bo'lishi mumkin.",
  "Port ko'rinmasa tartib: kabelni tekshirish (ma'lumot simlari bormi), drayverni tekshirish, boshqa USB portga ulash."],
 "Drayverlarni oldindan barcha kompyuterlarga o'rnatib qo'ying — aks holda birinchi dars butunlay drayver o'rnatishga ketadi.",
 [("Port ko'rinmasa birinchi nima tekshiriladi?", "USB kabel — unda ma'lumot simlari bormi."),
  ("Klon platalar uchun qaysi drayver kerak?", "CH340.")],
 "Faqat zaryadlash uchun mo'ljallangan USB kabelni ishlatish."),

"Blokli dasturlash muhiti (mBlock) bilan tanishuv": T(
 "mBlock muhitini ochib, interfeys qismlari bilan tanishish",
 ["mBlock — bloklardan dastur yig'iladigan muhit. Blok — bu tayyor buyruq, uni sichqoncha bilan sudrab olib qo'yiladi.",
  "Interfeys qismlari: bloklar palitrasi (chapda), ishchi maydon (o'rtada), qurilma paneli va yuklash tugmasi.",
  "Bloklar rang bo'yicha guruhlangan: harakat, boshqaruv, sezish, amallar. Rang blokning turini bildiradi.",
  "Bloklar faqat mos joyga ulanadi — bu sintaksis xatosining oldini oladi. Matnli dasturlashdagi nuqta-vergul muammosi bu yerda yo'q."],
 "Blokli muhitning asosiy afzalligini ayting: sintaksis xatosi bo'lmaydi, shuning uchun o'quvchi MANTIQqa e'tibor qarata oladi.",
 [("Blok nima?", "Tayyor buyruq, uni sudrab olib qo'yiladi."),
  ("Blokli dasturlashning afzalligi nima?", "Sintaksis xatosi bo'lmaydi.")],
 "Bloklarni mos bo'lmagan joyga ulashga urinish — ular birikmaydi."),

"Birinchi blok: platani yoqish": T(
 "Platani mBlock ga ulab, aloqani tekshirish va birinchi blokni ishlatish",
 ["Plata ulanadi, mBlock da qurilma tanlanadi (Arduino Uno) va ulanish tugmasi bosiladi.",
  "Ikki rejim bor: Live (jonli — kompyuter platani real vaqtda boshqaradi) va Upload (dastur plataga yuklanadi).",
  "Live rejimda kompyuter uzilsa dastur to'xtaydi. Upload rejimda esa plata mustaqil ishlaydi.",
  "Boshlanish uchun Live rejim qulay — natija darhol ko'rinadi va yuklashni kutish kerak emas."],
 "Ikki rejim farqini aniq tushuntiring — o'quvchilar Live rejimda ishlab, keyin platani uzganda dastur to'xtaganidan hayron bo'ladi.",
 [("Live va Upload rejimlari farqi nima?", "Live da kompyuter boshqaradi, Upload da plata mustaqil ishlaydi."),
  ("Qaysi rejimda plata kompyutersiz ishlaydi?", "Upload rejimida.")],
 "Live rejimda ishlab, platani mustaqil ishlaydi deb o'ylash."),

"LEDni blok bilan yoqish va o'chirish": T(
 "Ikki blok bilan LEDni yoqish va o'chirish",
 ["\"Raqamli pinni yoqish/o'chirish\" blogi ishlatiladi: pin raqami va holati (HIGH/LOW) tanlanadi.",
  "Bu blok matnli dasturlashdagi digitalWrite ga to'g'ri keladi.",
  "LED tashqi pinga ulanadi (masalan D9) yoki plataning o'z LEDi (D13) ishlatiladi.",
  "Blok bir marta bajariladi. Takrorlanishi uchun uni takrorlash blogining ichiga qo'yish kerak."],
 "Blok va matnli buyruq mosligini har darsda ko'rsatib boring. 6-sinfda matnli dasturlashga o'tishda bu bog'lanish katta yordam beradi.",
 [("LEDni yoqish blogi qaysi buyruqqa to'g'ri keladi?", "digitalWrite ga."),
  ("Blok bir marta bajariladimi?", "Ha, takrorlanishi uchun sikl kerak.")],
 "Blokni takrorlash siklisiz qo'yib, LED miltillashini kutish."),

"Kutish (delay) blogi": T(
 "Kutish blogi bilan turli tezlikda miltillash naqshlarini yaratish",
 ["Kutish blogi dasturni belgilangan vaqtga to'xtatib turadi. Vaqt sekundda beriladi (matnli kodda millisekundda).",
  "Miltillash uchun: yoqish - kutish - o'chirish - kutish ketma-ketligi kerak.",
  "Kutish vaqti kichraysa miltillash tezlashadi. 0,05 sekunddan kichik bo'lsa ko'z sezmaydi va LED doim yonayotgandek ko'rinadi.",
  "Kutish paytida plata BOSHQA HECH NARSA QILMAYDI — tugmani ham o'qimaydi."],
 "0,05 sekund chegarasini sinatib ko'rsating: tez miltillash yorqinlikning kamayishiga o'xshab ko'rinadi. Bu keyingi PWM mavzusiga tabiiy kirish.",
 [("Kutish blogi vaqtni qaysi birlikda oladi?", "Sekundda."),
  ("Juda tez miltillash qanday ko'rinadi?", "LED doim yonayotgandek, faqat xiraroq.")],
 "Kutishsiz yoqish-o'chirish qo'yish — LED miltillayotgani ko'rinmaydi."),

"Ikki blokni ketma-ket qo'yish": T(
 "Bir necha blokni ketma-ket qo'yib, aniq ketma-ketlikda ishlaydigan dastur yasash",
 ["Dastur — buyruqlarning KETMA-KETLIGI. Bloklar yuqoridan pastga birma-bir bajariladi.",
  "Tartib muhim: yoqish-kutish-o'chirish va yoqish-o'chirish-kutish butunlay boshqa natija beradi.",
  "Ikkinchi holatda LED yonib-o'chishi shu qadar tez bo'ladiki, ko'z uni sezmaydi.",
  "Bu tushuncha algoritmning asosi: qadamlar tartibi natijani belgilaydi."],
 "Ikki tartibni sinatib ko'rsating. Bir xil bloklar, boshqa tartib, butunlay boshqa natija — bu algoritm tushunchasining eng aniq namoyishi.",
 [("Bloklar qanday tartibda bajariladi?", "Yuqoridan pastga."),
  ("Tartib o'zgarsa natija o'zgaradimi?", "Ha, butunlay boshqa bo'lishi mumkin.")],
 "Blok tartibiga e'tibor bermaslik."),

"Birinchi dasturni plataga yuklash": T(
 "Upload rejimida dasturni yuklab, platani kompyutersiz ishlatish",
 ["Upload rejimida dastur plataning xotirasiga yoziladi va u mustaqil ishlaydi.",
  "Yuklash bir necha sekund davom etadi. Bu paytda plataning RX/TX diodlari miltillaydi.",
  "Yuklangan dastur plata xotirasida saqlanadi: kompyuter uzilsa ham, quvvat qayta berilsa ham ishlayveradi.",
  "Yangi dastur yuklansa eskisi o'chadi. Plataga bir vaqtda faqat bitta dastur sig'adi."],
 "Yuklashdan keyin USB ni uzib, batareyadan quvvat berib ko'rsating. Mustaqil ishlaydigan qurilma — o'quvchilar uchun katta yutuq hissi.",
 [("Yuklangan dastur qayerda saqlanadi?", "Plataning xotirasida."),
  ("Plataga nechta dastur sig'adi?", "Bir vaqtda bittasi.")],
 "Live rejimda ishlab, platani mustaqil deb o'ylash."),

# ==================================================== 2-CHORAK: Blokli dasturlash — chiqish qurilmalari
"Takrorlash (sikl) blogi": T(
 "Takrorlash blogi bilan miltillash dasturini qisqartirish",
 ["Takrorlash blogi ichidagi buyruqlarni belgilangan marta yoki cheksiz bajaradi.",
  "\"Doim\" blogi — cheksiz takrorlanish, matnli koddagi loop() ga to'g'ri keladi.",
  "\"10 marta takrorla\" blogi — aniq son bilan, matnli koddagi for sikliga to'g'ri keladi.",
  "Sikl kod uzunligini keskin kamaytiradi: 20 blok o'rniga 3 blok yetadi."],
 "Siklsiz va sikl bilan yozilgan dasturni yonma-yon ko'rsating. Blok sonining farqi siklning foydasini gapirmasdan tushuntiradi.",
 [("\"Doim\" blogi qaysi matnli konstruksiyaga to'g'ri keladi?", "loop() ga."),
  ("Sikl nima beradi?", "Takrorlanadigan kodni qisqartiradi.")],
 "Har takrorlanish uchun bloklarni qo'lda nusxalash."),

"Bir nechta LEDni navbat bilan yoqish": T(
 "Beshta LEDni navbat bilan yoqadigan dastur yasash",
 ["Har LED o'z piniga va o'z rezistoriga ulanadi (masalan D2-D6).",
  "Navbat bilan yoqish: birini yoqib, kutib, o'chirib, keyingisiga o'tish.",
  "Muhim: oldingi LEDni o'chirmasa, hammasi ketma-ket yonib qoladi va \"yugurish\" effekti bo'lmaydi.",
  "Umumiy tok hisoblanadi: beshta LED birga yonsa 75 mA. Bu Arduino uchun xavfsiz."],
 "O'chirishni unutgan variantni ataylab yozdiring va natijani ko'rsating. Xatoni ko'rish to'g'ri yechimni mustahkamlaydi.",
 [("Yugurish effekti uchun nima qilish kerak?", "Keyingisini yoqishdan oldin oldingisini o'chirish."),
  ("Beshta LED qancha tok oladi?", "Taxminan 75 mA.")],
 "Oldingi LEDni o'chirishni unutish."),

"Svetofor: blokli dastur": T(
 "Uch rangli LED bilan haqiqiy svetofor siklini blokda yasash",
 ["Svetofor sikli: yashil (5 s) -> sariq (2 s) -> qizil (5 s) -> qizil+sariq (1 s) -> yashil.",
  "Algoritm avval QOG'OZDA yoziladi: qaysi holatda qaysi chiroq yonadi va qancha turadi.",
  "Har holatda uch LEDning holati aniq belgilanadi — bittasini o'chirishni unutish tez-tez uchraydi.",
  "Real svetoforda vaqtlar harakat zichligiga qarab o'zgaradi. Buni keyinchalik tugma bilan qo'shish mumkin."],
 "Algoritmni qog'ozda jadval qilib yozdiring: holat / qizil / sariq / yashil / vaqt. Jadval bo'yicha dastur yig'ish xatosiz bo'ladi.",
 [("Svetofor siklida nechta asosiy holat bor?", "To'rtta."),
  ("Har holatda nechta LEDning holati belgilanadi?", "Uchalasi ham.")],
 "Bir LEDni o'chirishni unutib, ikki rang birga yonib qolishi."),

"Yugurayotgan olov effekti": T(
 "Sikl bilan yugurayotgan olov effektini yasab, tezligini sozlash",
 ["Effekt: yoqilgan LED chapdan o'ngga siljib boradi, oldingisi o'chadi.",
  "Sikl va o'zgaruvchi bilan yozilsa dastur ancha qisqaradi: pin raqami o'zgaruvchida saqlanadi va har siklda oshadi.",
  "Ikki tomonlama harakat uchun ikki sikl kerak: biri oldinga, ikkinchisi orqaga.",
  "Tezlik kutish vaqti bilan sozlanadi. 0,05-0,1 sekund tabiiy ko'rinadi."],
 "Ikki tomonlama harakatni qo'shimcha vazifa qilib bering — bu mantiqni mustaqil kengaytirish tajribasi.",
 [("Effekt uchun nima kerak?", "Keyingisini yoqib, oldingisini o'chirish."),
  ("Tabiiy tezlik uchun kutish qancha bo'ladi?", "0,05-0,1 sekund.")],
 "Kutish vaqtini juda katta qilish — effekt ko'rinmaydi, shunchaki LEDlar navbat bilan yonadi."),

"O'zgaruvchi blogi bilan tanishuv": T(
 "O'zgaruvchi yaratib, kutish vaqtini bir joydan boshqarish",
 ["O'zgaruvchi — nomlangan quticha, unga qiymat saqlanadi va keyin nomi bilan ishlatiladi.",
  "mBlock da o'zgaruvchi \"O'zgaruvchilar\" bo'limida yaratiladi va nom beriladi.",
  "Afzalligi: qiymat bir joyda o'zgartirilsa, u ishlatilgan hamma joyda o'zgaradi.",
  "Nom ma'noli bo'lishi kerak: \"tezlik\" yaxshi, \"a\" yomon."],
 "10 ta kutish blogidagi qiymatni qo'lda o'zgartirish vazifasini bering, keyin o'zgaruvchi bilan yechimni ko'rsating. Farq juda yaqqol seziladi.",
 [("O'zgaruvchining afzalligi nima?", "Qiymat bir joyda o'zgartiriladi."),
  ("Nom qanday bo'lishi kerak?", "Ma'noli, nima saqlashini bildiradigan.")],
 "Har blokda qiymatni qo'lda yozish."),

"Sanoqni ekranda ko'rish": T(
 "Sanoq o'zgaruvchisini yaratib, uning qiymatini kuzatish",
 ["Sanoq — har takrorlanishda bittaga oshadigan o'zgaruvchi. \"O'zgaruvchini 1 ga oshir\" blogi ishlatiladi.",
  "Qiymatni ko'rish uchun Serial (ketma-ket aloqa) blogi yoki mBlock ning ekran oynasi ishlatiladi.",
  "Sanoq bilan takrorlanishlar sonini, hodisalar sonini yoki vaqtni hisoblash mumkin.",
  "Sanoqni nolga qaytarishni unutmaslik kerak — aks holda u cheksiz o'sib boradi."],
 "Sanoq qiymatini real vaqtda ko'rish o'quvchilar uchun dasturning \"ichini ko'rish\" imkoniyati — bu nosozlik topishning asosi.",
 [("Sanoq nima?", "Har takrorlanishda oshib boradigan o'zgaruvchi."),
  ("Sanoqni ko'rish uchun nima ishlatiladi?", "Serial aloqa yoki ekran oynasi.")],
 "Sanoqni nolga qaytarishni unutish."),

"RGB LED va rang aralashtirish": T(
 "RGB LED bilan 8 ta asosiy rangni hosil qilib, jadval tuzish",
 ["RGB LED — bitta korpusda uchta LED. Har biri o'z piniga ulanadi, umumiy oyoq GND yoki 5V ga.",
  "Yoqiq/o'chiq holatda 8 kombinatsiya: o'chiq, qizil, yashil, ko'k, sariq, siyan, magenta, oq.",
  "Yorug'likda ranglar QO'SHILUVCHI aralashadi: uchala rang birga oq beradi (bo'yoqda esa qora).",
  "Oraliq ranglar uchun yorqinlikni o'zgartirish kerak — bu keyingi darsdagi PWM mavzusi."],
 "Bo'yoq va yorug'lik aralashishi farqini albatta ayting — rasm darsidagi tajriba bu yerda ishlamaydi va bu chalkashlik yaratadi.",
 [("Qizil va yashil qo'shilsa qaysi rang chiqadi?", "Sariq."),
  ("Yorug'likda uch rang qo'shilsa nima bo'ladi?", "Oq.")],
 "Bo'yoq aralashtirish qoidasini yorug'likka ko'chirish."),

"PWM: yorqinlikni sekin o'zgartirish": T(
 "PWM blogi bilan LED yorqinligini silliq oshirib-kamaytirish",
 ["PWM — pinni juda tez yoqib-o'chirish. Yoqiq vaqt ulushi qancha katta bo'lsa, LED shuncha yorqin ko'rinadi.",
  "Blokda qiymat 0 dan 255 gacha beriladi: 0 — o'chiq, 255 — to'liq yorqin, 128 — yarim.",
  "Faqat ~ belgili pinlarda ishlaydi: 3, 5, 6, 9, 10, 11.",
  "Silliq o'zgarish uchun sikl ishlatiladi: qiymat 0 dan 255 gacha bittalab oshiriladi, orasida kichik kutish."],
 "PWM ni oldingi darsdagi tez miltillash tajribasi bilan bog'lang — o'quvchilar bu hodisani allaqachon ko'rgan va tushunish oson bo'ladi.",
 [("PWM qiymati qanday oraliqda beriladi?", "0 dan 255 gacha."),
  ("Qaysi pinlarda ishlaydi?", "~ belgili pinlarda.")],
 "PWM'siz pinda yorqinlikni o'zgartirmoqchi bo'lish."),

"Zummer bilan tovush chiqarish": T(
 "Passiv zummerga turli chastota berib, tovushni o'zgartirish",
 ["Passiv zummer chastota berilganda tovush chiqaradi. Aktiv zummer esa faqat bitta tonda ishlaydi.",
  "Chastota gerts (Hz) da beriladi: qancha katta bo'lsa tovush shuncha ingichka.",
  "Inson qulog'i 20 dan 20000 Hz gacha eshitadi.",
  "Blokda nota yoki chastota tanlash mumkin — mBlock da ikkala variant ham bor."],
 "Chastotani asta oshirib, tovushning ingichkalashishini eshittiring. Fizik hodisani quloq bilan sezish juda samarali.",
 [("Chastota oshsa tovush qanday o'zgaradi?", "Ingichkalashadi."),
  ("Melodiya uchun qaysi zummer kerak?", "Passiv.")],
 "Aktiv zummer bilan turli nota chiqarishga urinish."),

"Nota va melodiya": T(
 "Nota bloklari bilan tanish qo'shiqning bir qismini chalish",
 ["Notalar aniq chastotalarga ega: DO 262, RE 294, MI 330, FA 349, SOL 392, LYA 440, SI 494 Hz.",
  "Melodiya — notalar va ularning davomiyliklari ketma-ketligi.",
  "Notalar orasida qisqa pauza bo'lishi kerak, aks holda ular qo'shilib ketadi.",
  "Oktava — chastotaning ikki barobarlanishi: LYA 440, bir oktava yuqorisi 880 Hz."],
 "Tanish melodiyani (masalan maktab qo'ng'irog'i) tanlang. O'zi chalgan tanish ohang o'quvchi uchun katta yutuq hissi beradi.",
 [("LYA notasining chastotasi qancha?", "440 Hz."),
  ("Notalar orasida nima kerak?", "Qisqa pauza.")],
 "Pauzasiz notalarni ketma-ket qo'yish — ohang tanib bo'lmas holga keladi."),

"Servo motorni burish": T(
 "Servo blogi bilan motorni turli burchaklarga burish",
 ["Servo berilgan BURCHAKDA turadi. Blokda burchak 0 dan 180 gacha beriladi.",
  "Servoning uch simi: qizil (5V), jigarrang yoki qora (GND), sariq yoki to'q sariq (signal).",
  "Burilishga vaqt kerak — buyruqdan keyin kutish qo'yiladi, aks holda keyingi buyruq oldingisini uzib qo'yadi.",
  "Servo ko'p tok oladi (500 mA gacha) — alohida quvvat manbai kerak, GND umumiy bo'lishi shart."],
 "Alohida quvvat va umumiy GND qoidasini har servo darsida takrorlang. Arduino'dan quvvatlantirilgan servo platani qayta yuklaydi.",
 [("Servo qanday burchak oralig'ida ishlaydi?", "0 dan 180 gacha."),
  ("Servo quvvatini qayerdan olish kerak?", "Alohida manbadan, GND umumiy holda.")],
 "Servoni Arduino 5V pinidan quvvatlantirish."),

"Servo bilan shlagbaum": T(
 "Servo bilan ochilib-yopiladigan shlagbaum maketini yasash",
 ["Shlagbaum ikki holatda: yopiq (0 daraja) va ochiq (90 daraja).",
  "Silliq harakat uchun burchak birdan emas, bosqichma-bosqich o'zgartiriladi — sikl bilan 1 gradusdan.",
  "Mexanik cheklov muhim: shlagbaum to'siqqa tegib qolsa servo majburan burilishga urinadi va qiziydi.",
  "Shuning uchun burchak chegaralari sinovda aniqlanadi va dasturda qat'iy cheklanadi."],
 "Mexanik cheklov masalasini alohida ayting: majburan burilayotgan servo tovush chiqaradi va bu uni ishdan chiqarish belgisi.",
 [("Silliq harakat qanday qilinadi?", "Burchakni bosqichma-bosqich o'zgartirib."),
  ("Servo tovush chiqarsa nima demak?", "U majburan burilishga urinmoqda — burchak chegarasi noto'g'ri.")],
 "Servoni mexanik chegaradan tashqariga burishga urinish."),

"DC motorni yurgizish": T(
 "Tranzistor yoki drayver orqali motorni yurgizib, ishlashini kuzatish",
 ["Motor ko'p tok oladi — u hech qachon to'g'ridan-to'g'ri plata piniga ulanmaydi.",
  "Boshqarish uchun tranzistor yoki motor drayveri ishlatiladi. Modulda flyback diod ham bo'ladi.",
  "Motorga alohida quvvat beriladi, GND esa plata bilan umumiy bo'lishi shart.",
  "Ishga tushish paytida tok eng katta bo'ladi — quvvat manbai buni ko'tara olishi kerak."],
 "Motorni pinga ulash urinishini oldindan to'xtating. Bu xato pinni ishdan chiqaradi va platani almashtirishga to'g'ri keladi.",
 [("Motor nega to'g'ridan-to'g'ri pinga ulanmaydi?", "U pin bera oladigandan ancha ko'p tok oladi."),
  ("Ikki manba ishlatilganda nima umumiy bo'lishi kerak?", "GND.")],
 "Motorni to'g'ridan-to'g'ri pinga ulash."),

"Motor tezligini boshqarish": T(
 "PWM bilan motor tezligini uch darajada boshqarish",
 ["Motor tezligi PWM bilan boshqariladi: qiymat 0 dan 255 gacha.",
  "Past qiymatlarda motor aylanmasligi mumkin — ishga tushish uchun minimal kuchlanish kerak (o'lik zona).",
  "Har motorda bu chegara har xil. Uni sinovda aniqlash kerak: qiymatni asta oshirib, aylanish boshlangan nuqtani yozib olish.",
  "Yechim: ishga tushirish uchun qisqa vaqtga to'liq quvvat berib, keyin kerakli darajaga tushirish."],
 "O'lik zonani har guruh o'z motori uchun o'lchasin. Bu real muhandislik o'lchovi va natijalar har xil chiqadi.",
 [("Nega past PWM da motor aylanmaydi?", "Ishga tushish uchun minimal kuchlanish kerak."),
  ("Bu qanday hal qilinadi?", "Qisqa vaqtga to'liq quvvat berib, keyin pasaytirib.")],
 "Barcha motorlar bir xil chegaraga ega deb hisoblash."),

"Ikki motorli aravacha": T(
 "Ikki motorli aravachani oldinga, orqaga va burilishga dasturlash",
 ["Ikki motorli aravachada burilish motorlarning turli tezligi hisobiga bo'ladi.",
  "Oldinga: ikkalasi bir xil tezlikda. O'ngga burilish: chap motor tez, o'ng sekin.",
  "Joyida burilish: motorlar qarama-qarshi yo'nalishda aylanadi.",
  "Amalda motorlar bir xil emas: bir xil qiymatda biri tezroq aylanadi va aravacha qiyshayadi. Tuzatish koeffitsienti kiritiladi."],
 "Aravachaning qiyshayishini har guruh o'zi o'lchab, tuzatsin. Bu real muammoni real yechish tajribasi.",
 [("Burilish qanday bo'ladi?", "Motorlarning turli tezligi hisobiga."),
  ("Nega aravacha to'g'ri yurmaydi?", "Motorlar bir xil emas, tuzatish kerak.")],
 "Ikki motorga bir xil qiymat berib, to'g'ri yurishni kutish."),

"Blok bilan tovush va harakatni birlashtirish": T(
 "Tovush, yorug'lik va harakatni birga ishlatadigan dastur yozish",
 ["Bir necha qurilmani birga boshqarishda VAQT muammosi chiqadi: kutish blogi butun dasturni to'xtatadi.",
  "Masalan zummer 2 sekund chalayotganda motor to'xtab turadi — bu kutilmagan natija.",
  "Blokli muhitda bu muammoni to'liq hal qilish qiyin — bu matnli dasturlashdagi millis() mavzusiga olib boradi.",
  "Hozircha yechim: uzun kutishlarni bir necha qisqa bo'lakka bo'lish va orasida boshqa amallarni bajarish."],
 "Bu muammoni ochiq ko'rsating va yechim 6-sinfda (millis) berilishini ayting. O'quvchi muammoni bilib, keyingi yilga qiziqish bilan keladi.",
 [("Kutish blogi nima muammo yaratadi?", "Butun dasturni to'xtatadi."),
  ("Hozircha qanday yechim bor?", "Uzun kutishni qisqa bo'laklarga bo'lish.")],
 "Uzun kutish qo'yib, boshqa qurilmalar to'xtab qolishidan hayron bo'lish."),

"Dasturdagi xatoni topish": T(
 "Xatolari bor dasturni bosqichma-bosqich tekshirib tuzatish",
 ["Blokli dasturda sintaksis xatosi bo'lmaydi — faqat MANTIQIY xato bo'ladi.",
  "Mantiqiy xato: dastur ishlaydi, lekin kutilganidan boshqacha. Uni topish uchun dastur qadamma-qadam kuzatiladi.",
  "Usul: bloklarni vaqtincha o'chirib (yoki ajratib qo'yib), qaysi qismi muammo ekanini aniqlash.",
  "O'zgaruvchilar qiymatini ekranda ko'rsatish — bu dasturning ichida nima bo'layotganini ko'rishning eng oson yo'li."],
 "Bloklarni ajratib qo'yish usulini ko'rsating — bu yarmiga bo'lish usulining blokli muhitdagi ko'rinishi va juda samarali.",
 [("Blokli dasturda qanday xato bo'ladi?", "Faqat mantiqiy xato."),
  ("Xatoni topish uchun nima qilinadi?", "Bloklarni bo'lib sinash va o'zgaruvchilarni ko'rish.")],
 "Butun dasturni bir yo'la o'zgartirishga urinish."),

"Dasturni tartibli va tushunarli yozish": T(
 "Chalkash yig'ilgan dasturni tartibga solib, izohlar qo'shish",
 ["Tartibli dastur: bloklar tik ustunda, guruhlar orasida bo'shliq, o'zgaruvchilarga ma'noli nom.",
  "mBlock da izoh qo'shish mumkin — blokka o'ng tugma bosib \"Add comment\".",
  "Izoh NEGA shunday qilinganini tushuntirsin: \"kutish 0,5 s — servo burilishga ulgursin\".",
  "Yaxshi dasturning mezoni: boshqa o'quvchi uni o'qib, nima qilishini tushuna olishi."],
 "O'quvchilar dasturlarini almashtirib, bir-birinikini tushuntirib bersin. \"Tushunmadim\" javobi tartibli yozishning zarurligini isbotlaydi.",
 [("Izohda nima yozilishi kerak?", "Nega shunday qilingani."),
  ("Yaxshi dasturning mezoni nima?", "Boshqa odam uni tushuna olishi.")],
 "O'zgaruvchilarga \"a\", \"b\" kabi nom berish."),

# ==================================================== 3-CHORAK: Blokli dasturlash — sensorlar
"Shart (agar ... bo'lsa) blogi": T(
 "Shart blogi bilan tugmaga javob beradigan dastur yasash",
 ["Shart blogi: agar shart bajarilsa, ichidagi buyruqlar bajariladi; bajarilmasa — o'tkazib yuboriladi.",
  "Shart — rost yoki yolg'on bo'ladigan ifoda: \"pin bosilganmi?\", \"qiymat 500 dan kattami?\"",
  "Shart bloki \"doim\" siklining ichida bo'lishi kerak — aks holda u faqat bir marta tekshiriladi.",
  "Bu qurilmani \"aqlli\" qiladigan asosiy blok: u atrofga qarab qaror qabul qiladi."],
 "Shartni sikl ichiga qo'yish qoidasini alohida ta'kidlang. Bu eng ko'p uchraydigan xato va uni topish qiyin.",
 [("Shart nima?", "Rost yoki yolg'on bo'ladigan ifoda."),
  ("Shart bloki qayerda turishi kerak?", "\"Doim\" siklining ichida.")],
 "Shartni sikldan tashqarida qoldirish — u faqat bir marta tekshiriladi."),

"Tugmani o'qish va shart bilan ishlatish": T(
 "Tugma bosilganda LEDni yoqadigan dastur yasash",
 ["Tugma raqamli kirish sifatida o'qiladi. \"Raqamli pin qiymati\" blogi HIGH yoki LOW qaytaradi.",
  "Tugmaning ikkinchi oyog'i GND ga ulanadi va tortuvchi rezistor (10 kOm) VCC ga tortadi.",
  "Tortuvchi rezistorsiz kirish \"osilgan\" holatda bo'ladi va tasodifiy qiymat beradi.",
  "Sxemaga qarab mantiq teskari bo'lishi mumkin: tugma bosilganda LOW o'qiladi."],
 "Tortuvchi rezistorsiz tugmaning tasodifiy ishlashini ko'rsating — bu apparat va dastur bog'liqligining aniq misoli.",
 [("Tortuvchi rezistorsiz kirish qanday bo'ladi?", "Osilgan holatda, tasodifiy qiymat beradi."),
  ("Tortuvchi rezistor qiymati odatda qancha?", "10 kOm.")],
 "Tortuvchi rezistorni qo'ymaslik."),

"Aks holda (else) blogi": T(
 "Ikki holat uchun turli javob beradigan dastur yasash",
 ["\"Agar ... bo'lsa ... aks holda ...\" blogi ikki yo'lni beradi: shart rost bo'lsa birinchisi, yolg'on bo'lsa ikkinchisi.",
  "Bu \"agar\" blogini ikki marta yozishdan afzal: mantiq aniqroq va xato imkoniyati kam.",
  "Misol: agar tugma bosilgan bo'lsa LEDni yoq, aks holda o'chir.",
  "Ikki yo'ldan doim BIRI bajariladi — hech qachon ikkalasi ham yoki hech biri emas."],
 "\"Doim biri bajariladi\" xossasini ta'kidlang — bu shart mantiqining muhim xususiyati va keyinchalik murakkab shartlarni tushunishga yordam beradi.",
 [("Else blogi qachon bajariladi?", "Shart yolg'on bo'lganda."),
  ("Ikkala yo'l ham bajarilishi mumkinmi?", "Yo'q, doim faqat biri.")],
 "Ikki alohida \"agar\" bloki yozib, ular bir-birini bekor qilishiga yo'l qo'yish."),

"Ikki tugmali boshqaruv": T(
 "Ikki tugma bilan boshqariladigan qurilma yasash (yoqish va o'chirish)",
 ["Ikki tugma ikki alohida pinga ulanadi va har biri alohida o'qiladi.",
  "Har tugmaga o'z shart bloki kerak. Ular ketma-ket tekshiriladi.",
  "Ikki tugma bir vaqtda bosilishi ham mumkin — bu holatni alohida ko'rib chiqish kerak.",
  "Amaliy misol: bir tugma yoqadi, ikkinchisi o'chiradi — bu lift va stanoklarning odatiy boshqaruvi."],
 "Ikkala tugma bir vaqtda bosilganda nima bo'lishini o'quvchilar o'zi hal qilsin. Bu chetki holatlar (edge case) haqida o'ylash ko'nikmasi.",
 [("Har tugmaga nima kerak?", "O'z pini va o'z shart bloki."),
  ("Ikkalasi birga bosilsa nima bo'ladi?", "Buni dastur muallifi oldindan hal qilishi kerak.")],
 "Ikki tugma bir vaqtda bosilishi holatini hisobga olmaslik."),

"Potensiometrni o'qish (analog)": T(
 "Potensiometrni A0 ga ulab, qiymatlarni kuzatish",
 ["Analog kirish 0 dan 1023 gacha qiymat qaytaradi: 0 = 0 V, 1023 = 5 V.",
  "Potensiometrning uchala oyog'i ulanadi: chetkilari 5V va GND ga, o'rtasi A0 ga.",
  "Buralganda qiymat silliq o'zgaradi — bu raqamli kirishdan asosiy farq.",
  "Qiymatni ekranda kuzatish kerak: u haqiqatan 0 dan 1023 gacha o'zgaryaptimi tekshiriladi."],
 "Qiymatlarni real vaqtda ko'rsatib, potensiometrni buratib ko'ring. Raqamlarning silliq o'zgarishi analog tushunchasini yaqqol ochadi.",
 [("Analog kirish qanday oraliq beradi?", "0 dan 1023 gacha."),
  ("Potensiometrning nechta oyog'i ulanadi?", "Uchtasi ham.")],
 "Faqat ikki oyoqni ulash — qiymat o'zgarmaydi."),

"Potensiometr bilan yorqinlikni boshqarish": T(
 "Potensiometr bilan LED yorqinligini real vaqtda boshqarish",
 ["Muammo: analog kirish 0-1023 beradi, PWM chiqishi esa 0-255 qabul qiladi. Diapazonlar mos emas.",
  "Yechim — moslash (map): qiymatni bir oraliqdan boshqasiga proporsional o'tkazish. mBlock da \"map\" blogi bor.",
  "Yoki oddiy bo'lish: 1023 / 4 = 255. Bu taxminiy, lekin amalda yetarli.",
  "Teskari boshqaruv ham mumkin: potensiometr o'ngga burilganda yorqinlik kamaysin."],
 "Diapazonlarning mos kelmasligi muammosini avval his qildiring: to'g'ridan-to'g'ri ulansa LED tez to'yinadi. Keyin yechim mantiqiy ko'rinadi.",
 [("Analog kirish va PWM chiqish diapazonlari mos keladimi?", "Yo'q — 0-1023 va 0-255."),
  ("Bu qanday hal qilinadi?", "Moslash (map) yoki 4 ga bo'lish bilan.")],
 "Analog qiymatni to'g'ridan-to'g'ri PWM ga berish."),

"Fotorezistor: yorug'likni o'lchash": T(
 "Fotorezistorli bo'luvchini o'qib, uch xil yorug'likda qiymatni yozib olish",
 ["Fotorezistor 10 kOm rezistor bilan bo'luvchiga ulanadi, o'rta nuqta analog pinga boradi.",
  "Qorong'ida va yorug'da qiymat farq qiladi. Har sinf va sensorda bu qiymatlar har xil.",
  "Shuning uchun har guruh o'z sensori uchun uch nuqtani o'lchab yozadi: qorong'i, xonaki, chiroq nuri.",
  "Chegara shu o'lchovlar asosida tanlanadi — odatda qorong'i va xonaki qiymatlarning o'rtasi."],
 "Tayyor chegara bermang. Kalibrlash ko'nikmasi — sensor bilan ishlashning asosi va uni faqat o'zi bajarib o'rganadi.",
 [("Nega tayyor chegara ishlatilmaydi?", "Har sensor va sharoitda qiymatlar farq qiladi."),
  ("Chegara qanday tanlanadi?", "O'lchangan qiymatlarning orasidan.")],
 "Boshqa guruhning chegarasini ko'chirib olish."),

"Avtomatik tungi chiroq": T(
 "Qorong'ida o'zi yonadigan chiroq dasturini yozish va sozlash",
 ["Mantiq: agar yorug'lik chegaradan past bo'lsa LEDni yoq, aks holda o'chir.",
  "Muammo: chegara atrofida qiymat tebranib, LED miltillaydi.",
  "Yechim — ikki chegara: yoqish uchun bir qiymat (masalan 300), o'chirish uchun kattaroq (400).",
  "Bu gisterezis deb ataladi va deyarli barcha avtomatik tizimlarda ishlatiladi."],
 "Miltillash muammosini avval ko'rsating. Yechimni o'quvchilar o'zi taklif qilishi mumkin — bu haqiqiy muhandislik lahzasi.",
 [("Nega chiroq miltillaydi?", "Chegara atrofida qiymat tebranadi."),
  ("Gisterezis nima?", "Yoqish va o'chirish uchun ikki xil chegara.")],
 "Bitta chegara bilan cheklanib, miltillashni sensorning nosozligi deb o'ylash."),

"Termistor bilan harorat": T(
 "Termistorli bo'luvchini o'qib, issiq va sovuq holatda qiymatni solishtirish",
 ["Termistor 10 kOm rezistor bilan bo'luvchiga ulanadi. NTC turida issiqda qarshilik kamayadi.",
  "Analog qiymat haroratga bog'liq o'zgaradi, lekin u GRADUS emas — shunchaki raqam.",
  "Gradusga aylantirish uchun kalibrlash kerak: ma'lum haroratlarda qiymat o'lchab, jadval tuziladi.",
  "5-sinf uchun aniq gradus shart emas — \"issiq/sovuq\" chegarasi bilan ishlash yetarli."],
 "Aniq gradus va nisbiy qiymat farqini aniq ayting. O'quvchilar sensordan darhol gradus kutadi va bu tushunmovchilikni oldindan hal qilish kerak.",
 [("Analog qiymat gradusmi?", "Yo'q, shunchaki raqam — kalibrlash kerak."),
  ("NTC termistorda issiqda qarshilik qanday bo'ladi?", "Kamayadi.")],
 "Analog qiymatni gradus deb qabul qilish."),

"Haroratli ogohlantirish": T(
 "Belgilangan chegaradan oshganda signal beradigan qurilma yasash",
 ["Mantiq: agar harorat qiymati chegaradan oshsa, zummer va qizil LEDni yoq.",
  "Chegarani aniqlash: kerakli haroratda sensor qiymatini o'lchab, uni chegara qilib olish.",
  "Gisterezis bu yerda ham kerak — aks holda chegara atrofida signal uzuq-yuluq bo'ladi.",
  "Termistor o'lchanadigan yuzaga tegib turishi kerak. Havodagi harorat va yuza harorati farq qiladi."],
 "Qurilmani issiq stakan bilan sinatib ko'ring va javob vaqtini o'lchang. Javob tezligi ham muhandislik parametri.",
 [("Chegara qanday aniqlanadi?", "Kerakli haroratda sensor qiymatini o'lchab."),
  ("Termistor qayerga joylashtiriladi?", "O'lchanadigan yuzaga tegib turadigan joyga.")],
 "Chegarani taxminan tanlash — qurilma noto'g'ri haroratda ishlaydi."),

"Ultratovush sensori: masofa": T(
 "HC-SR04 bilan masofani o'lchab, qiymatlarni kuzatish",
 ["HC-SR04 ultratovush impulsi yuboradi va qaytishini kutadi. Vaqtdan masofa hisoblanadi.",
  "mBlock da tayyor blok bor — u hisobni o'zi bajarib, masofani santimetrda beradi.",
  "Ikki pin ulanadi: TRIG (impuls yuborish) va ECHO (qaytishni qabul qilish).",
  "Ish diapazoni 2-400 sm. Yumshoq va qiya yuzalarda natija noto'g'ri chiqadi."],
 "Turli materiallarda (karton, mato, shisha) o'lchatib solishtiring. Sensorning chegaralarini bilish uni to'g'ri ishlatishning sharti.",
 [("HC-SR04 uchun nechta pin kerak?", "Ikkita: TRIG va ECHO."),
  ("Qanday yuzalarda natija noto'g'ri chiqadi?", "Yumshoq va qiya yuzalarda.")],
 "Yumshoq yuzada o'lchab, sensorni nosoz deb hisoblash."),

"Masofaga qarab tovush chiqarish": T(
 "Masofa kamayganda tez-tez signal beradigan parkovka radari yasash",
 ["Mantiq: masofa kamaysa, signallar orasidagi vaqt qisqarsin.",
  "Kutish vaqti masofaga moslanadi: uzoq masofada uzun pauza, yaqinda qisqa.",
  "Juda yaqin masofada (5 sm dan kam) uzluksiz signal — bu \"to'xta\" degan aniq ishora.",
  "Bu avtomobil parkovka radarining aynan ishlash tamoyili."],
 "Real parkovka radari bilan solishtiring. O'quvchilar mashinada eshitgan tovushni o'zi yaratishi kuchli motivatsiya beradi.",
 [("Masofa kamayganda signal qanday o'zgaradi?", "Tez-tez beriladi."),
  ("Juda yaqinda nima bo'lishi kerak?", "Uzluksiz signal.")],
 "Masofa chegaradan chiqqan holatlarni hisobga olmaslik."),

"Harakat datchigi (PIR)": T(
 "PIR bilan harakatni sezib, chiroqni avtomatik yoqadigan tizim yasash",
 ["PIR issiq jismlardan kelayotgan IK nurlanish o'zgarishini sezadi. Qimirlamay turgan odamni sezmaydi.",
  "Chiqish raqamli: harakat sezilganda HIGH bo'ladi.",
  "Modulda ikki potensiometr: sezgirlik va ushlab turish vaqti.",
  "Yoqilgandan keyin 30-60 sekund isinish kerak — bu vaqtda yolg'on signallar bo'ladi."],
 "Isinish vaqtini albatta ayting — aks holda o'quvchilar yolg'on signallarni nosozlik deb o'ylab, sozlamalarni behuda o'zgartiradi.",
 [("PIR nimani sezadi?", "Issiq jismlarning harakatini."),
  ("Yoqilgandan keyin qancha kutish kerak?", "30-60 sekund.")],
 "Isinishni kutmasdan sozlamalarni o'zgartirishga kirishish."),

"Tuproq namligi sensori": T(
 "Sensorni kalibrlab, quruq va nam tuproqda qiymatlarni solishtirish",
 ["Sensor tuproq qarshiligini o'lchaydi: nam tuproqda qarshilik kichik, qiymat past.",
  "Kalibrlash ikki nuqtada: quruq havoda va suvda. Oradagi qiymatlar shu ikkisiga qarab baholanadi.",
  "Har tuproq turi uchun qiymatlar farq qiladi — kalibrlash qayta bajariladi.",
  "Sensorga doimiy quvvat berilmaydi: elektroliz elektrodlarni yemiradi va sensor bir necha haftada ishdan chiqadi."],
 "Elektroliz muammosini ayting va faqat o'lchash paytida quvvat berish yechimini ko'rsating. Bu oddiy yechim sensor umrini bir necha barobar uzaytiradi.",
 [("Nam tuproqda qiymat qanday bo'ladi?", "Past."),
  ("Nega sensorga doimiy quvvat berilmaydi?", "Elektroliz elektrodlarni yemiradi.")],
 "Sensorni doimiy 5 V ga ulab qoldirish."),

"Suv sathi sensori": T(
 "Suv sathi sensori bilan idishdagi suv miqdorini sezuvchi qurilma yasash",
 ["Sensor platadagi parallel yo'laklardan iborat. Suvga botgan qismi qancha ko'p bo'lsa, qiymat shuncha katta.",
  "Bu aniq sath emas — nisbiy ko'rsatkich. Aniq o'lchov uchun boshqa turdagi sensor kerak.",
  "Suvning tuz miqdori natijaga ta'sir qiladi: sho'r suvda qiymat boshqacha bo'ladi.",
  "Elektroliz muammosi bu yerda ham bor — davriy o'lchash tavsiya etiladi."],
 "Turli suvlarda (tozalangan, tuzli) o'lchatib solishtiring. Natija farqi sensorning cheklovini yaqqol ko'rsatadi.",
 [("Sensor aniq sathni beradimi?", "Yo'q, nisbiy ko'rsatkich beradi."),
  ("Nima natijaga ta'sir qiladi?", "Suvning tuz miqdori.")],
 "Sensorning elektronika qismini suvga botirish — faqat pastki yo'laklar suvga tegishi kerak."),

"Ikki shartni birlashtirish (VA / YOKI)": T(
 "Ikki sensorli shartli dastur yozib, VA va YOKI mantiqlarini solishtirish",
 ["VA — ikkala shart ham bajarilishi kerak. YOKI — kamida bittasi yetarli.",
  "mBlock da bu bloklar \"Amallar\" bo'limida: \"va\", \"yoki\", \"emas\".",
  "Amaliy misol: sug'orish faqat tuproq quruq VA yorug' bo'lsa ishlasin (kechasi sug'ormaslik uchun).",
  "YOKI misoli: yong'in signali tutun YOKI harorat chegaradan oshsa ishlasin."],
 "1-yildagi ikki tugmali VA/YOKI zanjirlariga havola qiling — bir xil mantiq, endi dasturiy shaklda.",
 [("VA qachon rost beradi?", "Ikkala shart ham rost bo'lganda."),
  ("Sug'orish uchun qaysi mantiq mos?", "VA — quruq va yorug' bo'lsa.")],
 "VA va YOKI ni almashtirib qo'yish — tizim butunlay boshqacha ishlaydi."),

"Sensor qiymatini ekranda kuzatish": T(
 "Bir necha sensor qiymatini bir vaqtda ekranda kuzatish",
 ["Sensor qiymatlarini ko'rish — nosozlik topishning eng samarali usuli.",
  "mBlock da qiymatlarni ekran oynasida yoki Serial orqali ko'rsatish mumkin.",
  "Bir necha qiymatni ko'rsatishda ularni nom bilan ajratish kerak: \"Yoruglik: 450, Harorat: 620\".",
  "Qiymatlar kutilgan oraliqda ekanini tekshirish — sensor to'g'ri ulanganini tasdiqlaydi."],
 "\"Avval qiymatni ko'r, keyin mantiq yoz\" tartibini o'rnating. Ko'r-ko'rona dastur yozish eng ko'p vaqt yo'qotadi.",
 [("Qiymatlarni ko'rish nima uchun kerak?", "Sensor to'g'ri ishlayotganini tekshirish uchun."),
  ("Bir necha qiymat qanday ko'rsatiladi?", "Har birini nomi bilan ajratib.")],
 "Qiymatlarni ko'rmasdan darhol shart yozishga kirishish."),

"Sensorli qurilmani sozlash (kalibrlash)": T(
 "Barcha sensorlarni kalibrlab, chegaralar jadvalini tuzish",
 ["Kalibrlash — sensor ko'rsatkichini haqiqiy holatga moslash jarayoni.",
  "Tartib: 1) ma'lum holatlarda qiymatlarni o'lchash, 2) jadval tuzish, 3) chegara tanlash, 4) sinash va tuzatish.",
  "Kamida ikki nuqta kerak: eng past va eng yuqori holat.",
  "Kalibrlash natijasi hujjat sifatida saqlanadi — qurilma ko'chirilsa yoki sensor almashtirilsa qayta bajariladi."],
 "Kalibrlash jadvalini rasmiy hujjat sifatida yozdiring. Bu o'lchov madaniyatining muhim qismi va boshqa fanlarda ham kerak bo'ladi.",
 [("Kalibrlash uchun kamida nechta nuqta kerak?", "Ikkita — eng past va eng yuqori."),
  ("Sensor almashtirilsa nima qilinadi?", "Kalibrlash qayta bajariladi.")],
 "Bir marta kalibrlab, natijani doimiy deb hisoblash."),

# ==================================================== 4-CHORAK: Blokli loyihalar
"LCD ekran bilan tanishuv": T(
 "LCD 1602 ni I2C moduli bilan ulab, ishga tushirish",
 ["LCD 1602 — 2 qator, har qatorda 16 belgi.",
  "I2C moduli bilan faqat 4 sim kerak: VCC, GND, SDA (A4), SCL (A5).",
  "mBlock da tayyor bloklar bor: ekranni ishga tushirish, matn chiqarish, tozalash.",
  "Ekran yonib turgan, lekin matn ko'rinmasa — birinchi navbatda kontrast potensiometrini burash kerak."],
 "Kontrast muammosini oldindan ayting — yangi ekranda matn ko'rinmasligi juda ko'p uchraydi va o'quvchilar ekranni nosoz deb o'ylaydi.",
 [("LCD 1602 da nechta belgi sig'adi?", "32 ta — 2 qator x 16 belgi."),
  ("Matn ko'rinmasa nima tekshiriladi?", "Kontrast potensiometri.")],
 "Kontrastni tekshirmasdan ekranni nosoz deb hisoblash."),

"LCD'ga matn chiqarish": T(
 "Ekranning turli joylariga matn chiqarib, joylashuv bilan tanishish",
 ["Matn chiqarishdan oldin kursor joyi belgilanadi: ustun (0-15) va qator (0-1).",
  "Sanoq NOLDAN boshlanadi: birinchi ustun 0, birinchi qator ham 0.",
  "Eski matn ustiga qisqaroq yangi matn yozilsa, eski qoldiq ko'rinib turadi.",
  "Yechim: ekranni tozalash yoki yangi matndan keyin bo'sh joy yozish."],
 "Eski matn qoldig'i muammosini ataylab ko'rsating (100 dan 99 ga o'tganda \"990\" chiqadi). Bu klassik xato va yodda qoladi.",
 [("Birinchi qator qaysi raqam bilan belgilanadi?", "0 bilan."),
  ("Nega raqam noto'g'ri ko'rinadi?", "Eski matn qoldig'i tozalanmagan.")],
 "Har siklda ekranni tozalash — ekran miltillaydi."),

"LCD'da sensor qiymatini ko'rsatish": T(
 "Sensor qiymatini LCD ekranda real vaqtda ko'rsatuvchi qurilma yasash",
 ["Bu birinchi to'liq qurilma: sensor (kirish) + ekran (chiqish).",
  "Ekranni har siklda yangilash kerak emas — bu miltillash beradi. 0,5 sekundda bir marta yetarli.",
  "Ekran maketi oldindan qog'ozda chiziladi: qaysi ma'lumot qayerda turadi. 16x2 juda kichik.",
  "O'lchov birligini ham yozish kerak: \"Harorat: 450\" emas, \"Namlik: 45%\"."],
 "Ekran maketini 16x2 katakcha chizib rejalashtirishni talab qiling. Bu foydalanuvchi interfeysi dizaynining eng sodda shakli.",
 [("Ekranni qanchalik tez-tez yangilash kerak?", "0,5 sekundda bir marta."),
  ("Nega o'lchov birligi yoziladi?", "Foydalanuvchi raqamni tushunishi uchun.")],
 "Har siklda ekranni to'liq yangilash."),

"IR pult bilan boshqarish": T(
 "IR qabul qiluvchini ulab, pult tugmalarini tanish",
 ["IR pult har tugma uchun o'z kodini infraqizil nur orqali yuboradi.",
  "Qabul qiluvchi modul (VS1838) uch oyoqli: VCC, GND, OUT.",
  "mBlock da tayyor blok bor — u kelgan kodni qaytaradi.",
  "Kodlar har pultda boshqacha — avval o'z pultingizning kodlarini o'qib, jadval tuzish kerak."],
 "Kodlarni o'qish bosqichini alohida qism qiling. Har juftlik o'z pultining kodlar jadvalini tuzsin — bu keyingi ishda kerak bo'ladi.",
 [("Pult kodlari universalmi?", "Yo'q, har pultda o'ziga xos."),
  ("Kodlarni qanday bilib olinadi?", "Ekranda o'qib, jadval tuzib.")],
 "Boshqa pultning kodlarini ishlatish."),

"Pult tugmalarini tanib olish": T(
 "Pult kodlari jadvalini tuzib, har tugmaga vazifa biriktirish",
 ["Har tugmaning kodi o'qib olinadi va jadvalga yoziladi: tugma nomi va kodi.",
  "Dastur kelgan kodni jadvaldagilar bilan solishtirib, mos amalni bajaradi.",
  "Bir necha shart bloklari ketma-ket qo'yiladi — har kod uchun bittadan.",
  "Ba'zi pultlar tugma bosib turilganda takrorlash kodini yuboradi — uni alohida qayta ishlash kerak."],
 "Takrorlash kodini oldindan ayting — u kutilmagan xatti-harakatga sabab bo'ladi va sababini topish qiyin.",
 [("Kodlar qayerda saqlanadi?", "Jadvalda, tugma nomi bilan birga."),
  ("Tugma bosib turilganda nima yuboriladi?", "Takrorlash kodi.")],
 "Takrorlash kodini hisobga olmaslik — buyruq bir necha marta bajariladi."),

"Rele bilan chiroqni yoqish": T(
 "Rele moduli orqali alohida manbali chiroqni dasturdan boshqarish",
 ["Rele moduli uch pinli: VCC, GND, IN. Ichida tranzistor, diod va ba'zan optopara bor.",
  "Ko'p modullar TESKARI mantiqda: IN ga LOW berilganda rele yoqiladi.",
  "Yuklama COM va NO kontaktlariga ulanadi.",
  "Sinfda maksimal 12 V yuklama ishlatiladi. 220 V faqat o'qituvchi namoyishida."],
 "Teskari mantiqni oldindan sinab, sinfga aytib qo'ying — aks holda to'g'ri yozilgan dastur ham teskari natija beradi.",
 [("Ko'p rele modullarida rele qachon yoqiladi?", "IN ga LOW berilganda."),
  ("Sinfda maksimal qanday yuklama ruxsat etiladi?", "12 V.")],
 "220 V bilan mustaqil ishlashga urinish."),

"Bir nechta sensorli tizim": T(
 "Uch sensorli tizim yig'ib, ularni birga ishlatish",
 ["Bir necha sensorni birga ishlatishda har biri o'z piniga ulanadi va alohida o'qiladi.",
  "Analog pinlar cheklangan (A0-A5) — ular yetmasa raqamli chiqishli sensorlar tanlanadi.",
  "Har sensor alohida sinaladi, keyin birlashtiriladi. Birdan hammasini ulash xatoni topishni qiyinlashtiradi.",
  "Umumiy quvvat hisobga olinadi: har sensor tok oladi va ularning yig'indisi plata imkoniyatidan oshmasligi kerak."],
 "\"Bittalab qo'shish\" tartibini majburiy qiling: bir sensor ishlagach keyingisi qo'shiladi. Bu murakkab tizim qurishning asosiy usuli.",
 [("Sensorlar qanday tartibda qo'shiladi?", "Bittalab, har biri sinalgandan keyin."),
  ("Analog pinlar yetmasa nima qilinadi?", "Raqamli chiqishli sensorlar tanlanadi.")],
 "Hamma sensorni birdan ulab, ishlamasa qayerdan izlashni bilmay qolish."),

"Qurilmaning ish algoritmini chizish": T(
 "O'z qurilmasining algoritmini blok-sxema ko'rinishida chizish",
 ["Algoritm — masalani yechish qadamlarining aniq ketma-ketligi.",
  "Blok-sxema belgilari: oval (boshlanish/tugash), to'rtburchak (amal), romb (shart), strelka (yo'nalish).",
  "Shart rombidan ikki strelka chiqadi: \"ha\" va \"yo'q\".",
  "Blok-sxema dasturdan OLDIN chiziladi — u xatolarni kod yozishdan avval topishga imkon beradi."],
 "Blok-sxema chizishni majburiy bosqich qiling. Rejasiz kod yozish 5-sinfda eng ko'p vaqt yo'qotadigan xato.",
 [("Rombda nima yoziladi?", "Shart."),
  ("Blok-sxema qachon chiziladi?", "Dastur yozishdan oldin.")],
 "Blok-sxemani dastur yozilgandan keyin \"hisobot uchun\" chizish."),

"Algoritmni blokli dasturga aylantirish": T(
 "Chizilgan blok-sxemani mBlock dasturiga aylantirish",
 ["Blok-sxemaning har elementi dasturdagi blokka mos keladi: amal — buyruq bloki, romb — shart bloki.",
  "Strelkalar bloklarning ketma-ketligini bildiradi.",
  "Sikl blok-sxemada orqaga qaytadigan strelka bilan ko'rsatiladi — dasturda esa takrorlash bloki bilan.",
  "Aylantirish bosqichma-bosqich bajariladi: har element ko'chirilgach, u chizmada belgilanadi."],
 "Aylantirishni birgalikda bir marta bajarib ko'rsating. Mosligni bir marta ko'rgan o'quvchi keyin mustaqil qila oladi.",
 [("Blok-sxemadagi romb dasturda nimaga aylanadi?", "Shart blokiga."),
  ("Orqaga qaytadigan strelka nimani bildiradi?", "Siklni.")],
 "Chizmaga qaramasdan xotiradan yozishga urinish — qadamlar tushib qoladi."),

"Qurilmani bosqichma-bosqich sinash": T(
 "Qurilmani qismlarga bo'lib, har birini alohida sinash",
 ["Sinash tartibi: har qism alohida, keyin juft-juft, oxirida hammasi birga.",
  "Har qism uchun oddiy test dasturi yoziladi: faqat shu qismni tekshiradi.",
  "Sinov natijalari jadvalga yoziladi: nima sinaldi, natija qanday, muammo bormi.",
  "Muammo topilsa u darhol tuzatiladi — keyingi bosqichga o'tilmaydi. Aks holda muammolar to'planib ketadi."],
 "Sinov jadvalini tarqating va to'ldirishni talab qiling. Hujjatlashtirilgan sinov — muhandislik madaniyatining asosi.",
 [("Sinash qanday tartibda olib boriladi?", "Har qism alohida, keyin birga."),
  ("Muammo topilsa nima qilinadi?", "Darhol tuzatiladi, keyingi bosqichga o'tilmaydi.")],
 "Hamma narsani yig'ib bo'lgach sinashga kirishish."),

"Xatoni topish va tuzatish": T(
 "Ishlamayotgan qurilmani tizimli usul bilan tuzatish",
 ["Xato ikki joyda bo'lishi mumkin: sxemada yoki dasturda. Ularni ajratish birinchi qadam.",
  "Sxemani tekshirish: eng oddiy test dasturi yuklanadi. Ishlasa — sxema joyida.",
  "Dasturni tekshirish: qiymatlarni ekranda ko'rish va bloklarni bo'lib sinash.",
  "Bir vaqtda faqat BITTA narsa o'zgartiriladi — aks holda nima yordam berganini bilib bo'lmaydi."],
 "\"Sxemami, dasturmi?\" savolini birinchi qadam qilib o'rnating. Bu ikkiga bo'lish usulining amaliy ko'rinishi va vaqtni juda tejaydi.",
 [("Xatoni qanday ajratish mumkin?", "Sxemaga oddiy test dasturi yuklab."),
  ("Nega bir vaqtda bitta narsa o'zgartiriladi?", "Nima yordam berganini aniq bilish uchun.")],
 "Bir necha narsani birdan o'zgartirish."),

"Qurilmani yaxshilash: qo'shimcha imkoniyat": T(
 "Ishlaydigan qurilmaga bitta yangi imkoniyat qo'shish",
 ["Yaxshilash ishlaydigan asosdan boshlanadi — avval asosiy vazifa bajarilsin, keyin qo'shimchalar.",
  "Yangi imkoniyat qo'shishdan oldin ishlaydigan dastur nusxasi saqlanadi. Muammo chiqsa qaytish mumkin.",
  "Qo'shimcha imkoniyat misollari: ovozli signal, ekranda ko'rsatish, pult bilan sozlash, rejim tanlash.",
  "Har qo'shimchadan keyin butun tizim qayta sinaladi — yangi qism eskisini buzmaganini tekshirish uchun."],
 "Nusxa saqlash odatini o'rnating (loyiha_v1, loyiha_v2). Bu versiya nazoratining eng sodda shakli va ko'p muammodan qutqaradi.",
 [("Yaxshilashdan oldin nima qilinadi?", "Ishlaydigan dastur nusxasi saqlanadi."),
  ("Har qo'shimchadan keyin nima qilinadi?", "Butun tizim qayta sinaladi.")],
 "Ishlaydigan dasturni saqlamasdan o'zgartirish."),

"Korpus yasash va montaj": T(
 "Qurilmani karton yoki plastik korpusga joylashtirish",
 ["Korpus uch vazifani bajaradi: himoya, xavfsizlik va foydalanish qulayligi.",
  "Tartib: avval boshqaruv elementlari (tugma, ekran) joyi belgilanadi, keyin plata, oxirida simlar.",
  "Batareya almashtiriladigan joyda bo'lishi kerak.",
  "Isish nazarga olinadi: qiziydigan komponentlar yonida havo o'tishi uchun teshik qoldiriladi."],
 "Foydalanuvchi nuqtai nazarini kiriting: \"tugmani ko'rmasdan topa olasizmi?\" Bu dizayn tafakkurining boshlanishi.",
 [("Korpusning uch vazifasi qaysi?", "Himoya, xavfsizlik, foydalanish qulayligi."),
  ("Batareya joyi qanday bo'lishi kerak?", "Almashtirish oson bo'ladigan.")],
 "Teshiklarni plata joylashtirilgandan keyin o'lchash — ular mos kelmaydi."),

"Simlarni tartibga solish": T(
 "Qurilma ichidagi simlarni tartibga solib, mahkamlash",
 ["Tartibsiz simlar uch muammo yaratadi: uzilib qoladi, qisqa tutashadi va ta'mirlashni imkonsiz qiladi.",
  "Tartibga solish usullari: simlarni bog'lash (styajka), kanal ichiga yig'ish, rang bo'yicha ajratish.",
  "Har simga birka (belgi) qo'yish tavsiya etiladi — qayerdan qayerga borishini bildiradi.",
  "Simlar harakatlanuvchi qismlarga tegmasligi kerak — motor va servo yonida bu ayniqsa muhim."],
 "Silkitish sinovini o'tkazing: tartibli va tartibsiz montajni silkitib, farqni ko'rsating. Amaliy isbot eng ishonarli.",
 [("Tartibsiz simlar qanday muammo yaratadi?", "Uzilish, qisqa tutashuv va ta'mirlash qiyinligi."),
  ("Nega simlarga birka qo'yiladi?", "Qayerdan qayerga borishini bilish uchun.")],
 "Simlarni mahkamlamaslik — tashishda ular uzilib qoladi."),

"Qurilma uchun qo'llanma yozish": T(
 "Qurilmani ishlatish bo'yicha qisqa qo'llanma yozish",
 ["Qo'llanma foydalanuvchi uchun yoziladi, muhandis uchun emas — texnik atamalar minimal bo'lsin.",
  "Tarkibi: qurilma nima qiladi, qanday yoqiladi, boshqaruv elementlari, sozlash, muammolar va yechimlar.",
  "\"Muammolar va yechimlar\" bo'limi eng foydali qism: \"chiroq yonmayapti — batareyani tekshiring\".",
  "Rasm yoki chizma matn bilan birga bo'lsa tushunish ancha oson bo'ladi."],
 "Qo'llanmani boshqa sinf o'quvchisiga o'qitib sinang. Tushunmasa — qo'llanma yaxshi emas, bu eng adolatli sinov.",
 [("Qo'llanma kim uchun yoziladi?", "Foydalanuvchi uchun."),
  ("Qaysi bo'lim eng foydali?", "Muammolar va yechimlar.")],
 "Texnik atamalar bilan to'ldirilgan qo'llanma yozish."),

"Taqdimotga tayyorgarlik": T(
 "Loyiha taqdimotini tayyorlab, mashq qilish",
 ["Taqdimot tuzilishi: qurilma qanday muammoni yechadi, qanday ishlaydi, namoyish, nimani yaxshilash mumkin.",
  "Namoyish oldindan sinaladi. Zaxira variant tayyorlanadi — video yozib qo'yish.",
  "Vaqt cheklovi: 3-5 daqiqa. Har qismga qancha vaqt ajratilishi oldindan rejalanadi.",
  "Mashq qilish shart: bir marta ovoz chiqarib aytib ko'rish taqdimot sifatini sezilarli oshiradi."],
 "Har guruh kamida bir marta mashq qilsin va vaqtni o'lchasin. Vaqtdan chiqib ketish eng ko'p uchraydigan muammo.",
 [("Taqdimot qancha davom etadi?", "3-5 daqiqa."),
  ("Nega zaxira video kerak?", "Jonli namoyish buzilib qolishi mumkin.")],
 "Mashq qilmasdan taqdimotga chiqish."),

"Boshqalarning loyihasini baholash": T(
 "Boshqa guruhlarning loyihalarini mezon bo'yicha baholash",
 ["Baholash mezonlari oldindan e'lon qilinadi: ishlashi, murakkabligi, ijodkorligi, taqdimoti, hujjati.",
  "Tanqid KONSTRUKTIV bo'lishi kerak: \"yomon\" emas, \"agar ... qo'shilsa yaxshiroq bo'lardi\".",
  "Har baholovchi kamida bitta ijobiy va bitta taklif aytadi.",
  "Boshqalarni baholash o'z ishini ham yaxshiroq ko'rishga o'rgatadi — bu ko'nikma o'z-o'zini baholashdan boshlanadi."],
 "\"Bir maqtov, bir taklif\" qoidasini o'rnating. Bu tanqidni foydali va xafa qilmaydigan holga keltiradi.",
 [("Tanqid qanday bo'lishi kerak?", "Konstruktiv — taklif bilan."),
  ("Har baholovchi nima aytadi?", "Kamida bitta ijobiy va bitta taklif.")],
 "Faqat kamchiliklarni sanab, ijobiy tomonlarni aytmaslik."),

"Yakuniy sinov va tuzatish": T(
 "Loyihani to'liq sinovdan o'tkazib, oxirgi tuzatishlarni kiritish",
 ["Yakuniy sinov ro'yxat bo'yicha bajariladi: har imkoniyat alohida tekshiriladi va belgilanadi.",
  "Uzoq muddat ishlatib ko'rish shart — ba'zi muammolar faqat vaqt o'tgach ko'rinadi.",
  "Chetki holatlar sinaladi: eng past va eng yuqori qiymatlar, tugmani tez-tez bosish, quvvatni uzib-ulash.",
  "Tuzatishdan keyin butun ro'yxat qayta bajariladi — tuzatish boshqa joyni buzmaganini tekshirish uchun."],
 "Sinov ro'yxatini (checklist) tuzib bering. Ro'yxat bo'yicha ishlash hech narsani tushirib qoldirmaslikning eng ishonchli usuli.",
 [("Yakuniy sinov qanday olib boriladi?", "Ro'yxat bo'yicha, har imkoniyat alohida."),
  ("Tuzatishdan keyin nima qilinadi?", "Butun ro'yxat qayta bajariladi.")],
 "Faqat asosiy vazifani sinab, chetki holatlarni tekshirmaslik."),
}
