# -*- coding: utf-8 -*-
"""2-yil, 8-sinf — ESP32 ilg'or, IoT tizimlari, TinyML va yakuniy loyiha."""

from kb_5_8 import T

MAVZULAR = {

# ==================================================== 1-CHORAK: ESP32 — ilg'or imkoniyatlar
"ESP32 arxitekturasi: ikki yadro va xotira": T(
 "Ikki yadroni sinab, vazifalarni yadrolarga taqsimlash",
 ["ESP32 da ikki Xtensa LX6 yadrosi bor: Core 0 va Core 1. Har biri 240 MHz gacha.",
  "Odatda Arduino kodi Core 1 da ishlaydi, WiFi va Bluetooth esa Core 0 da.",
  "Xotira turlari: SRAM (520 KB, tez), flesh (dastur uchun), PSRAM (ba'zi platalarda qo'shimcha, sekinroq).",
  "Vazifani ma'lum yadroga biriktirish mumkin: xTaskCreatePinnedToCore(). Bu og'ir hisoblarni WiFi dan ajratadi."],
 "Ikki yadro imkoniyatini amalda ko'rsating: bir yadroda og'ir hisob, ikkinchisida LED miltillashi. Miltillash to'xtamasligi kuchli namoyish.",
 [("ESP32 da nechta yadro bor?", "Ikkita."),
  ("Arduino kodi odatda qaysi yadroda ishlaydi?", "Core 1 da.")],
 "Og'ir hisoblarni WiFi bilan bir yadroda bajarish — aloqa uziladi."),

"Pinlar, ADC va DAC xususiyatlari": T(
 "ADC va DAC ni sinab, chiziqsizlikni o'lchab, tuzatish jadvalini tuzish",
 ["ADC 12 razryadli (0-4095), lekin chiziqsiz — ayniqsa chekka qiymatlarda.",
  "Ishonchli o'lchov diapazoni standart sozlamada 0,15-2,45 V. Attenuatsiya sozlamasi bilan diapazonni kengaytirish mumkin.",
  "DAC — ESP32 da HAQIQIY analog chiqish bor: GPIO25 va GPIO26, 8 razryadli (0-255).",
  "DAC bilan sinus to'lqin, audio signal yoki silliq boshqaruv kuchlanishi hosil qilish mumkin — PWM dan farqli o'laroq bu haqiqiy analog."],
 "DAC ni PWM bilan solishtiring: ossilloskop yoki RC filtr bilan farqni ko'rsating. Bu \"PWM analog emas\" fikrini yakunlaydi.",
 [("ESP32 da haqiqiy analog chiqish bormi?", "Ha, DAC — GPIO25 va GPIO26 da."),
  ("ADC ning asosiy kamchiligi nima?", "Chiziqsizligi.")],
 "ADC ni kalibrlashsiz aniq o'lchov uchun ishlatish."),

"PWM, touch va Hall imkoniyatlari": T(
 "Uch imkoniyatni bir loyihada birga ishlatib, sozlamalarni o'rganish",
 ["LEDC: 16 mustaqil kanal, har biriga o'z chastotasi va razryadi.",
  "Touch: 10 sig'imli sensorli pin. Chegara kalibrlanadi, atrof-muhit ta'sir qiladi.",
  "Ichki Hall datchigi: sezgirligi past, faqat namoyish uchun mos.",
  "Touch pinlari uyqu rejimidan uyg'otish uchun ham ishlatilishi mumkin — bu batareyali qurilmalar uchun qimmatli."],
 "Touch bilan uyg'otish imkoniyatini ko'rsating — bu quvvat tejash va foydalanish qulayligini birlashtiradigan chiroyli yechim.",
 [("ESP32 da nechta touch pini bor?", "10 ta."),
  ("Touch pini yana nima uchun ishlatiladi?", "Uyqu rejimidan uyg'otish uchun.")],
 "Touch chegarasini kalibrlashsiz qoldirish."),

"I2C va SPI: bir nechta qurilma": T(
 "Bir necha I2C va SPI qurilmasini birga ulab, shina yuklamasini boshqarish",
 ["I2C: manzil bo'yicha, ikki sim, ko'p qurilma. SPI: CS pini bo'yicha, to'rt sim, tez.",
  "ESP32 da ikkita apparat I2C va uchta SPI shinasi bor — ular alohida ishlatilishi mumkin.",
  "Bir xil manzilli I2C qurilmalari uchun yechim: ikkinchi I2C shinasini ishlatish yoki I2C multiplekser (TCA9548A).",
  "Shina uzunligi cheklangan: I2C uchun odatda 1 metrgacha. Uzunroq bo'lsa tortuvchi rezistorlarni kamaytirish yoki tezlikni pasaytirish kerak."],
 "Ikkinchi I2C shinasini ishlatishni ko'rsating — bu bir xil manzilli modullar muammosining eng oddiy yechimi.",
 [("ESP32 da nechta apparat I2C shinasi bor?", "Ikkita."),
  ("Bir xil manzilli qurilmalar uchun qanday yechim bor?", "Ikkinchi shina yoki multiplekser.")],
 "Uzun I2C simlarini tortib, aloqa beqaror bo'lishiga yo'l qo'yish."),

"OLED va grafik interfeys": T(
 "OLED da menyu va grafikli foydalanuvchi interfeysi yasash",
 ["Foydalanuvchi interfeysi (UI) — qurilma bilan muloqot usuli. Kichik ekranda uni rejalashtirish muhim.",
  "Menyu tuzilmasi: elementlar ro'yxati, joriy tanlov belgisi, tugmalar bilan harakat.",
  "Holat mashinasi (state machine) usuli qulay: qurilma holatlar to'plamiga ega va tugma holatlar orasida o'tkazadi.",
  "Grafik elementlar: progress bar, grafik, ikonkalar. Ular ma'lumotni matndan tezroq yetkazadi."],
 "Holat mashinasi tushunchasini kiriting — bu murakkab interfeys va boshqaruv mantiqini tartibga solishning asosiy usuli.",
 [("Holat mashinasi nima?", "Qurilmaning holatlar to'plami va ular orasidagi o'tishlar."),
  ("Nega grafik elementlar foydali?", "Ma'lumotni matndan tezroq yetkazadi.")],
 "Menyuni holat mashinasisiz, ichma-ich shartlar bilan qurish — kod boshqarib bo'lmas holga keladi."),

"microSD: ma'lumot yozish va o'qish": T(
 "SD kartga ma'lumot yozib, keyin o'qib, tahlil qilish",
 ["SD kart SPI bilan ulanadi. Kutubxona: SD.h yoki SD_MMC.h (tezroq, lekin ko'proq pin).",
  "Yozish: SD.open(fayl, FILE_APPEND), println, close(). O'qish: SD.open(fayl, FILE_READ), readStringUntil.",
  "Fayl tizimi FAT32 bo'lishi kerak. 32 GB dan katta kartlar exFAT bilan formatlangan bo'ladi va ishlamaydi.",
  "Yozish tezligi cheklangan: har close() operatsiyasi vaqt oladi. Tez yozishda buferlash ishlatiladi."],
 "FAT32 talabini ayting — katta kartlar ishlamasligi ko'p uchraydi va sabab topilmaydi.",
 [("Kart qanday fayl tizimida bo'lishi kerak?", "FAT32."),
  ("Tez yozish uchun nima qilinadi?", "Buferlash — bir necha yozuvni yig'ib, keyin saqlash.")],
 "32 GB dan katta exFAT kartni ishlatishga urinish."),

"RTC va vaqt bo'yicha vazifalar": T(
 "Vaqt bo'yicha rejalashtirilgan vazifalar tizimini qurish",
 ["DS3231 aniq vaqt beradi. NTP (internet vaqt xizmati) ham ishlatilishi mumkin — WiFi bo'lsa RTC kerak bo'lmaydi.",
  "Ikkalasini birga ishlatish eng ishonchli: internet bo'lsa NTP dan sinxronlash, bo'lmasa RTC dan olish.",
  "Vazifalar jadvali tuziladi: har vazifa uchun vaqt va amal. Bajarilganini belgilash uchun bayroq kerak.",
  "Vaqt zonasi va yozgi vaqt masalasi: NTP UTC beradi, mahalliy vaqtga o'tkazish kerak (O'zbekiston UTC+5)."],
 "NTP va RTC ni birga ishlatish arxitekturasini ko'rsating — bu ishonchli tizim qurishning tipik yechimi.",
 [("NTP nima?", "Internet orqali aniq vaqtni olish xizmati."),
  ("O'zbekiston vaqt zonasi qanday?", "UTC+5.")],
 "Vaqt zonasini hisobga olmay, UTC vaqtni mahalliy deb ishlatish."),

"INA219: tok va quvvat o'lchash": T(
 "INA219 bilan qurilmaning tok iste'molini o'lchab, quvvat byudjetini tuzish",
 ["INA219 shunt rezistordagi kuchlanishni o'lchab, tokni hisoblaydi. I2C bilan ulanadi.",
  "U bir vaqtda kuchlanish, tok va quvvatni beradi. Diapazon: ±3,2 A, aniqlik 0,8 mA.",
  "Ulash: yuklama bilan KETMA-KET, ya'ni tok modul orqali o'tadi.",
  "Bu modul batareyali loyihalarda juda foydali: real iste'molni o'lchab, ish muddatini aniq hisoblash mumkin."],
 "Qurilmaning turli rejimlaridagi iste'molni o'lchatib, quvvat byudjeti jadvalini tuzdiring. Bu muhandislik hisobining amaliy misoli.",
 [("INA219 qanday ulanadi?", "Yuklama bilan ketma-ket."),
  ("U nimalarni o'lchaydi?", "Kuchlanish, tok va quvvatni.")],
 "INA219 ni parallel ulash — u tokni o'lchay olmaydi."),

"BMP280: bosim va balandlik": T(
 "BMP280 bilan bosim va balandlikni o'lchab, ob-havo o'zgarishini kuzatish",
 ["BMP280 atmosfera bosimini o'lchaydi. I2C manzili 0x76 yoki 0x77.",
  "Balandlik bosimdan hisoblanadi: balandlik oshsa bosim kamayadi. Har 8 metrda taxminan 1 hPa.",
  "Aniqlik yuqori: ±1 hPa, bu ±8 metr balandlikka to'g'ri keladi. Nisbiy o'zgarish esa ancha aniqroq seziladi.",
  "MUHIM: balandlik hisobi dengiz sathidagi bosimga tayanadi, u esa ob-havoga qarab o'zgaradi. Shuning uchun mutlaq balandlik noaniq bo'ladi."],
 "Bosimning ob-havoga bog'liqligini ko'rsating: bir necha kun kuzatib, bosim pasayishi bilan ob-havo o'zgarishini solishtiring.",
 [("Har 8 metrda bosim qancha o'zgaradi?", "Taxminan 1 hPa."),
  ("Nega mutlaq balandlik noaniq?", "Dengiz sathidagi bosim ob-havoga qarab o'zgaradi.")],
 "Balandlikni mutlaq aniq deb qabul qilish."),

"HX711: yuk va og'irlik o'lchash": T(
 "Tenzodatchik va HX711 bilan tarozi yasab, kalibrlash",
 ["Tenzodatchik (load cell) og'irlik ta'sirida deformatsiyalanadi va qarshiligi juda kichik o'zgaradi.",
  "Bu o'zgarish juda kichik — HX711 uni 24 razryadli aniqlik bilan kuchaytirib o'qiydi.",
  "Kalibrlash shart: ma'lum og'irlikdagi buyum qo'yilib, koeffitsient hisoblanadi.",
  "Tara (idish og'irligini ayirish) funksiyasi: bo'sh holatdagi qiymat esda saqlanadi va keyingi o'lchovlardan ayiriladi."],
 "Tarozini haqiqiy o'lchov bilan tekshiring (masalan 100 gramm suv). Aniqlikni raqamlar bilan baholash muhandislik ko'nikmasi.",
 [("HX711 nima qiladi?", "Tenzodatchikning kichik signalini kuchaytirib, aniq o'qiydi."),
  ("Tara nima?", "Idish og'irligini natijadan ayirish.")],
 "Kalibrlashsiz xom qiymatni gramm deb hisoblash."),

"Sensorlarni kalibrlash va aniqlik": T(
 "Barcha sensorlarni etalon bilan solishtirib, kalibrlash hujjatini tuzish",
 ["Kalibrlash — sensor ko'rsatkichini etalon bilan solishtirib, tuzatish kiritish.",
  "Ikki nuqtali kalibrlash: ikkita ma'lum qiymat olinadi va chiziqli tuzatish hisoblanadi (siljish va koeffitsient).",
  "Ko'p nuqtali kalibrlash aniqroq: bir necha nuqta olinadi va oraliq qiymatlar interpolyatsiya qilinadi.",
  "Aniqlik (accuracy) va takrorlanuvchanlik (precision) farqi: birinchisi haqiqiy qiymatga yaqinlik, ikkinchisi takroriy o'lchovlarning bir-biriga yaqinligi."],
 "Aniqlik va takrorlanuvchanlik farqini nishonga otish misolida tushuntiring — bu klassik va juda tushunarli tasvir.",
 [("Ikki nuqtali kalibrlash nima beradi?", "Siljish va koeffitsientni — chiziqli tuzatishni."),
  ("Aniqlik va takrorlanuvchanlik farqi nima?", "Birinchisi haqiqatga yaqinlik, ikkinchisi natijalarning o'zaro yaqinligi.")],
 "Takrorlanuvchanlikni aniqlik deb hisoblash — sensor doim bir xil, lekin noto'g'ri qiymat berishi mumkin."),

"Ma'lumotni filtrlash (o'rtacha, silliqlash)": T(
 "Turli filtrlarni qo'llab, shovqin kamayishini o'lchab solishtirish",
 ["Oddiy o'rtacha: N ta o'lchov yig'indisi N ga bo'linadi. Sodda, lekin kechikish beradi.",
  "Harakatlanuvchi o'rtacha: oxirgi N ta qiymat aylanma buferda saqlanadi va o'rtachasi olinadi.",
  "Mediana filtri: N ta qiymat tartiblanib, o'rtadagisi olinadi. Yagona keskin chetlanishlarni butunlay yo'q qiladi.",
  "Eksponensial filtr: yangi = alfa * o'lchov + (1 - alfa) * eski. Kam xotira talab qiladi, alfa silliqlash darajasini belgilaydi."],
 "Uch filtrni bir grafikda xom ma'lumot bilan yonma-yon ko'rsating. Har birining xarakteri (kechikish, keskinlik) yaqqol ko'rinadi.",
 [("Mediana filtri nimadan yaxshi himoya qiladi?", "Yagona keskin chetlanishlardan."),
  ("Eksponensial filtrning afzalligi nima?", "Kam xotira talab qiladi.")],
 "Juda kuchli filtrlash — signal silliq bo'ladi, lekin haqiqiy o'zgarishlarga kech javob beradi."),

"Deep sleep va batareya hisobi": T(
 "Quvvat byudjetini hisoblab, batareya muddatini bashorat qilish va tekshirish",
 ["Deep sleep da iste'mol 10 mikroamperga tushadi (ishlash rejimida 150 mA).",
  "O'rtacha iste'mol hisoblanadi: (ishlash toki x ishlash vaqti + uyqu toki x uyqu vaqti) / umumiy vaqt.",
  "Misol: har 10 daqiqada 5 sekund ishlasa: (150 x 5 + 0,01 x 595) / 600 = 1,26 mA. 2000 mAh bilan 66 kun.",
  "Amalda kamroq: batareyaning o'z-o'zidan razryadlanishi, harorat va stabilizator yo'qotishlari. Zaxira 30%."],
 "Hisobni INA219 bilan real o'lchov bilan solishtiring. Nazariya va amaliyot farqini raqamlarda ko'rish qimmatli tajriba.",
 [("Deep sleep da iste'mol qancha?", "Taxminan 10 mikroamper."),
  ("Nega amalda muddat qisqaroq bo'ladi?", "O'z-o'zidan razryadlanish, harorat va yo'qotishlar tufayli.")],
 "Faqat ishlash rejimidagi iste'molni hisoblash."),

"Quvvat manbai va stabilizator": T(
 "Turli quvvat manbalarini sinab, stabilizator yo'qotishlarini o'lchash",
 ["Chiziqli stabilizator (AMS1117, 7805) sodda va arzon, lekin ortiqcha kuchlanishni ISSIQLIKKA aylantiradi.",
  "Yo'qotish: (kirish - chiqish) x tok. 12 V dan 5 V ga 500 mA da: 7 x 0,5 = 3,5 vatt issiqlik.",
  "Impulsli stabilizator (DC-DC) ancha samarali (85-95%), lekin qimmatroq va shovqin chiqaradi.",
  "Batareyali loyihalarda impulsli stabilizator majburiy — chiziqli stabilizator energiyaning yarmini isrof qiladi."],
 "Chiziqli stabilizatorning qizishini qo'l bilan sezdiring va yo'qotishni hisoblang. Energiya samaradorligi shu bilan aniq ma'no oladi.",
 [("Chiziqli stabilizatorda yo'qotish qanday hisoblanadi?", "(kirish - chiqish) x tok."),
  ("Batareyali loyihada qaysi tur afzal?", "Impulsli (DC-DC) stabilizator.")],
 "Batareyali loyihada chiziqli stabilizator ishlatish — batareya tez tugaydi."),

"Vazifalarni bo'lish (FreeRTOS g'oyasi)": T(
 "Bir necha vazifani parallel bajaruvchi dastur yozish",
 ["FreeRTOS — ESP32 da o'rnatilgan real vaqt operatsion tizimi. U bir necha vazifani navbat bilan bajaradi.",
  "Vazifa yaratish: xTaskCreate(funksiya, nom, stek, parametr, ustuvorlik, dastak).",
  "Har vazifa o'z stekiga ega. Stek yetmasa dastur qulaydi — bu topish qiyin xato.",
  "Vazifalar orasida ma'lumot almashish uchun navbat (queue) yoki semafor ishlatiladi. To'g'ridan-to'g'ri o'zgaruvchi ishlatish xavfli."],
 "Vazifalar orasida ma'lumot almashish masalasini alohida ta'kidlang — bu ko'p oqimli dasturlashning eng qiyin va eng muhim qismi.",
 [("FreeRTOS nima qiladi?", "Bir necha vazifani navbat bilan bajaradi."),
  ("Vazifalar orasida ma'lumot qanday uzatiladi?", "Navbat (queue) yoki semafor orqali.")],
 "Vazifalar orasida oddiy global o'zgaruvchi ishlatish — ma'lumot buzilishi mumkin."),

"Kodni modullarga bo'lish": T(
 "Katta loyihani bir necha faylga bo'lib, tuzilmasini yaxshilash",
 ["Katta loyihada bitta fayl boshqarib bo'lmas holga keladi. Uni modullarga bo'lish kerak.",
  "Arduino IDE da qo'shimcha tab (.h va .cpp fayllar) yaratish mumkin.",
  ".h faylda e'lonlar (funksiya nomlari), .cpp faylda amalga oshirish yoziladi.",
  "Modul mustaqil bo'lishi kerak: u boshqa modullarga imkon qadar kam bog'liq bo'lsin. Bu sinash va qayta ishlatishni osonlashtiradi."],
 "Bir loyihani birgalikda modullarga bo'ling. Natijadagi tuzilma o'quvchilarga professional dasturlash ko'rinishini ochadi.",
 [(".h faylda nima yoziladi?", "E'lonlar — funksiya va o'zgaruvchi nomlari."),
  ("Modul qanday bo'lishi kerak?", "Mustaqil, boshqalarga kam bog'liq.")],
 "Barcha kodni bitta faylda saqlab, uni bir necha ming qatorga cho'zish."),

"Kutubxona yozish asoslari": T(
 "O'z kutubxonasini yozib, boshqa loyihada ishlatish",
 ["Kutubxona — qayta ishlatiladigan kod to'plami. U sinf (class) sifatida yoziladi.",
  "Sinf tuzilishi: public (tashqaridan ko'rinadigan) va private (ichki) qismlar.",
  "Konstruktor — sinf obyekti yaratilganda bajariladigan funksiya. Unda boshlang'ich sozlamalar beriladi.",
  "Kutubxonaga hujjat va misol qo'shish shart — usiz uni boshqa odam (va bir oydan keyin o'zingiz ham) ishlata olmaydi."],
 "O'z kutubxonasini yozish — bu chorakning eng katta qadami. Uni oddiy vazifadan (masalan sensor o'qish va filtrlash) boshlang.",
 [("Kutubxona qanday yoziladi?", "Sinf (class) sifatida."),
  ("Konstruktor nima qiladi?", "Obyekt yaratilganda boshlang'ich sozlamalarni bajaradi.")],
 "Kutubxonaga misol va hujjat qo'shmaslik."),

"Nosozlik topish: mantiqiy analiz": T(
 "Murakkab nosozlikni tizimli tahlil bilan topib, hujjatlashtirish",
 ["Murakkab tizimda nosozlik izlash gipoteza asosida olib boriladi: taxmin qilinadi, sinov o'ylab topiladi, natija tekshiriladi.",
  "Har gipoteza yozib boriladi: taxmin, sinov, natija, xulosa. Bu takroriy ishni oldini oladi.",
  "Vaqtga bog'liq nosozliklar (bir necha soatdan keyin) eng qiyin: ular xotira sizishi, sanoq to'lib ketishi yoki aloqa uzilishidan kelib chiqadi.",
  "Loglash yordam beradi: qurilma o'z ishini SD kartga yozib borsa, nosozlikdan oldin nima bo'lganini ko'rish mumkin."],
 "Gipoteza jadvalini yuritishni majburiy qiling. Bu ilmiy usulning muhandislikdagi ko'rinishi va murakkab muammolarni hal qilishning yagona ishonchli yo'li.",
 [("Nosozlik izlash qanday olib boriladi?", "Gipoteza qo'yib, uni sinov bilan tekshirib."),
  ("Vaqtga bog'liq nosozliklar sabablari nima?", "Xotira sizishi, sanoq to'lishi, aloqa uzilishi.")],
 "Gipotezalarni yozmasdan, tasodifiy o'zgartirishlar qilish."),

# ==================================================== 2-CHORAK: IoT tizimlari
"WiFi va tarmoq asoslari (takrorlash va chuqurlashtirish)": T(
 "Tarmoq diagnostikasi vositalari bilan aloqani tahlil qilish",
 ["WiFi ulanish bosqichlari: skanerlash, autentifikatsiya, assotsiatsiya, DHCP orqali IP olish.",
  "Har bosqichda xato bo'lishi mumkin — WiFi.status() qaysi bosqichda muammo borligini ko'rsatadi.",
  "Signal kuchi RSSI: -50 yaxshi, -70 chegara, -80 dan past ishonchsiz. Antenna joylashuvi va to'siqlar ta'sir qiladi.",
  "Kanal to'qnashuvi: 2.4 GHz da 13 kanal bor, lekin ular qisman ustma-ust tushadi. Band kanal aloqani sekinlashtiradi."],
 "Telefondagi WiFi analizator ilovasi bilan sinf tarmog'ini ko'rsating — kanallar va signal kuchi ko'rinadigan bo'lganda tushuncha aniqlashadi.",
 [("RSSI -80 dBm nimani bildiradi?", "Signal juda kuchsiz."),
  ("Kanal to'qnashuvi nimaga olib keladi?", "Aloqa sekinlashadi.")],
 "Signal kuchini tekshirmasdan qurilmani uzoq joyga o'rnatish."),

"Veb-server va API tushunchasi": T(
 "RESTful API tuzilmasini loyihalab, ESP32 da amalga oshirish",
 ["API — dasturlar o'rtasida ma'lumot almashish qoidalari to'plami.",
  "REST tamoyillari: har resurs o'z manziliga ega (/harorat, /rele), amallar HTTP metodlari bilan (GET o'qish, POST o'zgartirish).",
  "Javob JSON formatida qaytariladi — bu mashina o'qishi uchun qulay va standart.",
  "Yaxshi API ning mezoni: hujjatga qarab boshqa dasturchi undan foydalana olishi."],
 "API va veb-sahifa farqini aniq ajrating: sahifa odam uchun, API dastur uchun. Bu tushuncha IoT arxitekturasining asosi.",
 [("API nima?", "Dasturlar o'rtasida ma'lumot almashish qoidalari."),
  ("REST da o'qish uchun qaysi metod ishlatiladi?", "GET.")],
 "API dan HTML qaytarish — u JSON qaytarishi kerak."),

"JSON formati bilan ishlash": T(
 "JSON ma'lumotni yaratib va o'qib, tuzilmali ma'lumot bilan ishlash",
 ["JSON — matn ko'rinishidagi ma'lumot formati. Tuzilishi: {\"kalit\": qiymat, \"kalit2\": qiymat2}.",
  "Qiymat turlari: son, matn (qo'shtirnoqda), true/false, massiv [...], ichki obyekt {...}.",
  "Kutubxona: ArduinoJson. Yaratish uchun JsonDocument, o'qish uchun deserializeJson.",
  "Xotira: JSON hujjat uchun oldindan joy ajratiladi. Yetmasa ma'lumot qisqarib qoladi — hajmni to'g'ri hisoblash kerak."],
 "ArduinoJson saytidagi Assistant vositasini ko'rsating — u kerakli xotira hajmini hisoblab beradi va ko'p vaqt tejaydi.",
 [("JSON da matn qanday yoziladi?", "Qo'shtirnoq ichida."),
  ("Xotira yetmasa nima bo'ladi?", "Ma'lumot qisqarib qoladi.")],
 "JSON hujjat hajmini kam ajratish — ma'lumot to'liq bo'lmaydi va xato ham chiqmaydi."),

"HTTP GET va POST so'rovlari": T(
 "Ikki metod bilan so'rov yuborib, farqini amalda ko'rish",
 ["GET — ma'lumot olish uchun. Parametrlar URL da: /update?field1=25.",
  "POST — ma'lumot yuborish uchun. Ma'lumot so'rov tanasida yuboriladi.",
  "GET ning cheklovi: URL uzunligi cheklangan va parametrlar log fayllarda ko'rinib qoladi (maxfiy ma'lumot uchun mos emas).",
  "POST da Content-Type sarlavhasi ko'rsatilishi kerak: application/json yoki application/x-www-form-urlencoded."],
 "Maxfiylik masalasini ta'kidlang: parol GET orqali yuborilsa u serverning loglarida qoladi. Bu amaliy xavfsizlik qoidasi.",
 [("Maxfiy ma'lumot qaysi metod bilan yuboriladi?", "POST bilan."),
  ("POST da qanday sarlavha kerak?", "Content-Type.")],
 "Maxfiy ma'lumotni GET parametrlarida yuborish."),

"Bulut platformasiga ulanish": T(
 "Bulut platformasida loyiha yaratib, ESP32 ni ulash",
 ["Bulut platformalari: ThingSpeak, Blynk, Adafruit IO, ThingsBoard. Har birining o'z afzalligi bor.",
  "Umumiy ish oqimi: hisob ochish, qurilma yoki kanal yaratish, kalit olish, kodda kalitni ishlatish.",
  "Cheklovlar solishtiriladi: yuborish chastotasi, saqlash muddati, qurilmalar soni, bepul rejadagi imkoniyatlar.",
  "Vendor lock-in xavfi: bir platformaga qattiq bog'lanish uni almashtirishni qiyinlashtiradi. Kodni qatlamlarga bo'lish bu xavfni kamaytiradi."],
 "Vendor lock-in tushunchasini kiriting — bu texnologiya tanlashdagi strategik masala va o'quvchilarga yangi qarash beradi.",
 [("Vendor lock-in nima?", "Bir platformaga qattiq bog'lanib qolish."),
  ("Uni qanday kamaytirish mumkin?", "Kodni qatlamlarga bo'lib, aloqa qismini ajratib.")],
 "Platformaga xos kodni butun loyihaga tarqatib yuborish."),

"Ma'lumotni vizualizatsiya qilish": T(
 "Bulut panelida grafik va indikatorlar bilan panel yasash",
 ["Vizualizatsiya turlari: chiziqli grafik (vaqt bo'yicha o'zgarish), ustunli diagramma (solishtirish), indikator (joriy holat), xarita.",
  "Grafik turini ma'lumotga qarab tanlash kerak: vaqt qatori uchun chiziqli, toifalar uchun ustunli.",
  "O'q chegaralari muhim: avtomatik masshtab kichik o'zgarishni katta ko'rsatib, chalg'itishi mumkin.",
  "Yaxshi panelning mezoni: bir qarashda tizim holati tushunarli bo'lishi."],
 "Chalg'ituvchi grafik misolini ko'rsating (masshtab tufayli kichik o'zgarish katta ko'rinadi). Ma'lumotni halol ko'rsatish — muhim axloqiy masala.",
 [("Vaqt bo'yicha o'zgarish uchun qaysi grafik mos?", "Chiziqli grafik."),
  ("Avtomatik masshtab nima bilan chalg'itishi mumkin?", "Kichik o'zgarishni katta ko'rsatib.")],
 "Grafik turini ma'lumotga mos kelmaydigan qilib tanlash."),

"MQTT: broker, mavzu (topic), obuna": T(
 "MQTT tizimini qurib, mavzular tuzilmasini loyihalash",
 ["Broker — markaziy vositachi. Ommaviy brokerlar (test.mosquitto.org) sinov uchun, o'z brokeri ishlab chiqarish uchun.",
  "Mavzu (topic) tuzilmasi daraxt ko'rinishida: uy/oshxona/harorat. Bu tartib tizimni kengaytirishni osonlashtiradi.",
  "Obuna qilishda wildcard ishlatiladi: uy/+/harorat (bir daraja), uy/# (barcha ostki mavzular).",
  "QoS darajalari: 0 (yetkazish kafolatlanmaydi), 1 (kamida bir marta), 2 (aynan bir marta). Yuqori QoS ko'proq trafik."],
 "Mavzu tuzilmasini loyihalash mashqini bering: 10 xonali uy uchun mavzular daraxtini chizish. Bu arxitektura ko'nikmasi.",
 [("Wildcard # nimani bildiradi?", "Barcha ostki mavzularni."),
  ("QoS 2 nimani kafolatlaydi?", "Xabar aynan bir marta yetkazilishini.")],
 "Mavzu nomlarini tizimsiz tanlash — tizim kengayganda boshqarib bo'lmaydi."),

"MQTT bilan ikki tomonlama boshqaruv": T(
 "MQTT orqali qurilmani boshqarish va holatini kuzatish tizimini qurish",
 ["Ikki tomonlama: qurilma holatni yuboradi (publish) va buyruqlarga obuna bo'ladi (subscribe).",
  "Alohida mavzular ishlatiladi: uy/chiroq/holat (qurilmadan) va uy/chiroq/buyruq (qurilmaga).",
  "Buyruqni bajargach qurilma yangi holatni e'lon qilishi kerak — bu boshqaruvchi tomonga tasdiq beradi.",
  "Last Will and Testament (LWT): qurilma aloqani yo'qotsa, broker oldindan belgilangan xabarni yuboradi. Bu \"qurilma o'chdi\" ni bildiradi."],
 "LWT mexanizmini ko'rsating — bu IoT tizimlarida qurilma holatini ishonchli kuzatishning nafis yechimi.",
 [("Nega holat va buyruq uchun alohida mavzu kerak?", "Aylanma (qayta ishga tushish) hosil bo'lmasligi uchun."),
  ("LWT nima qiladi?", "Qurilma aloqani yo'qotsa avtomatik xabar yuboradi.")],
 "Bitta mavzuni ham holat, ham buyruq uchun ishlatish — cheksiz aylanma hosil bo'ladi."),

"Telegram bot: to'liq boshqaruv paneli": T(
 "Telegram botni to'liq boshqaruv interfeysiga aylantirish",
 ["Klaviatura (keyboard) tugmalari foydalanuvchiga tayyor variantlarni ko'rsatadi va buyruq yozish kerak bo'lmaydi.",
  "Inline klaviatura xabar ostida chiqadi va bosilganda callback yuboradi — bu interaktiv panel yasashga imkon beradi.",
  "Menyu tuzilmasi holat mashinasi bilan boshqariladi: har foydalanuvchi qaysi bo'limda ekani eslab qolinadi.",
  "Xavfsizlik: har buyruqda chat ID tekshiriladi. Ruxsat berilgan ID lar ro'yxati kodda saqlanadi."],
 "Inline klaviatura bilan panel yasashni ko'rsating — natija professional ko'rinadi va o'quvchilarni juda ilhomlantiradi.",
 [("Inline klaviatura nima beradi?", "Xabar ostida interaktiv tugmalar."),
  ("Menyu holati qanday boshqariladi?", "Holat mashinasi bilan.")],
 "Har buyruqda chat ID ni tekshirmaslik."),

"Ogohlantirish tizimi (alert)": T(
 "Ko'p darajali ogohlantirish tizimini loyihalab, amalga oshirish",
 ["Ogohlantirish darajalari: ma'lumot (info), ogohlantirish (warning), xavf (critical). Har darajaga o'z javobi.",
  "Takroriy xabarlarning oldini olish: bayroq va minimal interval (masalan bir soatda bir marta).",
  "Eskalatsiya: agar muammo hal bo'lmasa, ogohlantirish darajasi oshadi yoki boshqa kanalga yuboriladi.",
  "Normal holatga qaytganda ham xabar berish kerak — foydalanuvchi muammo tugaganini bilishi lozim."],
 "Normal holatga qaytish xabarini ta'kidlang — bu ko'p unutiladi, lekin foydalanuvchi uchun ogohlantirishning o'zi kabi muhim.",
 [("Nega minimal interval qo'yiladi?", "Takroriy xabarlar bilan spam qilmaslik uchun."),
  ("Normal holatga qaytganda nima qilinadi?", "Bu haqda ham xabar beriladi.")],
 "Faqat muammo boshlanganda xabar berib, hal bo'lganini aytmaslik."),

"BLE bilan telefonga ulanish": T(
 "BLE orqali telefon ilovasi bilan ma'lumot almashish",
 ["BLE tuzilmasi: Service (xizmat) ichida Characteristic (xususiyat). Har biriga UUID.",
  "Characteristic xossalari: read (o'qish), write (yozish), notify (o'zgarganda avtomatik xabar).",
  "Notify eng samarali: telefon so'rab turishi kerak emas, qurilma o'zi yuboradi.",
  "Sinov uchun nRF Connect ilovasi. O'z ilovasini yozish uchun MIT App Inventor sodda variant beradi."],
 "MIT App Inventor ni tavsiya qiling — u blokli muhit bo'lgani uchun o'quvchilar tez ilova yasay oladi va bu kuchli motivatsiya.",
 [("Notify nima beradi?", "Qiymat o'zgarganda telefonga avtomatik xabar."),
  ("BLE da ma'lumot qanday tashkil qilinadi?", "Service ichida Characteristic.")],
 "Telefon tomonidan doim so'rab turish (polling) — batareya behuda sarflanadi."),

"Bir nechta qurilmali tarmoq (mesh g'oyasi)": T(
 "Bir necha qurilmadan iborat tarmoq loyihalab, aloqa sxemasini chizish",
 ["Yulduz (star) topologiyasi: barcha qurilmalar markazga (router yoki broker) ulanadi. Sodda, lekin markaz ishdan chiqsa hammasi to'xtaydi.",
  "Mesh topologiyasi: qurilmalar bir-biri orqali xabar uzatadi. Masofa kengayadi va ishonchlilik oshadi.",
  "ESP-MESH (painlessMesh kutubxonasi) ESP32 uchun mesh tarmoq quradi.",
  "Mesh murakkabroq: kechikish oshadi, quvvat ko'proq sarflanadi va nosozlik topish qiyinlashadi. U faqat zarur bo'lganda tanlanadi."],
 "Ikki topologiyani chizib solishtiring: afzallik va kamchiliklari. Arxitektura tanlash — muhandislik qarorining eng yuqori darajasi.",
 [("Mesh topologiyasining afzalligi nima?", "Masofa kengayadi va ishonchlilik oshadi."),
  ("Uning kamchiligi nima?", "Murakkabroq, kechikish va quvvat sarfi ko'proq.")],
 "Oddiy vazifa uchun mesh tanlash — ortiqcha murakkablik."),

"Xavfsizlik: parol, shifrlash asoslari": T(
 "Loyihadagi zaifliklarni aniqlab, himoya choralarini amalga oshirish",
 ["Asosiy zaifliklar: kodda ochiq parol, autentifikatsiyasiz API, shifrlanmagan aloqa, yangilanmaydigan dastur.",
  "Parollarni alohida faylda (secrets.h) saqlash va uni ochiq joyga qo'ymaslik.",
  "TLS/SSL aloqani shifrlaydi. ESP32 buni qo'llab-quvvatlaydi, lekin sertifikat kerak va xotira ko'proq talab qiladi.",
  "Xesh funksiyasi: parolni ochiq saqlash o'rniga uning xeshi saqlanadi. Xeshdan asl parolni tiklab bo'lmaydi."],
 "Xesh tushunchasini oddiy misolda ko'rsating — bu parol saqlashning to'g'ri usuli va kiberxavfsizlikning asosiy g'oyalaridan biri.",
 [("Xesh funksiyasining xossasi nima?", "Undan asl qiymatni tiklab bo'lmaydi."),
  ("Parollar qayerda saqlanadi?", "Alohida faylda, ochiq joyga qo'yilmaydigan.")],
 "Parolni kodda ochiq saqlab, loyihani ommaga ochiq joyga yuklash."),

"OTA: masofadan dastur yangilash": T(
 "OTA orqali dasturni simsiz yangilab, jarayonni tahlil qilish",
 ["OTA (Over The Air) — dasturni WiFi orqali yangilash. ArduinoOTA kutubxonasi bilan amalga oshiriladi.",
  "Flesh xotira ikki qismga bo'linadi: joriy dastur va yangisi. Yuklash tugagach qurilma yangisiga o'tadi.",
  "Shuning uchun dastur hajmi flesh xotiraning yarmidan oshmasligi kerak.",
  "Xavfsizlik: OTA ga parol qo'yish shart. Aks holda tarmoqdagi istalgan odam qurilmaga o'z dasturini yuklashi mumkin."],
 "OTA parolini majburiy qiling — parolsiz OTA qurilmani to'liq egallash imkonini beradi va bu jiddiy zaiflik.",
 [("Nega dastur hajmi fleshning yarmidan oshmasligi kerak?", "Yangi dastur uchun joy kerak."),
  ("OTA da qanday himoya kerak?", "Parol.")],
 "OTA ni parolsiz qoldirish."),

"Tizim arxitekturasini chizish": T(
 "Loyiha arxitekturasini bir necha darajada chizib, hujjatlashtirish",
 ["Arxitektura chizmasi tizim qismlarini va ular orasidagi aloqalarni ko'rsatadi.",
  "Darajalar: kontekst (tizim va tashqi dunyo), konteyner (asosiy qismlar), komponent (har qismning ichi).",
  "Har aloqada uzatiladigan ma'lumot va protokol ko'rsatiladi: \"ESP32 -> broker: harorat, MQTT\".",
  "Yaxshi arxitektura chizmasining mezoni: yangi odam uni ko'rib, tizim qanday ishlashini tushunishi."],
 "Uch darajali chizmani birgalikda chizing. Bu murakkab tizimni tushunish va tushuntirishning eng samarali usuli.",
 [("Arxitektura chizmasida nima ko'rsatiladi?", "Qismlar va ular orasidagi aloqalar."),
  ("Aloqada nima yoziladi?", "Uzatiladigan ma'lumot va protokol.")],
 "Faqat komponentlarni chizib, aloqalarni ko'rsatmaslik."),

"Nosozlikka chidamlilik (qayta ulanish)": T(
 "Tizimni uzilishlarga chidamli qilish uchun qayta ulanish mantiqini yozish",
 ["Uzilish muqarrar: WiFi uziladi, broker javob bermaydi, sensor xato beradi. Tizim buni ko'tara olishi kerak.",
  "Qayta ulanish mantiqida ORTIB BORUVCHI kutish (exponential backoff) ishlatiladi: 1 s, 2 s, 4 s, 8 s. Bu tarmoqni bo'g'ib qo'ymaydi.",
  "Watchdog taymer: dastur qotib qolsa qurilmani avtomatik qayta yuklaydi. ESP32 da o'rnatilgan.",
  "Ma'lumotni yo'qotmaslik: aloqa yo'q bo'lganda ma'lumot buferga yoki SD kartga saqlanadi va aloqa tiklangach yuboriladi."],
 "Ortib boruvchi kutish g'oyasini ta'kidlang — har sekundda qayta urinish tarmoqni bo'g'adi va bu keng tarqalgan xato.",
 [("Exponential backoff nima?", "Qayta urinishlar orasidagi vaqtni ortib boruvchi qilish."),
  ("Watchdog taymer nima qiladi?", "Dastur qotib qolsa qurilmani qayta yuklaydi.")],
 "Har sekundda qayta ulanishga urinish — tarmoq bo'g'iladi."),

"Loglash va diagnostika": T(
 "Loglash tizimini qurib, nosozlikni log orqali tahlil qilish",
 ["Log — qurilmaning ish tarixi yozuvi. U nosozlik sabablarini aniqlashning asosiy manbai.",
  "Log darajalari: DEBUG (batafsil), INFO (odatiy hodisalar), WARNING (e'tibor talab qiladi), ERROR (xato).",
  "Har yozuvda vaqt belgisi bo'lishi shart — usiz hodisalar ketma-ketligini tiklab bo'lmaydi.",
  "Saqlash joyi: Serial (faqat ulangan holda), SD kart (uzoq muddat), bulut (masofadan ko'rish)."],
 "Log darajalarini ishlatishni o'rgating: ishlab chiqarishda DEBUG o'chiriladi, aks holda log fayli tez to'ladi va foydasiz bo'ladi.",
 [("Nega logda vaqt belgisi kerak?", "Hodisalar ketma-ketligini tiklash uchun."),
  ("Ishlab chiqarishda qaysi daraja o'chiriladi?", "DEBUG.")],
 "Vaqt belgisiz log yozish — tahlil qilib bo'lmaydi."),

"Tizimni sinovdan o'tkazish": T(
 "To'liq sinov rejasini tuzib, tizimni bosqichma-bosqich sinash",
 ["Sinov turlari: funksional (imkoniyatlar ishlaydimi), integratsion (qismlar birga ishlaydimi), yuklamali (uzoq va og'ir sharoitda), tiklanish (uzilishdan keyin).",
  "Sinov rejasi jadval: nima sinaladi, qanday qadamlar, kutilgan natija, haqiqiy natija, holat.",
  "Regressiya sinovi: har tuzatishdan keyin oldingi sinovlar qayta bajariladi.",
  "Qabul mezonlari oldindan belgilanadi: tizim qanday shartlarda tayyor deb hisoblanadi."],
 "Sinov rejasini jadval shaklida tuzdiring. Bu professional dasturiy ta'minot ishlab chiqishning standart amaliyoti.",
 [("Regressiya sinovi nima?", "Tuzatishdan keyin oldingi sinovlarni qayta bajarish."),
  ("Qabul mezonlari qachon belgilanadi?", "Oldindan, sinovdan avval.")],
 "Sinov rejasisiz, tasodifiy sinash."),

# ==================================================== 3-CHORAK: Mashinaviy o'rganish va TinyML
"SI, mashinaviy o'rganish va chuqur o'rganish": T(
 "Uch tushunchani misollar bilan ajratib, tarixiy rivojlanishini chizish",
 ["SI — inson aqliy vazifalarini bajaruvchi tizimlar sohasi. 1950-yillardan beri rivojlanmoqda.",
  "ML — SI ning bir qismi: qoidalar qo'lda emas, ma'lumotdan o'rganiladi.",
  "DL — ML ning bir qismi: ko'p qatlamli neyron tarmoqlar. 2012-yildan keyin keskin rivojlandi.",
  "Rivojlanish sabablari: katta ma'lumot, kuchli hisoblash quvvati (GPU) va yaxshilangan algoritmlar. Uchtasi birga kerak bo'ldi."],
 "Uch omil (ma'lumot, quvvat, algoritm) haqidagi fikrni ta'kidlang — bu texnologiya nima uchun aynan hozir rivojlanganini tushuntiradi.",
 [("DL ML ning bir qismimi?", "Ha."),
  ("DL ning rivojlanishiga nima sabab bo'ldi?", "Katta ma'lumot, GPU quvvati va yaxshilangan algoritmlar.")],
 "SI, ML va DL ni sinonim sifatida ishlatish."),

"Nazorat ostida va nazoratsiz o'rganish": T(
 "Ikki turdagi o'rganishga misollar topib, jadval tuzish",
 ["Nazorat ostida (supervised): ma'lumotda to'g'ri javob bor. Model kirish va javob orasidagi bog'liqlikni o'rganadi.",
  "Nazoratsiz (unsupervised): to'g'ri javob yo'q. Model ma'lumotdagi tuzilmani o'zi topadi — masalan guruhlarga bo'ladi (klasterlash).",
  "Anomaliya aniqlash ko'pincha nazoratsiz: normal holatlar o'rganiladi va ulardan farq qiladigan holat anomaliya deb belgilanadi.",
  "TinyML da ikkalasi ham ishlatiladi: tasnif — nazorat ostida, nosozlik sezish — ko'pincha nazoratsiz."],
 "Anomaliya aniqlash misolini ta'kidlang: uni nazoratsiz qilish afzal, chunki barcha nosozlik turlarini oldindan yig'ib bo'lmaydi.",
 [("Nazorat ostida o'rganishda nima bor?", "Ma'lumotda to'g'ri javob."),
  ("Nega anomaliya aniqlash nazoratsiz qilinadi?", "Barcha nosozlik turlarini oldindan yig'ib bo'lmaydi.")],
 "Anomaliya aniqlash uchun barcha nosozlik turlarini yig'ishga urinish."),

"Neyron tarmoq g'oyasi: oddiy tushuntirish": T(
 "Bitta neyron ishlashini qog'ozda hisoblab, tarmoq tuzilmasini chizish",
 ["Neyron: kirishlar o'z og'irliklariga ko'paytiriladi, yig'iladi, siljish qo'shiladi va aktivatsiya funksiyasidan o'tkaziladi.",
  "Formula: chiqish = f(w1*x1 + w2*x2 + ... + b). f — aktivatsiya funksiyasi (masalan ReLU: manfiy bo'lsa 0, aks holda o'zi).",
  "Tarmoq — neyronlarning qatlamlari. Kirish qatlami, yashirin qatlamlar, chiqish qatlami.",
  "O'rganish — og'irliklarni (w) sozlash jarayoni. Xato hisoblanadi va og'irliklar uni kamaytiradigan tomonga siljiydi."],
 "Bitta neyronni qog'ozda qo'lda hisoblatish — bu neyron tarmoqni sehrli qutidan matematik amalga aylantiradi va qo'rquvni yo'qotadi.",
 [("Neyron nima qiladi?", "Kirishlarni og'irliklarga ko'paytirib yig'adi va aktivatsiyadan o'tkazadi."),
  ("O'rganish nima?", "Og'irliklarni sozlash jarayoni.")],
 "Neyron tarmoqni tushunib bo'lmaydigan \"qora quti\" deb hisoblash."),

"TinyML: mikrokontrollerda model": T(
 "TinyML cheklovlarini hisoblab, model talablarini aniqlash",
 ["TinyML — ML modellarini mikrokontrollerda ishlatish. Cheklovlar: xotira (kilobaytlar), quvvat (milliamperlar), hisoblash quvvati.",
  "Odatiy TinyML modeli 20-200 KB. Bulutdagi modellar esa gigabaytlar bo'lishi mumkin.",
  "Afzalliklari: kechikish yo'q (internet kerak emas), maxfiylik (ma'lumot chiqmaydi), kam quvvat, arzon.",
  "Cheklovi: model sodda bo'lishi kerak. Murakkab vazifalar (tabiiy tilni tushunish) mikrokontrollerda bajarilmaydi."],
 "Afzallik va cheklovlarni jadval qilib solishtiring. Texnologiyaning chegaralarini bilish uni to'g'ri qo'llashning sharti.",
 [("Odatiy TinyML modeli qancha joy egallaydi?", "20-200 kilobayt."),
  ("TinyML ning uch afzalligi nima?", "Kechikish yo'q, maxfiylik, kam quvvat.")],
 "Mikrokontrollerda murakkab modellarni ishlatishga urinish."),

"Edge Impulse: to'liq ish oqimi": T(
 "To'liq ish oqimini boshdan oxirigacha bir loyihada bajarish",
 ["Ish oqimi: Data acquisition -> Impulse design -> Feature generation -> Training -> Model testing -> Deployment.",
  "Impulse — ma'lumotni qayta ishlash zanjiri: kirish bloki, belgi ajratish bloki, o'rganish bloki.",
  "Belgi ajratish bloki ma'lumot turiga qarab tanlanadi: Spectral Analysis (harakat), MFCC (ovoz), Image (tasvir).",
  "Har bosqichda natijani ko'rish mumkin — bu qaysi bosqichda muammo borligini aniqlashga yordam beradi."],
 "Har bosqichda natijani ko'rish odatini o'rnating — bu ML da nosozlik topishning asosiy usuli va ko'r-ko'rona ishlashdan qutqaradi.",
 [("Impulse nima?", "Ma'lumotni qayta ishlash zanjiri."),
  ("Ovoz uchun qanday belgi ajratish bloki ishlatiladi?", "MFCC yoki MFE.")],
 "Belgi ajratish blokini vazifaga mos kelmaydigan qilib tanlash."),

"Ma'lumot to'plash strategiyasi": T(
 "Loyiha uchun ma'lumot to'plash rejasini tuzib, amalga oshirish",
 ["Reja tuziladi: qanday sinflar, har biriga nechta namuna, kim va qanday sharoitda yig'adi.",
  "Xilma-xillik ataylab rejalashtiriladi: turli odamlar, vaqt, joy, sharoit.",
  "Real sharoitga yaqin ma'lumot yig'ish shart. Ideal sharoitda yig'ilgan ma'lumot real ishlashda foyda bermaydi.",
  "Ma'lumot yig'ish loyiha vaqtining eng katta qismini oladi — buni rejaga kiritish kerak."],
 "Real sharoit talabini ta'kidlang: laboratoriyada mukammal yig'ilgan dataset ko'chada ishlamaydi. Bu ML loyihalarining eng ko'p uchraydigan muvaffaqiyatsizlik sababi.",
 [("Ma'lumot qanday sharoitda yig'ilishi kerak?", "Real ishlash sharoitiga yaqin."),
  ("Ma'lumot yig'ish loyiha vaqtining qancha qismini oladi?", "Eng katta qismini.")],
 "Ideal, laboratoriya sharoitida ma'lumot yig'ish."),

"Ma'lumot sifati va muvozanati": T(
 "Datasetni tahlil qilib, muvozanat va sifat muammolarini aniqlash",
 ["Muvozanat: har sinfdan taxminan teng miqdorda namuna. Nomutanosib datasetda model ko'p uchraydigan sinfni afzal ko'radi.",
  "Misol: 95% normal va 5% nosoz namuna bo'lsa, model hammani \"normal\" desa ham 95% aniqlik oladi — lekin foydasiz.",
  "Shuning uchun nomutanosib datasetda aniqlik emas, boshqa ko'rsatkichlar (precision, recall, F1) ishlatiladi.",
  "Yechimlar: kam sinf uchun ko'proq ma'lumot yig'ish, ko'p sinfdan kamaytirish yoki og'irlik berish."],
 "95% aniqlik misolini albatta ko'rsating — bu statistikaning eng muhim va eng ko'p chalg'itadigan tuzog'i.",
 [("Nomutanosib datasetda aniqlik nega aldamchi?", "Model faqat ko'p sinfni tanlab ham yuqori foiz oladi."),
  ("Yechim nima?", "Ma'lumotni muvozanatlash yoki boshqa ko'rsatkichlar ishlatish.")],
 "Nomutanosib datasetda faqat aniqlikka qarab baholash."),

"Belgi ajratish (feature extraction)": T(
 "Turli belgi ajratish usullarini sinab, natijalarni solishtirish",
 ["Belgi ajratish — xom ma'lumotdan model uchun muhim xususiyatlarni hisoblash.",
  "Harakat uchun: o'rtacha, standart chetlanish, minimal, maksimal, spektral quvvat (chastota tahlili).",
  "Ovoz uchun: MFCC — inson eshitish xususiyatlarini hisobga oluvchi spektral belgilar.",
  "Yaxshi belgi tanlash modelni sodda va tez qiladi. Xom ma'lumotdan o'rgatish ko'proq ma'lumot va katta model talab qiladi."],
 "Belgi ajratish natijasini vizual ko'rsating (Edge Impulse feature explorer). Sinflar ajralib turishini ko'rish tushunchani ochadi.",
 [("Belgi ajratish nima qiladi?", "Xom ma'lumotdan muhim xususiyatlarni hisoblaydi."),
  ("Yaxshi belgi nima beradi?", "Model soddaroq va tezroq bo'ladi.")],
 "Belgi ajratishni o'tkazib, xom ma'lumotni to'g'ridan-to'g'ri modelga berish."),

"Model turini tanlash": T(
 "Turli model turlarini sinab, vazifaga mosini tanlash",
 ["Sodda modellar: mantiqiy regressiya, qaror daraxti. Kam resurs, tushunarli, lekin murakkab bog'liqliklarni topa olmaydi.",
  "Neyron tarmoq: murakkabroq bog'liqliklarni topadi, lekin ko'proq ma'lumot va resurs talab qiladi.",
  "Konvolyutsion tarmoq (CNN): tasvir va spektrogramma uchun. Fazoviy tuzilmani hisobga oladi.",
  "Tanlov mezoni: eng sodda model bilan boshlash. Agar u yetarli bo'lsa, murakkabini ishlatishning hojati yo'q."],
 "\"Eng sodda modeldan boshlash\" tamoyilini o'rnating — bu Occam ustarasining ML dagi ko'rinishi va juda muhim amaliy qoida.",
 [("Qaysi modeldan boshlash kerak?", "Eng soddasidan."),
  ("CNN qaysi ma'lumot turi uchun mos?", "Tasvir va spektrogramma uchun.")],
 "Darhol eng murakkab modelni tanlash."),

"O'rgatish parametrlari (epoch, learning rate)": T(
 "Parametrlarni o'zgartirib, ularning natijaga ta'sirini o'lchash",
 ["Epoch — butun dataset bo'ylab bir marta o'tish. Ko'p epoch yaxshiroq o'rganish beradi, lekin overfitting xavfi oshadi.",
  "Learning rate — og'irliklar har qadamda qancha o'zgarishi. Juda katta bo'lsa model yaqinlasha olmaydi, juda kichik bo'lsa o'rganish sekin.",
  "Batch size — bir vaqtda qayta ishlanadigan namunalar soni. Xotira va tezlikka ta'sir qiladi.",
  "Parametrlarni tanlash tajriba yo'li bilan bajariladi. Har o'zgarish natijasi yozib boriladi."],
 "Learning rate ni juda katta qilib sinab ko'rsating: o'rgatish grafigi sakraydi va yaqinlashmaydi. Bu parametrning ma'nosini yaqqol ochadi.",
 [("Epoch nima?", "Butun dataset bo'ylab bir marta o'tish."),
  ("Learning rate juda katta bo'lsa nima bo'ladi?", "Model yaqinlasha olmaydi.")],
 "Parametrlarni bir vaqtda bir necha o'zgartirib, ta'sirini aniqlay olmaslik."),

"Aniqlik, chalkashlik matritsasi, F1": T(
 "Turli ko'rsatkichlarni hisoblab, ularning ma'nosini tahlil qilish",
 ["Aniqlik (accuracy) — to'g'ri javoblar ulushi. Nomutanosib datasetda aldamchi.",
  "Precision — model \"ha\" degan holatlarning nechtasi haqiqatan \"ha\". Yolg'on ogohlantirish qimmat bo'lsa muhim.",
  "Recall — haqiqiy \"ha\" holatlarning nechtasini model topdi. Hodisani o'tkazib yuborish qimmat bo'lsa muhim.",
  "F1 — precision va recall ning garmonik o'rtachasi. Ikkalasini muvozanatlash kerak bo'lganda ishlatiladi."],
 "Precision va recall tanlovini vaziyatga bog'lab tushuntiring: yong'in signalizatsiyasida recall muhim, spam filtrida precision. Bu tushunchani amaliy qiladi.",
 [("Recall nimani o'lchaydi?", "Haqiqiy holatlarning nechtasi topilganini."),
  ("Yong'in signalizatsiyasida qaysi ko'rsatkich muhimroq?", "Recall — hodisani o'tkazib yubormaslik.")],
 "Faqat aniqlikka qarab modelni baholash."),

"Overfitting va uni oldini olish": T(
 "Overfitting'ni hosil qilib, turli usullar bilan bartaraf etish",
 ["Overfitting — model o'rgatish ma'lumotini yodlab, yangisida xato qilishi.",
  "Belgisi: o'rgatish aniqligi 99%, test aniqligi 60%. Katta farq aniq ishora.",
  "Sabablari: ma'lumot kam, model juda murakkab, o'rgatish juda uzoq.",
  "Yechimlar: ko'proq ma'lumot, soddaroq model, erta to'xtatish (early stopping), dropout, ma'lumotni sun'iy ko'paytirish."],
 "Overfitting'ni ataylab hosil qiling va har yechimni navbat bilan qo'llab, natijani o'lchang. Bu tizimli tajriba ko'nikmasini beradi.",
 [("Overfitting belgisi nima?", "O'rgatish va test aniqliklari orasidagi katta farq."),
  ("Dropout nima qiladi?", "O'rgatish paytida neyronlarning bir qismini tasodifiy o'chirib, yodlashning oldini oladi.")],
 "Faqat o'rgatish aniqligiga qarab modelni yaxshi deb hisoblash."),

"Modelni siqish va kvantlash": T(
 "Kvantlangan va kvantlanmagan modelni hajm, tezlik va aniqlik bo'yicha solishtirish",
 ["Kvantlash — parametrlarni float32 dan int8 ga o'tkazish. Hajm 4 marta kamayadi.",
  "Tezlik ham oshadi: butun sonli hisoblash mikrokontrollerda ancha tez bajariladi.",
  "Aniqlik odatda 1-2% pasayadi — bu deyarli har doim maqbul almashuv.",
  "Boshqa usullar: pruning (kam ahamiyatli bog'lanishlarni o'chirish), knowledge distillation (katta modeldan kichigini o'rgatish)."],
 "Uch ko'rsatkichni (hajm, tezlik, aniqlik) jadval qilib solishtiring. Muhandislik kelishuvini raqamlar bilan ko'rsatish eng ishonarli.",
 [("Kvantlash hajmni qancha kamaytiradi?", "Taxminan 4 marta."),
  ("Aniqlik qancha pasayadi?", "Odatda 1-2%.")],
 "Kvantlashdan qochib, model xotiraga sig'masligiga yo'l qo'yish."),

"Modelni qurilmaga joylash": T(
 "Modelni qurilmaga joylab, resurs sarfini o'lchash",
 ["Edge Impulse dan Arduino kutubxonasi olinadi va IDE ga qo'shiladi.",
  "Resurs sarfi o'lchanadi: flesh xotira (model hajmi), RAM (ishlash paytida), bashorat vaqti.",
  "Edge Impulse bu ko'rsatkichlarni oldindan bashorat qiladi, lekin real qurilmada tekshirish shart.",
  "RAM yetmasa dastur yuklanadi, lekin ishlash paytida qulaydi — bu topish qiyin xato."],
 "Real resurs sarfini o'lchashni majburiy qiling — bashorat va haqiqat farq qilishi mumkin va buni bilish muhim.",
 [("Qanday uch ko'rsatkich o'lchanadi?", "Flesh, RAM va bashorat vaqti."),
  ("RAM yetmasa nima bo'ladi?", "Dastur ishlash paytida qulaydi.")],
 "Faqat bashorat qilingan ko'rsatkichlarga ishonib, real o'lchov qilmaslik."),

"Real vaqtda ishlash va kechikish (latency)": T(
 "Bashorat vaqtini o'lchab, tizim javob tezligini hisoblash",
 ["Kechikish (latency) — kirish kelgandan javob chiqquncha o'tgan vaqt.",
  "U bir necha qismdan iborat: ma'lumot yig'ish, belgi ajratish, bashorat, javob.",
  "Ko'pincha eng ko'p vaqt ma'lumot yig'ishga ketadi: 1 sekundlik ovoz namunasi uchun kamida 1 sekund kerak.",
  "Real vaqt talabi vazifaga bog'liq: imo-ishora uchun 200 ms yetarli, xavfsizlik tizimi uchun tezroq kerak bo'lishi mumkin."],
 "Kechikishning tarkibiy qismlarini alohida o'lchatting. Qaysi qism ko'p vaqt olishini bilish optimallashtirishning birinchi qadami.",
 [("Kechikish nima?", "Kirish kelgandan javob chiqquncha o'tgan vaqt."),
  ("Odatda eng ko'p vaqt qayerga ketadi?", "Ma'lumot yig'ishga.")],
 "Faqat bashorat vaqtini o'lchab, ma'lumot yig'ish vaqtini hisobga olmaslik."),

"Xotira va tezlik cheklovlari": T(
 "Resurs byudjetini tuzib, model va dastur talablarini muvozanatlash",
 ["Resurs byudjeti: umumiy flesh va RAM qanday taqsimlanadi — model, kutubxonalar, buferlar, dastur.",
  "Kamera tasviri katta joy egallaydi: 96x96 rangli rasm ~27 KB. PSRAM shuning uchun kerak.",
  "Stek va uyum (heap) alohida: rekursiv funksiyalar va katta lokal massivlar stekni to'ldirishi mumkin.",
  "Muvozanat: model murakkabligini oshirish aniqlikni oshiradi, lekin resurs va tezlikni yomonlashtiradi."],
 "Resurs byudjeti jadvalini tuzdiring. Bu cheklangan resurs bilan ishlashning professional usuli va muhandislik tafakkurini shakllantiradi.",
 [("96x96 rangli rasm qancha joy egallaydi?", "Taxminan 27 kilobayt."),
  ("Model murakkabligini oshirish nimaga olib keladi?", "Aniqlik oshadi, lekin resurs va tezlik yomonlashadi.")],
 "Resurs byudjetini hisoblamasdan modelni kattalashtirish."),

"Modelni yaxshilash sikli": T(
 "Tizimli yaxshilash sikli o'tkazib, natijalarni hujjatlashtirish",
 ["Sikl: baholash -> kamchilikni aniqlash -> gipoteza -> o'zgartirish -> qayta baholash.",
  "Kamchilikni aniqlash uchun chalkashlik matritsasi va xato qilingan namunalarni ko'rib chiqish kerak.",
  "Xato namunalarni ko'rish ko'pincha eng foydali: ular orasida qonuniyat topilishi mumkin (masalan hammasi yomon yorug'likda).",
  "Har urinish yozib boriladi: versiya, o'zgarish, natija. Bu takroriy ishni oldini oladi va eng yaxshi variantni topishga yordam beradi."],
 "Xato qilingan namunalarni birgalikda ko'rib chiqing. Ular orasidagi qonuniyatni topish — ML da eng qimmatli tahlil ko'nikmasi.",
 [("Yaxshilash sikli qanday bosqichlardan iborat?", "Baholash, kamchilik, gipoteza, o'zgartirish, qayta baholash."),
  ("Xato namunalarni ko'rish nima beradi?", "Ular orasida qonuniyat topilishi mumkin.")],
 "Xato namunalarni ko'rmasdan, tasodifiy parametrlarni o'zgartirish."),

"AI axloqi: xolislik, maxfiylik, mas'uliyat": T(
 "Loyihadagi axloqiy masalalarni tahlil qilib, hujjatga kiritish",
 ["Xolislik (bias): dataset bir guruhdan yig'ilsa, model boshqalarda yomon ishlaydi. Bu real hodisa — yuzni tanish tizimlarida keng muhokama qilingan.",
  "Maxfiylik: shaxsiy ma'lumot (ovoz, tasvir) yig'ishda rozilik kerak. TinyML da ma'lumot qurilmada qolishi katta afzallik.",
  "Shaffoflik: model qanday qaror qabul qilgani tushunarli bo'lishi kerak, ayniqsa muhim qarorlarda.",
  "Mas'uliyat: model xato qilsa kim javobgar — ishlab chiquvchimi, foydalanuvchimi? Bu savolga oldindan javob bo'lishi kerak."],
 "Xolislik masalasini o'z datasetlari misolida tahlil qiling: kimlardan yig'ilgan, kimlarda yomon ishlashi mumkin. Bu tushunchani shaxsiy tajribaga bog'laydi.",
 [("Xolislik qanday paydo bo'ladi?", "Dataset bir xil guruhdan yig'ilsa."),
  ("TinyML ning maxfiylik afzalligi nima?", "Ma'lumot qurilmada qoladi.")],
 "Axloqiy masalalarni \"texnik emas\" deb e'tiborsiz qoldirish."),

# ==================================================== 4-CHORAK: Yakuniy muhandislik loyihasi
"Muammoni aniqlash va tadqiq qilish": T(
 "Real muammoni tanlab, uni tadqiq qilib, hujjatlashtirish",
 ["Muhandislik loyihasi muammodan boshlanadi, texnologiyadan emas. \"ESP32 bilan nima qilsam ekan\" — noto'g'ri boshlanish.",
  "Muammoni tadqiq qilish: kim duch keladi, qanchalik tez-tez, hozir qanday hal qilinmoqda, nima qoniqtirmaydi.",
  "Manbalar: kuzatish, suhbat, so'rovnoma, mavjud yechimlarni o'rganish.",
  "Muammo bayoni aniq yozilishi kerak: kim, qachon, nimaga duch keladi va oqibati qanday."],
 "\"Texnologiyadan emas, muammodan boshlash\" tamoyilini qat'iy o'rnating. Bu muhandislik va havaskorlik orasidagi asosiy farq.",
 [("Loyiha nimadan boshlanadi?", "Muammodan, texnologiyadan emas."),
  ("Muammo bayonida nima bo'lishi kerak?", "Kim, qachon, nimaga duch keladi va oqibati.")],
 "\"Bu texnologiya bilan nima qilsam ekan\" savolidan boshlash."),

"Foydalanuvchi ehtiyojini o'rganish": T(
 "Bo'lajak foydalanuvchilar bilan suhbat o'tkazib, ehtiyojlarni aniqlash",
 ["Foydalanuvchini o'rganish usullari: suhbat, kuzatish, so'rovnoma.",
  "Suhbatda ochiq savollar beriladi: \"buni qanday qilasiz?\" — \"bizning qurilmamiz yoqadimi?\" emas.",
  "Odamlar nima xohlashini aniq ayta olmaydi, lekin nima qiynayotganini yaxshi biladi. Shuning uchun muammoni so'rash kerak, yechimni emas.",
  "Foydalanuvchi portreti (persona) tuziladi: kim, qanday sharoitda, qanday tayyorgarlik bilan ishlatadi."],
 "Ochiq savol berish texnikasini mashq qildiring. Yopiq savollar javobni oldindan belgilaydi va foydasiz ma'lumot beradi.",
 [("Suhbatda qanday savol berilishi kerak?", "Ochiq savol — muammo haqida."),
  ("Nega yechimni so'rash noto'g'ri?", "Odamlar nima xohlashini aniq ayta olmaydi.")],
 "\"Bizning g'oyamiz yoqadimi?\" deb so'rash — javob deyarli doim ijobiy bo'ladi va foydasiz."),

"Texnik topshiriq yozish": T(
 "Loyiha uchun to'liq texnik topshiriq hujjatini yozish",
 ["Texnik topshiriq (TZ) — loyihaga qo'yiladigan talablar hujjati. U kelishuv asosi bo'lib xizmat qiladi.",
  "Tarkibi: maqsad, funksional talablar (nima qiladi), texnik talablar (qanday ko'rsatkichlar bilan), cheklovlar, qabul mezonlari.",
  "Har talab O'LCHANADIGAN bo'lishi kerak: \"tez ishlasin\" emas, \"javob vaqti 500 ms dan oshmasin\".",
  "Qabul mezonlari: loyiha qanday shartlarda bajarilgan hisoblanadi. Bu oldindan kelishilishi shart."],
 "O'lchanadigan talab yozish mashqini bering: noaniq talablarni aniq talablarga aylantirish. Bu ko'nikma har qanday kasbda kerak bo'ladi.",
 [("Talablar qanday bo'lishi kerak?", "O'lchanadigan."),
  ("Qabul mezonlari nima?", "Loyiha bajarilgan hisoblanadigan shartlar.")],
 "Noaniq talablar yozish — natijani baholab bo'lmaydi."),

"Yechim variantlarini solishtirish": T(
 "Uch yechim variantini mezonlar bo'yicha solishtirib, tanlovni asoslash",
 ["Kamida uch variant ko'rib chiqiladi. Birinchi kelgan g'oya kamdan-kam eng yaxshisi bo'ladi.",
  "Solishtirish jadvali: mezonlar (narx, murakkablik, ishonchlilik, vaqt) va har variant bo'yicha baho.",
  "Mezonlarga og'irlik berish mumkin: ba'zilari muhimroq. Og'irlikli yig'indi tanlovni asoslaydi.",
  "Tanlov sababi yozib qo'yiladi — keyinchalik \"nega shunday qilingan?\" savoliga javob bo'ladi."],
 "Uch variant talabini qat'iy qo'ying. Bitta g'oyaga darhol yopishib olish — eng ko'p uchraydigan loyihalash xatosi.",
 [("Kamida nechta variant ko'rib chiqiladi?", "Uchta."),
  ("Nega tanlov sababi yoziladi?", "Keyinchalik qarorni tushuntirish uchun.")],
 "Birinchi g'oyaga yopishib, boshqa variantlarni ko'rib chiqmaslik."),

"Tizim arxitekturasini loyihalash": T(
 "Loyiha arxitekturasini bir necha darajada chizib, hujjatlashtirish",
 ["Arxitektura — tizim qismlari va ular orasidagi aloqalar.",
  "Darajalar: kontekst (tizim va tashqi dunyo), konteyner (asosiy qismlar), komponent (qismlarning ichi).",
  "Har aloqada ma'lumot va protokol ko'rsatiladi.",
  "Arxitektura qarorlari yozib boriladi: nima tanlandi, nima uchun, qanday muqobillar rad etildi."],
 "Arxitektura qarorlari yozuvini (ADR) kiriting — bu professional amaliyot va o'quvchilarni tizimli fikrlashga o'rgatadi.",
 [("Arxitekturada nima ko'rsatiladi?", "Qismlar va ular orasidagi aloqalar."),
  ("Nega qarorlar yozib boriladi?", "Keyinchalik sababni tushuntirish uchun.")],
 "Arxitekturani chizmasdan darhol yig'ishga kirishish."),

"Komponentlarni tanlash va asoslash": T(
 "Har komponent uchun kamida ikki variantni solishtirib, tanlovni asoslash",
 ["Tanlash mezonlari: texnik moslik (kuchlanish, tok, protokol), mavjudlik, narx, hujjat sifati, jamoa qo'llab-quvvatlashi.",
  "Datasheet o'qiladi: Absolute Maximum Ratings va ish sharoitlari tekshiriladi.",
  "Zaxira qoldiriladi: ishchi qiymat maksimalning 50-70% idan oshmasin.",
  "Komponentlar ro'yxati (BOM) tuziladi: nomi, nominali, soni, narxi, manbasi."],
 "Hujjat sifati mezonini ta'kidlang — yaxshi hujjatlangan va keng ishlatiladigan komponent arzonroq va murakkabroq muqobildan afzal.",
 [("Zaxira qoidasi qanday?", "Ishchi qiymat maksimalning 50-70% idan oshmasin."),
  ("BOM da nima bo'ladi?", "Nomi, nominali, soni, narxi, manbasi.")],
 "Faqat narxga qarab komponent tanlash."),

"Sxemani chizish": T(
 "Loyihaning to'liq printsipial sxemasini chizib, tekshirish",
 ["Printsipial sxema barcha ulanishlarni ko'rsatadi. U montaj va nosozlik topish uchun asosiy hujjat.",
  "Chizish qoidalari: standart belgilar, komponentlarga belgi va nominal, quvvat yuqorida, GND pastda, simlar kam kesishsin.",
  "Quvvat taqsimoti alohida ko'rsatiladi: qaysi qism qaysi manbadan quvvat oladi.",
  "Sxema tekshiriladi: har komponentning har oyog'i ulanganmi, quvvat va GND to'g'rimi, himoya elementlari bormi."],
 "Sxemani boshqa guruhga tekshirtiring. Yangi ko'z xatolarni ancha yaxshi topadi — bu peer review amaliyoti.",
 [("Sxemada quvvat qayerda chiziladi?", "Yuqorida, GND pastda."),
  ("Sxema qanday tekshiriladi?", "Har oyoq ulanganmi, quvvat va himoya to'g'rimi.")],
 "Sxemasiz to'g'ridan-to'g'ri yig'ishga kirishish."),

"Prototipni yig'ish (1-bosqich)": T(
 "Prototipning birinchi bosqichini yig'ib, asosiy qismlarni sinash",
 ["Birinchi bosqichda asosiy zanjir yig'iladi: quvvat, mikrokontroller va bitta sensor.",
  "Har komponent qo'shilgach sinaladi — birdan hammasini yig'ish xatoni topishni imkonsiz qiladi.",
  "Quvvat birinchi tekshiriladi: kuchlanishlar to'g'rimi, isish bormi, iste'mol kutilganchami.",
  "Yig'ilgan holat suratga olinadi va sxema bilan solishtiriladi. Bu hujjatning bir qismi bo'ladi."],
 "Suratga olishni odat qiling — keyinchalik qayta yig'ishda va hujjatlashda bu suratlar juda foydali bo'ladi.",
 [("Birinchi navbatda nima tekshiriladi?", "Quvvat — kuchlanishlar va iste'mol."),
  ("Komponentlar qanday qo'shiladi?", "Bittalab, har biri sinalgach.")],
 "Hammasini birdan yig'ib, ishlamasa qayerdan izlashni bilmay qolish."),

"Dasturni yozish (1-bosqich)": T(
 "Dasturning asosiy qismini yozib, sinab ko'rish",
 ["Birinchi bosqichda asosiy oqim yoziladi: sensorni o'qish, qiymatni ko'rsatish.",
  "Kod modullarga bo'linadi: har vazifa uchun alohida funksiya yoki fayl.",
  "Har funksiya alohida sinaladi. Serial orqali qiymatlarni chiqarish majburiy.",
  "Ishlaydigan versiya saqlanadi. Keyingi bosqichda muammo chiqsa unga qaytish mumkin."],
 "Versiya saqlashni majburiy qiling. Bu yakuniy loyihada ayniqsa muhim — vaqt kam va yo'qotilgan ishni tiklashga imkon bo'lmaydi.",
 [("Kod qanday tuziladi?", "Modullarga bo'lib, har vazifa uchun alohida funksiya."),
  ("Nega versiya saqlanadi?", "Muammo chiqsa ishlaydigan variantga qaytish uchun.")],
 "Butun dasturni bir yo'la yozib, keyin sinashga urinish."),

"AI modelini o'rgatish va integratsiya": T(
 "Loyiha uchun modelni o'rgatib, dasturga integratsiya qilish",
 ["Model alohida o'rgatiladi va sinaladi, keyin dasturga qo'shiladi.",
  "Integratsiya bosqichlari: kutubxonani qo'shish, ma'lumotni model kutgan formatga keltirish, bashoratni olish, natijani qayta ishlash.",
  "Ma'lumot formati muhim: model o'rgatishda ishlatilgan formatga aynan mos bo'lishi kerak (namuna chastotasi, o'lcham, tartib).",
  "Bashorat natijasi chegara bilan filtrlanadi — ishonchsiz natijalar rad etiladi."],
 "Format mosligini ta'kidlang: o'rgatish va ishlatishda ma'lumot boshqacha tayyorlansa, model butunlay noto'g'ri ishlaydi va sabab topilmaydi.",
 [("Ma'lumot formati nimaga mos bo'lishi kerak?", "O'rgatishda ishlatilgan formatga."),
  ("Bashorat natijasi bilan nima qilinadi?", "Chegara bilan filtrlanadi.")],
 "O'rgatish va ishlatishda ma'lumotni turlicha tayyorlash."),

"Birinchi sinov va o'lchov": T(
 "Prototipni to'liq sinovdan o'tkazib, ko'rsatkichlarni o'lchash",
 ["Sinov rejasi bo'yicha bajariladi: har talab alohida tekshiriladi va natija yoziladi.",
  "O'lchanadigan ko'rsatkichlar: aniqlik, javob vaqti, iste'mol, ishlash muddati.",
  "Real sharoitda sinash shart — laboratoriya sharoitidagi natija aldamchi bo'lishi mumkin.",
  "Natijalar texnik topshiriqdagi talablar bilan solishtiriladi: qaysi talab bajarildi, qaysi biri yo'q."],
 "Natijalarni TZ bilan solishtirishni majburiy qiling. Bu obyektiv baholashning yagona usuli va \"ishladi\" degan noaniq javobni yo'q qiladi.",
 [("Natijalar nima bilan solishtiriladi?", "Texnik topshiriqdagi talablar bilan."),
  ("Qayerda sinash kerak?", "Real ishlash sharoitida.")],
 "Faqat laboratoriya sharoitida sinash."),

"Kamchiliklarni aniqlash": T(
 "Sinov natijalarini tahlil qilib, kamchiliklar ro'yxatini tuzish",
 ["Kamchiliklar ro'yxati: tavsif, qanday sharoitda yuzaga keladi, muhimlik darajasi, taxminiy sabab.",
  "Muhimlik darajalari: kritik (tizim ishlamaydi), jiddiy (asosiy vazifa buziladi), o'rtacha, kichik.",
  "Ustuvorlik: kritik va jiddiylar birinchi hal qilinadi. Barcha kamchilikni tuzatishga vaqt yetmasligi mumkin.",
  "Har kamchilik uchun takrorlash qadamlari yoziladi — usiz tuzatilganini tekshirib bo'lmaydi."],
 "Muhimlik bo'yicha saralashni o'rgating: vaqt cheklangan va nimani tuzatmaslikni tanlash ham qaror qabul qilishdir.",
 [("Kamchiliklar qanday saralanadi?", "Muhimlik darajasi bo'yicha."),
  ("Nega takrorlash qadamlari yoziladi?", "Tuzatilganini tekshirish uchun.")],
 "Barcha kamchilikni bir xil muhim deb hisoblash."),

"Yaxshilash va qayta sinash": T(
 "Kamchiliklarni tuzatib, regressiya sinovini o'tkazish",
 ["Tuzatish ustuvorlik bo'yicha bajariladi. Har tuzatishdan keyin uning ishlaganini tekshirish shart.",
  "Regressiya sinovi: tuzatish boshqa joyni buzmaganini tekshirish uchun oldingi sinovlar qayta bajariladi.",
  "Bir vaqtda bitta kamchilik tuzatiladi — bir necha o'zgarish birga kiritilsa, muammo chiqqanda sababini topib bo'lmaydi.",
  "Tuzatilgan versiya saqlanadi va o'zgarishlar ro'yxati yuritiladi."],
 "Regressiya sinovini majburiy qiling — bu yakuniy loyihada ayniqsa muhim, chunki oxirgi tuzatish butun tizimni buzishi mumkin.",
 [("Regressiya sinovi nima?", "Tuzatish boshqa joyni buzmaganini tekshirish."),
  ("Bir vaqtda nechta kamchilik tuzatiladi?", "Bittasi.")],
 "Bir necha tuzatishni birga kiritib, keyin sinash."),

"Korpus va yakuniy montaj": T(
 "Loyihani yakuniy korpusga joylashtirib, mustahkam montaj qilish",
 ["Korpus talablari: himoya, xavfsizlik, foydalanish qulayligi, isishni chiqarish, antenna uchun joy.",
  "Montaj tartibi: boshqaruv elementlari, ekran, plata, simlar, batareya.",
  "Simlar mahkamlanadi va birkalanadi. Harakatlanuvchi qismlarga tegmasligi tekshiriladi.",
  "Yakuniy tekshiruv: silkitish sinovi, uzoq ishlatish, isishni o'lchash."],
 "Silkitish sinovini albatta o'tkazing — bu chala ulanishlarni topishning eng tez usuli va taqdimotdan oldin muammoni oldini oladi.",
 [("Korpusda antenna uchun nima hisobga olinadi?", "Metall qismlar signalni to'sadi."),
  ("Yakuniy tekshiruvga nima kiradi?", "Silkitish, uzoq ishlatish, isish.")],
 "Antennani metall qismlar orasiga joylashtirish."),

"Foydalanuvchi qo'llanmasi yozish": T(
 "Qurilma uchun to'liq foydalanuvchi qo'llanmasi yozish",
 ["Qo'llanma foydalanuvchi uchun yoziladi — texnik atamalar minimal.",
  "Tarkibi: qurilma nima qiladi, tarkibi, ishga tushirish, boshqaruv, sozlash, xavfsizlik, muammolar va yechimlar.",
  "\"Muammolar va yechimlar\" eng foydali bo'lim: eng ko'p uchraydigan holatlar va ularning yechimi.",
  "Rasm va chizmalar matn bilan birga bo'lsa tushunish ancha oson bo'ladi."],
 "Qo'llanmani boshqa sinf o'quvchisiga sinatib ko'ring — tushunmasa qo'llanma yaxshi emas. Bu eng adolatli sinov.",
 [("Qo'llanma kim uchun yoziladi?", "Foydalanuvchi uchun."),
  ("Qaysi bo'lim eng foydali?", "Muammolar va yechimlar.")],
 "Texnik atamalar bilan to'ldirilgan qo'llanma yozish."),

"Texnik hujjat tayyorlash": T(
 "Loyihaning to'liq texnik hujjatini yig'ib, rasmiylashtirish",
 ["Texnik hujjat tarkibi: TZ, arxitektura, sxema, BOM, kod (izohli), model tavsifi, sinov natijalari, cheklovlar.",
  "Hujjat boshqa muhandis loyihani davom ettira olishi uchun yetarli bo'lishi kerak.",
  "Qarorlar va ularning sabablari yoziladi — bu hujjatning eng qimmatli qismi.",
  "Cheklovlar va kelajakdagi yaxshilash yo'llari alohida bo'limda beriladi."],
 "\"Boshqa muhandis davom ettira oladimi?\" mezonini qo'ying. Bu hujjat sifatining aniq va tekshiriladigan o'lchovi.",
 [("Hujjatning eng qimmatli qismi nima?", "Qarorlar va ularning sabablari."),
  ("Hujjat sifatining mezoni nima?", "Boshqa muhandis loyihani davom ettira olishi.")],
 "Faqat natijani hujjatlashtirib, qarorlar sababini yozmaslik."),

"Taqdimot va himoyaga tayyorgarlik": T(
 "Yakuniy taqdimotni tayyorlab, mashq qilish va savollarga tayyorlanish",
 ["Taqdimot tuzilishi: muammo, tadqiq natijalari, yechim, arxitektura, namoyish, sinov natijalari, cheklovlar, xulosa.",
  "Vaqt taqsimoti oldindan rejalanadi. Namoyish uchun vaqtning kamida uchdan biri qoldiriladi.",
  "Zaxira video majburiy — jonli namoyish buzilishi juda ko'p uchraydi.",
  "Ehtimolli savollarga tayyorgarlik: nima uchun shu yechim, qanday muqobillar bor edi, qanday cheklovlar bor."],
 "Uchta ehtimolli savolga oldindan tayyorlanishni talab qiling. Bu himoyaga ishonch beradi va o'z ishini chuqurroq tushunishga majbur qiladi.",
 [("Namoyishga vaqtning qancha qismi ajratiladi?", "Kamida uchdan biri."),
  ("Nega zaxira video kerak?", "Jonli namoyish buzilishi mumkin.")],
 "Mashq qilmasdan va zaxirasiz taqdimotga chiqish."),

"Boshqa loyihalarni baholash (peer review)": T(
 "Boshqa guruhlarning loyihalarini mezonlar bo'yicha baholash",
 ["Baholash mezonlari oldindan e'lon qilinadi: muammoning dolzarbligi, yechimning texnik darajasi, ishlashi, hujjat, taqdimot.",
  "Tanqid konstruktiv bo'ladi: kamchilikni ko'rsatib, taklif ham beriladi.",
  "Baholovchi o'z bahosini asoslashi kerak — \"yoqmadi\" emas, \"chunki ...\".",
  "Peer review ikki tomonlama foydali: baholovchi ham boshqalarning yechimlaridan o'rganadi va o'z ishiga yangi ko'z bilan qaraydi."],
 "Baholash varaqasini mezonlar bilan tarqating. Tuzilmali baholash adolatli va foydali bo'ladi, erkin fikr esa ko'pincha shaxsiy munosabatga aylanadi.",
 [("Tanqid qanday bo'lishi kerak?", "Konstruktiv — taklif bilan va asoslangan."),
  ("Peer review baholovchiga nima beradi?", "Boshqalarning yechimlaridan o'rganish imkonini.")],
 "Asossiz baho berish yoki faqat kamchiliklarni sanash."),
}
