# -*- coding: utf-8 -*-
"""1-yil, 5-sinf — elektronika (platasiz). 72 mavzu uchun aniq kontent."""

from kb_5_8 import T

MAVZULAR = {

# ==================================================== 1-CHORAK: Elektr toki va oddiy zanjir
"Elektr xavfsizligi: nima mumkin, nima mumkin emas": T(
 "Xavfsizlik plakatini to'ldirish va ish o'rnini qoidaga solib tayyorlash",
 ["Darsda ishlatiladigan barcha manba past kuchlanishli: 3-9 V batareya va 5 V USB. Bu kuchlanish inson uchun xavfsiz, chunki quruq teri qarshiligi 10 000 omdan katta va tok deyarli o'tmaydi.",
  "Xavf kuchlanishdan emas, TOKDAN keladi. Rozetkadagi 220 V esa hayot uchun xavfli — unga hech qachon o'z zanjirimizni ulamaymiz.",
  "Uch qat'iy qoida: rozetkaga tegilmaydi; batareyaning ikki qutbi bir-biriga to'g'ridan-to'g'ri ulanmaydi (qisqa tutashuv); sxema o'zgartirilishidan oldin quvvat uziladi.",
  "Qizigan komponent — ogohlantirish belgisi. Qo'l bilan tekshiriladi emas, darhol quvvat uziladi va o'qituvchi chaqiriladi."],
 "Qoidalarni ro'yxat qilib o'qib bermang — har biriga sabab bering. Batareyani qisqa tutashtirib (o'zingiz, qisqa vaqt) simning qizishini ko'rsating: bitta ko'rsatilgan tajriba o'nta ogohlantirishdan kuchli ta'sir qiladi.",
 [("Nega 3 V batareya xavfsiz, 220 V rozetka xavfli?", "Kuchlanish katta bo'lsa, tanadan o'tadigan tok ham katta bo'ladi; 3 V dan teri orqali sezilarli tok o'ta olmaydi."),
  ("Sim qizib ketsa birinchi navbatda nima qilinadi?", "Quvvat uziladi, keyin sabab izlanadi.")],
 "O'quvchilar batareya \"kichkina, demak xavfsiz\" deb o'ylab, uni cho'ntakda kalit bilan birga olib yuradi — qutblar tutashib, batareya qizib ketadi."),

"Elektr toki nima: zaryadning harakati": T(
 "Statik zaryad tajribasi: ishqalangan shar bilan qog'oz parchalarini tortish",
 ["Har bir moddada musbat (proton) va manfiy (elektron) zaryadlar bor. Odatda ular teng — modda neytral.",
  "Metallda elektronlar atomga mahkam bog'lanmagan, ular \"erkin\". Zanjirga kuchlanish berilsa, shu erkin elektronlar bir tomonga siljiydi — bu elektr toki.",
  "Tok kuchi amperda (A) o'lchanadi. 1 A — bir sekundda kesim orqali juda katta miqdordagi zaryad o'tishi. Bizning zanjirlarimizda odatda 0,001-0,05 A (1-50 mA) tok yuradi.",
  "Muhim: elektronlar manfiydan musbatga harakatlanadi, lekin tarixiy kelishuv bo'yicha tok yo'nalishi musbatdan manfiyga deb chiziladi. Sxemada shu kelishuvga amal qilamiz."],
 "Suv o'xshatishini kiriting va butun yil davomida ishlating: quvur = sim, suv = zaryad, nasos bosimi = kuchlanish, oqim tezligi = tok. O'quvchilar keyinchalik Om qonunini shu obraz orqali oson tushunadi.",
 [("Tok nima?", "Zaryadlangan zarrachalarning yo'naltirilgan harakati."),
  ("Nima uchun metall tokni o'tkazadi?", "Unda atomga mahkam bog'lanmagan erkin elektronlar bor.")],
 "\"Tok simda suvdek oqib keladi va tugaydi\" degan tasavvur — aslida zaryad zanjirni aylanib chiqadi, hech qayerda \"sarflanib\" yo'qolmaydi."),

"Batareya — tok manbai, musbat va manfiy qutb": T(
 "Turli batareyalarni ko'rib chiqish, qutblarini aniqlash va kuchlanishini yozib olish",
 ["Batareya ichida kimyoviy reaksiya boradi va u zaryadni bir qutbdan ikkinchisiga \"itaradi\". Ya'ni batareya zaryad yaratmaydi — u zaryadni harakatlantirish uchun bosim (kuchlanish) hosil qiladi.",
  "Musbat qutb (+) korpusda dumaloq chiqiq bilan, manfiy (-) tekis tomon bilan belgilanadi. AA/AAA element 1,5 V, \"krona\" 9 V, litiy akkumulyator 3,7 V beradi.",
  "Bir necha elementni ketma-ket ulash kuchlanishni qo'shadi: to'rtta AA = 6 V. Parallel ulash kuchlanishni oshirmaydi, faqat ish vaqtini uzaytiradi.",
  "Batareya \"tugaganda\" kimyoviy modda tugaydi va kuchlanish pasayadi: 1,5 V element 1,1 V ga tushsa, ko'p qurilma ishlamay qoladi."],
 "Yangi va eski batareyani multimetrsiz farqlab bo'lmasligini ta'kidlang — keyingi chorakda aynan shuni o'lchashadi. Bu ikki chorak orasida bog'lanish hosil qiladi.",
 [("Ikkita 1,5 V elementni ketma-ket ulasak necha volt bo'ladi?", "3 V."),
  ("Batareya zaryad yaratadimi?", "Yo'q, u zaryadni harakatlantiruvchi kuchlanish hosil qiladi.")],
 "Qutbni teskari ulash. LED va ba'zi modullar teskari qutblanishda umuman ishlamaydi yoki kuyadi."),

"Yopiq va ochiq zanjir": T(
 "Batareya, lampochka va simdan zanjir yig'ib, simni uzib-ulab yoqib-o'chirish",
 ["Tok faqat YOPIQ zanjirda yuradi: manbaning bir qutbidan chiqib, iste'molchidan o'tib, ikkinchi qutbga qaytishi kerak.",
  "Zanjirning istalgan joyi uzilsa (ochiq zanjir), butun zanjirda tok to'xtaydi — faqat uzilgan joyda emas.",
  "Uzilish ko'rinmasligi mumkin: sim ichidan uzilgan, kontakt oksidlangan, breadboardga oyoq to'liq kirmagan. Tashqi ko'rinish yaxshi bo'lsa ham zanjir ochiq bo'lishi mumkin.",
  "Kalit — bu ataylab qo'yilgan boshqariladigan uzilish joyi."],
 "Zanjirni yig'ib, o'quvchi ko'rmaydigan joydan bitta simni bo'shatib qo'ying va \"nega yonmayapti?\" deb so'rang. Nosozlik izlash ko'nikmasi birinchi darsdanoq boshlanadi.",
 [("Zanjirning bir joyi uzilsa, qolgan qismida tok bormi?", "Yo'q, butun zanjirda tok to'xtaydi."),
  ("Kalit nima qiladi?", "Zanjirni boshqariladigan tarzda uzadi va ulaydi.")],
 "Faqat bitta simni ulab, ikkinchi qutbni ulashni unutish — zanjir yopilmaydi va o'quvchi komponentni nosoz deb o'ylaydi."),

"O'tkazgich va izolyator: qaysi materialdan tok o'tadi": T(
 "10 xil buyumni zanjirga qo'yib sinash va jadvalga \"o'tkazadi / o'tkazmaydi\" deb yozish",
 ["O'tkazgichda erkin elektron ko'p: mis, alyuminiy, temir, grafit (qalam o'zagi), tuzli suv, inson tanasi.",
  "Izolyatorda erkin elektron deyarli yo'q: plastmassa, rezina, shisha, quruq yog'och, quruq qog'oz, havo.",
  "Mutlaq izolyator yo'q — kuchlanish yetarlicha katta bo'lsa, havo ham teshiladi (chaqmoq shunday hosil bo'ladi).",
  "Simning ichi mis (o'tkazgich), usti rangli plastmassa (izolyator) — ikkalasi birga xavfsiz uzatishni ta'minlaydi."],
 "Grafit tajribasini albatta qiling: qog'ozga qalam bilan qalin chiziq chizib, uchiga simni tegizing — LED xira yonadi. Bu \"o'tkazgich = metall\" degan tor tasavvurni buzadi.",
 [("Grafit o'tkazgichmi?", "Ha, shuning uchun qalam chizig'i orqali kuchsiz tok o'tadi."),
  ("Nega sim usti plastmassa bilan qoplangan?", "Plastmassa izolyator — tokning kerakmas joyga o'tishini to'sadi.")],
 "Quruq va nam yog'ochni bir xil deb hisoblash: nam yog'och va nam qo'l tokni ancha yaxshi o'tkazadi."),

"Birinchi zanjir: batareya va lampochka": T(
 "Batareya-tutqich, kalit va lampochkadan to'liq ishlaydigan zanjir yig'ish",
 ["Eng oddiy zanjir uch qismdan iborat: manba (batareya), iste'molchi (lampochka) va ulash yo'li (simlar).",
  "Lampochka ichidagi ingichka volfram sim katta qarshilikka ega. Tok o'tganda u 2000 darajagacha qiziydi va yorug'lik chiqaradi — ya'ni elektr energiya issiqlik va yorug'likka aylanadi.",
  "Yig'ish tartibi: avval hamma narsa quvvatsiz ulanadi, ulanishlar tekshiriladi, oxirida batareya ulanadi. Bu tartib butun kurs davomida saqlanadi.",
  "Lampochka qutbga bog'liq emas — u ikki tomonlama ishlaydi. LED esa bog'liq, buni keyingi darsda ko'ramiz."],
 "Birinchi ishlagan zanjir kuchli taassurot qoldiradi — shoshiltirmang, har bir juftlik o'zi yoqib ko'rsin. Yig'ish tartibini (quvvat oxirida) shu yerda odat qilib qo'ying.",
 [("Zanjirning uch asosiy qismi qaysilar?", "Manba, iste'molchi va ulovchi simlar."),
  ("Lampochkada elektr energiya nimaga aylanadi?", "Issiqlik va yorug'likka.")],
 "Batareyani birinchi bo'lib ulash — sxemada xato bo'lsa, komponent darhol kuyadi."),

"LED bilan tanishuv: uzun va kalta oyoq": T(
 "5 xil rangli LEDni tekshirish va qutbini aniqlash",
 ["LED — yarimo'tkazgichli diod. U tokni faqat BIR yo'nalishda o'tkazadi va shu paytda yorug'lik chiqaradi.",
  "Uzun oyoq — anod (+), kalta oyoq — katod (-). Katod tomonda korpus chekkasi ham tekis qirqilgan bo'ladi.",
  "LED lampochkadan tejamli: bir xil yorug'lik uchun ~10 marta kam energiya sarflaydi va deyarli qizimaydi.",
  "Har rangning o'z tushish kuchlanishi bor: qizil ~1,8-2,0 V, yashil va sariq ~2,0-2,2 V, ko'k va oq ~3,0-3,2 V. Shuning uchun ko'k LED 3 V batareyada xira yonadi."],
 "LEDni teskari ulab ko'rsating — kuymaydi, shunchaki yonmaydi. \"Yonmayapti\" ning eng ko'p sababi shu ekanini o'quvchilar esda saqlab qolsin.",
 [("LEDning uzun oyog'i qaysi qutb?", "Anod, ya'ni musbat (+)."),
  ("Nega ko'k LED qizil LEDga qaraganda ko'proq kuchlanish talab qiladi?", "Uning tushish kuchlanishi kattaroq (~3 V).")],
 "Oyoqlari qirqilgan LEDda uzun-kalta farqi yo'qoladi; bunday holda korpusning tekis chekkasiga (katod) qarash kerak."),

"LED nima uchun rezistorsiz kuyadi": T(
 "Bitta LEDni rezistor bilan va rezistorsiz sinash (rezistorsizi — o'qituvchi namoyishida)",
 ["LED o'zi tokni cheklamaydi. Kuchlanish uning tushish kuchlanishidan oshsa, tok deyarli chegarasiz o'sadi va kristall bir necha sekundda kuyadi.",
  "LED uchun xavfsiz tok — 10-20 mA. 5 V manbaga to'g'ridan-to'g'ri ulansa, tok 100 mA dan oshib ketadi.",
  "Rezistor ortiqcha kuchlanishni o'ziga oladi: 5 V dan 2 V LEDga tushsa, qolgan 3 V rezistorda qoladi.",
  "Standart qiymat: 5 V zanjir uchun 220 Om, 3,3 V uchun 100-150 Om. Aniq hisobni keyingi chorakda o'rganamiz."],
 "Kuyish jarayonini o'zingiz namoyish qiling (xavfsiz masofada, ko'zoynak bilan) — bir marta ko'rgan o'quvchi rezistorni boshqa unutmaydi. Sinfga sarflangan bitta LED arziydi.",
 [("LED uchun xavfsiz tok qancha?", "Taxminan 10-20 mA."),
  ("Rezistor nima qiladi?", "Ortiqcha kuchlanishni o'ziga oladi va tokni cheklaydi.")],
 "Bitta rezistorni bir necha LEDga umumiy qilib qo'yish — bunda har bir LEDga tegishli tok kamayadi va yorqinlik notekis bo'ladi."),

"Rezistor: rangli halqalarni o'qish": T(
 "Aralashtirilgan 20 ta rezistorni rangli kod bo'yicha saralab, qiymati bo'yicha tartiblash",
 ["Rezistor kichkina, ustiga raqam sig'maydi — shuning uchun qiymati rangli halqalar bilan yoziladi.",
  "To'rt halqali rezistorda: 1-halqa = birinchi raqam, 2-halqa = ikkinchi raqam, 3-halqa = nechta nol qo'shiladi, 4-halqa = aniqlik (oltin = 5%).",
  "Rang-raqam tartibi: qora 0, jigarrang 1, qizil 2, to'q sariq 3, sariq 4, yashil 5, ko'k 6, binafsha 7, kulrang 8, oq 9.",
  "Misol: qizil-qizil-jigarrang = 2, 2 va bitta nol = 220 Om. Jigarrang-qora-to'q sariq = 1, 0 va uchta nol = 10 000 Om = 10 kOm."],
 "Halqani qaysi tomondan o'qishni aytib bering: oltin/kumush halqa har doim OXIRIDA turadi. O'quvchilar ko'pincha teskari o'qib, 220 Om o'rniga 122 Om deb chiqaradi.",
 [("Qizil-qizil-jigarrang necha om?", "220 Om."),
  ("Uchinchi halqa nimani bildiradi?", "Birinchi ikki raqamdan keyin nechta nol qo'shilishini.")],
 "Rezistorni teskari tomondan o'qish. Oltin yoki kumush halqa doim o'ng tomonda turishi kerak."),

"Breadboard tuzilishi: qaysi teshiklar o'zaro bog'langan": T(
 "Multimetrning \"zumlash\" rejimi bilan breadboardning ichki ulanishlarini xaritaga tushirish",
 ["Breadboard — kavsharlashsiz zanjir yig'iladigan taxta. Ichida metall qisqichlar bor, ular ba'zi teshiklarni o'zaro ulab turadi.",
  "Chetdagi uzun chiziqlar (+ va - belgili) — quvvat shinalari. Ular butun uzunlik bo'ylab ulangan.",
  "O'rtadagi qismda esa har bir ustundagi 5 ta teshik o'zaro ulangan, lekin o'rtadagi tirqishdan narigi tomonga o'tmaydi.",
  "Tirqish ataylab qo'yilgan: mikrosxemaning ikki qatorli oyoqlari ikki tomonga tushib, o'zaro tutashib ketmasligi uchun."],
 "Har bir o'quvchi breadboard rasmini daftariga chizib, ulangan teshiklarni bo'yab chiqsin. Shu chizma yil davomida ularning eng ko'p qaraydigan sahifasi bo'ladi.",
 [("O'rtadagi tirqish nima uchun kerak?", "Mikrosxema oyoqlari ikki tomonga tushib, o'zaro tutashib ketmasligi uchun."),
  ("Chetdagi uzun chiziqlar nima?", "Quvvat shinalari — + va -.")],
 "Bir ustunga ikkita komponent oyog'ini qo'yib, ularni \"ulanmagan\" deb hisoblash — aslida ular tutashgan bo'ladi."),

"Breadboard'da birinchi LED zanjiri": T(
 "Breadboardda 220 Om rezistor bilan LED zanjirini toza montaj qoidalariga rioya qilib yig'ish",
 ["Zanjir yo'li: batareya + -> quvvat shinasi -> rezistor -> LED anodi -> LED katodi -> manfiy shina -> batareya -.",
  "Rezistorni LEDdan oldin yoki keyin qo'yish farq qilmaydi — ketma-ket zanjirda tok hamma joyda bir xil. Muhimi, u zanjirda bo'lishi.",
  "Toza montaj qoidasi: simlar qisqa va tekis kesilgan, taxta ustidan o'tib ketmaydi, rang bilan ajratiladi (qizil = +, qora = -).",
  "Komponent oyog'i teshikka to'liq kirishi kerak — chala kirgan oyoq eng ko'p uchraydigan nosozlik sababi."],
 "Toza montajni birinchi kundan talab qiling. \"Ishlasa bo'ldi\" degan yondashuv 4-chorakdagi murakkab sxemada nosozlik topishni imkonsiz qilib qo'yadi.",
 [("Rezistorni LEDdan keyin qo'ysa bo'ladimi?", "Ha, ketma-ket zanjirda o'rni ahamiyatsiz."),
  ("Nega simlar rang bilan ajratiladi?", "Sxemani o'qish va xatoni topish oson bo'lishi uchun.")],
 "Simni teshikka chala tiqish — zanjir goh ishlaydi, goh ishlamaydi va o'quvchi sababini topa olmaydi."),

"Ikkita LED: ketma-ket ulash": T(
 "Ikki LEDni ketma-ket ulab, yorqinligini bitta LEDli zanjir bilan solishtirish",
 ["Ketma-ket ulanishda komponentlar bitta yo'lga tizilgan bo'ladi: tok ularning hammasidan bir xil miqdorda o'tadi.",
  "Manba kuchlanishi komponentlar orasida BO'LINADI: 5 V da ikkita qizil LED bo'lsa, har biriga ~2 V tushadi, qolgani rezistorga.",
  "Shuning uchun ketma-ket ulangan LEDlar bitta LEDga qaraganda xiraroq yonadi.",
  "5 V manbaga ketma-ket uchtadan ortiq LED ulab bo'lmaydi — kuchlanish yetmay qoladi va hech biri yonmaydi."],
 "Yorqinlik farqini yonma-yon ikkita zanjir yig'ib ko'rsating. \"Xira\" tushunchasi solishtirilgandagina ko'rinadi.",
 [("Ketma-ket zanjirda tok qanday taqsimlanadi?", "Taqsimlanmaydi — hamma joyda bir xil."),
  ("Nega ketma-ket ulangan LEDlar xiraroq yonadi?", "Kuchlanish ular orasida bo'linadi.")],
 "5 V ga ketma-ket 3-4 ta LED ulab, \"hammasi buzuq\" degan xulosaga kelish — aslida kuchlanish yetishmaydi."),

"Ikkita LED: parallel ulash": T(
 "Ikki LEDni har biriga alohida rezistor bilan parallel ulash",
 ["Parallel ulanishda har bir komponent manbaga o'z yo'li bilan ulanadi — kuchlanish hammasiga bir xil tushadi.",
  "Shuning uchun parallel LEDlar bitta LED kabi yorqin yonadi.",
  "Lekin manbadan olinadigan umumiy tok qo'shiladi: ikkita LED 20 mA dan olsa, batareyadan 40 mA chiqadi va u tezroq tugaydi.",
  "Har bir LEDga ALOHIDA rezistor kerak. Bitta umumiy rezistor qo'yilsa, LEDlar tokni teng bo'lishmaydi va biri yorqinroq yonadi."],
 "Umumiy rezistorli va alohida rezistorli variantni ikkalasini yig'dirib solishtiring — farq ko'z bilan ko'rinadi va qoida yodda qoladi.",
 [("Parallel ulanishda kuchlanish qanday taqsimlanadi?", "Hammasiga bir xil tushadi."),
  ("Nega har bir LEDga alohida rezistor kerak?", "Aks holda ular tokni teng bo'lishmaydi va yorqinligi har xil bo'ladi.")],
 "Ikki LEDga bitta rezistor qo'yish — yorqinlik notekis bo'ladi va vaqt o'tib biri kuyadi."),

"Tugma: zanjirni uzish va ulash": T(
 "Tugma bilan boshqariladigan LED zanjirini yig'ish va tugma oyoqlarining ichki bog'lanishini aniqlash",
 ["Tugma (taktil tugma) — bosilgan paytda zanjirni ulaydigan, qo'yib yuborilganda uzadigan kalit.",
  "To'rt oyoqli tugmada oyoqlar juft-juft ichkaridan doim ulangan: qarama-qarshi juftlar bosilganda tutashadi.",
  "Shuning uchun tugmani noto'g'ri burib ulash mumkin — bunda LED bosmasdan ham doim yonib turadi.",
  "To'g'ri ulash: tugmani breadboardning o'rta tirqishi ustiga qo'yilsa, ikki juft oyoq ikki tomonga tushadi va chalkashish yo'qoladi."],
 "Tugmaning ichki bog'lanishini multimetr bilan aniqlatting. Bu \"buzuq tugma\" degan noto'g'ri xulosalarni butun yil davomida oldini oladi.",
 [("Tugmaning to'rt oyog'i qanday bog'langan?", "Juft-juft bo'lib doim ulangan; bosilganda ikki juft o'zaro tutashadi."),
  ("Tugmani breadboardda qayerga qo'yish qulay?", "O'rta tirqish ustiga, ikki juft oyoq ikki tomonga tushishi uchun.")],
 "Tugmani 90 daraja burib ulash — natijada zanjir doim yopiq bo'lib qoladi."),

"Vklyuchatel: holatni saqlaydigan kalit": T(
 "Tugmali va vklyuchatelli ikki zanjirni yonma-yon yig'ib, farqini yozib olish",
 ["Tugma faqat bosib turilganda ulaydi (momentiy kontakt), vklyuchatel esa holatni saqlaydi (fiksatsiyalanadigan kontakt).",
  "Chiroq vklyuchateli, kompyuter tugmasi, klaviatura tugmasi — qaysi biri qaysi turga kirishini ayta olish kerak.",
  "Uch oyoqli vklyuchatelda o'rta oyoq — umumiy (COM), chetdagilari esa ikki holat. Bu bilan bitta kalit ikki zanjirni almashtirib ulashi mumkin.",
  "Dasturlash bosqichida bu farq muhim bo'ladi: tugma bilan holat saqlash uchun kod yozish kerak, vklyuchatelda esa kerak emas."],
 "Bu darsda mexanik yechim va dasturiy yechim farqiga ilk bor ishora qiling — 2-yilda tugma bilan holat saqlash (toggle) mavzusi shu yerdan boshlanadi.",
 [("Tugma va vklyuchatel orasidagi asosiy farq nima?", "Vklyuchatel holatni saqlaydi, tugma faqat bosilgan paytda ulaydi."),
  ("Uch oyoqli vklyuchatelda o'rta oyoq nima?", "Umumiy kontakt (COM).")],
 "Uch oyoqli kalitni chetki ikki oyog'iga ulash — bunda kalit umuman ishlamaydi."),

"Ikki tugma ketma-ket: \"VA\" mantiqi": T(
 "Ikki tugmani ketma-ket ulab, faqat ikkalasi bosilganda yonadigan zanjir yig'ish",
 ["Ketma-ket ulangan ikki tugmada tok ikkalasidan ham o'tishi kerak — demak LED faqat IKKALASI bosilganda yonadi.",
  "Bu mantiqda \"VA\" (AND) amali deyiladi: natija rost bo'lishi uchun ikkala shart ham rost bo'lishi kerak.",
  "Rostlik jadvali: 0 va 0 = 0; 1 va 0 = 0; 0 va 1 = 0; 1 va 1 = 1.",
  "Hayotda: press-stanok ikki qo'l bilan bosiladigan ikki tugmaga ega — ishchining qo'li mexanizm ostida qolmasligi uchun aynan VA mantiqi ishlatiladi."],
 "Xavfsizlik pressi misolini albatta ayting — mantiq amali mavhum tushuncha bo'lib qolmaydi, hayotdagi aniq masalaning yechimiga aylanadi.",
 [("Ikki tugma ketma-ket ulansa LED qachon yonadi?", "Faqat ikkalasi bir vaqtda bosilganda."),
  ("Bu qaysi mantiq amali?", "\"VA\" (AND).")],
 "Rostlik jadvalini to'ldirishda 1 va 0 kombinatsiyalarini tashlab ketish — hamma to'rt holatni yozish kerak."),

"Ikki tugma parallel: \"YOKI\" mantiqi": T(
 "Ikki tugmani parallel ulab, xonaning ikki eshigidan boshqariladigan chiroq maketini yig'ish",
 ["Parallel ulangan tugmalarda tok ikki yo'ldan birortasi ochilsa o'tadi — LED istalgan bittasi bosilganda yonadi.",
  "Bu \"YOKI\" (OR) amali: natija rost bo'lishi uchun kamida bitta shart rost bo'lsa yetadi.",
  "Rostlik jadvali: 0 yoki 0 = 0; 1 yoki 0 = 1; 0 yoki 1 = 1; 1 yoki 1 = 1.",
  "Hayotda: yong'in signalizatsiyasi — binoning istalgan tugmasi bosilsa signal ishlaydi. Bu ham parallel, ya'ni YOKI mantiqi."],
 "VA va YOKI zanjirlarini yonma-yon qoldirib, o'quvchilarga ikkalasini sinatib chiqing. Ikki darsning natijasi bitta jadvalda solishtirilsa, tushuncha mustahkamlanadi.",
 [("Ikki tugma parallel ulansa LED qachon yonadi?", "Kamida bittasi bosilganda."),
  ("Yong'in tugmalari qaysi mantiq bo'yicha ulanadi?", "YOKI — istalgan biri signal beradi.")],
 "Parallel tugmalarni bir xil ustunga qo'yib, ularni tasodifan qisqa tutashtirish."),

"Sxema chizish: belgilar tili": T(
 "O'zi yig'gan uchta zanjirni shartli belgilar bilan daftarga chizish",
 ["Sxema — zanjirning fotosurati emas, uning MANTIQINING chizmasi. Komponent qayerda turishi emas, nimaga ulangani muhim.",
  "Asosiy belgilar: batareya = uzun va kalta chiziq juftligi; rezistor = to'rtburchak; LED = uchburchak va chiziq, yonida ikki strelka; kalit = uzilgan chiziq; GND = uch qisqaruvchi gorizontal chiziq.",
  "Simlar faqat to'g'ri burchak ostida buriladi. Kesishgan joyda nuqta bo'lsa — ulangan, nuqta bo'lmasa — ulanmagan.",
  "Butun dunyoda bu belgilar bir xil: o'zbek, xitoy va nemis muhandisi bir-birining sxemasini tarjimasiz o'qiy oladi."],
 "\"Sxema — muhandislarning xalqaro tili\" g'oyasini urg'ulang. Har bir keyingi amaliy ish avval sxema chizishdan boshlansin — bu odat 7-8-sinfda katta yordam beradi.",
 [("Sxemada kesishgan simlar nuqtasiz chizilsa nima degani?", "Ular ulanmagan, bir-birining ustidan o'tib ketgan."),
  ("Sxema va fotosurat farqi nimada?", "Sxema joylashuvni emas, ulanish mantiqini ko'rsatadi.")],
 "Komponentlarni breadboarddagidek joylashtirib chizishga urinish — sxema o'qib bo'lmas holga keladi."),

# ==================================================== 2-CHORAK: O'lchov va Om qonuni
"Multimetr bilan tanishuv: rejimlar va xavfsizlik": T(
 "Multimetr rejimlarini o'rganish va zumlash (prozvonka) bilan simlarni tekshirish",
 ["Multimetr — uchta asbob bitta korpusda: voltmetr (kuchlanish), ommetr (qarshilik), ampermetr (tok).",
  "Rejim tanlagich: V (kuchlanish), Om belgisi (qarshilik), A yoki mA (tok). Har rejim uchun o'lchov chegarasi ham tanlanadi — kutilgan qiymatdan bir pog'ona katta chegara olinadi.",
  "Shchup joyi muhim: qora doim COM ga, qizil esa V/Om teshigiga. Tok o'lchashda qizil shchup ALOHIDA (A yoki mA) teshikka ko'chiriladi.",
  "Zumlash rejimi (diod/tovush belgisi) — ikki nuqta o'zaro ulangan bo'lsa asbob \"biq\" qiladi. Uzilgan simni topishning eng tez yo'li."],
 "Birinchi darsda faqat zumlash va kuchlanishni bering. Tok rejimini keyinroq, alohida ogohlantirish bilan o'rgating — noto'g'ri ulangan ampermetr multimetrni ishdan chiqaradi.",
 [("Qora shchup qaysi teshikka ulanadi?", "COM."),
  ("Zumlash rejimi nima uchun kerak?", "Ikki nuqta o'zaro ulanganini tez tekshirish uchun.")],
 "Tok rejimida qolgan multimetrni kuchlanish o'lchashga urinish — bu ichki predoxranitelni kuydiradi. Eng ko'p uchraydigan va eng qimmat xato."),

"Kuchlanishni o'lchash (Volt)": T(
 "Batareya, rezistor va LEDdagi kuchlanishni o'lchab, jadvalga yozish",
 ["Kuchlanish — ikki nuqta ORASIDAGI farq. Shuning uchun uni bir nuqtada o'lchab bo'lmaydi, doim ikki nuqta kerak.",
  "Voltmetr PARALLEL ulanadi: shchuplar komponentning ikki oyog'iga qo'yiladi, zanjirni uzish shart emas.",
  "Voltmetrning ichki qarshiligi juda katta (millionlab om), shuning uchun u zanjirdan deyarli tok olmaydi va o'lchashning o'zi natijaga ta'sir qilmaydi.",
  "Manfiy qiymat chiqsa — shchuplar teskari qo'yilgan; qiymat to'g'ri, faqat ishorasi teskari."],
 "\"Kuchlanish doim ikki nuqta orasida\" degan fikrni qayta-qayta takrorlang. Bu chorakda o'quvchilar eng ko'p qiynaladigan tushuncha aynan shu.",
 [("Voltmetr qanday ulanadi?", "Parallel, komponentning ikki oyog'iga."),
  ("Ekranda -3,2 V chiqsa nima degani?", "Shchuplar teskari qo'yilgan, qiymat esa 3,2 V.")],
 "Bitta shchupni komponentga, ikkinchisini havoda qoldirib o'lchashga urinish."),

"Batareya kuchlanishi: yangi va eski batareya": T(
 "5 ta turli batareyaning kuchlanishini o'lchab, \"yaroqli / yaroqsiz\" deb saralash",
 ["Yangi AA element 1,5-1,6 V ko'rsatadi. 1,3 V — yarim ishlatilgan, 1,1 V dan past — amalda tugagan.",
  "Bo'sh (yuklamasiz) o'lchash aldashi mumkin: tugagan batareya bo'sh holatda 1,4 V ko'rsatib, yuklama ulanishi bilan 0,9 V ga tushadi.",
  "Shuning uchun to'g'ri sinov — yuklama bilan o'lchash: LED yoki motor ulangan holda kuchlanishni ko'rish.",
  "Kuchlanishning yuklamada cho'kishi batareyaning ICHKI QARSHILIGI kattalashganini bildiradi. Eski batareyada u bir necha om bo'ladi."],
 "Har bir juftlikka bittadan eski batareya bering va yuklamasiz/yuklamali farqni o'zlari topsin. Bu kashfiyot ta'sirchan bo'ladi.",
 [("Tugagan AA elementning kuchlanishi taxminan qancha?", "1,1 V dan past."),
  ("Nega batareyani yuklama bilan o'lchash kerak?", "Bo'sh holatda tugagan batareya ham normal qiymat ko'rsatishi mumkin.")],
 "Faqat bo'sh kuchlanishga qarab \"batareya yaxshi\" deb xulosa qilish."),

"Qarshilikni o'lchash (Om)": T(
 "20 ta rezistorni o'lchab, rangli kod bilan solishtirish va farqni foizda hisoblash",
 ["Qarshilik faqat QUVVATSIZ zanjirda o'lchanadi. Ommetr o'zi kichik tok yuboradi va tushgan kuchlanishga qarab qarshilikni hisoblaydi.",
  "Komponent zanjirda turgan bo'lsa, uning yoniga ulangan boshqa komponentlar ham hisobga qo'shilib, natija noto'g'ri chiqadi. To'g'ri o'lchash uchun komponentni kamida bir tomondan uzish kerak.",
  "Ekranda \"1\" yoki \"OL\" chiqsa — o'lchov chegarasi kichik yoki zanjir uzilgan (cheksiz qarshilik).",
  "Barmoq bilan ikkala shchupni ushlab turmang: inson tanasi ham qarshilik (bir necha yuz kOm) va u natijaga qo'shilib ketadi."],
 "\"Zanjirdan uzmasdan o'lchash mumkin emas\" qoidasini amalda ko'rsating: bir xil rezistorni zanjirda va zanjirdan tashqarida o'lchating, farqni ko'rsating.",
 [("Qarshilikni o'lchashda quvvat ulangan bo'lishi kerakmi?", "Yo'q, zanjir albatta quvvatsiz bo'lishi kerak."),
  ("Ekranda OL chiqsa nima degani?", "Qiymat chegaradan katta yoki zanjir uzilgan.")],
 "Rezistorning ikkala oyog'ini barmoq bilan bosib turib o'lchash — natija haqiqiy qiymatdan farq qiladi."),

"Rezistor nominalini o'lchab, rangli kod bilan solishtirish": T(
 "Har bir rezistorning o'lchangan va nominal qiymatini jadvalga yozib, chetlanishni foizda hisoblash",
 ["Rangli kod NOMINAL qiymatni beradi — ishlab chiqaruvchi mo'ljallagan qiymatni.",
  "Haqiqiy qiymat undan biroz farq qiladi. Oltin halqa 5% aniqlikni bildiradi: 220 Om rezistor 209-231 Om orasida bo'lsa yaroqli.",
  "Chetlanish foizi: (o'lchangan - nominal) / nominal x 100%. Masalan 227 Om bo'lsa: (227-220)/220 x 100 = 3,2% — normal.",
  "Sanoatda aniqroq rezistorlar ham bor (1%, 0,1%), lekin ular qimmat. Odatiy zanjir uchun 5% yetarli."],
 "Foizli chetlanishni hisoblash matematika darsi bilan bevosita bog'lanadi — buni ochiq ayting, fanlararo bog'liqlik ko'rinib tursin.",
 [("220 Om rezistor 5% aniqlikda qaysi oraliqda bo'lishi kerak?", "209 dan 231 omgacha."),
  ("Chetlanish 8% chiqsa nima deyish mumkin?", "Rezistor ko'rsatilgan aniqlikka mos emas, yaroqsiz.")],
 "Chetlanishni oddiy ayirma sifatida (7 Om) yozib qo'yish — foizga aylantirilmasa, turli nominallarni solishtirib bo'lmaydi."),

"Tokni o'lchash (Amper): zanjirni uzib ulash": T(
 "LED zanjirini uzib, ampermetrni ketma-ket ulash va tokni o'lchash",
 ["Ampermetr KETMA-KET ulanadi: zanjir uziladi va asbob shu uzilgan joyga qo'yiladi, ya'ni butun tok undan o'tadi.",
  "Ampermetrning ichki qarshiligi juda kichik — deyarli sim. Shuning uchun uni parallel (komponent ustiga) ulash QISQA TUTASHUV yaratadi.",
  "Ulashdan oldin qizil shchup A yoki mA teshigiga ko'chiriladi. Buni unutish eng ko'p uchraydigan xato.",
  "Odatiy LED zanjirida tok 10-20 mA bo'ladi. Agar 200 mA ko'rsatsa — sxemada rezistor yo'q yoki qisqa tutashuv bor."],
 "Bu darsda xato qimmatga tushadi: multimetrning predoxraniteli kuyadi. Har bir juftlik ulanishini SIZ tekshirib, keyin quvvat berishlariga ruxsat bering.",
 [("Ampermetr qanday ulanadi?", "Ketma-ket, zanjir uzib."),
  ("Ampermetrni parallel ulasak nima bo'ladi?", "Qisqa tutashuv yuzaga keladi va predoxranitel kuyadi.")],
 "Kuchlanish o'lchagandek shchupni komponent ustiga qo'yish — ampermetr uchun bu qisqa tutashuv."),

"Om qonuni: U = I x R": T(
 "Uch xil rezistor bilan zanjir yig'ib, U va R ni o'lchab, I ni hisoblash va o'lchangan tok bilan solishtirish",
 ["Om qonuni uchta kattalikni bog'laydi: U = I x R. U — volt, I — amper, R — om.",
  "Formuladan uch ko'rinishda foydalaniladi: U = I x R, I = U / R, R = U / I. Ikkitasi ma'lum bo'lsa, uchinchisi topiladi.",
  "Misol: 5 V manbaga 1000 Om rezistor ulansa, I = 5 / 1000 = 0,005 A = 5 mA.",
  "Bog'liqlik teskari proporsional: qarshilik ikki barobar oshsa, tok ikki barobar kamayadi. Kuchlanish ikki barobar oshsa, tok ham ikki barobar oshadi."],
 "Doskaga uchburchak chizing: yuqorida U, pastda I va R. Topmoqchi bo'lgan harfni barmoq bilan yopsa, qolganlari formulani ko'rsatadi. Bu usul o'quvchilarga formulani yodlashsiz qo'llash imkonini beradi.",
 [("5 V va 250 Om bo'lsa tok qancha?", "I = 5/250 = 0,02 A = 20 mA."),
  ("Tok 10 mA, qarshilik 470 Om. Kuchlanish qancha?", "U = 0,01 x 470 = 4,7 V.")],
 "mA ni A ga aylantirmaslik: 20 mA ni formulaga 20 deb qo'yish natijani 1000 marta xato qiladi."),

"Om qonuni bilan hisoblash mashqlari": T(
 "10 ta masalani yechib, ikkitasini amalda o'lchov bilan tekshirish",
 ["Hisoblashda birliklarni bir tizimga keltirish shart: mA ni A ga (1000 ga bo'lish), kOm ni Om ga (1000 ga ko'paytirish).",
  "Foydali qisqartma: volt / kiloom = milliamper. Ya'ni 5 V / 1 kOm = 5 mA. Bu shakl bilan hisob nolsiz va tezroq bajariladi.",
  "Har javob mantiqan tekshiriladi: 5 V zanjirda 3 A tok chiqsa, xato bor — bunday tok kichik batareyadan chiqmaydi.",
  "Amalda o'lchangan qiymat hisoblangandan 5-10% farq qilishi normal: rezistor aniqligi, simlarning qarshiligi va batareyaning cho'kishi ta'sir qiladi."],
 "Har masalada javobning O'LCHOV BIRLIGINI yozishni talab qiling. Birliksiz javob — noto'g'ri javob, bu qoida fizika darsida ham bir xil.",
 [("9 V va 470 Om: tok qancha?", "9/470 = 0,019 A = 19 mA."),
  ("12 V da 100 mA oqsa, qarshilik qancha?", "R = 12/0,1 = 120 Om.")],
 "Javobni birliksiz yozish yoki mA va A ni aralashtirib yuborish."),

"LED uchun rezistorni hisoblab tanlash": T(
 "Qizil, yashil va ko'k LED uchun rezistorni hisoblab, natijani o'lchov bilan tekshirish",
 ["Hisob formulasi: R = (U manba - U led) / I led.",
  "Misol: 5 V manba, qizil LED (2 V), kerakli tok 15 mA. R = (5 - 2) / 0,015 = 200 Om. Eng yaqin standart qiymat — 220 Om.",
  "Ko'k LED uchun: (5 - 3,2) / 0,015 = 120 Om. Ya'ni har rangga o'z rezistori kerak bo'ladi.",
  "Hisoblangan qiymatdan KATTAROQ rezistor olinadi — bunda tok biroz kam bo'ladi, LED xiraroq yonadi lekin xavfsiz. Kichikroq olish esa LEDni kuydiradi."],
 "\"Yaqin standart qiymat qaysi tomonga yaxlitlanadi?\" savolini ochiq bering va sababini o'quvchilarning o'zi topsin. Bu muhandislik qaroridir, matematik yaxlitlash emas.",
 [("5 V, yashil LED (2,1 V), 15 mA uchun rezistor?", "(5-2,1)/0,015 = 193 Om, ya'ni 220 Om olinadi."),
  ("Nega kattaroq rezistor olinadi?", "Tok kamayadi va LED xavfsiz ishlaydi.")],
 "LEDning tushish kuchlanishini hisobga olmasdan R = U/I qilib hisoblash — natija noto'g'ri chiqadi."),

"Ketma-ket zanjirda kuchlanish taqsimoti": T(
 "Uchta har xil rezistorli ketma-ket zanjirda har biridagi kuchlanishni o'lchash va yig'indisini manba bilan solishtirish",
 ["Ketma-ket zanjirda manba kuchlanishi komponentlar orasida bo'linadi va ularning yig'indisi manba kuchlanishiga TENG bo'ladi.",
  "Taqsimot qarshilikka proporsional: qarshilik qancha katta bo'lsa, unga tushadigan kuchlanish shuncha katta.",
  "Misol: 9 V manba, 1 kOm va 2 kOm ketma-ket. Umumiy 3 kOm, tok 3 mA. Birinchisida 3 V, ikkinchisida 6 V. Yig'indi 9 V.",
  "Umumiy qarshilik ketma-ket ulanishda oddiy qo'shiladi: R = R1 + R2 + R3."],
 "O'lchangan uch qiymatning yig'indisi manbaga teng chiqishini o'quvchilar o'zlari ko'rsin — bu Kirxgof qonunining birinchi tanishuvi, nomini aytmasdan.",
 [("6 V zanjirda 100 Om va 200 Om ketma-ket. Har biriga qancha tushadi?", "2 V va 4 V."),
  ("Ketma-ket zanjirning umumiy qarshiligi qanday topiladi?", "Qarshiliklar qo'shiladi.")],
 "Kuchlanish teng bo'linadi deb o'ylash — u qarshilikka proporsional bo'linadi."),

"Ketma-ket zanjirda tok hamma joyda bir xil": T(
 "Ketma-ket zanjirning uch nuqtasida tokni o'lchab, teng chiqishini tasdiqlash",
 ["Ketma-ket zanjirda tok uchun bitta yo'l bor — shuning uchun uning qiymati hamma nuqtada bir xil.",
  "Bu suv o'xshatishida yaqqol ko'rinadi: bitta quvurda oqim tezligi hamma joyda bir xil, chunki suv boshqa yo'lga ketolmaydi.",
  "Tokni zanjirning boshida, o'rtasida va oxirida o'lchab ko'rish mumkin — uch qiymat bir xil chiqadi (o'lchov xatoligi doirasida).",
  "Undan kelib chiqadigan xulosa: ketma-ket ulangan LEDlar tokni \"bo'lishmaydi\", ular bir xil tok bilan yonadi, lekin kuchlanish yetmasa hech biri yonmaydi."],
 "Uch o'lchovni doskada jadval qilib yozing. Bir xil raqamlarni ko'rish o'quvchida \"demak haqiqatan ham shunday ekan\" ishonchini hosil qiladi.",
 [("Ketma-ket zanjirda tok qayerda kattaroq — boshidami, oxiridami?", "Bir xil, farq yo'q."),
  ("Nega shunday?", "Tok uchun bitta yo'l bor, u boshqa yo'lga ketolmaydi.")],
 "Tok \"sarflanadi va kamayadi\" degan tasavvur — bu eng chuqur o'rnashgan noto'g'ri fikr, uni o'lchov bilan buzish kerak."),

"Parallel zanjirda kuchlanish bir xil": T(
 "Uchta parallel tarmoqli zanjirda har biriga tushgan kuchlanishni o'lchash",
 ["Parallel ulangan barcha tarmoqlar bir xil ikki nuqtaga ulangan — demak hammasiga bir xil kuchlanish tushadi.",
  "Uy elektr tarmog'i shu tamoyilda ishlaydi: har bir rozetkada 220 V, qaysi qurilma ulanganidan qat'i nazar.",
  "Shuning uchun bitta chiroq o'chsa, qolganlari yonaveradi — ular alohida tarmoqlarda.",
  "Parallel zanjirda umumiy qarshilik har qanday alohida qarshilikdan KICHIK bo'ladi, chunki tokka qo'shimcha yo'l ochiladi."],
 "Yangi yil chiroqchalarini misol qiling: eski (ketma-ket) girlyandada bitta lampa kuysa hammasi o'chadi, yangisida (parallel) esa faqat bittasi o'chadi.",
 [("Parallel tarmoqlarda kuchlanish qanday?", "Hammasida bir xil."),
  ("Bitta parallel tarmoq uzilsa qolganlari ishlaydimi?", "Ha, ular mustaqil.")],
 "Parallel zanjirda umumiy qarshilikni qo'shib hisoblash — u aksincha kamayadi."),

"Parallel zanjirda tok qanday taqsimlanadi": T(
 "Ikki parallel tarmoqda tokni alohida va umumiy o'lchab, qo'shilishini tasdiqlash",
 ["Parallel zanjirda umumiy tok tarmoqlar orasida BO'LINADI, tarmoq toklari yig'indisi umumiy tokka teng.",
  "Taqsimot qarshilikka teskari proporsional: qarshilik kichik tarmoqdan ko'proq tok oqadi.",
  "Misol: 6 V, ikki tarmoq — 300 Om va 600 Om. Birinchisidan 20 mA, ikkinchisidan 10 mA, umumiy 30 mA.",
  "Ikki bir xil rezistor parallel bo'lsa, umumiy qarshilik ikki barobar kamayadi: 200 va 200 Om = 100 Om."],
 "Yo'l o'xshatishini bering: ikki yo'lakdan keng yo'lakka ko'proq odam kiradi. Qarshilik kichik = yo'lak keng.",
 [("6 V da 300 va 600 Om parallel. Umumiy tok?", "20 + 10 = 30 mA."),
  ("Ikkita 200 Om parallel bo'lsa umumiy qarshilik?", "100 Om.")],
 "Parallel tarmoqlarda tok teng bo'linadi deb hisoblash — u qarshilikka teskari proporsional bo'linadi."),

"Kuchlanish bo'luvchi": T(
 "Ikki rezistordan bo'luvchi yig'ib, o'rta nuqtadagi kuchlanishni hisoblash va o'lchash",
 ["Kuchlanish bo'luvchi — ketma-ket ulangan ikki rezistor; o'rtadagi nuqtadan kichraytirilgan kuchlanish olinadi.",
  "Formula: U chiqish = U kirish x R2 / (R1 + R2), bunda R2 — pastki (GND ga ulangan) rezistor.",
  "Misol: 9 V, R1 = 10 kOm, R2 = 5 kOm. U chiqish = 9 x 5 / 15 = 3 V.",
  "Bo'luvchidan tok olinsa, chiqish kuchlanishi pasayadi. Shuning uchun u sensor signalini o'qish kabi kam tok talab qiladigan joylarda ishlatiladi, motor quvvatlantirish uchun emas."],
 "Bu zanjir keyingi yillarda har bir analog sensorda uchraydi — fotorezistor, termistor, tuproq sensori hammasi shu tamoyilda ishlaydi. Buni ochiq ayting.",
 [("12 V, R1 = 1 kOm, R2 = 2 kOm. Chiqish qancha?", "12 x 2 / 3 = 8 V."),
  ("Nega bo'luvchidan motorni quvvatlantirib bo'lmaydi?", "Tok olinishi bilan chiqish kuchlanishi keskin pasayadi.")],
 "Formulada R1 va R2 ni almashtirib yuborish — pastki rezistor R2 ekanini aniq belgilab olish kerak."),

"Potensiometr: o'zgaruvchan rezistor": T(
 "Potensiometrni LED bilan ulab, yorqinlikni silliq boshqarish va uchala oyoqdagi kuchlanishni o'lchash",
 ["Potensiometr — bu sozlanadigan kuchlanish bo'luvchi. Uning ichida qarshilikli yo'lak bor, o'rta oyoq esa shu yo'lak bo'ylab siljiydigan kontakt.",
  "Chetki ikki oyoq orasidagi qarshilik doim o'zgarmas (masalan 10 kOm). O'rta oyoq bilan chetkilar orasidagi qarshilik esa buralganda o'zgaradi.",
  "Ikki oyoq ishlatilsa — oddiy o'zgaruvchan rezistor (reostat). Uchala oyoq ishlatilsa — kuchlanish bo'luvchi.",
  "Buralganda ikki qarshilikning yig'indisi doim bir xil qoladi: biri 3 kOm bo'lsa, ikkinchisi 7 kOm."],
 "Yig'indi doim 10 kOm bo'lib qolishini o'lchab ko'rsating — potensiometrning ichki tuzilishi shu bitta o'lchov bilan tushunarli bo'ladi.",
 [("10 kOm potensiometrda o'rta oyoq bir tomonda 3 kOm bo'lsa, ikkinchi tomonda qancha?", "7 kOm."),
  ("Potensiometrning uchala oyog'i ishlatilsa u nima vazifasini bajaradi?", "Sozlanadigan kuchlanish bo'luvchi.")],
 "Faqat chetki ikki oyoqni ulab, \"potensiometr ishlamayapti\" deb xulosa qilish — o'rta oyoq ulanmasa kuchlanish o'zgarmaydi."),

"Qisqa tutashuv: nima va nega xavfli": T(
 "Ampermetr bilan qarshilikning kamayishi tokni qanday oshirishini o'lchab ko'rsatish (nazorat ostida)",
 ["Qisqa tutashuv — manbaning ikki qutbi orasida qarshiliksiz (yoki juda kichik qarshilikli) yo'l paydo bo'lishi.",
  "Om qonuniga ko'ra, R nolga intilsa, I cheksiz o'sadi. Amalda tokni faqat batareyaning ichki qarshiligi va simlar cheklaydi.",
  "Natijada sim va batareya qiziydi. Litiy akkumulyatorda bu yong'inga olib kelishi mumkin.",
  "Himoya usullari: predoxranitel (tok ortsa ichidagi sim uzilib qoladi), tokni cheklovchi rezistor va ehtiyotkor montaj."],
 "Namoyishni faqat o'zingiz, AA batareya va ingichka sim bilan, bir necha sekundda bajaring. Litiy akkumulyator bilan hech qachon ko'rsatmang.",
 [("Qisqa tutashuvda tok nega keskin oshadi?", "Qarshilik nolga yaqinlashadi, Om qonuniga ko'ra tok o'sadi."),
  ("Predoxranitel qanday himoya qiladi?", "Tok ortganda ichidagi sim uzilib, zanjirni ochib qo'yadi.")],
 "Breadboardda + va - shinalarni tasodifan bir sim bilan ulab qo'yish — bu eng ko'p uchraydigan qisqa tutashuv sababi."),

"O'lchov xatoligi: nega qiymat biroz farq qiladi": T(
 "Bir xil rezistorni 5 marta o'lchab, o'rtacha qiymat va tarqoqlikni hisoblash",
 ["Hech bir o'lchov mutlaq aniq emas. Xatolik uch manbadan keladi: asbobning o'z aniqligi, komponentning chetlanishi va o'lchash usuli.",
  "Multimetrning aniqligi pasportda yozilgan, masalan ±(0,5% + 2 birlik). Bu 220 Om uchun taxminan ±3 Om degani.",
  "Bir necha marta o'lchab o'rtachasini olish tasodifiy xatolikni kamaytiradi, lekin tizimli xatolikni (asbobning doimiy siljishi) tuzatmaydi.",
  "Ilmiy yozuv qoidasi: 219,7 Om deb yozish 220 Om dan ko'ra aniqroq ma'lumot berayotgandek ko'rinadi — lekin asbob aniqligi bunga imkon bermasa, bu yolg'on aniqlik bo'ladi."],
 "\"Yolg'on aniqlik\" tushunchasini kiriting — bu o'quvchilarga fizika, kimyo va geografiya darslarida ham kerak bo'ladigan ilmiy madaniyat.",
 [("Xatolikning uch manbasini ayting.", "Asbob aniqligi, komponent chetlanishi, o'lchash usuli."),
  ("Bir necha marta o'lchash nimani kamaytiradi?", "Tasodifiy xatolikni.")],
 "O'lchov natijasini asbob ko'rsatgan barcha raqamlar bilan yozib, uni haqiqiy aniqlik deb hisoblash."),

"Nosozlik topish: ishlamayotgan zanjirni tekshirish tartibi": T(
 "O'qituvchi ataylab xato kiritgan 3 ta zanjirni tartib bo'yicha tekshirib, nosozlikni topish",
 ["Nosozlikni tasodifiy emas, TARTIB bilan izlash kerak. Tartib: 1) quvvat bormi, 2) zanjir yopiqmi, 3) qutblar to'g'rimi, 4) komponent butunmi.",
  "1-qadam: manba kuchlanishini o'lchash. Batareya 1,1 V bo'lsa, boshqa hech narsani tekshirishning hojati yo'q.",
  "2-qadam: zumlash bilan har bir ulanishni tekshirish — chala kirgan oyoq va ichidan uzilgan sim shu bosqichda topiladi.",
  "3-qadam: kuchlanishni bosqichma-bosqich o'lchab borish. Qayerda kuchlanish yo'qolsa, nosozlik o'sha yerda."],
 "Bu — chorakning eng muhim darsi. Har bir juftlikka o'zingiz xato kiritilgan zanjir bering va tartibni QOG'OZGA yozib borishlarini talab qiling. Tartibsiz izlash o'rgatilmasa, yil davomida har dars sekinlashadi.",
 [("Nosozlik izlashning birinchi qadami nima?", "Manbada kuchlanish bor-yo'qligini o'lchash."),
  ("Kuchlanish zanjirning bir joyida yo'qolsa nima demak?", "Nosozlik aynan o'sha joyda.")],
 "Hammasini bir vaqtda o'zgartirib ko'rish — bunda nima yordam berganini aniqlab bo'lmaydi va xato takrorlanadi."),

# ==================================================== 3-CHORAK: Komponentlar dunyosi
"Kondensator: zaryad to'plovchi idish": T(
 "Turli sig'imdagi kondensatorlarni ko'rib chiqish, belgilarini o'qish va qutbini aniqlash",
 ["Kondensator ikki metall plastinkadan iborat, ular orasi izolyator bilan ajratilgan. U zaryadni vaqtincha saqlaydi.",
  "Sig'im farada (F) o'lchanadi, lekin 1 F juda katta — amalda mikrofarad (uF), nanofarad (nF) va pikofarad (pF) ishlatiladi.",
  "Elektrolitik kondensator QUTBLI: korpusda oq chiziq va minus belgisi bor, kalta oyoq — manfiy. Teskari ulansa shishib, portlashi mumkin.",
  "Keramik kondensator qutbsiz. Ustidagi raqam kod bilan yoziladi: 104 = 10 va to'rtta nol pikofarad = 100 nF = 0,1 uF."],
 "104 kodini o'qishni rezistorning rangli kodi bilan yonma-yon tushuntiring — bir xil mantiq (raqamlar + nollar soni), o'quvchilar tez ilib oladi.",
 [("Kondensator nima saqlaydi?", "Elektr zaryadini."),
  ("Keramik kondensatordagi 104 kodi qancha?", "100 nF, ya'ni 0,1 uF.")],
 "Elektrolitik kondensatorni teskari ulash — u qiziydi va shishadi, ba'zan portlaydi."),

"Kondensatorni zaryadlash va bo'shatish": T(
 "1000 uF kondensatorni zaryadlab, LED orqali bo'shatish va so'nish vaqtini o'lchash",
 ["Kondensator manbaga ulanganda zaryad to'playdi — kuchlanishi asta-sekin manba kuchlanishiga yetadi.",
  "Manba uzilib, o'rniga LED ulansa, to'plangan zaryad LED orqali oqib chiqadi va u bir necha sekund yonib turadi.",
  "Zaryadlash tezligi rezistorga bog'liq: rezistor katta bo'lsa, tok kichik va zaryadlanish sekin.",
  "Kondensator batareya emas: u kichik miqdorda energiya saqlaydi, lekin uni juda tez berib yuboradi. Shuning uchun fotoapparat chaqnog'ida ishlatiladi."],
 "1000 uF kondensator bilan LEDni sekundlab yonib turishini ko'rsatish — bu darsning eng ta'sirchan lahzasi. \"Simsiz yonyapti!\" hayrati mavzuni mustahkam yodda qoldiradi.",
 [("Kondensator manbadan uzilgach LED nega yonaveradi?", "Unda to'plangan zaryad LED orqali oqib chiqadi."),
  ("Kondensator va batareya farqi nimada?", "Kondensator kam energiya saqlaydi, lekin uni juda tez beradi.")],
 "Katta sig'imli kondensatorni zaryadlangan holda qo'l bilan ushlab, oyoqlarini tutashtirib yuborish."),

"RC zanjir: vaqtni sanash": T(
 "R va C ni almashtirib, LEDning so'nish vaqtini o'lchab, jadval tuzish",
 ["Rezistor va kondensator birga qo'yilsa vaqt hosil qiluvchi zanjir bo'ladi. Vaqt doimiysi: T = R x C (om va farad — natija sekundda).",
  "T vaqtida kondensator manba kuchlanishining 63% igacha zaryadlanadi. To'liq zaryadlanish uchun taxminan 5T kerak.",
  "Misol: R = 10 kOm, C = 100 uF. T = 10000 x 0,0001 = 1 sekund. To'liq zaryadlanish ~5 sekund.",
  "Shu tamoyilda zinapoya chirog'i avtomati, taymer va signal kechiktirgichlar ishlaydi."],
 "Formulada birliklarni aylantirish (uF -> F) eng qiyin joyi. Doskada 100 uF = 0,0001 F ni ochiq yozib ko'rsating.",
 [("R = 1 kOm, C = 1000 uF. Vaqt doimiysi qancha?", "1000 x 0,001 = 1 sekund."),
  ("Kondensator qancha vaqtda to'liq zaryadlanadi?", "Taxminan 5T.")],
 "uF ni F ga aylantirmaslik — natija million marta xato chiqadi."),

"Diod: tok faqat bir tomonga": T(
 "Diodni ikki tomonlama ulab sinash va multimetrning diod rejimida tekshirish",
 ["Diod tokni faqat bir yo'nalishda o'tkazadi: anoddan katodga. Katod tomoni korpusda halqa bilan belgilanadi.",
  "To'g'ri yo'nalishda diodda ~0,7 V kuchlanish tushadi (kremniyli diod uchun). Teskari yo'nalishda esa deyarli tok o'tmaydi.",
  "Multimetrning diod rejimida to'g'ri yo'nalishda 0,5-0,7 ko'rsatadi, teskari yo'nalishda OL. Ikkala tomonda ham OL bo'lsa — diod uzilgan; ikkalasida ham 0 bo'lsa — teshilgan.",
  "LED ham diod, faqat u tok o'tganda yorug'lik ham chiqaradi."],
 "Diod rejimida sinashni har bir o'quvchi bajarsin — bu ko'nikma keyinchalik tranzistor va boshqa yarimo'tkazgichlarni tekshirishda ham kerak bo'ladi.",
 [("Diodda to'g'ri yo'nalishda qancha kuchlanish tushadi?", "Taxminan 0,7 V."),
  ("Diod ikkala tomonda ham OL ko'rsatsa nima demak?", "Diod uzilgan, ishlamaydi.")],
 "Halqa belgisini anod deb tushunish — halqa KATOD tomonini bildiradi."),

"Diod bilan zanjirni himoyalash": T(
 "Diodni himoya sifatida ulab, batareyani ataylab teskari ulash va zanjir ishlamay qolishini kuzatish",
 ["Ketma-ket qo'yilgan diod teskari qutblanishdan himoya qiladi: batareya teskari ulansa, diod tokni o'tkazmaydi va zanjir shunchaki ishlamaydi.",
  "Kamchiligi: to'g'ri ulanganda ham 0,7 V yo'qoladi. 5 V manbadan 4,3 V qoladi.",
  "Ikkinchi turdagi himoya — motor va rele bilan parallel qo'yiladigan teskari diod (flyback). Motor to'xtaganda g'altakda hosil bo'ladigan yuqori kuchlanish impulsini yo'q qiladi.",
  "Bu impuls bo'lmasa tranzistor va mikrokontroller kuyishi mumkin — shuning uchun motorli har bir zanjirda bu diod bo'lishi shart."],
 "Flyback diod keyingi choraklardagi motor va rele darslarida qayta-qayta uchraydi. Uni shu yerda tushuntirib, keyin \"o'sha diod\" deb eslatib turing.",
 [("Ketma-ket diod nimadan himoya qiladi?", "Batareyaning teskari ulanishidan."),
  ("Motor bilan parallel diod nima uchun kerak?", "Motor to'xtaganda hosil bo'ladigan yuqori kuchlanish impulsini yo'q qilish uchun.")],
 "Flyback diodni motorga to'g'ri yo'nalishda ulash — bu qisqa tutashuv, diod darhol kuyadi. U TESKARI ulanishi kerak."),

"Tranzistor: kichik tok katta tokni boshqaradi": T(
 "Tranzistorli zanjirda baza tokini va kollektor tokini o'lchab, kuchaytirish koeffitsientini hisoblash",
 ["Tranzistorning uch oyog'i bor: baza (B), kollektor (C), emitter (E). Bazadagi kichik tok kollektordan o'tadigan katta tokni boshqaradi.",
  "Kuchaytirish koeffitsienti (beta yoki hFE) — kollektor toki bazaga nisbatan necha marta katta. Odatiy qiymat 100-300.",
  "Misol: bazaga 1 mA berilsa, kollektordan 100-300 mA o'tishi mumkin. Shu bilan mikrokontrollerning kuchsiz pini motorni yurgiza oladi.",
  "Baza rezistorsiz ulanmaydi: baza-emitter o'tishi diod kabi, rezistorsiz katta tok o'tib tranzistorni kuydiradi. Odatda 1 kOm qo'yiladi."],
 "\"Kran\" o'xshatishi eng aniq ishlaydi: qo'l kuchi kichik (baza toki), kranadan chiqadigan suv kuchli (kollektor toki). Kran o'zi suv yaratmaydi — faqat oqimni boshqaradi.",
 [("Tranzistorning uch oyog'i qanday nomlanadi?", "Baza, kollektor, emitter."),
  ("Baza rezistori nima uchun kerak?", "Baza tokini cheklab, tranzistorni kuyishdan saqlash uchun.")],
 "Baza rezistorini qo'ymaslik — tranzistor bir necha sekundda ishdan chiqadi."),

"Tranzistor kalit sifatida": T(
 "Tugma bilan tranzistor orqali motorni yoqadigan zanjir yig'ish",
 ["Kalit rejimida tranzistor faqat ikki holatda ishlaydi: to'liq ochiq (to'yingan) yoki to'liq yopiq. Oraliq holat ishlatilmaydi.",
  "To'liq ochiq holatda kollektor-emitter orasida 0,2 V atrofida qoladi — deyarli sim kabi. Yopiq holatda esa tok o'tmaydi.",
  "Nima uchun tugmaning o'zi yetmaydi? Chunki tugma qo'l bilan bosiladi, tranzistor esa elektr signal bilan boshqariladi — uni sensor yoki mikrokontroller yoqishi mumkin.",
  "Kuchli yuklama uchun tranzistor turini to'g'ri tanlash kerak: BC547 100 mA gacha, TIP122 esa 5 A gacha ko'taradi."],
 "\"Nega tugmaning o'zi kifoya qilmaydi?\" savolini o'quvchilarga bering. Javob avtomatlashtirishning butun mohiyatini ochadi — mashina o'zi qaror qabul qilishi uchun elektr bilan boshqariladigan kalit kerak.",
 [("Kalit rejimida tranzistor qaysi ikki holatda bo'ladi?", "To'liq ochiq yoki to'liq yopiq."),
  ("Nega tranzistor tugmadan afzal?", "Uni qo'l emas, elektr signal boshqaradi.")],
 "Kuchli yuklamaga kuchsiz tranzistor (BC547) qo'yish — u qizib, ishdan chiqadi."),

"RGB LED: uch rang bitta korpusda": T(
 "RGB LEDning to'rt oyog'ini aniqlab, har bir rangni alohida yoqib ko'rish",
 ["RGB LED — bitta korpusdagi uchta LED: qizil, yashil va ko'k. Ular umumiy bitta oyoqni bo'lishadi.",
  "Umumiy katod turida umumiy oyoq GND ga ulanadi va ranglar musbat signal bilan yoqiladi. Umumiy anod turida esa teskari.",
  "Eng uzun oyoq — umumiy. Uning qaysi tomonda ekaniga qarab qolgan uch oyoq R, G, B tartibida joylashadi.",
  "Har bir rangga ALOHIDA rezistor kerak, chunki ularning tushish kuchlanishi har xil: qizil ~2 V, yashil va ko'k ~3 V."],
 "Turini multimetrning diod rejimida aniqlashni ko'rsating: qora shchupni umumiy oyoqqa qo'yganda LED yonsa — umumiy katod.",
 [("RGB LEDning eng uzun oyog'i nima?", "Umumiy oyoq (katod yoki anod)."),
  ("Nega har rangga alohida rezistor kerak?", "Ularning tushish kuchlanishi har xil.")],
 "Umumiy anod LEDni umumiy katod deb ulash — hech qanday rang yonmaydi va LED buzuq deb o'ylanadi."),

"Rang aralashtirish: qizil + yashil + ko'k": T(
 "Uch rangni turli kombinatsiyalarda yoqib, hosil bo'lgan ranglar jadvalini tuzish",
 ["Yorug'likda ranglar QO'SHILUVCHI (additive) tarzda aralashadi: uchala rang birga yonsa oq hosil bo'ladi.",
  "Bo'yoqda esa aksincha — ayiruvchi aralashish, uchala rang qo'shilsa qora chiqadi. Shuning uchun rasm darsidagi qoida bu yerda ishlamaydi.",
  "Asosiy kombinatsiyalar: qizil + yashil = sariq, qizil + ko'k = siyohrang (magenta), yashil + ko'k = moviy (siyan).",
  "Telefon va televizor ekrani ham shu tamoyilda ishlaydi: har bir piksel uchta mayda RGB nuqtadan iborat."],
 "Telefon ekranini lupa yoki suv tomchisi orqali ko'rsating — RGB nuqtalar ko'rinadi. Bu darsni bevosita o'quvchining kundalik buyumiga bog'laydi.",
 [("Qizil va yashil qo'shilsa qaysi rang chiqadi?", "Sariq."),
  ("Yorug'likda uch rang qo'shilsa nima hosil bo'ladi?", "Oq.")],
 "Bo'yoq aralashtirish qoidasini yorug'likka ko'chirish — natija kutilganidan boshqa chiqadi."),

"7-segment indikator tuzilishi": T(
 "Indikatorning har bir segmentini alohida yoqib, oyoqlar xaritasini chizish",
 ["7-segment indikator — sakkizraqamli ko'rinishda joylashgan yettita LED (a, b, c, d, e, f, g) va bitta nuqta (dp).",
  "Segmentlar a — yuqori, b — o'ng yuqori, c — o'ng past, d — past, e — chap past, f — chap yuqori, g — o'rta.",
  "Barcha LEDlar bitta umumiy oyoqni bo'lishadi: umumiy katod yoki umumiy anod. Odatda ikkita COM oyog'i bo'ladi, ular ichkaridan ulangan.",
  "Har bir segmentga o'z rezistori kerak — jami 7 yoki 8 ta rezistor."],
 "Segmentlar xaritasini daftarga chizib, harflarini yozib qo'yish shart. Keyingi darsda raqam yasashda shu chizma ishlatiladi.",
 [("7-segmentda nechta LED bor?", "Yettita segment va bitta nuqta, jami sakkizta."),
  ("Nechta rezistor kerak?", "Har segmentga bittadan, ya'ni 7-8 ta.")],
 "Bitta umumiy rezistorni COM oyog'iga qo'yish — bunda yonayotgan segmentlar soniga qarab yorqinlik o'zgarib turadi."),

"7-segmentda raqam yasash": T(
 "0 dan 9 gacha raqamlar uchun segment kombinatsiyalari jadvalini tuzib, qo'lda yig'ib ko'rsatish",
 ["Har bir raqam segmentlarning ma'lum kombinatsiyasi: 1 = b va c; 7 = a, b, c; 0 = a, b, c, d, e, f (g dan tashqari hammasi); 8 = hamma segment.",
  "Jadval tuzilsa, uni ikkilik kod sifatida yozish mumkin: har segment 1 (yonadi) yoki 0 (yonmaydi).",
  "Masalan 0 raqami = 1111110 (a dan g gacha tartibda). Bu kod keyinchalik dasturda massiv sifatida ishlatiladi.",
  "Ba'zi raqamlarni ikki xil yozish mumkin (masalan 6 va 9 — dumi bilan yoki dumsiz), muhandis o'zi tanlaydi."],
 "Jadvalni to'ldirish — bu aslida dasturlashga kirish. 2-yilda xuddi shu jadval Arduino kodidagi massivga aylanadi; buni aytib qo'ying.",
 [("1 raqami uchun qaysi segmentlar yonadi?", "b va c."),
  ("8 raqami uchun-chi?", "Barcha yettita segment.")],
 "Segment harflarini o'zicha o'ylab chiqarish — standart tartib (a yuqoridan boshlanib soat yo'nalishi bo'yicha) bor va unga amal qilish kerak."),

"Passiv va aktiv zummer farqi": T(
 "Ikki zummerga bir xil doimiy kuchlanish berib, farqni eshitish va yozib olish",
 ["Aktiv zummer ichida generator bor: unga doimiy kuchlanish berilsa, u o'zi belgilangan chastotada tovush chiqaradi. Faqat bitta ton bera oladi.",
  "Passiv zummerda generator yo'q: unga o'zgaruvchan signal (chastota) berilishi kerak. Doimiy kuchlanish berilsa faqat \"chirt\" etadi va jim qoladi.",
  "Shuning uchun melodiya faqat PASSIV zummerda chalinadi — chastotani o'zgartirib nota hosil qilinadi.",
  "Tashqi farqi: aktiv zummer odatda balandroq va pastki tomoni yopiq, passivnikida esa plata ko'rinib turadi."],
 "Ikkalasiga bir xil batareyani ulab, farqni eshittiring. Bir marta eshitilgan farq o'nta tushuntirishdan aniqroq bo'ladi.",
 [("Melodiya chalish uchun qaysi zummer kerak?", "Passiv."),
  ("Aktiv zummerga doimiy kuchlanish berilsa nima bo'ladi?", "U o'zining doimiy tonida tovush chiqaradi.")],
 "Passiv zummerni doimiy kuchlanishga ulab, \"buzuq\" deb hisoblash."),

"Tovush: chastota va baland-pastlik": T(
 "Turli chastotalarni generatordan berib, qaysi notaga to'g'ri kelishini jadvalga yozish",
 ["Tovush — havoning tebranishi. Chastota (Gerts, Hz) — bir sekunddagi tebranishlar soni.",
  "Chastota katta bo'lsa tovush ingichka (baland), kichik bo'lsa yo'g'on (past) eshitiladi.",
  "Inson qulog'i taxminan 20 Hz dan 20 000 Hz gacha eshitadi. Yosh ulg'aygan sari yuqori chegara pasayadi.",
  "Musiqiy notalar aniq chastotalarga ega: LA = 440 Hz, DO (o'rta) = 262 Hz. Bir oktava yuqori nota chastotasi ikki barobar katta bo'ladi: LA yuqori = 880 Hz."],
 "Oktava = chastotaning ikki barobarlanishi qoidasini ko'rsating — bu musiqa va matematika o'rtasidagi eng chiroyli bog'lanish va o'quvchilarga juda ta'sir qiladi.",
 [("Chastota oshsa tovush qanday o'zgaradi?", "Ingichkalashadi (balandlashadi)."),
  ("LA notasi 440 Hz bo'lsa, bir oktava yuqorisi qancha?", "880 Hz.")],
 "Tovush \"balandligi\" (chastota) bilan \"ovoz kuchi\" (amplituda) ni chalkashtirish — bu ikki har xil kattalik."),

"DC motor: elektrdan harakat": T(
 "Motorni ikki tomonlama ulab, aylanish yo'nalishini va bo'sh yurish tokini o'lchash",
 ["DC motor ichida g'altak (rotor) va doimiy magnit (stator) bor. G'altakdan tok o'tganda magnit maydon hosil bo'ladi va u statordan itariladi — rotor aylanadi.",
  "Kollektor va cho'tkalar har yarim aylanishda tok yo'nalishini almashtiradi, shuning uchun aylanish to'xtamaydi.",
  "Kuchlanish oshsa motor tezroq aylanadi. Kuchlanish nominaldan yuqori bo'lsa g'altak qiziydi va izolyatsiyasi buziladi.",
  "Motor bo'sh yurganda kam tok oladi (masalan 70 mA), lekin valini ushlab to'xtatilsa tok bir necha barobar oshadi (start toki). Shuning uchun motor hech qachon plata pinidan to'g'ridan-to'g'ri quvvatlantirilmaydi."],
 "Start tokini ampermetr bilan ko'rsating: motorni ushlab turganda tok qanday sakrashini o'quvchilar o'z ko'zi bilan ko'rsin. Bu keyingi darsdagi tranzistorli boshqaruvning sababini asoslaydi.",
 [("Motor valini ushlab qolsak tok qanday o'zgaradi?", "Bir necha barobar oshadi."),
  ("Motor tezligi nimaga bog'liq?", "Berilgan kuchlanishga.")],
 "Motorni to'g'ridan-to'g'ri mikrokontroller pinidan yurgizishga urinish — pin start tokiga chiday olmaydi."),

"Motorning aylanish yo'nalishini o'zgartirish": T(
 "Ikki tomonlama vklyuchatel (H-ko'prik maketi) bilan motor yo'nalishini almashtiradigan zanjir yig'ish",
 ["Motorning aylanish yo'nalishi tok yo'nalishiga bog'liq: qutblarni almashtirsak, motor teskari aylanadi.",
  "Qo'lda almashtirish uchun ikki holatli o'tkazgich kalit (DPDT) ishlatiladi — u bir vaqtda ikkala simni almashtiradi.",
  "Avtomatik almashtirish uchun to'rtta kalit (yoki tranzistor) kerak bo'ladi — bu H-ko'prik sxemasi deb ataladi, chunki chizmasi H harfiga o'xshaydi.",
  "H-ko'prikda bir vaqtda bir tomondagi ikki kalitni yoqish MUMKIN EMAS — bu qisqa tutashuv. Tayyor drayver mikrosxemalarida (L298N) bu himoya ichida qilingan."],
 "H-ko'prik sxemasini doskada chizib, o'quvchilarga \"qaysi ikki kalit birga yoqilsa motor o'ngga aylanadi?\" deb toptiring. Bu 4-chorakdagi L298N darsiga tayyorlaydi.",
 [("Motorni teskari aylantirish uchun nima qilinadi?", "Tok yo'nalishi, ya'ni qutblar almashtiriladi."),
  ("H-ko'prikda nechta kalit bor?", "To'rtta.")],
 "H-ko'prikda bir ustundagi ikki kalitni birga yoqib, qisqa tutashuv hosil qilish."),

"Rele: kuchsiz signal kuchli yuklamani yoqadi": T(
 "Rele bilan alohida batareyadan quvvat oladigan motorni yoqadigan zanjir yig'ish",
 ["Rele — elektromagnit kalit. Ichida g'altak va mexanik kontakt bor: g'altakdan tok o'tsa, magnit kontaktni tortadi va u ulanadi.",
  "Muhim afzalligi — GALVANIK AJRATISH: boshqaruv zanjiri (5 V) va yuklama zanjiri (masalan 12 V yoki 220 V) bir-biriga elektr jihatdan ulanmagan.",
  "Rele kontaktlari uch xil: COM (umumiy), NO (odatda ochiq) va NC (odatda yopiq). NO ga ulansa, rele yoqilganda zanjir ulanadi.",
  "G'altak bilan parallel teskari diod SHART: rele o'chganda g'altakda 100 V dan ortiq impuls hosil bo'ladi va u tranzistorni kuydiradi."],
 "220 V ni faqat namoyish tarzida, O'ZINGIZ ko'rsating; o'quvchilar 220 V bilan mustaqil ishlamaydi. Darsda ular faqat past kuchlanishli yuklama bilan ishlaydi.",
 [("Rele qanday kalit turi?", "Elektromagnit kalit."),
  ("NO kontakti nimani bildiradi?", "Odatda ochiq — rele yoqilganda ulanadi.")],
 "G'altakka teskari diod qo'ymaslik — boshqaruvchi tranzistor yoki plata pini kuyadi."),

"Fotorezistor: yorug'lik qarshilikni o'zgartiradi": T(
 "Fotorezistorning qarshiligini yorug'da, xonaki yorug'likda va qorong'ida o'lchab, grafik chizish",
 ["Fotorezistor (LDR) — yorug'lik tushganda qarshiligi kamayadigan komponent. Uning yuzasidagi ilonizi yo'lak yarimo'tkazgich moddadan.",
  "Odatiy qiymatlar: yorug'da 1-10 kOm, xonaki yorug'likda 10-50 kOm, qorong'ida 200 kOm dan 1 MOm gacha.",
  "Bog'liqlik chiziqli emas — yorug'lik ikki barobar oshsa, qarshilik ikki barobar kamaymaydi. Shuning uchun grafik egri chiziq bo'ladi.",
  "Fotorezistorni kuchlanish bo'luvchiga qo'yib, o'rta nuqtadan yorug'likka qarab o'zgaradigan kuchlanish olinadi — sensorning butun ishlash tamoyili shu."],
 "Uch holatdagi o'lchovni jadval qilib, o'quvchilar daftarida grafikka aylantirsin. Chiziqsiz bog'liqlikni o'z ko'zi bilan ko'rish keyingi darsdagi kalibrlashni tushunarli qiladi.",
 [("Qorong'ida fotorezistor qarshiligi qanday bo'ladi?", "Katta — yuz kiloomdan yuqori."),
  ("Fotorezistor qaysi zanjirda ishlatiladi?", "Kuchlanish bo'luvchida.")],
 "Fotorezistorni to'g'ridan-to'g'ri LEDga ketma-ket ulab, \"sensor\" deb hisoblash — signal olish uchun bo'luvchi kerak."),

"Termistor: harorat qarshilikni o'zgartiradi": T(
 "Termistorning qarshiligini xona haroratida va barmoq bilan isitilganda o'lchash",
 ["Termistor — harorat o'zgarganda qarshiligi o'zgaradigan rezistor. Eng ko'p ishlatiladigani NTC turi: harorat oshsa qarshilik KAMAYADI.",
  "Odatiy NTC termistor 25 daraja Selsiyda 10 kOm bo'ladi. 35 darajada ~6,5 kOm ga tushadi.",
  "PTC turi ham bor: unda harorat oshsa qarshilik ortadi. U ko'pincha himoya elementi sifatida ishlatiladi.",
  "Termistor ham fotorezistor kabi kuchlanish bo'luvchiga qo'yiladi va chiqishdagi kuchlanish haroratga qarab o'zgaradi."],
 "Barmoq bilan ushlab qarshilikning o'zgarishini real vaqtda ko'rsating — multimetr ekranidagi raqamning sekin siljishi juda ishonarli namoyish.",
 [("NTC termistorda harorat oshsa qarshilik qanday o'zgaradi?", "Kamayadi."),
  ("10 kOm termistor qaysi haroratda 10 kOm bo'ladi?", "25 daraja Selsiyda.")],
 "Termistorni oddiy rezistor deb hisoblab, o'lchash paytida barmoq bilan ushlab turish — natija o'zgarib ketadi."),

# ==================================================== 4-CHORAK: Sensorlar va yig'ma qurilma
"Yorug'lik sensorli zanjir": T(
 "Fotorezistor + tranzistor + LEDdan qorong'ida yonadigan avtomat yig'ish",
 ["To'liq sensorli zanjir uch qismdan iborat: sezish (fotorezistorli bo'luvchi), qaror (tranzistor), ijro (LED).",
  "Bo'luvchida fotorezistor yuqorida, oddiy rezistor pastda bo'lsa — qorong'ida o'rta nuqta kuchlanishi pasayadi. Joyi almashtirilsa, aksincha.",
  "Tranzistor bazasiga 0,7 V dan yuqori kuchlanish kelganda ochiladi va LEDni yoqadi. Ya'ni chegara qiymat 0,7 V.",
  "Sezgirlikni sozlash uchun pastki rezistor o'rniga potensiometr qo'yiladi — bu tungi chiroqlarning haqiqiy sxemasi."],
 "Sezish - qaror - ijro uchligini doskaga yozib qo'ying va 4-chorakdagi har bir zanjirda shu uchtasini o'quvchilarga ko'rsatib boring. Bu robototexnikaning asosiy tuzilmasi.",
 [("Sensorli zanjirning uch qismi qaysilar?", "Sezish, qaror qabul qilish, ijro."),
  ("Sezgirlikni qanday sozlash mumkin?", "Bo'luvchining ikkinchi rezistorini potensiometr bilan almashtirib.")],
 "Fotorezistor va rezistorni bo'luvchida almashtirib qo'yish — zanjir teskari ishlaydi (yorug'da yonadi)."),

"Harorat sensorli zanjir": T(
 "Termistorli bo'luvchi va tranzistor bilan issiq bo'lganda signal beradigan zanjir yig'ish",
 ["Termistorli bo'luvchi ham yorug'lik zanjiri kabi ishlaydi, faqat sezgi kattaligi — harorat.",
  "Chegarani sozlash: potensiometrni buray-buray, kerakli haroratda tranzistor ochiladigan holat topiladi.",
  "Termistor issiq buyumga tegib turishi kerak — havodagi harorat va buyum harorati farq qiladi. Bu o'lchash usulining muhim sharti.",
  "Bu zanjir aniq harorat KO'RSATMAYDI, faqat \"chegaradan oshdi / oshmadi\" deb signal beradi. Aniq raqam uchun mikrokontroller kerak — bu keyingi yil mavzusi."],
 "\"Chegara sensori\" va \"o'lchov asbobi\" farqini aniq ajrating. O'quvchilar ko'pincha zanjirdan aniq gradus kutadi.",
 [("Bu zanjir haroratni ko'rsatadimi?", "Yo'q, faqat chegaradan oshganini bildiradi."),
  ("Chegara qanday sozlanadi?", "Bo'luvchidagi potensiometr bilan.")],
 "Termistorni buyumga tegizmasdan havoda ushlab, javob sekin kelishidan hayron bo'lish."),

"Magnit va reed datchigi": T(
 "Reed datchikli eshik ochilganini sezuvchi signalizatsiya maketini yig'ish",
 ["Reed datchik — shisha kolbaga kavsharlangan ikki elastik kontakt. Magnit yaqinlashsa ular tortilib tutashadi.",
  "Magnit uzoqlashishi bilan kontaktlar o'z holiga qaytadi. Ya'ni bu magnit bilan boshqariladigan oddiy kalit.",
  "Turi ikkita: NO (magnit kelganda ulanadi) va NC (magnit kelganda uziladi). Signalizatsiyada odatda NC ishlatiladi — sim kesilsa ham signal beradi.",
  "Ishonchli ishlash masofasi 10-20 mm. Kolba shishadan, shuning uchun oyoqlarini kolbaga yaqin joyidan bukmaslik kerak — sinadi."],
 "NC turining signalizatsiyada afzalligini so'rab toping: \"o'g'ri simni kesib qo'ysa nima bo'ladi?\" Bu xavfsizlik muhandisligining klassik misoli.",
 [("Reed datchik nimaga javob beradi?", "Magnit maydonga."),
  ("Signalizatsiyada nega NC turi afzal?", "Sim kesilsa ham zanjir uzilib, signal beradi.")],
 "Reed datchik oyoqlarini kolbaga yaqin joydan bukish — shisha yorilib, datchik ishdan chiqadi."),

"Hall datchigi: magnit maydonni sezish": T(
 "Hall datchigi bilan magnitning yaqinlashishini sezish va aylanish sonini sanash maketi",
 ["Hall datchigi magnit maydonini ELEKTRON usulda sezadi — mexanik kontakt yo'q, shuning uchun cheksiz ko'p marta ishlaydi va tez javob beradi.",
  "Uch oyog'i bor: VCC, GND va chiqish (OUT). Chiqishda magnit bor-yo'qligiga qarab yuqori yoki past daraja bo'ladi.",
  "Ikki turi: raqamli (bor/yo'q deb javob beradi) va analog (maydon kuchiga proporsional kuchlanish beradi).",
  "Amaliy qo'llanishi: velosiped spidometri (g'ildirakdagi magnitni sanaydi), motor aylanish datchigi, telefon qopqog'ini sezish."],
 "Velosiped spidometri misolini ishlating — o'quvchilar bu qurilmani biladi va uning ichida nima borligini bilish qiziqish uyg'otadi.",
 [("Hall va reed datchiklarining asosiy farqi nima?", "Hall elektron, mexanik kontaktsiz; reed mexanik kontaktli."),
  ("Spidometr aylanishni qanday sanaydi?", "G'ildirakdagi magnit har aylanishda datchik yonidan o'tadi.")],
 "Hall datchigining chiqish oyog'ini tortuvchi rezistorsiz ulash — ba'zi turlarida signal noaniq bo'ladi."),

"Tovush (mikrofon) datchigi": T(
 "Mikrofon moduli bilan qarsakka javob beradigan zanjir yig'ish va sezgirlikni sozlash",
 ["Mikrofon havo tebranishini juda kichik elektr signalga aylantiradi — millivoltlar tartibida.",
  "Shuning uchun modulda kuchaytirgich va komparator bor: kuchaytirilgan signal chegara bilan solishtiriladi va raqamli chiqish beriladi.",
  "Moduldagi potensiometr aynan shu chegarani sozlaydi. Juda sezgir qilinsa har shovqindan ishlaydi, juda past qilinsa qarsakni ham sezmaydi.",
  "Modulda odatda ikki chiqish bor: A0 (analog, tovush kuchi) va D0 (raqamli, chegaradan oshdi/oshmadi)."],
 "Sezgirlikni sozlashni har bir juftlik o'zi qilsin — bu sozlash jarayoni sensor bilan ishlashning eng muhim ko'nikmasi va uni faqat amalda o'rganish mumkin.",
 [("Modulda potensiometr nimani sozlaydi?", "Ishga tushish chegarasini."),
  ("A0 va D0 chiqishlari farqi nima?", "A0 tovush kuchini, D0 chegaradan oshganini beradi.")],
 "Sezgirlikni maksimalga burab qo'yish — modul doimiy signal berib turadi va foydasiz bo'ladi."),

"Suv sathi datchigi": T(
 "Suv sathi datchigi bilan idishdagi suv miqdorini sezuvchi ogohlantirgich yig'ish",
 ["Suv sathi datchigi — platadagi bir necha parallel o'tkazgich yo'lak. Suv ularni tutashtirgan sari qarshilik kamayadi.",
  "Ya'ni u sathni RAQAM bilan o'lchamaydi, balki suvga botgan qismi qancha ko'p bo'lsa, shuncha kichik qarshilik beradi.",
  "Suvning tuz miqdori natijaga ta'sir qiladi: sho'r suvda qarshilik kichikroq. Shuning uchun har muhitda kalibrlash kerak.",
  "Datchik doimiy suvda turishi mumkin emas: elektroliz tufayli yo'laklar yemiriladi. Uzoq ishlatishda unga faqat o'lchash paytida quvvat beriladi."],
 "Elektroliz masalasini ayting — bu o'quvchilar uchun kutilmagan va kimyo bilan bog'lanadigan qiziq nuqta. Kimyo darsidagi elektroliz mavzusiga havola qiling.",
 [("Datchik suvga qancha ko'p botsa qarshilik qanday o'zgaradi?", "Kamayadi."),
  ("Nega datchik doimiy quvvat ostida turmasligi kerak?", "Elektroliz yo'laklarni yemiradi.")],
 "Datchikning yuqori qismidagi elektronikani suvga botirib yuborish — faqat pastki yo'laklar suvga tegishi kerak."),

"Tuproq namligi datchigi": T(
 "Quruq va nam tuproqda datchik ko'rsatkichini o'lchab, sug'orish chegarasini aniqlash",
 ["Rezistiv datchik ikki elektrod orasidagi tuproq qarshiligini o'lchaydi: nam tuproq yaxshi o'tkazadi, quruq tuproq — yomon.",
  "Sig'imli (capacitive) datchik esa elektrodlarni tuproqqa tegizmaydi, u tuproqning dielektrik xossasini o'lchaydi. Shuning uchun yemirilmaydi va uzoq xizmat qiladi.",
  "Rezistiv turi arzon, lekin bir necha oyda korroziyadan ishdan chiqadi. Amaliy loyihalar uchun sig'imli turi tavsiya etiladi.",
  "Har tuproq turi uchun chegara boshqacha: qumli va gilli tuproqda bir xil namlikda ko'rsatkich har xil chiqadi. Shuning uchun kalibrlash shart."],
 "Ikkala datchik turini yonma-yon qo'yib solishtiring va \"qaysi biri arzon, qaysi biri uzoq ishlaydi\" degan muhandislik savolini muhokama qiling.",
 [("Nam tuproqda qarshilik qanday bo'ladi?", "Kichik."),
  ("Nega sig'imli datchik afzal?", "Elektrodlari tuproqqa tegmaydi, korroziyaga uchramaydi.")],
 "Bir tuproqda sozlangan chegarani boshqa tuproqqa ko'chirish — natija noto'g'ri chiqadi."),

"Qiyalik (tilt) datchigi": T(
 "Tilt datchigi bilan quti ag'darilganda signal beradigan zanjir yig'ish",
 ["Tilt datchik ichida kichik metall sharcha (yoki simob tomchisi) bor. Qurilma qiyshaysa, sharcha siljib ikki kontaktni tutashtiradi.",
  "Ya'ni u burchakni o'lchamaydi — faqat \"qiyshaydi / qiyshaymadi\" deb javob beradi. Ishga tushish burchagi odatda 15-30 daraja.",
  "Sharchali turi arzon va xavfsiz; simobli turi aniqroq, lekin simob zaharli va ta'lim uchun ishlatilmaydi.",
  "Aniq burchak kerak bo'lsa akselerometr (MPU6050) ishlatiladi — u har uch o'q bo'yicha qiyalikni gradusda beradi. Bu 7-sinf mavzusi."],
 "Telefon ekranining aylanishi qaysi datchik bilan bo'lishini so'rang. Javob (akselerometr) keyingi yillarga ko'prik bo'ladi.",
 [("Tilt datchik burchakni o'lchaydimi?", "Yo'q, faqat qiyshayganini bildiradi."),
  ("Aniq burchak uchun nima ishlatiladi?", "Akselerometr.")],
 "Datchikni gorizontal qo'yib, u umuman ishlamayotgandek tuyulishi — u faqat ma'lum yo'nalishda qiyshayganda ishlaydi."),

"Olov datchigi va xavfsizlik": T(
 "Olov datchigi bilan shamning alangasini sezuvchi ogohlantirgich yig'ish (o'qituvchi nazorati ostida)",
 ["Olov datchigi infraqizil nurni sezadi. Alangada 760-1100 nm oralig'idagi IK nurlanish kuchli bo'ladi.",
  "Datchikning ko'rish burchagi ~60 daraja, masofasi 20-100 sm. Undan uzoqdagi olovni sezmaydi.",
  "Quyosh nuri va lampa nuri ham IK chiqaradi — shuning uchun yolg'on ishga tushish bo'lishi mumkin. Haqiqiy yong'in datchiklarida shuning uchun tutun datchigi bilan birga ishlatiladi.",
  "Xavfsizlik: sinfda ochiq olov faqat o'qituvchi qo'lida, o'chirish vositasi (qum yoki mato) yonida turishi shart."],
 "Bu darsda olovni FAQAT o'zingiz yoqing. Sinfda ochiq olov bo'lgan yagona dars — tayyorgarlikni oldindan qiling va qoidani ochiq e'lon qiling.",
 [("Olov datchigi nimani sezadi?", "Alangadan chiqadigan infraqizil nurni."),
  ("Nega u yolg'on ishga tushishi mumkin?", "Quyosh va lampa ham IK nur chiqaradi.")],
 "Datchikni derazaga qaratib qo'yish — quyosh nuridan doimiy signal beradi."),

"Analog va raqamli sensor farqi": T(
 "Bir xil hodisani analog va raqamli chiqishdan o'lchab, natijalarni solishtirish",
 ["Analog sensor uzluksiz qiymat beradi: masalan fotorezistorli bo'luvchi 0 dan 5 V gacha istalgan kuchlanishni berishi mumkin.",
  "Raqamli sensor faqat ikki holat beradi: 0 yoki 1, ya'ni \"chegaradan past\" yoki \"chegaradan baland\".",
  "Ko'p modullarda ikkalasi ham bor: A0 (analog) va D0 (raqamli). D0 aslida moduldagi komparator analog signalni chegara bilan solishtirib chiqargan natija.",
  "Qaysi birini tanlash vazifaga bog'liq: \"qorong'i bo'ldimi?\" uchun raqamli yetadi; \"qanchalik qorong'i?\" uchun analog kerak."],
 "Tanlov savolini o'quvchilarga bering: \"chiroqni yoqish uchun qaysi biri kerak, yorqinlikni sekin oshirish uchun qaysi biri?\" Muhandislik qarori shu yerdan boshlanadi.",
 [("Raqamli sensor nechta holat beradi?", "Ikkita: 0 yoki 1."),
  ("Yorug'lik darajasini raqam bilan bilish uchun qaysi chiqish kerak?", "Analog.")],
 "D0 chiqishini analog deb o'ylab, undan darajali qiymat kutish."),

"Signalni tranzistor bilan kuchaytirish": T(
 "Sensor signalini tranzistor orqali LEDga uzatib, kuchaytirish ta'sirini o'lchash",
 ["Sensorning chiqish toki juda kichik (mikroamperlar) — u LED yoki motorni yurgiza olmaydi.",
  "Tranzistor shu kichik tokni kuchaytiradi: bazaga 0,1 mA kelsa, kollektordan 20 mA o'tishi mumkin.",
  "Kuchaytirish koeffitsientini o'lchab ko'rish mumkin: baza tokini va kollektor tokini o'lchab, bir-biriga bo'lish kerak.",
  "Katta yuklama uchun bitta tranzistor yetmasa, ikkitasi ketma-ket qo'yiladi (Darlington sxemasi) — koeffitsientlar ko'payadi va 10 000 marta kuchaytirish olinadi."],
 "Darlington sxemasini shunchaki nom sifatida aytib qo'ying, chuqurlashtirmang — 5-sinf uchun asosiysi \"kichik tok katta tokni boshqaradi\" g'oyasi.",
 [("Sensor signalini nega kuchaytirish kerak?", "Uning toki LED yoki motorni yurgizish uchun juda kichik."),
  ("Kuchaytirish koeffitsienti qanday topiladi?", "Kollektor tokini baza tokiga bo'lib.")],
 "Sensorni to'g'ridan-to'g'ri motorga ulashga urinish — sensor kuyadi yoki umuman ishlamaydi."),

"Ikki sensorli zanjir: birgalikda ishlash": T(
 "Yorug'lik va harorat sensorlarini birga ulab, ikkala shart bajarilganda ishlaydigan zanjir yig'ish",
 ["Ikki sensorni ketma-ket ulash \"VA\" mantiqini beradi: ijro faqat ikkala shart bajarilganda ishlaydi.",
  "Parallel ulash esa \"YOKI\" beradi: istalgan bittasi ishga tushsa yetarli.",
  "Amaliy misol: issiqxona shamollatgichi faqat HAM issiq, HAM kunduzi bo'lsa ishlashi kerak — bu VA mantiqi.",
  "Ikki sensorli zanjirda har birining chegarasi alohida sozlanadi, aks holda biri doim ishga tushib turadi va ikkinchisining ta'siri ko'rinmaydi."],
 "1-chorakdagi ikki tugmali VA/YOKI darsiga aniq havola qiling. O'quvchilar bir xil mantiq turli komponentlarda takrorlanishini ko'rsa, tushuncha umumlashadi.",
 [("Ikki sensor ketma-ket ulansa qaysi mantiq hosil bo'ladi?", "VA."),
  ("Har bir sensor chegarasi alohida sozlanishi kerakmi?", "Ha, aks holda biri ikkinchisini bekor qiladi.")],
 "Ikki sensorni ulab, chegaralarni sozlamasdan qoldirish — zanjir tasodifiy ishlagandek ko'rinadi."),

"Sxema bo'yicha yig'ish mashqi": T(
 "Berilgan uch printsipial sxemani mustaqil o'qib, breadboardda yig'ish",
 ["Sxemani yig'ishga aylantirish tartibi: 1) quvvat shinalarini ulash, 2) asosiy komponentlarni joylash, 3) signal simlarini tortish, 4) tekshirish, 5) quvvat berish.",
  "Sxemadagi GND belgilari bir-biriga sim bilan chizilmagan bo'lsa ham — ular hammasi bitta nuqtaga ulanadi. Bu sxema tilining qisqartmasi.",
  "Xuddi shunday, VCC yoki +5V belgilari ham o'zaro ulangan hisoblanadi.",
  "Yig'ilgan sxemani tekshirishning tez usuli: sxemadagi har bir chiziqni qalam bilan belgilab chiqish, breadboardda o'sha ulanish borligini tasdiqlagach."],
 "GND belgilarining o'zaro ulanganini alohida tushuntiring — bu sxema o'qishdagi eng ko'p uchraydigan tushunmovchilik.",
 [("Sxemadagi bir necha GND belgisi nimani bildiradi?", "Ular hammasi bitta umumiy nuqtaga ulangan."),
  ("Yig'ishni nimadan boshlash kerak?", "Quvvat shinalarini ulashdan.")],
 "GND belgilarini alohida-alohida nuqtalar deb tushunib, ularni ulashni unutish."),

"O'z sxemangni qog'ozda chizish": T(
 "O'zi o'ylab topgan qurilma sxemasini standart belgilar bilan chizib, o'qituvchiga tekshirtirish",
 ["Sxema chizish tartibi: chapda manba, o'ngda iste'molchi, yuqorida musbat shina, pastda GND. Bu odatiy joylashuv sxemani o'qishni osonlashtiradi.",
  "Har bir komponentga nom va nominal yoziladi: R1 220 Om, C1 100 uF, LED1. Bu belgilash keyin komponentlar ro'yxatini tuzishda ishlatiladi.",
  "Simlar imkon qadar kesishmasligi kerak. Kesishish zarur bo'lsa, ulanmagani nuqtasiz chiziladi.",
  "Sxemaning yonida qisqa izoh bo'lishi kerak: qurilma nima qiladi va qaysi shartda ishga tushadi."],
 "Belgilash (R1, C1) tizimini talab qiling — bu keyingi yillarda komponentlar ro'yxati va montaj chizmasi bilan ishlashga asos bo'ladi.",
 [("Sxemada GND odatda qayerda chiziladi?", "Pastda."),
  ("Nima uchun komponentlarga R1, C1 kabi nom beriladi?", "Ro'yxat tuzish va ular haqida gapirish oson bo'lishi uchun.")],
 "Sxemani belgilashsiz chizish — keyin uni o'zi ham o'qiy olmaydi."),

"Nosozlik topish: murakkab zanjirda": T(
 "5 komponentli, ikki xatoli zanjirni bo'lib-bo'lib tekshirish usuli bilan tuzatish",
 ["Murakkab zanjirda nosozlikni izlashning eng samarali usuli — YARMIGA BO'LISH: zanjirni ikkiga bo'lib, qaysi yarmida muammo borligini aniqlash, keyin shu yarmini yana ikkiga bo'lish.",
  "Sakkiz bosqichli zanjirda bu usul bilan xato 3 ta tekshiruvda topiladi, ketma-ket tekshirishda esa 8 tagacha kerak bo'ladi.",
  "Ikkinchi usul — bo'laklarga ajratib sinash: har bir bo'lakni alohida ishlatib ko'rish, keyin birlashtirish.",
  "Ikkita xato bir vaqtda bo'lsa eng qiyin holat: birinchisini tuzatgach ham zanjir ishlamaydi va o'quvchi tuzatish noto'g'ri deb o'ylaydi. Shuning uchun har tuzatishdan keyin tizimli tekshiruv qayta boshlanadi."],
 "Ataylab IKKITA xato kiriting — bu qiyin, lekin real hayotda ko'p uchraydigan holat. Xatolar bir-birini yashirishi mumkinligini muhokama qiling.",
 [("Yarmiga bo'lish usuli nima beradi?", "Xatoni ancha kam tekshiruvda topish imkonini."),
  ("Bir xatoni tuzatgach zanjir ishlamasa nima demak?", "Ikkinchi xato ham bor bo'lishi mumkin.")],
 "Bitta xatoni topgach izlashni to'xtatish."),

"Komponentni to'g'ri tanlash: katalogdan": T(
 "Berilgan vazifa uchun katalogdan mos komponent tanlab, tanlovini asoslash",
 ["Komponent tanlashda uch mezon: ELEKTR mosligi (kuchlanish, tok, quvvat), FIZIK mosligi (o'lcham, oyoqlar), NARX.",
  "Har komponentning maksimal qiymatlari bor: rezistorning quvvati (0,25 Vt), tranzistorning maksimal toki, kondensatorning maksimal kuchlanishi.",
  "Qoida: ishchi qiymat maksimalning 50-70% idan oshmasligi kerak — zaxira qoldiriladi. 5 V zanjirga 6,3 V kondensator emas, 16 V li olinadi.",
  "Datasheet — ishlab chiqaruvchining rasmiy hujjati. Undagi birinchi jadval (Absolute Maximum Ratings) eng muhim ma'lumotni beradi."],
 "Datasheetning bitta sahifasini proyektorda ochib, birgalikda o'qing. 5-sinf uchun to'liq tushunish shart emas — maqsad \"bunday hujjat bor va unda javob bor\" degan bilim.",
 [("Komponent tanlashning uch mezoni qaysi?", "Elektr mosligi, fizik mosligi, narx."),
  ("5 V zanjir uchun qanday kondensator olinadi?", "Kamida 10-16 V ga mo'ljallangani.")],
 "Faqat nominalga qarab tanlash, maksimal kuchlanish yoki quvvatga e'tibor bermaslik."),

"Qurilmani korpusga joylashtirish": T(
 "Yig'ilgan zanjirni karton yoki plastik qutiga joylashtirib, tugma va LEDlarni tashqariga chiqarish",
 ["Korpus uch vazifani bajaradi: himoya (chang, zarba), xavfsizlik (tokli qismlarga tegib bo'lmaydi) va foydalanish qulayligi.",
  "Joylashtirish tartibi: avval boshqaruv elementlari (tugma, kalit, LED) joyi belgilanadi, keyin plata joylashtiriladi, oxirida simlar tortiladi.",
  "Batareya ALMASHTIRILADIGAN bo'lishi kerak — uning joyi qopqoq ostida yoki alohida bo'linmada bo'lsin.",
  "Isish nazarga olinadi: qiziydigan komponentlar (rezistor, stabilizator, motor drayveri) yonida havo o'tishi uchun teshik qoldiriladi."],
 "Foydalanuvchi nuqtai nazarini kiriting: \"tugmani ko'r-ko'rona topa olasizmi? Batareyani almashtirish uchun butun qurilmani buzish kerakmi?\" Bu dizayn tafakkurining boshlanishi.",
 [("Korpusning uch vazifasi qaysi?", "Himoya, xavfsizlik, foydalanish qulayligi."),
  ("Batareya joyi qanday bo'lishi kerak?", "Almashtirish oson bo'ladigan joyda.")],
 "Barcha teshiklarni plata joylashtirilgandan keyin o'lchash — natijada teshiklar mos kelmaydi."),

"Taqdimot: o'z qurilmangni tushuntirish": T(
 "Har bir juftlik o'z qurilmasini 3 daqiqada tushuntirib berish",
 ["Texnik taqdimotning to'rt qismi: 1) qurilma qanday muammoni yechadi, 2) qanday ishlaydi, 3) namoyish, 4) nimani yaxshilash mumkin.",
  "Ishlash tamoyilini tushuntirishda sezish - qaror - ijro tuzilmasidan foydalanish qulay: nima sezadi, qanday qaror qabul qiladi, nima qiladi.",
  "Namoyish taqdimotning eng muhim qismi — u albatta oldindan sinab ko'rilgan bo'lishi kerak.",
  "\"Nimani yaxshilash mumkin\" qismi kuchsizlikni tan olish emas, aksincha — muallif o'z ishini tanqidiy baholay olishini ko'rsatadi."],
 "To'rt qismli tuzilmani doskaga yozib qo'ying va har bir juftlik shu tartibda gapirsin. Bu chorak yakuni bo'lib, keyingi yillardagi loyiha himoyalariga tayyorgarlik.",
 [("Texnik taqdimot qaysi to'rt qismdan iborat?", "Muammo, ishlash tamoyili, namoyish, yaxshilash imkoniyati."),
  ("Namoyishdan oldin nima qilish shart?", "Uni sinab ko'rish.")],
 "Faqat \"biz nima yasadik\" deb gapirib, \"nima uchun\" qismini tashlab ketish."),
}
