# -*- coding: utf-8 -*-
"""2-yil, 6-sinf — elektronikadan mikrokontrollerga, matnli Arduino."""

from kb_5_8 import T

MAVZULAR = {

# ==================================================== 1-CHORAK: Elektronikadan mikrokontrollerga
"Om qonuni va quvvat: takrorlash": T(
 "Zanjir yig'ib, U, I, R va P ni o'lchab, hisob bilan solishtirish",
 ["U = I x R. Quvvat: P = U x I = I kvadrat x R = U kvadrat / R.",
  "Amaliy qisqartma: V / kOm = mA. 5 V / 1 kOm = 5 mA.",
  "Rezistorda ajraladigan quvvat uning nominal quvvatidan (odatda 0,25 Vt) oshmasligi kerak.",
  "Javob tekshiriladi: birlik to'g'rimi, qiymat realmi, teskari hisob mos keladimi."],
 "Bu takrorlash darsi — yangi material bermang. Yozgi tanaffusdan keyingi bo'shliqlarni aniqlab, to'ldirish maqsad.",
 [("100 Om da 5 V bo'lsa quvvat qancha?", "0,25 Vt — chegarada, kuchliroq rezistor kerak."),
  ("V / kOm nima beradi?", "Milliamperni.")],
 "Quvvatni tekshirmaslik — rezistor qiziydi va nominal siljiydi."),

"Kuchlanish bo'luvchi va sensor ulash": T(
 "Fotorezistor va termistorni bo'luvchiga ulab, chiqish kuchlanishini o'lchash",
 ["Bo'luvchi: U chiqish = U kirish x R2 / (R1 + R2). R2 — GND ga ulangan pastki rezistor.",
  "Barcha qarshilikli sensorlar (fotorezistor, termistor, tuproq) shu sxemada ulanadi.",
  "Sensor yuqorida yoki pastda bo'lishi natijani teskarilaydi — buni ataylab tanlash mumkin.",
  "Ikkinchi rezistor qiymati sensor qarshiligining o'rta qiymatiga yaqin bo'lsa, sezgirlik eng katta bo'ladi."],
 "\"Ikkinchi rezistor sensor qarshiligiga yaqin bo'lsin\" qoidasini ayting — bu sezgirlikni sezilarli oshiradi va kam biladigan detal.",
 [("Sensorni yuqoriga qo'ysak natija qanday bo'ladi?", "Teskari — pastga qo'yilgandagiga nisbatan."),
  ("Ikkinchi rezistor qanday tanlanadi?", "Sensor qarshiligining o'rta qiymatiga yaqin.")],
 "Ikkinchi rezistorni tasodifiy tanlash — sezgirlik past bo'ladi."),

"Tranzistor, rele, diod: takrorlash": T(
 "Uch komponentni bir zanjirda ishlatib, har birining vazifasini tushuntirish",
 ["Tranzistor kalit sifatida: baza rezistori majburiy (1 kOm), to'yingan holda kollektor-emitter 0,2 V.",
  "Rele boshqaruv va yuklama zanjirlarini ajratadi. G'altagi 40 mA oladi — tranzistor orqali boshqariladi.",
  "Flyback diod g'altakli yuklamaga parallel va teskari ulanadi — MAJBURIY.",
  "Uchtasi birga: mikrokontroller pini -> tranzistor -> rele g'altagi (diod bilan) -> kuchli yuklama."],
 "Uch komponentning zanjirdagi o'rnini bir chizmada ko'rsating. Bu chorakda mikrokontroller qo'shilganda shu zanjir asos bo'ladi.",
 [("Rele nima uchun tranzistor orqali boshqariladi?", "G'altagi plata pinidan ko'proq tok oladi."),
  ("Flyback diod qanday ulanadi?", "Parallel va teskari yo'nalishda.")],
 "Flyback diodni unutish."),

"Analog va raqamli signal": T(
 "Bir hodisani analog va raqamli usulda o'lchab, natijalarni solishtirish",
 ["Analog signal uzluksiz o'zgaradi va cheksiz ko'p qiymat qabul qila oladi.",
  "Raqamli signal faqat aniq darajalarga ega. Eng oddiy holatda ikkita: 0 va 1.",
  "Analogni raqamliga aylantirish — diskretlash: qiymat ma'lum sondagi darajalarga bo'linadi. Arduino da 1024 daraja.",
  "Aylantirishda ma'lumot qisman yo'qoladi, lekin raqamli signal shovqinga chidamli va uzatish oson."],
 "Musiqa yozuvini misol qiling: vinil plastinka analog, MP3 raqamli. Shovqinga chidamlilik va aniqlik farqini shu misol yaxshi ochadi.",
 [("Analog signalning asosiy xususiyati nima?", "Uzluksiz o'zgarishi."),
  ("Raqamli signalning afzalligi nima?", "Shovqinga chidamli va uzatish oson.")],
 "Analog va raqamlini \"eski va yangi\" deb tushunish — bu ikki xil signal turi, biri ikkinchisidan yaxshi emas."),

"Mikrokontroller nima va nimasi bilan farq qiladi": T(
 "Tranzistorli avtomat va mikrokontrollerli yechimni solishtirib, jadval tuzish",
 ["Mikrokontroller — bitta mikrosxemadagi kompyuter: protsessor, xotira, kirish-chiqish pinlari.",
  "Kompyuterdan farqi: operatsion tizimi yo'q, bitta dastur bajaradi, kam quvvat sarflaydi, tashqi qurilmalarga bevosita ulanadi.",
  "Oddiy zanjirdan farqi: mantiq simlar bilan emas, DASTUR bilan belgilanadi.",
  "Shuning uchun bir xil apparat bilan butunlay boshqa vazifani bajarish mumkin — faqat dasturni almashtirish yetadi."],
 "Kompyuter va mikrokontroller farqini jadval qilib to'ldiring: operatsion tizim, quvvat, narx, vazifa. Bu tushunchani aniq chegaralaydi.",
 [("Mikrokontrollerda mantiq nima bilan belgilanadi?", "Dastur bilan."),
  ("Kompyuterdan asosiy farqi nima?", "Operatsion tizimi yo'q, bitta dastur bajaradi.")],
 "Mikrokontrollerni kichik kompyuter deb to'liq tenglashtirish."),

"Arduino Uno: pinlar va imkoniyatlar": T(
 "Pin xaritasini chizib, har guruhning imkoniyatlarini yozish",
 ["ATmega328P: 32 KB flesh, 2 KB SRAM, 16 MHz. Raqamli D0-D13, analog A0-A5.",
  "PWM pinlari ~ belgili: 3, 5, 6, 9, 10, 11. A4 va A5 I2C uchun band bo'lishi mumkin.",
  "D0 va D1 Serial aloqa uchun ishlatiladi — ularga komponent ulash yuklashni buzadi.",
  "Pin toki: xavfsiz 20 mA, mutlaq chegara 40 mA. Butun plata 200 mA gacha."],
 "D0/D1 cheklovini alohida ayting — bu pinlarga komponent ulangan bo'lsa dastur yuklanmaydi va sabab topilmaydi.",
 [("Qaysi pinlar Serial aloqa uchun band?", "D0 va D1."),
  ("Pindan xavfsiz qancha tok olinadi?", "20 mA.")],
 "D0 va D1 ga komponent ulash — dastur yuklanmaydi."),

"IDE bilan tanishuv (matnli muhit)": T(
 "Arduino IDE ni sozlab, misol dasturni ochib, kompilyatsiya qilish",
 ["IDE oynasi qismlari: kod maydoni, tekshirish (Verify) va yuklash (Upload) tugmalari, xabarlar oynasi.",
  "Verify kodni tekshiradi va kompilyatsiya qiladi, lekin yuklamaydi. Xatolarni topish uchun qulay.",
  "Xabarlar oynasi xatolarni ko'rsatadi. Xato xabarida QATOR RAQAMI bo'ladi — o'sha qatorga qarash kerak.",
  "Misollar: File > Examples. Yangi mavzuni doim misoldan boshlash tavsiya etiladi."],
 "Xato xabarini o'qishni birinchi darsdan o'rgating. Xabarni o'qimasdan kodni tasodifan o'zgartirish — eng ko'p vaqt yo'qotadigan odat.",
 [("Verify tugmasi nima qiladi?", "Kodni tekshiradi va kompilyatsiya qiladi."),
  ("Xato xabarida nima ko'rsatiladi?", "Xato turi va qator raqami.")],
 "Xato xabarini o'qimasdan kodni tasodifan o'zgartirish."),

"Blokli va matnli dasturlash: solishtirish": T(
 "Bir xil vazifani blokli va matnli usulda bajarib, ikkalasini solishtirish",
 ["Blokli: sintaksis xatosi yo'q, tez boshlash mumkin, lekin murakkab dastur uchun joy yetmaydi.",
  "Matnli: yozish tezroq (bir marta o'rganilgach), imkoniyatlar cheksiz, lekin sintaksisga qat'iy amal qilish kerak.",
  "Mosligi: \"raqamli pinni yoq\" blogi = digitalWrite(pin, HIGH); \"kut\" blogi = delay(ms).",
  "Professional dasturlash matnli — barcha kutubxonalar va misollar matnli kodda yozilgan."],
 "Bir vazifani ikki usulda bajartirib, kod uzunligi va yozish vaqtini solishtiring. Bu o'tishning sababini raqam bilan ko'rsatadi.",
 [("Blokli dasturlashning afzalligi nima?", "Sintaksis xatosi bo'lmaydi."),
  ("Matnli dasturlashning afzalligi-chi?", "Imkoniyatlari cheksiz, barcha kutubxonalar shunda.")],
 "Matnli koddagi nuqta-vergul va katta-kichik harflar farqini e'tiborsiz qoldirish."),

"Birinchi dastur: Blink": T(
 "Blink dasturini yozib, o'zgartirib, natijani kuzatish",
 ["Blink: setup ichida pinMode(13, OUTPUT); loop ichida digitalWrite(13, HIGH), delay(1000), digitalWrite(13, LOW), delay(1000).",
  "Har buyruq oxirida NUQTA-VERGUL bo'lishi shart. Uni unutish eng ko'p uchraydigan sintaksis xatosi.",
  "Katta-kichik harf farq qiladi: digitalWrite to'g'ri, DigitalWrite xato.",
  "Kodni tartibli yozish: har buyruq alohida qatorda, qavslar ichidagi qism ichkariga surilgan."],
 "Nuqta-vergul va katta-kichik harf qoidalarini birinchi darsda mustahkamlang. Bu ikkisi barcha sintaksis xatolarining 80% ini tashkil qiladi.",
 [("Har buyruq oxirida nima bo'lishi kerak?", "Nuqta-vergul."),
  ("digitalWrite va DigitalWrite bir xilmi?", "Yo'q, katta-kichik harf farq qiladi.")],
 "Nuqta-vergulni unutish."),

"setup() va loop() nima qiladi": T(
 "Ikki funksiyaga har xil kod qo'yib, farqni kuzatish",
 ["setup() plata yoqilganda yoki reset bosilganda BIR MARTA bajariladi.",
  "loop() setup tugagach cheksiz takrorlanadi va plata o'chirilmaguncha to'xtamaydi.",
  "setup ichida: pinMode, Serial.begin, kutubxonalarni ishga tushirish, boshlang'ich qiymatlar.",
  "loop ichida: sensorlarni o'qish, qaror qabul qilish, ijro qurilmalarini boshqarish."],
 "Miltillash kodini setup ichiga qo'yib ko'rsating: LED bir marta miltillaydi va to'xtaydi. Bu farqni bir zumda ochadi.",
 [("setup() necha marta bajariladi?", "Bir marta."),
  ("Serial.begin qayerda yoziladi?", "setup() ichida.")],
 "Serial.begin ni loop ichiga yozish."),

"pinMode va digitalWrite": T(
 "Bir necha LEDni turli pinlarda mustaqil boshqarish",
 ["pinMode(pin, OUTPUT) — pinni chiqish qilib belgilaydi. INPUT esa kirish.",
  "digitalWrite(pin, HIGH) — 5 V beradi, LOW — 0 V.",
  "pinMode odatda setup ichida bir marta yoziladi.",
  "pinMode unutilsa digitalWrite ishlamaydi: pin kirish holatida qoladi va faqat ichki tortuvchi rezistor yoqiladi."],
 "pinMode ni ataylab unutib, LEDning xira yonishini ko'rsating. Sababini tushuntirish pin rejimlari tushunchasini mustahkamlaydi.",
 [("pinMode qayerda yoziladi?", "setup() ichida."),
  ("pinMode unutilsa nima bo'ladi?", "LED xira yonadi yoki umuman yonmaydi.")],
 "pinMode ni unutish."),

"delay va vaqt": T(
 "Turli delay qiymatlari bilan naqshlar yaratib, delay ning kamchiligini aniqlash",
 ["delay(ms) dasturni belgilangan millisekundga to'xtatadi.",
  "Kamchiligi: bu vaqtda plata boshqa hech narsa qila olmaydi — tugmani ham o'qimaydi.",
  "Buni sinab ko'rish oson: delay(3000) qo'yib, tugmani bosing — u javob bermaydi.",
  "Yechim millis() bilan — u vaqtni sanaydi, lekin dasturni to'xtatmaydi. Bu keyingi chorak mavzusi."],
 "delay muammosini ataylab sinatib ko'rsating. Muammoni his qilgan o'quvchi millis() ni keyinchalik yaxshi o'zlashtiradi.",
 [("delay paytida tugma o'qiladimi?", "Yo'q."),
  ("Yechim nima?", "millis() bilan vaqtni sanash.")],
 "Uzun delay qo'yib, qurilmaning javob bermasligidan hayron bo'lish."),

"Bir nechta LEDni boshqarish": T(
 "Beshta LEDni mustaqil boshqarib, turli naqshlar yaratish",
 ["Har LED o'z piniga va o'z rezistoriga ulanadi. Beshta LED uchun D2-D6 qulay.",
  "Har biri uchun pinMode setup ichida yoziladi — kod uzun bo'lib ketadi.",
  "Bu keyingi chorakdagi sikl va massiv mavzusiga tabiiy ehtiyoj yaratadi.",
  "Umumiy tok: 5 x 15 = 75 mA. Bu Arduino uchun xavfsiz, lekin 20 ta LED uchun tashqi quvvat kerak bo'lardi."],
 "Kod uzunligidan bezovtalik hosil bo'lsin — keyingi chorakdagi sikl \"qutqaruvchi\" bo'lib ko'rinadi va yaxshi o'zlashtiriladi.",
 [("Beshta LED qancha tok oladi?", "Taxminan 75 mA."),
  ("Har LEDga alohida rezistor kerakmi?", "Ha.")],
 "Bir necha LEDni bitta pinga ulash."),

"Svetofor dasturi": T(
 "Uch rangli LED bilan svetofor siklini matnli kodda yozish",
 ["Sikl: yashil (5 s) -> sariq (2 s) -> qizil (5 s) -> qizil+sariq (1 s) -> yashil.",
  "Algoritm avval qog'ozda jadval qilib yoziladi: holat / qizil / sariq / yashil / vaqt.",
  "Har holatda uch LEDning holati aniq belgilanadi — bittasini o'chirishni unutish tez-tez uchraydi.",
  "Kodni funksiyaga bo'lish mumkin: holat(qizil, sariq, yashil, vaqt) — bu kodni ancha qisqartiradi."],
 "Funksiyaga bo'lish variantini ko'rsating. 6-sinf darajasida bu erta, lekin kodning qanchalik qisqarishini ko'rish qiziqish uyg'otadi.",
 [("Svetofor siklida nechta holat bor?", "To'rtta asosiy holat."),
  ("Algoritm qayerda yoziladi?", "Avval qog'ozda jadval qilib.")],
 "Bir LEDni o'chirishni unutib, ikki rang birga yonib qolishi."),

"Kodni izoh bilan yozish": T(
 "Yozilgan dasturga izohlar qo'shib, boshqa o'quvchiga o'qitib sinash",
 ["Izoh ikki xil: // bir qatorli, /* ... */ ko'p qatorli.",
  "Izoh kompilyatsiyada tashlab ketiladi — u faqat odam uchun.",
  "Izoh NEGA shunday qilinganini tushuntirsin. \"i ni oshiradi\" foydasiz — kod o'zi buni ko'rsatadi.",
  "Faylning boshida qisqa izoh bo'lishi kerak: dastur nima qiladi, qanday sxema kerak, kim va qachon yozgan."],
 "Fayl boshidagi izohni majburiy qiling: nima, qanday sxema, kim, qachon. Bu keyinchalik o'z kodini tanishning yagona yo'li.",
 [("// va /* */ farqi nima?", "Birinchisi bir qatorli, ikkinchisi ko'p qatorli izoh."),
  ("Izohda nima yozilishi kerak?", "Nega shunday qilingani.")],
 "Har qatorga foydasiz izoh yozib, muhim qarorlarni tushuntirmaslik."),

"Xatolik xabarlarini o'qish": T(
 "Ataylab xato kiritib, xabarni o'qib, xatoni topish mashqi",
 ["Xato xabarida uch narsa bor: fayl nomi, QATOR RAQAMI va xato tavsifi.",
  "Ko'p uchraydigan xatolar: 'expected ;' (nuqta-vergul unutilgan), 'was not declared' (o'zgaruvchi e'lon qilinmagan), 'expected }' (qavs yopilmagan).",
  "MUHIM: xato ko'rsatilgan qatordan OLDINGI qatorda bo'lishi mumkin. Masalan nuqta-vergul unutilsa, xato keyingi qatorda ko'rinadi.",
  "Birinchi xatodan boshlash kerak — bitta xato ko'pincha o'nlab keyingi xatoni keltirib chiqaradi."],
 "\"Birinchi xatodan boshlang\" qoidasini o'rnating. 20 ta xato ro'yxatini ko'rgan o'quvchi vahimaga tushadi, aslida sabab bitta bo'lishi mumkin.",
 [("Xato xabarida nima ko'rsatiladi?", "Fayl, qator raqami va xato tavsifi."),
  ("Nechta xatodan boshlash kerak?", "Birinchisidan — qolganlari uning oqibati bo'lishi mumkin.")],
 "Oxirgi xatodan boshlash yoki hamma xatoni birdan tuzatishga urinish."),

"Sxema va kodni birga tekshirish": T(
 "Xatolari bor loyihada sxema va kodni ajratib tekshirish",
 ["Xato ikki joyda bo'lishi mumkin: sxemada yoki kodda. Ularni ajratish birinchi qadam.",
  "Ajratish usuli: sxemani tekshirish uchun eng oddiy kod (Blink) yuklanadi. Ishlasa — sxema joyida.",
  "Kod tekshiruvi: Serial.println bilan qiymatlarni chiqarish va dastur qayergacha yetganini ko'rish.",
  "Bir vaqtda faqat bitta narsa o'zgartiriladi."],
 "\"Sxemami, kodmi?\" savolini birinchi qadam qilib o'rnating. Bu ikkiga bo'lish usulining eng foydali ko'rinishi.",
 [("Sxema va koddagi xatoni qanday ajratish mumkin?", "Oddiy test kodi yuklab ko'rish bilan."),
  ("Serial.println nima uchun ishlatiladi?", "Dastur qayergacha yetganini va qiymatlarni ko'rish uchun.")],
 "Sxema va kodni bir vaqtda o'zgartirish."),

"Kodni saqlash va tartibga solish": T(
 "Loyiha fayllarini tartibli saqlab, versiya nusxalarini yaratish",
 ["Arduino IDE har sketchni o'z papkasida saqlaydi. Papka nomi fayl nomi bilan bir xil bo'lishi shart.",
  "Fayl nomi ma'noli bo'lsin: \"svetofor_v1\" yaxshi, \"sketch_jan01a\" yomon.",
  "Versiya saqlash: har muhim bosqichdan keyin File > Save As bilan yangi nom (v1, v2, v3).",
  "Ishlaydigan versiyani saqlab qo'yish shart — yangi o'zgarish buzsa, qaytish mumkin bo'ladi."],
 "Versiya saqlash odatini o'rnating. Bu versiya nazoratining eng sodda shakli va o'quvchilarni ko'p yo'qotishdan qutqaradi.",
 [("Sketch papkasi nomi qanday bo'lishi kerak?", "Fayl nomi bilan bir xil."),
  ("Nega versiya nusxalari saqlanadi?", "Yangi o'zgarish buzsa qaytish uchun.")],
 "Bitta faylni doim ustiga yozib, ishlaydigan versiyani yo'qotish."),

# ==================================================== 2-CHORAK: Dasturlash asoslari
"O'zgaruvchi va ma'lumot turlari": T(
 "Turli turdagi o'zgaruvchilar bilan ishlab, chegaralarini sinab ko'rish",
 ["int — butun son (2 bayt, -32768..32767), long — katta butun (4 bayt), float — kasrli, bool — true/false, byte — 0..255.",
  "E'lon: int harorat = 25; — tur, nom, boshlang'ich qiymat.",
  "int chegarasidan oshsa qiymat manfiyga aylanadi (overflow). 32767 + 1 = -32768.",
  "Arduino Uno da 2 KB SRAM bor — turni to'g'ri tanlash xotira tejaydi."],
 "Overflow ni amalda ko'rsating: 32767 ga 1 qo'shib natijani chiqaring. Bu kutilmagan natija tur chegaralarini yodda qoldiradi.",
 [("int ning chegarasi qanday?", "-32768 dan 32767 gacha."),
  ("Overflow nima?", "Chegaradan oshganda qiymatning boshqa tomonga o'tib ketishi.")],
 "Chegaraga e'tibor bermay, katta qiymatlar uchun int ishlatish."),

"Arifmetik amallar": T(
 "Arifmetik amallar bilan hisoblash qilib, butun bo'lish xususiyatini aniqlash",
 ["Amallar: + - * / va % (qoldiq).",
  "MUHIM: butun sonlarni bo'lishda natija ham butun bo'ladi. 7 / 2 = 3, 0,5 emas.",
  "Kasrli natija kerak bo'lsa kamida bitta son float bo'lishi kerak: 7.0 / 2 = 3.5.",
  "% (qoldiq) juda foydali: son juftmi tekshirish (n % 2 == 0), aylanma hisob (indeks % massivUzunligi)."],
 "Butun bo'lish xususiyati eng ko'p uchraydigan mantiqiy xato manbai. Uni amalda ko'rsatib, doskaga yozib qo'ying.",
 [("7 / 2 int larda qancha beradi?", "3."),
  ("Kasrli natija olish uchun nima qilinadi?", "Kamida bitta sonni float qilish.")],
 "Butun bo'lishda kasrli natija kutish."),

"for sikli": T(
 "for sikli bilan LED effektlarini yozib, kod uzunligini solishtirish",
 ["for (boshlang'ich; shart; qadam) { ... }",
  "Misol: for (int i = 2; i <= 6; i++) — i 2 dan 6 gacha, har safar 1 ga oshadi.",
  "Teskari sikl: for (int i = 6; i >= 2; i--).",
  "Ichma-ich sikl (nested): tashqi sikl bir marta o'tganda ichki sikl to'liq aylanadi."],
 "Ichma-ich siklni ko'paytirish jadvalida ko'rsating — bu matematik masala bilan bog'lanadi va tushunarli bo'ladi.",
 [("for (int i = 0; i < 5; i++) necha marta bajariladi?", "Besh marta."),
  ("i-- nima qiladi?", "Har siklda i ni bittaga kamaytiradi.")],
 "Shart belgisini noto'g'ri qo'yish (< va <= ni chalkashtirish)."),

"for bilan LED effektlari": T(
 "Sikl bilan yugurayotgan olov va nafas olish effektlarini yasash",
 ["Yugurayotgan olov: sikl bilan pinlarni navbat bilan yoqib-o'chirish.",
  "Ikki tomonlama harakat: ikki sikl — biri oldinga, ikkinchisi orqaga.",
  "Nafas olish effekti (breathing): PWM qiymatini 0 dan 255 gacha va qaytadan sikl bilan o'zgartirish.",
  "Tabiiy ko'rinish uchun kvadratik moslash: ko'z yorqinlikni chiziqsiz sezadi."],
 "Nafas olish effektini chiziqli va kvadratik moslash bilan solishtiring. Farq ko'rinadi va inson sezgisining chiziqsizligi esda qoladi.",
 [("Nafas olish effekti qanday yasaladi?", "PWM qiymatini sikl bilan silliq o'zgartirib."),
  ("Nega kvadratik moslash tabiiyroq ko'rinadi?", "Ko'z yorqinlikni chiziqsiz sezadi.")],
 "Kutish vaqtini juda katta qilish — effekt bo'lak-bo'lak ko'rinadi."),

"while sikli": T(
 "while bilan shartga bog'liq takrorlanish yozib, for bilan solishtirish",
 ["while (shart) { ... } — shart rost bo'lguncha takrorlanadi.",
  "for takrorlanish soni ma'lum bo'lganda, while esa shartga bog'liq bo'lganda ishlatiladi.",
  "do { ... } while (shart) — kamida bir marta bajaradi, keyin shartni tekshiradi.",
  "Xavf: shart hech qachon yolg'on bo'lmasa cheksiz sikl hosil bo'ladi va dastur qotib qoladi."],
 "Cheksiz siklni ataylab yozdirib, reset bilan chiqishni ko'rsating. Bu xavfni bir marta ko'rish yetarli.",
 [("for va while qachon ishlatiladi?", "for — son ma'lum bo'lganda, while — shartga bog'liq bo'lganda."),
  ("do-while nimasi bilan farq qiladi?", "Kamida bir marta bajaradi.")],
 "while ichida shartga ta'sir qiladigan amalni unutish."),

"digitalRead va tugma": T(
 "Tugmani o'qib, holatini Serial monitorda kuzatish",
 ["digitalRead(pin) pin holatini HIGH yoki LOW deb qaytaradi.",
  "Pin INPUT yoki INPUT_PULLUP rejimida bo'lishi kerak.",
  "Tugma odatda bir oyog'i pinga, ikkinchisi GND ga ulanadi.",
  "O'qilgan qiymatni Serial monitorda ko'rish — tugma to'g'ri ulanganini tekshirishning eng oson yo'li."],
 "Avval qiymatni ko'rish, keyin mantiq yozish tartibini o'rnating. Ko'r-ko'rona kod yozish eng ko'p vaqt yo'qotadi.",
 [("digitalRead nima qaytaradi?", "HIGH yoki LOW."),
  ("Tugmaning ikkinchi oyog'i qayerga ulanadi?", "Odatda GND ga.")],
 "Tugma qiymatini tekshirmasdan darhol shart yozishga kirishish."),

"Tortuvchi (pull-up) rezistor": T(
 "Tortuvchi rezistorli va rezistorsiz tugmani solishtirib, farqni o'lchash",
 ["Rezistorsiz tugma bosilmaganda kirish \"osilgan\" holatda bo'ladi — qiymat tasodifiy o'zgaradi.",
  "Tashqi tortuvchi rezistor (10 kOm) kirishni VCC ga tortadi: bosilmaganda HIGH, bosilganda LOW.",
  "INPUT_PULLUP ichki tortuvchi rezistorni yoqadi — tashqi rezistor kerak bo'lmaydi. Mantiq bir xil: bosilganda LOW.",
  "Pastga tortuvchi (pull-down) esa GND ga tortadi va mantiq to'g'ri bo'ladi, lekin u tashqi rezistor talab qiladi."],
 "Rezistorsiz tugmaning tasodifiy qiymat berishini Serial monitorda ko'rsating — qo'l yaqinlashganda ham qiymat o'zgaradi.",
 [("INPUT_PULLUP da bosilgan tugma qanday o'qiladi?", "LOW."),
  ("Nega INPUT_PULLUP qulay?", "Tashqi rezistor kerak bo'lmaydi.")],
 "INPUT_PULLUP da mantiqni to'g'ri deb o'ylash — u teskari."),

"if sharti": T(
 "Sensor qiymatiga qarab qaror qabul qiladigan dastur yozish",
 ["if (shart) { ... } — shart rost bo'lsa bajariladi.",
  "Solishtirish: == (teng), != , > , < , >= , <=.",
  "MUHIM: tenglik uchun IKKI teng belgisi. Bitta teng qiymat berish degani va bu eng ko'p uchraydigan xato.",
  "if (x = 5) shart har doim rost bo'ladi — kompilyator ogohlantiradi, lekin xato bermaydi."],
 "== va = farqini katta harflar bilan doskaga yozing. Bu xatoni topish juda qiyin, chunki kod kompilyatsiya bo'laveradi.",
 [("Tenglikni tekshirish uchun qaysi belgi?", "== (ikki teng)."),
  ("if (x = 5) nima qiladi?", "x ga 5 beradi va shart doim rost bo'ladi.")],
 "if ichida bitta teng belgisi yozish."),

"else va else if": T(
 "Bir necha shartli tanlov yozib, shartlar tartibining ahamiyatini aniqlash",
 ["else — shart yolg'on bo'lganda. else if — bir necha shartni ketma-ket tekshirish.",
  "Birinchi rost chiqqan shart bajariladi, qolganlari tekshirilmaydi.",
  "Shuning uchun TARTIB muhim: kengroq shart oldin yozilsa, torroq shart hech qachon bajarilmaydi.",
  "Misol xato: if (x > 100) ... else if (x > 500) ... — ikkinchisi hech qachon ishlamaydi."],
 "Noto'g'ri tartibli misolni yozdirib, natijani ko'rsating. Xatoni ko'rish qoidani mustahkam yodda qoldiradi.",
 [("Nechta else if bajariladi?", "Faqat birinchi rost chiqqani."),
  ("Shartlar qanday tartibda yoziladi?", "Torroq shart oldin.")],
 "Shartlarni noto'g'ri tartibda yozish."),

"Mantiqiy amallar: && || !": T(
 "Ikki shartli mantiqiy ifodalar yozib, rostlik jadvalini to'ldirish",
 ["&& (VA) — ikkala shart ham rost. || (YOKI) — kamida bittasi. ! (EMAS) — teskarilaydi.",
  "Rostlik jadvali: 1&&1=1, qolganlari 0. 0||0=0, qolganlari 1.",
  "Qisqa tutashuvli hisoblash: && da birinchi shart yolg'on bo'lsa ikkinchisi tekshirilmaydi.",
  "Bitli amallar (& va |) boshqacha ishlaydi — ularni mantiqiy amallar bilan chalkashtirmaslik kerak."],
 "Rostlik jadvalini to'ldirtirish 1-yildagi ikki tugmali zanjirlarga havola qiladi — apparat va dasturiy mantiq birligini ko'rsatadi.",
 [("&& qachon rost beradi?", "Ikkala shart ham rost bo'lganda."),
  ("&& va & farqi nima?", "Birinchisi mantiqiy, ikkinchisi bitli amal.")],
 "&& o'rniga & yozish."),

"Tugma sakrashi (debounce)": T(
 "Tugma bosishlarini sanab, debounce bilan va usiz natijani solishtirish",
 ["Mexanik tugma bosilganda kontaktlar 5-50 ms davomida bir necha marta ochilib-yopiladi.",
  "Dastur juda tez ishlagani uchun bitta bosishni bir necha marta deb qabul qiladi.",
  "Dasturiy yechim: holat o'zgargach 20-50 ms kutish yoki millis() bilan oxirgi o'zgarish vaqtini eslab qolish.",
  "Apparat yechim: tugmaga parallel 100 nF kondensator."],
 "Debounce'siz sanoqni ko'rsating: bir marta bosilganda 3-7 chiqadi. Muammoni ko'rmagan o'quvchi yechimning qadrini bilmaydi.",
 [("Tugma sakrashi qancha davom etadi?", "5-50 millisekund."),
  ("Dasturiy yechim nima?", "Holat o'zgargach 20-50 ms kutib, qayta tekshirish.")],
 "Debounce'ni hisobga olmaslik — sanoq va menyu dasturlari noto'g'ri ishlaydi."),

"Serial monitor bilan kuzatish": T(
 "Dastur ichidagi qiymatlarni Serial orqali kuzatib, nosozlik topish",
 ["Serial.begin(9600) setup ichida. Serial.print / println bilan yuboriladi.",
  "Monitor oynasidagi tezlik kodda ko'rsatilgani bilan bir xil bo'lishi kerak.",
  "Nosozlik topish usuli: shubhali joylarga Serial.println(\"1-nuqta\") qo'yib, dastur qayergacha yetayotganini ko'rish.",
  "O'zgaruvchi qiymatlarini chiqarish taxminni tekshiradi va ko'r-ko'rona tuzatishdan qutqaradi."],
 "Serial'ni \"dasturning ko'zi\" deb tanishtiring. Bu ko'nikma butun kurs davomida eng ko'p ishlatiladi.",
 [("Serial.begin qayerda yoziladi?", "setup() ichida."),
  ("Ekranda tushunarsiz belgilar chiqsa nima tekshiriladi?", "Monitor oynasidagi tezlik.")],
 "Monitor tezligini kodda ko'rsatilganidan boshqa qo'yish."),

"Serial orqali qiymat yuborish": T(
 "Kompyuterdan Arduino'ga buyruq yuborib, qurilmani boshqarish",
 ["Serial ikki tomonlama: Arduino yuborishi ham, qabul qilishi ham mumkin.",
  "Qabul qilish: Serial.available() kelgan bayt borligini bildiradi, Serial.read() bitta bayt o'qiydi.",
  "Butun qatorni o'qish uchun Serial.readStringUntil('\\n') qulay.",
  "Kelgan buyruqni tekshirib, mos amal bajariladi — bu eng sodda boshqaruv interfeysi."],
 "Kompyuterdan buyruq yuborish o'quvchilarga juda qiziq ko'rinadi — bu ikki tomonlama aloqa tushunchasini ochadi.",
 [("Serial.available() nima qaytaradi?", "Kelgan baytlar sonini."),
  ("Butun qatorni qanday o'qiladi?", "Serial.readStringUntil bilan.")],
 "available() ni tekshirmasdan read() chaqirish — kutilmagan qiymat keladi."),

"O'z funksiyangni yozish": T(
 "Takrorlanadigan kodni funksiyaga chiqarib, dasturni qisqartirish",
 ["Funksiya: qaytaruvchiTuri nom(parametrlar) { ... }. void — qiymat qaytarmaydi.",
  "Funksiya setup va loop dan TASHQARIDA e'lon qilinadi.",
  "Chaqirish: nom(argumentlar);",
  "Bitta funksiya bitta aniq vazifani bajarishi kerak — bu uni sinash va qayta ishlatishni osonlashtiradi."],
 "Funksiyaga chiqarishdan oldingi va keyingi kodni solishtiring. Takrorlanishning yo'qolishi dasturlashning asosiy tamoyillaridan biri.",
 [("void nimani bildiradi?", "Funksiya qiymat qaytarmasligini."),
  ("Funksiya qayerda e'lon qilinadi?", "setup va loop dan tashqarida.")],
 "Funksiyani loop ichida e'lon qilishga urinish."),

"Funksiyaga qiymat uzatish": T(
 "Parametrli funksiyalar yozib, bir funksiyani turli qiymatlar bilan ishlatish",
 ["Parametr funksiyaga ma'lumot uzatadi: void miltilla(int pin, int vaqt).",
  "Chaqirishda argumentlar tartibi e'londagi tartib bilan mos bo'lishi kerak.",
  "return bilan natija qaytariladi: int yigindi(int a, int b) { return a + b; }",
  "Parametrlar funksiya ichida nusxa sifatida ishlaydi — ularni o'zgartirish tashqaridagi o'zgaruvchiga ta'sir qilmaydi."],
 "Parametrlar nusxa ekanini ko'rsating: funksiya ichida qiymatni o'zgartirib, tashqarida o'zgarmaganini tekshiring. Bu muhim tushuncha.",
 [("return nima qiladi?", "Natijani chaqiruvchi joyga qaytaradi."),
  ("Funksiya ichida parametrni o'zgartirsak tashqarida o'zgaradimi?", "Yo'q, u nusxa.")],
 "Argumentlar tartibini chalkashtirish."),

"Massiv bilan tanishuv": T(
 "Massiv yaratib, elementlar bilan ishlash",
 ["Massiv — bir turdagi qiymatlar to'plami: int pinlar[5] = {2, 3, 4, 5, 6};",
  "Elementga murojaat indeks bilan: pinlar[0] birinchi element.",
  "Indeks NOLDAN boshlanadi: 5 elementli massivda indekslar 0 dan 4 gacha.",
  "Chegaradan chiqish Arduino'da xato bermaydi — u boshqa o'zgaruvchining xotirasini buzadi va dastur tushunarsiz ishlaydi."],
 "Chegaradan chiqish xavfini alohida ta'kidlang: Arduino ogohlantirmaydi va bu xato eng qiyin topiladiganlardan biri.",
 [("5 elementli massivda indekslar qanday?", "0 dan 4 gacha."),
  ("Chegaradan chiqilsa nima bo'ladi?", "Boshqa xotira buziladi, dastur beqaror ishlaydi.")],
 "Massiv chegarasidan chiqish."),

"Massiv va sikl birga": T(
 "Massiv va sikl bilan bir necha qurilmani boshqarish",
 ["Massiv va sikl birga juda kuchli: for (int i = 0; i < 5; i++) digitalWrite(pinlar[i], HIGH);",
  "Massiv uzunligini hisoblash: sizeof(massiv) / sizeof(massiv[0]). Bu uzunlik o'zgarsa kodni tuzatish kerak bo'lmaydi.",
  "Sikl bilan massivni to'ldirish, qiymatlarni yig'ish, maksimal va minimalni topish mumkin.",
  "Aylanma bufer: indeks massiv oxiriga yetganda 0 ga qaytariladi — oxirgi N ta qiymatni saqlash uchun."],
 "sizeof usulini ko'rsating — u massiv uzunligi o'zgarganda kodni tuzatish kerak bo'lmasligini ta'minlaydi.",
 [("Massiv uzunligi qanday hisoblanadi?", "sizeof(massiv) / sizeof(massiv[0])."),
  ("Aylanma bufer nima uchun kerak?", "Oxirgi N ta qiymatni saqlash uchun.")],
 "Massiv uzunligini kodda qo'lda yozib, keyin uzunlik o'zgarganda tuzatishni unutish."),

"Kodni bo'laklarga bo'lish": T(
 "Uzun dasturni funksiyalarga bo'lib, tuzilmasini yaxshilash",
 ["Uzun loop() o'qib bo'lmas holga keladi. Uni funksiyalarga bo'lish kerak.",
  "Odatiy bo'linish: sensorlarniOqi(), qarorQabulQil(), ijroniBoshqar(), ekrangaChiqar().",
  "loop() ichida faqat shu funksiyalar chaqiriladi — u qisqa va tushunarli bo'ladi.",
  "Har funksiyani alohida sinash mumkin — bu nosozlik topishni sezilarli osonlashtiradi."],
 "Uzun loop() ni funksiyalarga bo'lish mashqini birgalikda bajaring. Natijadagi kod tuzilmasi o'quvchilarni hayratlantiradi.",
 [("loop() ichida nima bo'lishi kerak?", "Faqat funksiyalarning chaqiriqlari."),
  ("Funksiyalarga bo'lish nimani osonlashtiradi?", "Sinash va nosozlik topishni.")],
 "Butun mantiqni loop() ichiga yozib, uni bir necha yuz qatorga cho'zish."),

# ==================================================== 3-CHORAK: Analog signal va sensorlar
"analogRead va ADC": T(
 "Analog kirishlarni sinab, ADC ning ishlashini o'lchov bilan tekshirish",
 ["analogRead(pin) 0-1023 oralig'ida qiymat qaytaradi — 10 razryadli ADC.",
  "1024 = 2 ning 10-darajasi. Bitta darajaning qiymati 5 V / 1024 = 4,9 mV.",
  "O'lchash vaqti ~100 mikrosekund. Sekundiga taxminan 10000 marta o'qish mumkin.",
  "Kuchlanishga aylantirish: U = qiymat * 5.0 / 1023."],
 "1024 raqamining ikkilik sanoq tizimidan kelib chiqishini so'rang — bu informatika bilan tabiiy bog'lanish nuqtasi.",
 [("ADC nechta darajaga bo'ladi?", "1024 ta."),
  ("512 qiymati qanday kuchlanishga to'g'ri keladi?", "Taxminan 2,5 V.")],
 "analogRead ni raqamli pinda ishlatishga urinish."),

"Potensiometrni o'qish": T(
 "Potensiometrni o'qib, qiymatlarni Serial Plotter'da kuzatish",
 ["Potensiometrning uchala oyog'i ulanadi: chetkilari 5V va GND ga, o'rtasi analog pinga.",
  "Buralganda qiymat 0 dan 1023 gacha silliq o'zgaradi.",
  "Chetlarda qiymat aniq 0 va 1023 bo'lmasligi mumkin — bu normal, potensiometr ichki qarshiligi tufayli.",
  "Serial Plotter grafik ko'rsatadi va o'zgarish xarakterini bir qarashda ko'rish imkonini beradi."],
 "Plotter'da real vaqtda o'zgarishni ko'rsating — bu o'quvchilar uchun eng qiziqarli lahzalardan biri.",
 [("Potensiometr nechta oyog'i bilan ulanadi?", "Uchtasi ham."),
  ("Chetlarda aniq 0 va 1023 chiqmasligi normalmi?", "Ha, bu odatiy holat.")],
 "Faqat ikki oyoqni ulash."),

"map() funksiyasi": T(
 "Qiymatlarni turli oraliqlarga moslab, natijalarni jadvalga yozish",
 ["map(qiymat, eskiMin, eskiMax, yangiMin, yangiMax) proporsional o'tkazadi.",
  "Odatiy: map(analogRead(A0), 0, 1023, 0, 255) — ADC dan PWM ga.",
  "Teskari moslash: map(x, 0, 1023, 255, 0).",
  "constrain(qiymat, min, maks) bilan birga ishlatish tavsiya etiladi — u kutilmagan qiymatlardan himoya qiladi."],
 "map va constrain ni juftlik sifatida o'rgating. constrain'siz map kutilmagan natija berishi mumkin.",
 [("map(512, 0, 1023, 0, 255) taxminan qancha beradi?", "128."),
  ("constrain nima qiladi?", "Qiymatni chegaralar ichida ushlaydi.")],
 "map natijasini cheklamaslik."),

"PWM va analogWrite": T(
 "PWM bilan yorqinlik va tezlikni boshqarib, chastotani o'lchash",
 ["PWM — pinni tez yoqib-o'chirish. O'rtacha quvvat yoqiq vaqt ulushiga bog'liq.",
  "analogWrite(pin, 0-255). Faqat ~ belgili pinlarda: 3, 5, 6, 9, 10, 11.",
  "Chastota 490 Hz (5 va 6-pinlarda 980 Hz).",
  "PWM analog signal EMAS — u tez o'zgaruvchi raqamli signal. Bu nomdan kelib chiqadigan chalkashlik."],
 "\"PWM analog emas\" fikrini ta'kidlang — analogWrite nomi chalg'itadi va bu tushunmovchilik uzoq davom etadi.",
 [("analogWrite qanday oraliqda ishlaydi?", "0 dan 255 gacha."),
  ("PWM analog signalmi?", "Yo'q, tez o'zgaruvchi raqamli signal.")],
 "PWM'siz pinda analogWrite ishlatish."),

"LED yorqinligini boshqarish": T(
 "Potensiometr bilan yorqinlikni boshqarib, chiziqli va kvadratik moslashni solishtirish",
 ["Kod: yorqinlik = map(analogRead(A0), 0, 1023, 0, 255); analogWrite(9, yorqinlik);",
  "Ko'z yorqinlikni chiziqsiz sezadi: past darajalardagi o'zgarish ancha ko'proq seziladi.",
  "Tabiiy ko'rinish uchun kvadratik moslash: yorqinlik = (qiymat * qiymat) / 4096.",
  "Bu Weber-Fexner qonuni — u tovushga ham tegishli."],
 "Ikki moslashni yonma-yon sinatib ko'ring. Farq ko'rinadi va inson sezgisining chiziqsizligi haqidagi fikr esda qoladi.",
 [("Ko'z yorqinlikni chiziqli sezadimi?", "Yo'q, chiziqsiz."),
  ("Tabiiy ko'rinish uchun qanday moslash ishlatiladi?", "Kvadratik.")],
 "Chiziqli moslashdan tabiiy ko'rinish kutish."),

"RGB LED va rang": T(
 "RGB LED bilan silliq rang o'tishlarini yasash",
 ["Uch PWM pin uchta rangni mustaqil boshqaradi. Har biriga 0-255 qiymat.",
  "256 uchinchi darajada = 16,7 million tus.",
  "Silliq o'tish uchun bir rangdan ikkinchisiga qiymatlarni bosqichma-bosqich yaqinlashtirish kerak.",
  "Kamalak effekti: HSV rang modelidan foydalanish yoki uch kanalni fazalari siljigan sinus bilan boshqarish."],
 "Kamalak effektini ko'rsating — u matematik funksiya (sinus) bilan chiroyli natija hosil qilishning ajoyib misoli.",
 [("Nechta tus hosil qilish mumkin?", "16,7 million."),
  ("Kamalak effekti qanday yasaladi?", "Uch kanalni fazalari siljigan holda o'zgartirib.")],
 "Umumiy anod LEDda qiymatlarni teskarilashni unutish."),

"Fotorezistor va yorug'lik": T(
 "Fotorezistorni kalibrlab, yorug'lik darajalarini o'lchash",
 ["Fotorezistor 10 kOm rezistor bilan bo'luvchiga ulanadi.",
  "Odatiy qiymatlar: qorong'ida 50-150, xonaki yorug'likda 300-600, chiroq nurida 800-1000.",
  "Bu qiymatlar har sensor va sharoitda farq qiladi — kalibrlash shart.",
  "Bog'liqlik chiziqsiz: yorug'lik 10 barobar oshsa, qarshilik taxminan 10 barobar kamayadi."],
 "Har juftlik o'z sensorini kalibrlasin. Tayyor raqam bermang — kalibrlash ko'nikmasi sensor bilan ishlashning asosi.",
 [("Qorong'ida qiymat qanday bo'ladi?", "Past (fotorezistor yuqorida bo'lsa)."),
  ("Nega tayyor chegara ishlatilmaydi?", "Har sensor va sharoitda qiymatlar farq qiladi.")],
 "Boshqa guruhning chegarasini ko'chirib olish."),

"Tungi chiroq avtomati": T(
 "Gisterezisli tungi chiroq dasturini yozib, miltillashni yo'q qilish",
 ["Oddiy variant chegara atrofida miltillaydi: chiroq yonsa yorug' bo'ladi, sensor o'chiradi.",
  "Yechim — gisterezis: yoqish uchun bir chegara (300), o'chirish uchun kattaroq (400).",
  "Kod holat o'zgaruvchisi bilan yoziladi: joriy holatga qarab qaysi chegara tekshirilishi belgilanadi.",
  "Gisterezis deyarli barcha avtomatik tizimlarda ishlatiladi: termostat, bosim regulyatori, sath nazorati."],
 "Gisterezissiz variantni avval yozdiring va miltillashni ko'rsating. Muammoni ko'rgandan keyin yechim mantiqiy bo'ladi.",
 [("Gisterezis nima uchun kerak?", "Chegara atrofidagi miltillashni yo'q qilish uchun."),
  ("Ikki chegara qanday tanlanadi?", "Yoqish chegarasi o'chirishdan past.")],
 "Bitta chegara bilan cheklanish."),

"Termistor va harorat hisoblash": T(
 "Termistordan haroratni hisoblab, gradusda ko'rsatish",
 ["Termistor bo'luvchiga ulanadi. analogRead qiymatidan avval qarshilik hisoblanadi.",
  "R = 10000 * (1023 - qiymat) / qiymat (termistor yuqorida bo'lganda).",
  "Haroratni topish uchun B-parametr formulasi ishlatiladi (B odatda 3950). Kodda log funksiyasi kerak.",
  "Soddaroq yo'l — kalibrlash jadvali: ma'lum haroratlarda qiymat yozib olinadi va oraliq qiymatlar interpolyatsiya qilinadi."],
 "Formula murakkab — tayyor kod bering, lekin har qatorini tushuntiring. Maqsad qadamlarni tushunish, formulani yodlash emas.",
 [("Haroratga o'tish uchun avval nima hisoblanadi?", "Termistor qarshiligi."),
  ("Soddaroq usul qanday?", "Kalibrlash jadvali va interpolyatsiya.")],
 "analogRead qiymatini to'g'ridan-to'g'ri gradus deb qabul qilish."),

"DHT22 va kutubxona": T(
 "DHT22 dan harorat va namlikni o'qib, xatolarni qayta ishlash",
 ["DHT22 raqamli sensor: o'zi o'lchab, natijani raqam sifatida beradi.",
  "Kutubxona: DHT sensor library. #include <DHT.h>, DHT dht(2, DHT22);",
  "dht.readTemperature() va dht.readHumidity() float qaytaradi.",
  "Natija nan bo'lishi mumkin — buni isnan() bilan tekshirish SHART, aks holda hisoblar buziladi."],
 "isnan() tekshiruvini majburiy qiling. Tekshirilmagan nan butun hisobni buzadi va sabab uzoq izlanadi.",
 [("DHT22 dan qanchalik tez-tez o'qish mumkin?", "Sekundiga bir marta."),
  ("nan qaytsa nima qilinadi?", "isnan() bilan tekshirib, o'sha o'qishni tashlab yuborish.")],
 "isnan() ni tekshirmasdan natijani ishlatish."),

"HC-SR04 masofa o'lchash": T(
 "Ultratovush sensori bilan masofani o'lchab, natijani barqarorlashtirish",
 ["TRIG ga 10 mkrs impuls, ECHO da qaytish vaqti o'lchanadi. Masofa = vaqt * 0,034 / 2.",
  "0,034 koeffitsienti tovush tezligidan (340 m/s) kelib chiqadi.",
  "Diapazon 2-400 sm. Yumshoq va qiya yuzalarda natija noto'g'ri.",
  "Barqarorlik uchun 5 o'lchov olinadi va medianasi (o'rtadagisi) ishlatiladi — bu tasodifiy chetlanishlarni yo'q qiladi."],
 "Mediana va o'rtacha farqini tushuntiring: bitta katta xato o'rtachani buzadi, medianaga ta'sir qilmaydi. Statistikaning amaliy misoli.",
 [("Nega vaqt ikkiga bo'linadi?", "Tovush borib qaytadi."),
  ("Nega mediana afzal?", "Bitta katta xato natijaga ta'sir qilmaydi.")],
 "Bitta o'lchovga tayanish."),

"Parkovka radari g'oyasi": T(
 "Masofaga qarab signal chastotasini o'zgartiruvchi radar yasash",
 ["Mantiq: masofa kamaysa, signallar orasidagi pauza qisqarsin.",
  "Kechikish masofaga moslanadi: kechikish = map(masofa, 5, 100, 50, 1000).",
  "5 sm dan yaqin masofada uzluksiz signal — \"to'xta\" ishorasi.",
  "constrain() bilan qiymatni cheklash kerak — masofa diapazondan chiqsa kutilmagan natija bo'ladi."],
 "Real parkovka radari bilan solishtiring. Mashinada eshitilgan tovushni o'zi yaratish kuchli motivatsiya beradi.",
 [("Masofa kamayganda signal qanday o'zgaradi?", "Tez-tez beriladi."),
  ("constrain nima uchun kerak?", "Diapazondan chiqqan qiymatlardan himoya qilish uchun.")],
 "map natijasini cheklamaslik."),

"PIR harakat datchigi": T(
 "PIR bilan harakatni sezuvchi tizim yasab, yolg'on signallarni kamaytirish",
 ["PIR issiq jismlarning harakatini sezadi. Qimirlamay turgan odamni sezmaydi.",
  "Chiqish raqamli: harakat sezilganda HIGH.",
  "Ikki potensiometr: sezgirlik va ushlab turish vaqti. Isinish 30-60 sekund.",
  "Yolg'on signal sabablari: issiq havo oqimi, quyosh nuri, hayvonlar. Ikkinchi sensor bilan tasdiqlash ishonchlilikni oshiradi."],
 "Isinish vaqtini albatta ayting — aks holda o'quvchilar yolg'on signallarni nosozlik deb o'ylab, sozlamalarni behuda o'zgartiradi.",
 [("PIR qimirlamay turgan odamni sezadimi?", "Yo'q."),
  ("Yolg'on signalni qanday kamaytirish mumkin?", "Ikkinchi sensor bilan tasdiqlab.")],
 "Isinishni kutmasdan sozlamalarni o'zgartirish."),

"Tuproq namligi va suv datchigi": T(
 "Ikki datchikni kalibrlab, sug'orish tizimi mantiqini yozish",
 ["Ikkalasi qarshilik tamoyilida ishlaydi: nam muhitda qarshilik kichik.",
  "Kalibrlash ikki nuqtada: mutlaqo quruq va to'liq nam.",
  "Elektroliz muammosi: doimiy quvvat elektrodlarni yemiradi. Yechim — faqat o'lchash paytida quvvat berish.",
  "Sug'orish mantiqi: quruq bo'lsa nasosni yoq, lekin ma'lum vaqtdan ko'p ishlatma (himoya)."],
 "Nasos ishlash vaqtining cheklovini albatta qo'ydiring — sensor buzilsa yoki suv tugasa nasos to'xtovsiz ishlashi mumkin. Bu xavfsizlik mantiqidir.",
 [("Elektroliz qanday hal qilinadi?", "Faqat o'lchash paytida quvvat berib."),
  ("Nega nasos ishlash vaqti cheklanadi?", "Sensor buzilsa u to'xtovsiz ishlab ketmasligi uchun.")],
 "Nasosga vaqt chekloviqo'ymaslik."),

"Ovoz datchigi": T(
 "Ovoz datchigi bilan tovush darajasini o'lchab, indikator yasash",
 ["Modulda mikrofon, kuchaytirgich va komparator bor. A0 — tovush kuchi, D0 — chegaradan oshdi.",
  "Analog qiymat tez tebranadi — o'rtacha yoki maksimal qiymat olish kerak.",
  "Tovush darajasi indikatori: ma'lum vaqt oynasida maksimal qiymat topiladi va LEDlar shunga qarab yoqiladi.",
  "Mikrofon tovush KUCHINI o'lchaydi, mazmunini emas. Nutqni tanish uchun boshqa texnologiya kerak."],
 "\"Kuch\" va \"mazmun\" farqini aniq ajrating — o'quvchilar moduldan ovozni tanishni kutadi va bu tushunmovchilikni oldini olish kerak.",
 [("Modul nimani o'lchaydi?", "Tovush kuchini."),
  ("Qiymat tez tebransa nima qilinadi?", "Vaqt oynasida maksimal yoki o'rtacha olinadi.")],
 "Bitta o'lchovga tayanib, tovush darajasini baholash."),

"Sensorni kalibrlash": T(
 "Barcha sensorlarni kalibrlab, chegaralar hujjatini tayyorlash",
 ["Kalibrlash — sensor ko'rsatkichini haqiqiy holatga moslash.",
  "Tartib: ma'lum holatlarda o'lchash, jadval tuzish, chegara tanlash, sinash va tuzatish.",
  "Kamida ikki nuqta kerak. Ko'proq nuqta aniqroq natija beradi.",
  "Kalibrlash natijasi kodda alohida bo'limda (const qiymatlar) saqlanadi — bu keyinchalik tuzatishni osonlashtiradi."],
 "Kalibrlash qiymatlarini kodning boshida alohida bo'limda saqlashni talab qiling. Bu ularni topish va o'zgartirishni osonlashtiradi.",
 [("Kalibrlash uchun kamida nechta nuqta kerak?", "Ikkita."),
  ("Kalibrlash qiymatlari qayerda saqlanadi?", "Kodning boshida, alohida const qiymatlar sifatida.")],
 "Kalibrlash qiymatlarini kod ichiga tarqatib yuborish."),

"Bir nechta sensorni birga o'qish": T(
 "To'rt sensorli tizim yig'ib, ularni birga o'qishni tashkil qilish",
 ["Bir necha sensorni o'qishda vaqt masalasi chiqadi: DHT22 sekundiga bir marta, HC-SR04 esa tez-tez o'qilishi mumkin.",
  "Yechim: har sensor uchun o'z o'qish intervali va millis() bilan vaqt nazorati.",
  "Sensorlarni funksiyalarga bo'lish kodni tartibli qiladi: haroratniOqi(), masofaniOqi().",
  "Qiymatlarni global o'zgaruvchilarda saqlash — boshqa funksiyalar ularni ishlatishi uchun."],
 "Har sensorning o'z o'qish intervalini millis() bilan boshqarish — bu chorakning eng muhim texnik ko'nikmasi.",
 [("Nega har sensorga o'z intervali kerak?", "Ularning o'qish tezligi va talablari har xil."),
  ("Vaqtni nima bilan boshqariladi?", "millis() bilan.")],
 "Barcha sensorlarni bir xil intervalda o'qish — eng sekini butun tizimni sekinlashtiradi."),

"Sensor qiymatlarini tahlil qilish": T(
 "To'plangan ma'lumotni tahlil qilib, o'rtacha, maksimal va tendensiyani topish",
 ["Tahlil usullari: o'rtacha (umumiy holat), maksimal va minimal (chegaralar), mediana (chetlanishlarga chidamli).",
  "Silliqlash: harakatlanuvchi o'rtacha (moving average) — oxirgi N ta qiymatning o'rtachasi. Shovqinni kamaytiradi.",
  "Tendensiya: joriy qiymat oldingi o'rtachadan katta bo'lsa — o'sish, kichik bo'lsa — pasayish.",
  "Anomaliya: qiymat odatdagidan keskin farq qilsa — sensor nosozligi yoki haqiqiy hodisa bo'lishi mumkin."],
 "Harakatlanuvchi o'rtachani Serial Plotter'da xom qiymat bilan yonma-yon ko'rsating. Silliqlash ta'siri juda yaqqol ko'rinadi.",
 [("Harakatlanuvchi o'rtacha nima qiladi?", "Shovqinni kamaytirib, qiymatni silliqlaydi."),
  ("Mediana nimasi bilan afzal?", "Keskin chetlanishlarga chidamli.")],
 "Xom qiymatlarga tayanib qaror qabul qilish — shovqin tizimni beqaror qiladi."),

# ==================================================== 4-CHORAK: Ijro qurilmalari va loyiha
"Servo motorni boshqarish": T(
 "Servo bilan aniq burchakli mexanizm yasab, silliq harakatni ta'minlash",
 ["Servo kutubxonasi: #include <Servo.h>, Servo s; s.attach(9); s.write(burchak);",
  "Burchak 0-180. Burilish tezligi cheklangan: 60 daraja uchun 0,1-0,2 sekund.",
  "Silliq harakat: burchakni sikl bilan bosqichma-bosqich o'zgartirish.",
  "Servo 500 mA gacha oladi — alohida quvvat, GND umumiy."],
 "Alohida quvvat va umumiy GND qoidasini har servo darsida takrorlang — bu eng ko'p uchraydigan muammo.",
 [("Servo qancha tok oladi?", "500 mA gacha."),
  ("Silliq harakat qanday qilinadi?", "Burchakni bosqichma-bosqich o'zgartirib.")],
 "Servoni Arduino 5V pinidan quvvatlantirish."),

"Servo va sensor birgalikda": T(
 "Sensor qiymatiga qarab avtomatik ishlaydigan servo mexanizmi yasash",
 ["Sensor qiymati burchakka moslanadi: burchak = map(qiymat, min, maks, 0, 180).",
  "Silkinishni kamaytirish: kichik o'zgarishlarga buyruq bermaslik (agar farq 2 gradusdan kam bo'lsa).",
  "Sensor shovqini servoning tinimsiz silkinishiga olib keladi — silliqlash (o'rtacha) kerak.",
  "Amaliy misol: masofaga qarab ochiladigan eshik, yorug'likka qarab buriladigan quyosh paneli."],
 "Silkinish muammosini ataylab ko'rsating: filtrsiz servo tinimsiz titraydi. Yechim (o'lik zona + silliqlash) mantiqiy bo'lib ko'rinadi.",
 [("Nega servo silkinadi?", "Sensor shovqini har siklda yangi burchak beradi."),
  ("Bu qanday hal qilinadi?", "Silliqlash va kichik o'zgarishlarni e'tiborsiz qoldirish bilan.")],
 "Har loop siklida yangi burchak berish."),

"DC motor va tranzistor": T(
 "Tranzistor bilan motorni PWM orqali boshqarib, o'lik zonani o'lchash",
 ["Sxema: pin -> baza rezistori -> tranzistor; motor kollektor va manba orasida; flyback diod parallel.",
  "PWM bilan tezlik boshqariladi: analogWrite(pin, 0-255).",
  "Past qiymatlarda motor aylanmaydi — o'lik zona. Har motorda bu chegara har xil.",
  "Yechim: start uchun qisqa vaqtga to'liq quvvat berib, keyin kerakli darajaga tushirish."],
 "O'lik zonani har guruh o'z motori uchun o'lchasin. Natijalar har xil chiqadi va bu real muhandislik o'lchovi.",
 [("O'lik zona nima?", "Motor aylanmaydigan past PWM qiymatlari oralig'i."),
  ("Motorli sxemada qaysi element majburiy?", "Flyback diod.")],
 "Motorni to'g'ridan-to'g'ri pinga ulash."),

"L298N va motor yo'nalishi": T(
 "L298N bilan motorni ikki yo'nalishda boshqarib, kuchlanish yo'qotishini o'lchash",
 ["L298N ikki kanalli H-ko'prik: IN1, IN2 (yo'nalish), ENA (PWM tezlik).",
  "IN1=HIGH, IN2=LOW — oldinga; teskarisi — orqaga; ikkalasi teng — to'xtash.",
  "ENA jamperi olinmasa PWM ishlamaydi.",
  "L298N da 1,5-2 V yo'qoladi va u qiziydi. 12 V berilsa motorga ~10 V yetadi."],
 "Kuchlanish yo'qotishini o'lchatib ko'rsating — bu komponent tanlash oqibatlarining aniq misoli.",
 [("ENA pini nima uchun?", "PWM bilan tezlikni boshqarish uchun."),
  ("L298N da qancha kuchlanish yo'qoladi?", "1,5-2 V.")],
 "ENA jamperini olmasdan tezlikni boshqarmoqchi bo'lish."),

"Ikki motorli shassi": T(
 "Ikki motorli aravachani boshqarib, to'g'ri yurish uchun tuzatish kiritish",
 ["Burilish motorlarning turli tezligi hisobiga bo'ladi (differensial boshqaruv).",
  "Oldinga: ikkalasi bir xil. O'ngga: chap tez, o'ng sekin. Joyida burilish: qarama-qarshi yo'nalishda.",
  "Motorlar bir xil emas — bir xil PWM da aravacha qiyshayadi. Tuzatish koeffitsienti kiritiladi.",
  "Koeffitsientni topish: aravachani 2 metr yurgizib, chetlanishni o'lchash va tuzatishni sinash."],
 "Tuzatish koeffitsientini o'lchov orqali topish vazifasini bering. Bu real muhandislik masalasi va yechimi ham amaliy.",
 [("Burilish qanday bo'ladi?", "Motorlarning turli tezligi hisobiga."),
  ("Nega aravacha to'g'ri yurmaydi?", "Motorlar bir xil emas.")],
 "Bir xil PWM berib, to'g'ri yurishni kutish."),

"Qadamli motor 28BYJ-48": T(
 "Qadamli motor bilan aniq burchakli mexanizm yasash",
 ["28BYJ-48 + ULN2003 drayveri, to'rt pin (IN1-IN4).",
  "Stepper kutubxonasi: Stepper motor(2048, 8, 10, 9, 11); — pinlar tartibi ataylab shunday.",
  "To'liq aylanish 2048 qadam. 90 daraja = 512 qadam.",
  "To'xtaganda ham fazalarga tok berilib turadi va motor qiziydi — kerak bo'lmaganda fazalarni o'chirish quvvat tejaydi."],
 "To'xtagan motorning qizishini sezdiring. Quvvat boshqaruvining sodda va amaliy misoli.",
 [("To'liq aylanish necha qadam?", "2048."),
  ("Nega to'xtagan motor qiziydi?", "Fazalarga tok berilib turadi.")],
 "Kutubxonadagi pinlar tartibini \"tuzatish\"."),

"Zummer va melodiya": T(
 "Massiv bilan melodiya chalib, tugmalar bilan boshqariladigan asbob yasash",
 ["tone(pin, chastota, davomiylik) va noTone(pin). Passiv zummer kerak.",
  "Melodiya ikki massivda: notalar va davomiyliklar.",
  "Notalar orasida pauza — odatda davomiylikning 30% i.",
  "tone() Timer2 ni ishlatadi va 3, 11-pinlardagi PWM bilan to'qnashadi."],
 "Timer to'qnashuvini ayting — servo va zummer birga ishlatilganda muammo chiqadi va sababini bilish kerak.",
 [("Melodiya uchun nechta massiv kerak?", "Ikkita."),
  ("tone() qaysi pinlar bilan to'qnashadi?", "3 va 11-pinlardagi PWM bilan.")],
 "Ikki massivning uzunligini teng qilmaslik."),

"LCD 1602 va I2C": T(
 "I2C LCD ni ulab, ikki qatorli ma'lumot paneli yasash",
 ["I2C bilan 4 sim: VCC, GND, SDA (A4), SCL (A5). Kutubxona LiquidCrystal_I2C.",
  "Manzil 0x27 yoki 0x3F — I2C skaner bilan aniqlanadi.",
  "lcd.setCursor(ustun, qator), lcd.print(matn), lcd.clear().",
  "Eski matn qoldig'i muammosi: qisqaroq matn yozilganda oldingi belgilar ko'rinadi."],
 "I2C skaner dasturini har o'quvchining kompyuteriga saqlab qo'ying — bu barcha I2C modullarida birinchi qadam.",
 [("I2C uchun nechta sim kerak?", "To'rtta."),
  ("Manzil qanday aniqlanadi?", "I2C skaner dasturi bilan.")],
 "Manzilni tekshirmasdan tayyor kodni ishlatish."),

"LCD'da jonli ko'rsatkich": T(
 "Sensor qiymatini LCD ekranda real vaqtda ko'rsatuvchi qurilma yasash",
 ["Ekranni har loop siklida yangilash kerak emas — 500 ms da bir marta yetarli.",
  "Yangilash vaqtini millis() bilan boshqarish: agar millis() - oxirgiVaqt > 500 bo'lsa yangilash.",
  "Ekran maketi oldindan qog'ozda rejalanadi: 16x2 juda kichik.",
  "O'lchov birligi ham ko'rsatiladi: \"Harorat: 24.5 C\"."],
 "Ekran maketini 16x2 katakcha chizib rejalashtirishni talab qiling. Bu foydalanuvchi interfeysi dizaynining sodda shakli.",
 [("Ekranni qanchalik tez-tez yangilash kerak?", "500 ms da bir marta."),
  ("Yangilash vaqti nima bilan boshqariladi?", "millis() bilan.")],
 "Har siklda clear va print qilish — ekran miltillaydi."),

"7-segment indikator": T(
 "Bir razryadli indikatorda raqamlarni ko'rsatish",
 ["Har segment o'z piniga ulanadi (7 pin + rezistorlar).",
  "Raqamlar segment kombinatsiyalari sifatida massivda saqlanadi.",
  "Kod: raqamni indeks qilib, massivdan segment holatlarini olib, sikl bilan pinlarga yozish.",
  "Ko'p pin talab qilishi kamchilik — yechim 74HC595 siljish registri."],
 "Pinlar yetishmasligini his qildiring: 7 pin ketgach sensor uchun joy qolmaydi. Keyingi darsdagi registr shunda yechim bo'lib ko'rinadi.",
 [("Bir razryad uchun nechta pin kerak?", "Yettita."),
  ("Raqam kombinatsiyalari qayerda saqlanadi?", "Massivda.")],
 "Bitta umumiy rezistor ishlatish."),

"74HC595 siljish registri": T(
 "Siljish registri bilan 8 chiqishni uch pin orqali boshqarish",
 ["74HC595 uch pin bilan 8 chiqish beradi: DS, SHCP, STCP.",
  "shiftOut(dataPin, clockPin, MSBFIRST, qiymat) bitta baytni yuboradi, keyin STCP ga impuls beriladi.",
  "STCP ga impuls berilmasa chiqishlar yangilanmaydi — bu eng ko'p uchraydigan xato.",
  "Registrlarni ketma-ket ulash mumkin: bir xil 3 pin bilan 16, 24 va undan ko'p chiqish."],
 "Ketma-ket ulash imkoniyatini ko'rsating — 3 pin bilan 100 ta LEDni boshqarish o'quvchilarni hayratlantiradi.",
 [("74HC595 uchun nechta pin kerak?", "Uchta."),
  ("Chiqishlar yangilanmasa nima tekshiriladi?", "STCP ga impuls berilganmi.")],
 "STCP ga impuls berishni unutish."),

"IR pult bilan boshqarish": T(
 "Pult bilan bir necha qurilmani boshqaruvchi tizim yozish",
 ["IRremote kutubxonasi. Avval har tugma kodi o'qib olinadi va jadval tuziladi.",
  "switch...case bilan kodlarga qarab amallar bajariladi — bu else if zanjiridan tushunarliroq.",
  "Ba'zi pultlar tugma bosib turilganda takrorlash kodi yuboradi — uni alohida qayta ishlash kerak.",
  "Kodlarni const qiymatlar sifatida nomlab yozish tavsiya etiladi: const long TUGMA_1 = 0xFF30CF;"],
 "Kodlarni nomlangan const qilib yozishni talab qiling — 0xFF30CF dan ko'ra TUGMA_1 ancha tushunarli.",
 [("Pult kodlari universalmi?", "Yo'q."),
  ("Tugma bosib turilganda nima yuboriladi?", "Takrorlash kodi.")],
 "Takrorlash kodini hisobga olmaslik."),

"Rele va kuchli yuklama": T(
 "Rele orqali 12 V yuklamani dasturdan boshqarish",
 ["Rele moduli: VCC, GND, IN. Ichida tranzistor, diod va ko'pincha optopara bor.",
  "Ko'p modullar teskari mantiqda: IN ga LOW berilganda rele yoqiladi.",
  "Yuklama COM va NO kontaktlariga ulanadi.",
  "Sinfda maksimal 12 V. Rele tez-tez almashtirilsa kontaktlari yeyiladi — almashish chastotasini cheklash kerak."],
 "Rele kontaktlarining cheklangan resursini ayting: u sekundiga bir necha marta yoqib-o'chirilsa tez ishdan chiqadi.",
 [("Rele qachon yoqiladi?", "Ko'p modullarda IN ga LOW berilganda."),
  ("Nega almashish chastotasi cheklanadi?", "Kontaktlar yeyiladi.")],
 "Releni juda tez-tez yoqib-o'chirish."),

"Loyihani rejalashtirish": T(
 "Chorak loyihasi uchun texnik topshiriq va bosqichlar rejasini tuzish",
 ["Texnik topshiriqda aniq va O'LCHANADIGAN talablar bo'lishi kerak: \"tez\" emas, \"1 sekunddan kam\".",
  "Bosqichlarga bo'lish: har bosqich mustaqil sinaladigan bo'lsin.",
  "Har bosqich tugagach kod nusxasi saqlanadi — muammo chiqsa qaytish mumkin.",
  "Vaqt taqsimoti: rejalashtirish 20%, yig'ish va dasturlash 50%, sinash va tuzatish 30%."],
 "O'lchanadigan talablarni majburiy qiling. \"Yaxshi ishlasin\" ni tekshirib bo'lmaydi, \"3 sekundda javob bersin\" ni esa mumkin.",
 [("Talablar qanday yozilishi kerak?", "Aniq va o'lchanadigan."),
  ("Vaqtning qancha qismi sinovga ajratiladi?", "Taxminan 30%.")],
 "Sinovga vaqt qoldirmaslik."),

"Algoritmni chizish": T(
 "Loyiha algoritmini blok-sxema ko'rinishida chizish",
 ["Blok-sxema belgilari: oval (boshlanish/tugash), to'rtburchak (amal), romb (shart), parallelogramm (kirish/chiqish).",
  "Shart rombidan ikki strelka chiqadi: \"ha\" va \"yo'q\".",
  "Sikl orqaga qaytadigan strelka bilan ko'rsatiladi.",
  "Blok-sxema dasturdan OLDIN chiziladi — bu xatolarni kod yozishdan avval topishga imkon beradi."],
 "Blok-sxemani majburiy bosqich qiling. Rejasiz kod yozish eng ko'p vaqt yo'qotadigan odat.",
 [("Rombda nima yoziladi?", "Shart."),
  ("Blok-sxema qachon chiziladi?", "Dastur yozishdan oldin.")],
 "Blok-sxemani kod yozilgandan keyin \"hisobot uchun\" chizish."),

"Prototipni yig'ish va sinash": T(
 "Loyiha prototipini bosqichma-bosqich yig'ib, har bosqichni sinash",
 ["Prototip bosqichma-bosqich yig'iladi: har komponent qo'shilgach sinaladi.",
  "Har bosqich uchun oddiy test dasturi yoziladi — faqat shu qismni tekshiradi.",
  "Muammo topilsa darhol tuzatiladi, keyingi bosqichga o'tilmaydi.",
  "Sinov natijalari jadvalga yoziladi: nima sinaldi, natija, muammo bormi."],
 "\"Bittalab qo'shish\" tartibini majburiy qiling. Bu murakkab tizim qurishning asosiy usuli va vaqtni juda tejaydi.",
 [("Prototip qanday yig'iladi?", "Bosqichma-bosqich, har qismni sinab."),
  ("Muammo topilsa nima qilinadi?", "Darhol tuzatiladi.")],
 "Hammasini yig'ib bo'lgach sinashga kirishish."),

"Hujjatlashtirish: sxema va kod": T(
 "Loyiha uchun to'liq texnik hujjat tayyorlash",
 ["Hujjat tarkibi: tavsif, blok-sxema, printsipial sxema, komponentlar ro'yxati (BOM), izohli kod, foydalanish qo'llanmasi.",
  "BOM jadvali: nomi, nominali, soni, izoh. Bu ro'yxat bilan qurilmani boshqa odam takrorlay oladi.",
  "Kodda izoh NEGA shunday qilinganini tushuntirsin.",
  "Sinov natijalari ham hujjat qismi: nima sinaldi, qanday natija, qanday cheklovlar."],
 "\"Boshqa odam takrorlay oladimi?\" mezonini qo'ying. O'quvchilar hujjatlarini almashib, bir-birining qurilmasini yig'ishga urinsin.",
 [("BOM nima?", "Komponentlar ro'yxati jadvali."),
  ("Hujjatning sifat mezoni nima?", "Boshqa odam faqat unga qarab takrorlay olishi.")],
 "Faqat kod va sxemani hujjat deb hisoblash."),

"Taqdimot va himoya": T(
 "Loyihani texnik taqdimot ko'rinishida himoya qilish",
 ["Taqdimot tuzilishi: muammo, yechim, ishlash tamoyili, namoyish, natijalar, cheklovlar va rivojlantirish.",
  "Namoyish oldindan sinaladi va zaxira video tayyorlanadi.",
  "Natijalar raqamlar bilan beriladi: aniqlik, javob vaqti, ishlash muddati.",
  "Savollarga tayyorgarlik: eng ehtimolli uchta savolni oldindan o'ylab, javobini tayyorlash."],
 "Uchta ehtimolli savolga oldindan tayyorlanishni talab qiling. Bu himoyaga ishonch beradi va o'z ishini chuqurroq tushunishga majbur qiladi.",
 [("Natijalar qanday beriladi?", "Aniq raqamlar bilan."),
  ("Nega zaxira video kerak?", "Jonli namoyish buzilib qolishi mumkin.")],
 "Faqat \"nima yasadik\" ni gapirib, natija va cheklovlarni aytmaslik."),
}
