# -*- coding: utf-8 -*-
"""
5-8-sinf dasturi — mavzular xaritasi (syllabus).

Tuzilish 0-4 dasturi bilan AYNAN bir xil:
    har sinf-yil = 4 chorak x 21 dars = 84 dars
    har chorak   = 1 kirish + 18 mavzu + 1 nazorat + 1 loyiha

Yo'nalishlar (foydalanuvchi bilan kelishilgan):
             1-yil                              2-yil
    5-sinf   elektronika (platasiz)             elektronika + Arduino (blokli)
    6-sinf   elektronika (chuqurroq)            elektronika + Arduino (blokli -> matnli)
    7-sinf   elektronika (jadal) + Arduino      ESP32 + AI
    8-sinf   Arduino (2 chorak) + ESP32         ESP32 + AI (chuqur)

1-yilda AI YO'Q. 8-sinf 1-yilda faqat Arduino va ESP32.

Dars turlari (site/index.html dagi .type-badge klasslariga mos):
    elektronika, arduino, esp32, ai, nazorat, loyiha
"""

# Yordamchi: chorak yasash
def Q(nom, yonalish, kirish, mavzular, nazorat, loyiha):
    assert len(mavzular) == 18, f"{nom}: 18 ta mavzu kerak, {len(mavzular)} ta berilgan"
    return {"nom": nom, "yonalish": yonalish, "kirish": kirish,
            "mavzular": mavzular, "nazorat": nazorat, "loyiha": loyiha}


# ==================================================================== 1-YIL
# -------------------------------------------------------------- 5-sinf 1-yil
Y1_5 = {
"1-chorak": Q("Elektr toki va oddiy zanjir", "elektronika",
  "Kurs bilan tanishuv, elektr xavfsizligi, ish o'rnini tashkil qilish",
  [
    "Elektr xavfsizligi: nima mumkin, nima mumkin emas",
    "Elektr toki nima: zaryadning harakati",
    "Batareya — tok manbai, musbat va manfiy qutb",
    "Yopiq va ochiq zanjir",
    "O'tkazgich va izolyator: qaysi materialdan tok o'tadi",
    "Birinchi zanjir: batareya va lampochka",
    "LED bilan tanishuv: uzun va kalta oyoq",
    "LED nima uchun rezistorsiz kuyadi",
    "Rezistor: rangli halqalarni o'qish",
    "Breadboard tuzilishi: qaysi teshiklar o'zaro bog'langan",
    "Breadboard'da birinchi LED zanjiri",
    "Ikkita LED: ketma-ket ulash",
    "Ikkita LED: parallel ulash",
    "Tugma: zanjirni uzish va ulash",
    "Vklyuchatel: holatni saqlaydigan kalit",
    "Ikki tugma ketma-ket: \"VA\" mantiqi",
    "Ikki tugma parallel: \"YOKI\" mantiqi",
    "Sxema chizish: belgilar tili",
  ],
  "Berilgan sxema bo'yicha zanjirni mustaqil yig'ish va ishlatish",
  "Qo'l chirog'i: korpusli, tugmali, ishlaydigan qurilma"),

"2-chorak": Q("O'lchov va Om qonuni", "elektronika",
  "Nima uchun o'lchaymiz: taxmin va aniqlik farqi",
  [
    "Multimetr bilan tanishuv: rejimlar va xavfsizlik",
    "Kuchlanishni o'lchash (Volt)",
    "Batareya kuchlanishi: yangi va eski batareya",
    "Qarshilikni o'lchash (Om)",
    "Rezistor nominalini o'lchab, rangli kod bilan solishtirish",
    "Tokni o'lchash (Amper): zanjirni uzib ulash",
    "Om qonuni: U = I x R",
    "Om qonuni bilan hisoblash mashqlari",
    "LED uchun rezistorni hisoblab tanlash",
    "Ketma-ket zanjirda kuchlanish taqsimoti",
    "Ketma-ket zanjirda tok hamma joyda bir xil",
    "Parallel zanjirda kuchlanish bir xil",
    "Parallel zanjirda tok qanday taqsimlanadi",
    "Kuchlanish bo'luvchi",
    "Potensiometr: o'zgaruvchan rezistor",
    "Qisqa tutashuv: nima va nega xavfli",
    "O'lchov xatoligi: nega qiymat biroz farq qiladi",
    "Nosozlik topish: ishlamayotgan zanjirni tekshirish tartibi",
  ],
  "Zanjirni yig'ib, uch nuqtada o'lchash va Om qonuni bilan tekshirish",
  "Yorug'lik rostlagichli chiroq (potensiometrli)"),

"3-chorak": Q("Komponentlar dunyosi", "elektronika",
  "Komponent nima: har birining o'z vazifasi bor",
  [
    "Kondensator: zaryad to'plovchi idish",
    "Kondensatorni zaryadlash va bo'shatish",
    "RC zanjir: vaqtni sanash",
    "Diod: tok faqat bir tomonga",
    "Diod bilan zanjirni himoyalash",
    "Tranzistor: kichik tok katta tokni boshqaradi",
    "Tranzistor kalit sifatida",
    "RGB LED: uch rang bitta korpusda",
    "Rang aralashtirish: qizil + yashil + ko'k",
    "7-segment indikator tuzilishi",
    "7-segmentda raqam yasash",
    "Passiv va aktiv zummer farqi",
    "Tovush: chastota va baland-pastlik",
    "DC motor: elektrdan harakat",
    "Motorning aylanish yo'nalishini o'zgartirish",
    "Rele: kuchsiz signal kuchli yuklamani yoqadi",
    "Fotorezistor: yorug'lik qarshilikni o'zgartiradi",
    "Termistor: harorat qarshilikni o'zgartiradi",
  ],
  "Berilgan komponentlarni tanib, vazifasini tushuntirish va zanjirga qo'shish",
  "Avtomatik tungi chiroq: qorong'ida o'zi yonadi"),

"4-chorak": Q("Sensorlar va yig'ma qurilma", "elektronika",
  "Sensor nima: fizik kattalikni elektr signalga aylantirish",
  [
    "Yorug'lik sensorli zanjir",
    "Harorat sensorli zanjir",
    "Magnit va reed datchigi",
    "Hall datchigi: magnit maydonni sezish",
    "Tovush (mikrofon) datchigi",
    "Suv sathi datchigi",
    "Tuproq namligi datchigi",
    "Qiyalik (tilt) datchigi",
    "Olov datchigi va xavfsizlik",
    "Analog va raqamli sensor farqi",
    "Signalni tranzistor bilan kuchaytirish",
    "Ikki sensorli zanjir: birgalikda ishlash",
    "Sxema bo'yicha yig'ish mashqi",
    "O'z sxemangni qog'ozda chizish",
    "Nosozlik topish: murakkab zanjirda",
    "Komponentni to'g'ri tanlash: katalogdan",
    "Qurilmani korpusga joylashtirish",
    "Taqdimot: o'z qurilmangni tushuntirish",
  ],
  "Sensorli zanjirni yig'ib, ishlash tamoyilini tushuntirish",
  "Signalizatsiya qurilmasi: sensor + tovush + yorug'lik"),
}

# -------------------------------------------------------------- 6-sinf 1-yil
Y1_6 = {
"1-chorak": Q("Elektr va sxema tili", "elektronika",
  "Kurs bilan tanishuv, xavfsizlik va ish o'rni madaniyati",
  [
    "Atom, elektron va zaryad",
    "Elektr toki: zaryadning yo'naltirilgan harakati",
    "Kuchlanish: zaryadni harakatlantiruvchi kuch",
    "Tok manbalari: batareya, akkumulyator, adapter",
    "Zanjir elementlari va ularning shartli belgilari",
    "Printsipial sxemani o'qish",
    "Sxemani chizish: o'z zanjiringni qog'ozda",
    "Breadboard: ichki ulanishlar xaritasi",
    "Rezistor: vazifasi va rangli kodi",
    "Rezistor nominalini hisoblash mashqlari",
    "LED: yarimo'tkazgichli yorug'lik manbai",
    "LED uchun rezistorni hisoblash",
    "Ketma-ket ulanish qonuniyatlari",
    "Parallel ulanish qonuniyatlari",
    "Aralash (ketma-ket + parallel) ulanish",
    "Tugma, kalit va jamper: zanjirni boshqarish",
    "Montaj madaniyati: toza va tushunarli yig'ish",
    "Nosozlik topish usullari: bosqichma-bosqich tekshirish",
  ],
  "Sxema bo'yicha aralash ulanishli zanjir yig'ish",
  "Uch rejimli chiroq: kuchsiz, o'rtacha, kuchli"),

"2-chorak": Q("Om qonuni, quvvat va energiya", "elektronika",
  "O'lchov asboblari va o'lchash madaniyati",
  [
    "Multimetr tuzilishi va xavfsizlik qoidalari",
    "Kuchlanishni o'lchash amaliyoti",
    "Qarshilikni o'lchash amaliyoti",
    "Tokni o'lchash amaliyoti",
    "Om qonuni: formula va ma'nosi",
    "Om qonuni masalalari yechish",
    "Kuchlanish bo'luvchi: nazariya",
    "Kuchlanish bo'luvchi: amaliy o'lchov",
    "Potensiometr — sozlanadigan bo'luvchi",
    "Elektr quvvati: P = U x I",
    "Quvvatni hisoblab rezistor tanlash",
    "Energiya va iste'mol: kilovatt-soat",
    "Ketma-ket zanjirni o'lchab tekshirish",
    "Parallel zanjirni o'lchab tekshirish",
    "Batareyaning ichki qarshiligi: nega kuchlanish cho'kadi",
    "Qisqa tutashuv va himoya (predoxranitel)",
    "O'lchov aniqligi va xatolik",
    "Murakkab zanjirni tahlil qilish",
  ],
  "Zanjirni o'lchash, hisoblash va natijalarni solishtirish",
  "Batareya sinovchi qurilma"),

"3-chorak": Q("Yarimo'tkazgichlar va komponentlar", "elektronika",
  "Yarimo'tkazgich nima va nega u elektronikani o'zgartirdi",
  [
    "Kondensator: tuzilishi va sig'imi",
    "Kondensatorni zaryadlash va bo'shatish",
    "RC zanjir va vaqt doimiysi",
    "Kondensator turlari va tanlash",
    "Diod: p-n o'tish",
    "Diodni tekshirish va to'g'ri qutblash",
    "Diod ko'prigi: o'zgaruvchan tokni to'g'rilash",
    "Stabilitron: kuchlanishni ushlab turish",
    "Tranzistor tuzilishi va oyoqlari",
    "Tranzistor kalit rejimida",
    "Tranzistor bilan motorni yoqish",
    "NPN va PNP tranzistorlar farqi",
    "Rele: elektromagnit kalit",
    "Rele bilan kuchli yuklamani ulash",
    "Optopara va IK juftlik",
    "RGB LED va rang aralashtirish",
    "7-segment indikator bilan ishlash",
    "Komponentni katalog (datasheet) bo'yicha tanlash",
  ],
  "Tranzistorli yoki releli boshqaruv zanjirini yig'ish",
  "Avtomatik yoritish tizimi"),

"4-chorak": Q("Sensorlar va elektromexanika", "elektronika",
  "Sensor va ijro qurilmasi: avtomatik tizim g'oyasi",
  [
    "Sensor tushunchasi va turlari",
    "Fotorezistor: yorug'lik-qarshilik bog'liqligi",
    "Fotorezistorli avtomat zanjiri",
    "Termistor va harorat o'lchash",
    "Haroratli signalizatsiya",
    "Reed va Hall datchiklari",
    "Tovush datchigi",
    "Suv sathi va tuproq namligi datchiklari",
    "Qiyalik va tebranish datchiklari",
    "DC motor tuzilishi va ishlashi",
    "Motor tezligini o'zgartirish",
    "Motor yo'nalishini o'zgartirish: H-ko'prik g'oyasi",
    "Servo motor: burchakli harakat",
    "Qadamli motor haqida tushuncha",
    "Motorni himoyalash: diod va kondensator",
    "Sensor + ijro qurilmasi: avtomat qurish",
    "Qurilmani loyihalash bosqichlari",
    "Prototipdan korpusli qurilmaga",
  ],
  "Sensorli avtomatik zanjirni loyihalash va yig'ish",
  "Avtomatik sug'orish tizimi (elektron, platasiz)"),
}

# -------------------------------------------------------------- 7-sinf 1-yil
Y1_7 = {
"1-chorak": Q("Elektronika asoslari (jadal kurs)", "elektronika",
  "Kurs rejasi, xavfsizlik, jihoz bilan tanishuv",
  [
    "Tok, kuchlanish, qarshilik: asosiy kattaliklar",
    "Zanjir va sxema tili",
    "Breadboard va montaj qoidalari",
    "Rezistor va rangli kod",
    "LED va qutblanish",
    "Multimetr: kuchlanishni o'lchash",
    "Multimetr: qarshilik va tokni o'lchash",
    "Om qonuni va hisoblash",
    "Ketma-ket va parallel ulanish",
    "Kuchlanish bo'luvchi va potensiometr",
    "Tugma va kalitlar, tortuvchi rezistor",
    "Kondensator va RC zanjir",
    "Diod va himoya",
    "Tranzistor kalit sifatida",
    "Zummer va tovush hosil qilish",
    "DC motor va rele",
    "Quvvat manbalari va xavfsizlik",
    "Nosozlik topish: tizimli yondashuv",
  ],
  "Sxema bo'yicha zanjir yig'ish, o'lchash va hisoblash",
  "Elektron reaksiya o'yini (platasiz, tranzistorli)"),

"2-chorak": Q("Arduino: birinchi qadamlar", "arduino",
  "Mikrokontroller nima va u nimasi bilan oddiy zanjirdan farq qiladi",
  [
    "Arduino Uno platasi: pinlar xaritasi",
    "Arduino IDE va platani ulash",
    "Blink: birinchi dastur",
    "Dastur tuzilishi: setup() va loop()",
    "pinMode va digitalWrite",
    "delay() va vaqt boshqaruvi",
    "Bir nechta LED bilan ishlash",
    "Svetofor dasturi",
    "O'zgaruvchi (variable) tushunchasi",
    "Ma'lumot turlari: int, float, bool",
    "for sikli",
    "while sikli",
    "digitalRead: tugmani o'qish",
    "if sharti",
    "else va else if",
    "Tugma sakrashi (debounce) muammosi",
    "Serial monitor: plata bilan gaplashish",
    "Nosozlik topish: kod va sxemani birga tekshirish",
  ],
  "Berilgan vazifa bo'yicha dastur yozib, sxemani yig'ish",
  "Reaksiya tezligi o'yini (Arduino'da)"),

"3-chorak": Q("Analog signal va sensorlar", "arduino",
  "Analog va raqamli dunyo o'rtasidagi farq",
  [
    "analogRead: potensiometrni o'qish",
    "Qiymatlarni Serial monitorda kuzatish",
    "map() funksiyasi: qiymatni moslash",
    "PWM va analogWrite",
    "LED yorqinligini boshqarish",
    "RGB LED va rang boshqaruvi",
    "Fotorezistor bilan yorug'lik o'lchash",
    "Tungi chiroq avtomati",
    "Termistor va harorat hisoblash",
    "DHT22: raqamli sensor protokoli",
    "Kutubxona (library) ishlatish",
    "HC-SR04: masofa o'lchash",
    "Masofa bo'yicha ogohlantirish tizimi",
    "PIR: harakatni aniqlash",
    "Tuproq namligi sensori",
    "Suv va olov datchiklari",
    "O'z funksiyangni yozish",
    "Massiv (array) bilan ishlash",
  ],
  "Sensor qiymatini o'qib, shartga qarab ijro qurilmasini boshqarish",
  "Oddiy ob-havo stansiyasi"),

"4-chorak": Q("Ijro qurilmalari va ekran", "arduino",
  "Harakat va ma'lumot ko'rsatish: qurilmani to'liq qilish",
  [
    "Servo motorni boshqarish",
    "Servo va potensiometr birgalikda",
    "DC motorni tranzistor orqali yurgizish",
    "L298N bilan motor boshqaruvi",
    "Ikki motorli shassi: oldinga, orqaga, burilish",
    "Qadamli motor 28BYJ-48",
    "Passiv zummer va nota chastotalari",
    "Melodiya chalish (massiv bilan)",
    "LCD 1602 ni ulash",
    "LCD ekranga matn chiqarish",
    "I2C protokoli va 2 simli ulanish",
    "LCD + sensor: jonli ko'rsatkich",
    "7-segment indikatorni boshqarish",
    "74HC595: 3 pin bilan 8 chiqish",
    "IR pult bilan masofadan boshqarish",
    "Rele orqali qurilma yoqish",
    "Loyihani rejalashtirish va bosqichlarga bo'lish",
    "Sxema va kodni hujjatlashtirish",
  ],
  "Ijro qurilmasi va ekranli tizimni yig'ib, dasturlash",
  "Aqlli uy maketi: sensor, ekran, ijro qurilmasi"),
}

# -------------------------------------------------------------- 8-sinf 1-yil
Y1_8 = {
"1-chorak": Q("Elektronika va Arduino asoslari (jadal)", "arduino",
  "Kurs rejasi, xavfsizlik, jihoz va dasturiy muhit",
  [
    "Tok, kuchlanish, qarshilik va Om qonuni",
    "Multimetr bilan o'lchash amaliyoti",
    "Breadboard, rezistor, LED",
    "Ketma-ket, parallel va kuchlanish bo'luvchi",
    "Kondensator, diod, tranzistor",
    "Arduino platasi va IDE",
    "Blink va dastur tuzilishi",
    "pinMode, digitalWrite, delay",
    "O'zgaruvchi va ma'lumot turlari",
    "for va while sikllari",
    "digitalRead va tugma bilan ishlash",
    "if / else if / else",
    "Mantiqiy amallar: VA, YOKI, EMAS",
    "Serial monitor va nosozlik topish",
    "analogRead va analog signal",
    "PWM va analogWrite",
    "map() va qiymatlarni moslash",
    "Kodni toza yozish: nom berish va izoh",
  ],
  "Dastur va sxemani birga yig'ib, berilgan vazifani bajarish",
  "Yorug'lik va tovushli reaksiya o'yini"),

"2-chorak": Q("Arduino: sensorlar va ijro (yakun)", "arduino",
  "Kutubxonalar va tayyor modullar bilan ishlash",
  [
    "O'z funksiyangni yozish va qayta ishlatish",
    "Massiv va sikl bilan ishlash",
    "Fotorezistor va termistor",
    "DHT22 va kutubxona ishlatish",
    "HC-SR04 masofa o'lchagich",
    "PIR harakat datchigi",
    "Tuproq, suv va olov datchiklari",
    "Ovoz datchigi va qarsakli boshqaruv",
    "Servo motorni boshqarish",
    "DC motor va L298N",
    "Qadamli motor",
    "Rele bilan kuchli yuklama",
    "Zummer va melodiya",
    "LCD 1602 va I2C",
    "7-segment va 74HC595",
    "IR pult bilan boshqarish",
    "RFID RC522: identifikatsiya",
    "Loyihani hujjatlashtirish",
  ],
  "Ko'p komponentli tizimni yig'ib dasturlash",
  "Kirish nazorati tizimi (RFID + servo qulf)"),

"3-chorak": Q("ESP32 va WiFi", "esp32",
  "ESP32 nima: Arduino'dan farqi va imkoniyatlari",
  [
    "ESP32 pinlari va 3.3V mantiq darajasi",
    "IDE'ga ESP32 platasini qo'shish",
    "Birinchi dastur va Serial aloqa",
    "3.3V va 5V mos kelmasligi: nima qilish kerak",
    "ESP32'da raqamli kirish va chiqish",
    "ESP32'da analog o'qish (ADC)",
    "PWM (LEDC) va yorqinlik boshqaruvi",
    "Sensorlarni ESP32'ga ulash",
    "OLED ekranni I2C orqali ulash",
    "OLED'da matn va raqam chiqarish",
    "OLED'da grafik va chizma",
    "WiFi tarmog'iga ulanish",
    "IP manzil va tarmoq asoslari",
    "Veb-server yaratish",
    "Brauzerdan LED yoqish va o'chirish",
    "HTML sahifani platadan yuborish",
    "Sensor qiymatini veb-sahifada ko'rsatish",
    "WiFi xatolarini topish va tuzatish",
  ],
  "ESP32'da veb-server orqali qurilmani boshqarish",
  "Veb orqali boshqariladigan yoritish tizimi"),

"4-chorak": Q("IoT: internetga ulangan qurilma", "esp32",
  "IoT nima va u kundalik hayotda qayerda ishlatiladi",
  [
    "Ma'lumotni saqlash: microSD kart moduli",
    "Data logging: qiymatlarni vaqt bilan yozish",
    "RTC DS3231: real vaqt soati",
    "Vaqt bo'yicha avtomatlashtirish",
    "HTTP so'rov yuborish",
    "Bulut xizmatiga ma'lumot yuborish",
    "Bulutda grafik ko'rish va tahlil qilish",
    "Telegram bot bilan tanishuv",
    "Telegram orqali xabar yuborish",
    "Telegram orqali qurilmani boshqarish",
    "MQTT protokoli haqida tushuncha",
    "Ikki ESP32 o'rtasida aloqa",
    "Bluetooth (BLE) orqali boshqarish",
    "Quvvat tejash: deep sleep rejimi",
    "Batareyada mustaqil ishlaydigan qurilma",
    "Qurilma korpusi va yakuniy montaj",
    "Tizimni sinash va nosozliklarni yo'qotish",
    "Loyihani taqdim etish va himoya qilish",
  ],
  "IoT tizimini yig'ib, ma'lumotni uzoqdan ko'rsatish",
  "IoT ob-havo stansiyasi: sensor, bulut, Telegram"),
}

# ==================================================================== 2-YIL
# -------------------------------------------------------------- 5-sinf 2-yil
Y2_5 = {
"1-chorak": Q("Elektronikani eslash va kengaytirish", "elektronika",
  "O'tgan yilni eslash va yangi yil rejasi",
  [
    "Zanjir, tok, kuchlanish: takrorlash",
    "Multimetr bilan o'lchashni eslash",
    "Om qonuni: mashqlar",
    "Kuchlanish bo'luvchi va potensiometr",
    "Tranzistor kalit: takrorlash va mustahkamlash",
    "Kondensator va vaqt",
    "Rele bilan boshqarish",
    "Ikki sensorli avtomat",
    "Mikrokontroller nima: yangi tushuncha",
    "Arduino platasi bilan tanishuv",
    "Plataning pinlari va ularning vazifasi",
    "Kompyuterga ulash va drayver",
    "Blokli dasturlash muhiti (mBlock) bilan tanishuv",
    "Birinchi blok: platani yoqish",
    "LEDni blok bilan yoqish va o'chirish",
    "Kutish (delay) blogi",
    "Ikki blokni ketma-ket qo'yish",
    "Birinchi dasturni plataga yuklash",
  ],
  "Zanjirni yig'ib, blokli dastur bilan LEDni yoqish",
  "Miltillovchi chiroq: o'z ritmingda"),

"2-chorak": Q("Blokli dasturlash: chiqish qurilmalari", "arduino",
  "Dastur nima: kompyuterga beriladigan aniq buyruqlar",
  [
    "Takrorlash (sikl) blogi",
    "Bir nechta LEDni navbat bilan yoqish",
    "Svetofor: blokli dastur",
    "Yugurayotgan olov effekti",
    "O'zgaruvchi blogi bilan tanishuv",
    "Sanoqni ekranda ko'rish",
    "RGB LED va rang aralashtirish",
    "PWM: yorqinlikni sekin o'zgartirish",
    "Zummer bilan tovush chiqarish",
    "Nota va melodiya",
    "Servo motorni burish",
    "Servo bilan shlagbaum",
    "DC motorni yurgizish",
    "Motor tezligini boshqarish",
    "Ikki motorli aravacha",
    "Blok bilan tovush va harakatni birlashtirish",
    "Dasturdagi xatoni topish",
    "Dasturni tartibli va tushunarli yozish",
  ],
  "Berilgan vazifani blokli dastur bilan bajarish",
  "Musiqali yoritgich: tovush va rang birga"),

"3-chorak": Q("Blokli dasturlash: sensorlar", "arduino",
  "Sensor va dastur: qurilma atrofni sezishi",
  [
    "Shart (agar ... bo'lsa) blogi",
    "Tugmani o'qish va shart bilan ishlatish",
    "Aks holda (else) blogi",
    "Ikki tugmali boshqaruv",
    "Potensiometrni o'qish (analog)",
    "Potensiometr bilan yorqinlikni boshqarish",
    "Fotorezistor: yorug'likni o'lchash",
    "Avtomatik tungi chiroq",
    "Termistor bilan harorat",
    "Haroratli ogohlantirish",
    "Ultratovush sensori: masofa",
    "Masofaga qarab tovush chiqarish",
    "Harakat datchigi (PIR)",
    "Tuproq namligi sensori",
    "Suv sathi sensori",
    "Ikki shartni birlashtirish (VA / YOKI)",
    "Sensor qiymatini ekranda kuzatish",
    "Sensorli qurilmani sozlash (kalibrlash)",
  ],
  "Sensorni o'qib, shartga qarab qurilmani boshqarish",
  "Aqlli gulzor: quruq bo'lsa signal beradi"),

"4-chorak": Q("Blokli loyihalar", "arduino",
  "Loyiha nima: g'oyadan ishlaydigan qurilmagacha",
  [
    "LCD ekran bilan tanishuv",
    "LCD'ga matn chiqarish",
    "LCD'da sensor qiymatini ko'rsatish",
    "IR pult bilan boshqarish",
    "Pult tugmalarini tanib olish",
    "Rele bilan chiroqni yoqish",
    "Bir nechta sensorli tizim",
    "Qurilmaning ish algoritmini chizish",
    "Algoritmni blokli dasturga aylantirish",
    "Qurilmani bosqichma-bosqich sinash",
    "Xatoni topish va tuzatish",
    "Qurilmani yaxshilash: qo'shimcha imkoniyat",
    "Korpus yasash va montaj",
    "Simlarni tartibga solish",
    "Qurilma uchun qo'llanma yozish",
    "Taqdimotga tayyorgarlik",
    "Boshqalarning loyihasini baholash",
    "Yakuniy sinov va tuzatish",
  ],
  "O'z loyihangni mustaqil yig'ib, dasturlab ko'rsatish",
  "Yakuniy loyiha: o'zi tanlagan aqlli qurilma"),
}

# -------------------------------------------------------------- 6-sinf 2-yil
Y2_6 = {
"1-chorak": Q("Elektronikadan mikrokontrollerga", "elektronika",
  "O'tgan yilni eslash va mikrokontroller g'oyasi",
  [
    "Om qonuni va quvvat: takrorlash",
    "Kuchlanish bo'luvchi va sensor ulash",
    "Tranzistor, rele, diod: takrorlash",
    "Analog va raqamli signal",
    "Mikrokontroller nima va nimasi bilan farq qiladi",
    "Arduino Uno: pinlar va imkoniyatlar",
    "IDE bilan tanishuv (matnli muhit)",
    "Blokli va matnli dasturlash: solishtirish",
    "Birinchi dastur: Blink",
    "setup() va loop() nima qiladi",
    "pinMode va digitalWrite",
    "delay va vaqt",
    "Bir nechta LEDni boshqarish",
    "Svetofor dasturi",
    "Kodni izoh bilan yozish",
    "Xatolik xabarlarini o'qish",
    "Sxema va kodni birga tekshirish",
    "Kodni saqlash va tartibga solish",
  ],
  "Sxemani yig'ib, matnli dastur yozish",
  "Svetofor maketi: uch chiroq, to'g'ri ketma-ketlik"),

"2-chorak": Q("Dasturlash asoslari", "arduino",
  "Dastur mantiqi: ketma-ketlik, shart, takrorlash",
  [
    "O'zgaruvchi va ma'lumot turlari",
    "Arifmetik amallar",
    "for sikli",
    "for bilan LED effektlari",
    "while sikli",
    "digitalRead va tugma",
    "Tortuvchi (pull-up) rezistor",
    "if sharti",
    "else va else if",
    "Mantiqiy amallar: && || !",
    "Tugma sakrashi (debounce)",
    "Serial monitor bilan kuzatish",
    "Serial orqali qiymat yuborish",
    "O'z funksiyangni yozish",
    "Funksiyaga qiymat uzatish",
    "Massiv bilan tanishuv",
    "Massiv va sikl birga",
    "Kodni bo'laklarga bo'lish",
  ],
  "Shart va sikl ishlatilgan dastur yozish",
  "Elektron o'yin: reaksiya va ball hisobi"),

"3-chorak": Q("Analog signal va sensorlar", "arduino",
  "Atrofni o'lchash: sensorlar bilan ishlash",
  [
    "analogRead va ADC",
    "Potensiometrni o'qish",
    "map() funksiyasi",
    "PWM va analogWrite",
    "LED yorqinligini boshqarish",
    "RGB LED va rang",
    "Fotorezistor va yorug'lik",
    "Tungi chiroq avtomati",
    "Termistor va harorat hisoblash",
    "DHT22 va kutubxona",
    "HC-SR04 masofa o'lchash",
    "Parkovka radari g'oyasi",
    "PIR harakat datchigi",
    "Tuproq namligi va suv datchigi",
    "Ovoz datchigi",
    "Sensorni kalibrlash",
    "Bir nechta sensorni birga o'qish",
    "Sensor qiymatlarini tahlil qilish",
  ],
  "Sensor qiymatiga qarab ishlaydigan dastur yozish",
  "Ob-havo stansiyasi: harorat, namlik, yorug'lik"),

"4-chorak": Q("Ijro qurilmalari va loyiha", "arduino",
  "Qurilmani to'liq qilish: sezish, qaror, harakat",
  [
    "Servo motorni boshqarish",
    "Servo va sensor birgalikda",
    "DC motor va tranzistor",
    "L298N va motor yo'nalishi",
    "Ikki motorli shassi",
    "Qadamli motor 28BYJ-48",
    "Zummer va melodiya",
    "LCD 1602 va I2C",
    "LCD'da jonli ko'rsatkich",
    "7-segment indikator",
    "74HC595 siljish registri",
    "IR pult bilan boshqarish",
    "Rele va kuchli yuklama",
    "Loyihani rejalashtirish",
    "Algoritmni chizish",
    "Prototipni yig'ish va sinash",
    "Hujjatlashtirish: sxema va kod",
    "Taqdimot va himoya",
  ],
  "Ko'p komponentli qurilmani yig'ib dasturlash",
  "Aqlli uy maketi: to'liq tizim"),
}

# -------------------------------------------------------------- 7-sinf 2-yil
Y2_7 = {
"1-chorak": Q("ESP32 platformasi", "esp32",
  "ESP32: Arduino'dan keyingi qadam",
  [
    "ESP32 arxitekturasi va Arduino'dan farqi",
    "Pinlar xaritasi va 3.3V mantiq",
    "IDE'ga ESP32 qo'shish va birinchi yuklash",
    "5V va 3.3V mos kelmasligi muammosi",
    "Raqamli kirish va chiqish",
    "ADC: analog o'qish va uning xususiyatlari",
    "PWM (LEDC) kanallari",
    "Touch (sensorli) pinlar",
    "Hall datchigi (plata ichida)",
    "I2C: bir nechta qurilmani ulash",
    "OLED ekranni ulash",
    "OLED'da matn va raqam",
    "OLED'da grafik va diagramma",
    "SPI protokoli haqida tushuncha",
    "microSD kart va ma'lumot yozish",
    "RTC DS3231 va real vaqt",
    "Deep sleep va quvvat tejash",
    "ESP32 xatolarini topish (boot muammolari)",
  ],
  "ESP32'da sensor o'qib, OLED'da ko'rsatish",
  "Ma'lumot yozib boruvchi qurilma (data logger)"),

"2-chorak": Q("WiFi, veb va IoT", "esp32",
  "Internetga ulangan qurilma nima beradi",
  [
    "WiFi tarmog'iga ulanish",
    "IP manzil, port va tarmoq asoslari",
    "Veb-server yaratish",
    "HTML sahifani platadan yuborish",
    "Brauzerdan qurilmani boshqarish",
    "Sensor qiymatini sahifada ko'rsatish",
    "Sahifani avtomatik yangilash (AJAX g'oyasi)",
    "CSS bilan sahifani chiroyli qilish",
    "HTTP so'rov yuborish (client)",
    "Bulut xizmatiga ma'lumot yuborish",
    "Bulutda grafik va tahlil",
    "Telegram bot yaratish",
    "Telegram orqali xabar va ogohlantirish",
    "Telegram orqali boshqarish",
    "MQTT protokoli",
    "Ikki qurilma o'rtasida aloqa",
    "BLE (Bluetooth Low Energy) asoslari",
    "Tarmoq xavfsizligi asoslari",
  ],
  "WiFi orqali ma'lumot yuboradigan va boshqariladigan tizim",
  "IoT monitoring tizimi"),

"3-chorak": Q("Sun'iy intellekt asoslari", "ai",
  "Sun'iy intellekt nima va u qanday \"o'rganadi\"",
  [
    "Sun'iy intellekt, mashinaviy o'rganish, TinyML",
    "An'anaviy dastur va o'rganuvchi model farqi",
    "Ma'lumot (dataset) nima va nega muhim",
    "Belgi (feature) va sinf (class) tushunchasi",
    "Model o'rgatish jarayoni: qadamlar",
    "Edge Impulse platformasi bilan tanishuv",
    "Loyiha yaratish va qurilmani ulash",
    "MPU6050: harakat ma'lumotini yig'ish",
    "Imo-ishora uchun ma'lumot to'plash",
    "Ma'lumotni belgilash (labeling)",
    "O'rgatish va tekshirish to'plamlari",
    "Modelni o'rgatish va aniqlikni ko'rish",
    "Chalkashlik matritsasi (confusion matrix)",
    "Modelni qurilmaga yuklash",
    "Imo-ishorani real vaqtda tanish",
    "Modelni yaxshilash: ko'proq ma'lumot",
    "Ortiqcha moslashuv (overfitting) muammosi",
    "AI axloqi: ma'lumot va maxfiylik",
  ],
  "Imo-ishora tanuvchi modelni o'rgatib, qurilmada ishlatish",
  "Imo-ishora bilan boshqariladigan qurilma"),

"4-chorak": Q("AI qurilmasi: ovoz va tasvir", "ai",
  "Kamera va mikrofon: qurilma ko'radi va eshitadi",
  [
    "XIAO ESP32S3 Sense bilan tanishuv",
    "Mikrofondan ovoz ma'lumotini olish",
    "Ovoz buyruqlari uchun ma'lumot to'plash",
    "Ovoz modelini o'rgatish",
    "Ovoz bilan boshqarish (keyword spotting)",
    "Kamera bilan tanishuv va rasm olish",
    "Tasvir ma'lumotini to'plash",
    "Tasvirni belgilash va tayyorlash",
    "Tasvir tanish modelini o'rgatish",
    "Modelni qurilmaga yuklash va sinash",
    "Obyektni aniqlash (object detection) haqida",
    "Modelni siqish (quantization) nima uchun kerak",
    "AI + IoT: natijani internetga yuborish",
    "Loyiha g'oyasini tanlash va rejalashtirish",
    "Prototipni yig'ish",
    "Modelni o'rgatish va sozlash",
    "Tizimni sinash va o'lchash",
    "Loyihani hujjatlashtirish",
  ],
  "Ovoz yoki tasvir tanuvchi tizimni ishga tushirish",
  "Yakuniy AI loyihasi: ko'radigan yoki eshitadigan qurilma"),
}

# -------------------------------------------------------------- 8-sinf 2-yil
Y2_8 = {
"1-chorak": Q("ESP32: ilg'or imkoniyatlar", "esp32",
  "Kurs rejasi va muhandislik yondashuvi",
  [
    "ESP32 arxitekturasi: ikki yadro va xotira",
    "Pinlar, ADC va DAC xususiyatlari",
    "PWM, touch va Hall imkoniyatlari",
    "I2C va SPI: bir nechta qurilma",
    "OLED va grafik interfeys",
    "microSD: ma'lumot yozish va o'qish",
    "RTC va vaqt bo'yicha vazifalar",
    "INA219: tok va quvvat o'lchash",
    "BMP280: bosim va balandlik",
    "HX711: yuk va og'irlik o'lchash",
    "Sensorlarni kalibrlash va aniqlik",
    "Ma'lumotni filtrlash (o'rtacha, silliqlash)",
    "Deep sleep va batareya hisobi",
    "Quvvat manbai va stabilizator",
    "Vazifalarni bo'lish (FreeRTOS g'oyasi)",
    "Kodni modullarga bo'lish",
    "Kutubxona yozish asoslari",
    "Nosozlik topish: mantiqiy analiz",
  ],
  "Ko'p sensorli o'lchov tizimini yig'ib, ma'lumotni yozib borish",
  "Muhandislik o'lchov stansiyasi"),

"2-chorak": Q("IoT tizimlari", "esp32",
  "Tizim sifatida loyihalash: qurilma, tarmoq, interfeys",
  [
    "WiFi va tarmoq asoslari (takrorlash va chuqurlashtirish)",
    "Veb-server va API tushunchasi",
    "JSON formati bilan ishlash",
    "HTTP GET va POST so'rovlari",
    "Bulut platformasiga ulanish",
    "Ma'lumotni vizualizatsiya qilish",
    "MQTT: broker, mavzu (topic), obuna",
    "MQTT bilan ikki tomonlama boshqaruv",
    "Telegram bot: to'liq boshqaruv paneli",
    "Ogohlantirish tizimi (alert)",
    "BLE bilan telefonga ulanish",
    "Bir nechta qurilmali tarmoq (mesh g'oyasi)",
    "Xavfsizlik: parol, shifrlash asoslari",
    "OTA: masofadan dastur yangilash",
    "Tizim arxitekturasini chizish",
    "Nosozlikka chidamlilik (qayta ulanish)",
    "Loglash va diagnostika",
    "Tizimni sinovdan o'tkazish",
  ],
  "To'liq IoT tizimini yig'ib, uzoqdan boshqarish",
  "Aqlli uy IoT tizimi: bir nechta qurilma"),

"3-chorak": Q("Mashinaviy o'rganish va TinyML", "ai",
  "Sun'iy intellekt: nazariya va qurilmadagi amaliyot",
  [
    "SI, mashinaviy o'rganish va chuqur o'rganish",
    "Nazorat ostida va nazoratsiz o'rganish",
    "Neyron tarmoq g'oyasi: oddiy tushuntirish",
    "TinyML: mikrokontrollerda model",
    "Edge Impulse: to'liq ish oqimi",
    "Ma'lumot to'plash strategiyasi",
    "Ma'lumot sifati va muvozanati",
    "Belgi ajratish (feature extraction)",
    "Model turini tanlash",
    "O'rgatish parametrlari (epoch, learning rate)",
    "Aniqlik, chalkashlik matritsasi, F1",
    "Overfitting va uni oldini olish",
    "Modelni siqish va kvantlash",
    "Modelni qurilmaga joylash",
    "Real vaqtda ishlash va kechikish (latency)",
    "Xotira va tezlik cheklovlari",
    "Modelni yaxshilash sikli",
    "AI axloqi: xolislik, maxfiylik, mas'uliyat",
  ],
  "Model o'rgatib, qurilmaga joylash va aniqligini o'lchash",
  "Anomaliya aniqlovchi tizim (nosozlikni oldindan sezish)"),

"4-chorak": Q("Yakuniy muhandislik loyihasi", "ai",
  "Muhandislik sikli: muammo, yechim, prototip, sinov, himoya",
  [
    "Muammoni aniqlash va tadqiq qilish",
    "Foydalanuvchi ehtiyojini o'rganish",
    "Texnik topshiriq yozish",
    "Yechim variantlarini solishtirish",
    "Tizim arxitekturasini loyihalash",
    "Komponentlarni tanlash va asoslash",
    "Sxemani chizish",
    "Prototipni yig'ish (1-bosqich)",
    "Dasturni yozish (1-bosqich)",
    "AI modelini o'rgatish va integratsiya",
    "Birinchi sinov va o'lchov",
    "Kamchiliklarni aniqlash",
    "Yaxshilash va qayta sinash",
    "Korpus va yakuniy montaj",
    "Foydalanuvchi qo'llanmasi yozish",
    "Texnik hujjat tayyorlash",
    "Taqdimot va himoyaga tayyorgarlik",
    "Boshqa loyihalarni baholash (peer review)",
  ],
  "Loyihani texnik topshiriq bo'yicha bajarib, himoya qilish",
  "Yakuniy loyiha: AI integratsiyalangan IoT qurilmasi"),
}


SYLLABUS = {
    "1-yil": {"5-sinf": Y1_5, "6-sinf": Y1_6, "7-sinf": Y1_7, "8-sinf": Y1_8},
    "2-yil": {"5-sinf": Y2_5, "6-sinf": Y2_6, "7-sinf": Y2_7, "8-sinf": Y2_8},
}

CHORAKLAR = ["1-chorak", "2-chorak", "3-chorak", "4-chorak"]
SINFLAR = ["5-sinf", "6-sinf", "7-sinf", "8-sinf"]
YILLAR = ["1-yil", "2-yil"]


def tekshir():
    """Tuzilish to'g'riligini tekshiradi: har chorakda 21 dars bo'lishi kerak."""
    jami = 0
    xato = []
    for yil in YILLAR:
        for sinf in SINFLAR:
            for ch in CHORAKLAR:
                q = SYLLABUS[yil][sinf][ch]
                n = 1 + len(q["mavzular"]) + 1 + 1   # kirish + mavzular + nazorat + loyiha
                jami += n
                if n != 21:
                    xato.append(f"{yil} {sinf} {ch}: {n} dars (21 bo'lishi kerak)")
    return jami, xato


if __name__ == "__main__":
    jami, xato = tekshir()
    print("Jami dars:", jami)
    print("Sinf-yil soni:", len(YILLAR) * len(SINFLAR))
    if xato:
        print("XATOLAR:")
        for x in xato:
            print("  -", x)
    else:
        print("Tuzilish to'g'ri: har chorakda 21 dars")
