# -*- coding: utf-8 -*-
"""8 ta model/chorak x 4 chorak x 5 sinf — 1-yil uchun (100% qurish, dasturlashsiz)."""

YEAR1_POOLS = {
    "0-sinf": [
        ["Little Lantern 1", "Little Lantern 2", "Little Lantern 3", "Little Lantern 4",
         "Triangle", "Quadrilateral", "Parallelogram", "Wheelbarrow",
         "Balance", "Wheel Car", "Teeterboard", "Swing",
         "Cellphone Mount", "Hand Fan", "Jack", "Crane", "Barbecue Grill", "Sewing Machine"],
        ["Pulley Crane", "Counter Scale", "Pilers", "Jackknife",
         "Rail Gate", "Rake", "Hayfork", "Expansion Clamp",
         "Spinning Top 3", "Spinning Top 4", "Big Hand Fan", "Weirdo Clock",
         "Elastic Band Gun", "Hand Drill", "Grinding Machine", "Lantern",
         "Vigorous Extrusion Machine", "Wheel Barrow"],
        ["Electric Fan", "Rotating Plane", "Inertia Pull-Back Car", "Elasti-Car",
         "Santa Claus Car", "Gear Shifting Fan", "Pivoting Fan", "Christmas Tree",
         "Inertia Car 1", "Inertia Car 2", "Top Launcher (with wheels)", "Elasti-Pumper",
         "Flytrap", "Santa Claus Car 2", "Santa's Sleigh", "Skiing Man",
         "Armoured Vehicle", "Crawler Excavator"],
        ["Little Bear", "Little Deer", "Rabbit (AI)", "Automatic Gate",
         "Bull", "Score Indicator", "Sorting Box", "Conveyor",
         "Mouse (AI)", "Bus", "Cat And Mouse (AI)", "Color Sorting",
         "Buffalo (electric)", "Electric Tortoise", "Crab (electric)", "Electric Mouse",
         "Tyrannosaurus (AI)", "Crocodile (AI)"],
    ],
    "1-sinf": [
        ["Crane", "Pilers", "Jackknife", "Counter Scale",
         "Pulley Crane", "Wheelbarrow", "Hand Drill", "Grinding Machine",
         "Rail Gate", "Rake", "Hayfork", "Balance",
         "Teeterboard", "Swing", "Triangle", "Quadrilateral",
         "Little Lantern 1", "Little Lantern 2"],
        ["Rotating Plane", "Gear Shifting Fan", "Pivoting Fan", "Dancing Man",
         "Electric Helicopter", "Skiing Man", "Car Puller", "Hoeing Man",
         "Weighting Man", "Forklift", "Hammer Machine", "Sweeper",
         "Scarecrow", "Step Man", "Electric Fan", "Christmas Tree",
         "Santa's Sleigh", "Santa Claus Car"],
        ["Manual Joint Motion 1", "Manual Joint Motion 2", "Manual Joint Motion 3", "Manual Joint Motion 4",
         "Manual Buhr Mill", "Manual Drill Car", "Car with YL Man 1", "Car with YL Man 2",
         "Manual Gatling Gun", "Tumbler", "Manual Jumping YL Man 1", "Manual Jumping YL Man 2",
         "Manual Jumping YL Man 3", "Manual Rotating YL Man 1", "Manual Rocking YL Man 1", "Wings Car",
         "Car with YL Man 3", "Car with YL Man 4"],
        ["Little Bear", "Little Deer", "Automatic Gate", "Score Indicator",
         "Rabbit (AI)", "Mouse (AI)", "Bull", "Bus",
         "Cat And Mouse (AI)", "Crocodile (AI)", "Stegosaurus (AI)", "Crab (AI)",
         "Sorting Box", "Color Sorting", "Score Maker (AI)", "Conveyor",
         "Tyrannosaurus (AI)", "Programmable Car (AI)"],
    ],
    "2-sinf": [
        ["Manual Rotating YL Man 1", "Manual Rotating YL Man 2", "Manual Rotating YL Man 3", "Manual Rotating YL Man 4",
         "Manual Rotating YL Man 5", "Manual Rocking YL Man 1", "Manual Rocking YL Man 2", "Manual Rocking YL Man 3",
         "Excavator (Gear-driven)", "Crane", "Conveyor", "Rail Gate",
         "Manual Jumping YL Man 3", "Manual Jumping YL Man 4", "Manual Jumping YL Man 5", "Manual Buhr Mill",
         "Tumbler", "Manual Gatling Gun"],
        ["Dotting Machine", "Circling Machine", "Drawing Machine", "Weirdo Clock",
         "Sweeper", "Hammer Machine", "Forklift", "Oil Extractor",
         "Lifting Platform", "Line Car", "RWD Car", "Electric Sewing Machine",
         "Pterosaur", "Step Man", "Inchworm", "Armoured Vehicle",
         "Santa's Sleigh", "Santa Claus Car"],
        ["Rocking YL Man 1", "Rocking YL Man 2", "Rocking YL Man 3", "Rocking YL Man 4",
         "Rocking YL Man 5", "Jumping YL Man 1", "Jumping YL Man 2", "Jumping YL Man 3",
         "Jumping YL Man 4", "Roating YL Man 1", "Roating YL Man 2", "Electric Buhr Mill",
         "Joint Motion 1", "Joint Motion 2", "Electric Gatling Gun", "Electric Mouse",
         "Joint Motion 3", "Joint Motion 4"],
        ["Obstacle Avoiding Car", "Line Patrol Tank", "Line Patrol Dog", "Line Patrol Dragon",
         "Score Maker (AI)", "Bus", "Color Sorting", "Little Bear",
         "Automatic Gate", "Mine Clearance", "Sorting Box", "Bull",
         "Score Indicator", "Rabbit (AI)", "Mouse (AI)", "Intelligent Gate",
         "Harley", "Scooter (Prog)"],
    ],
    "3-sinf": [
        ["Eggbeater", "Tower Crane", "Ladder", "Bridge Crane",
         "Fork Lift Truck", "Excavator (Belt-driven)", "Manual Rocking YL Man 6", "Manual Rocking YL Man 7",
         "Manual Rocking YL Man 8", "Manual Rotating YL Man 6", "Manual Rotating YL Man 7", "Crab Premium",
         "Woodpecker", "Inspection Robot", "Patrol Car", "Dual Motor Lunar Rover",
         "Tyannosaurus Rex (Adv)", "Stegosaurus (Adv)"],
        ["Electric Tyrannosaurus", "Electric Stegosaurus", "Electric Crocodile", "Triceratops (electric)",
         "Dolphin (electric)", "Brachiosaurus (electric)", "Hadrosaur (electric)", "Euoplocephalus (electric)",
         "Buffalo (electric)", "Electric Mouse", "Electric Cat and Mouse", "Crab (electric)",
         "Electric Tortoise", "Electric Buhr Mill", "Joint Motion 3", "Joint Motion 4",
         "Line Patrol Tank", "Scooter (Prog)"],
        ["Formula Car", "Speeding Car", "Telecar", "Trailer",
         "Hooded Motorcycle", "Ploughing Tractor", "Dragon Boat", "Shark",
         "Infantry Fighting Vehicle", "Transformers", "Kowtow Machine", "Cheetch",
         "Propeller-driven Vehicle", "Osprey Aircraft", "Steam Train", "Koi",
         "Flytrap (Prog)", "Line Patrol Dog"],
        ["Transport Helicopter", "Infinite Loop", "Upside Down", "Obstacle Avoiding Car",
         "Line Patrol Dragon", "Mine Clearance", "Intelligent Gate", "Harley",
         "Elevator", "Ferris Wheel", "Storage Robot", "Rocking Trojan",
         "Turnable F1", "Battle Robot", "Combat Forklift", "Big Truck",
         "Interstellar Train", "Insert With Clips"],
    ],
    "4-sinf": [
        ["Tower Crane", "Bridge Crane", "Fork Lift Truck", "Ladder",
         "Intelligent Forklift", "Combat Forklift", "Storage Robot", "Big Truck",
         "Elevator", "Ferris Wheel", "Insert With Clips", "Crab Premium",
         "Woodpecker", "Eggbeater", "Excavator (Belt-driven)", "Excavator (Gear-driven)",
         "Tyannosaurus Rex (Adv)", "Stegosaurus (Adv)"],
        ["Patrol Car", "Inspection Robot", "Dual Motor Lunar Rover", "Battle Robot",
         "Obstacle Avoiding Car", "Obstacle Avoiding (2)", "Obstacle Avoiding (3)", "Harley",
         "Turnable F1", "Line Patrol Tank", "Line Patrol Dog", "Line Patrol Dragon",
         "Intelligent Gate", "Automatic Gate (Prog)", "Rocking Trojan", "Animal Trap",
         "Scooter (Prog)", "Flytrap (Prog)"],
        ["Moon Rover", "Off-road Rover", "Exploration Robot", "Star Fighting",
         "X Fighter", "Satellite Car", "Combat Robot", "War Robot",
         "Transport Walker", "Reconnaissance Walker", "Moon Exploration Vehicle", "Space Shuttle",
         "Batmobile", "Intersteller Radar Forklift", "Alien Reconnaissance Aircraft", "Interstellar Cannon",
         "Star War Aircraft", "Electric Crocodile 2.0"],
        ["Transformers", "Infinite Loop", "Interplanetary Repair Station", "Lunar Transporter",
         "Interplanetary Jet", "Satellite Rover", "Intersteller Pathfinder Robot", "Probe Robot",
         "Plantary System", "Collection Robot", "Moon Collection Rover", "Space Transport Aircraft",
         "Twin Propeller Aircraft", "Armoured Vehicle (Space)", "Interstellar Train", "Pastry Chef",
         "Infantry Fighting Vehicle", "Formula Car"],
    ],
}

QUARTER_INTRO = {
    "0-sinf": [
        "Chorak kirish: bloklar bilan tanishuv, xavfsizlik",
        "Chorak kirish: mexanizmlar nima uchun kerak?",
        "Chorak kirish: motor va controller bilan tanishuv (namoyish)",
        "Chorak kirish: sensor nima? (namoyish)",
    ],
    "1-sinf": [
        "Chorak kirish: Makerzoid to'plami, detallar nomlari, xavfsizlik",
        "Chorak kirish: motor qanday ishlaydi? (namoyish)",
        "Chorak kirish: qo'lda harakatlantiriladigan mexanizmlar (YL Corps)",
        "Chorak kirish: sensor turlari bilan tanishuv (namoyish)",
    ],
    "2-sinf": [
        "Chorak kirish: o'tgan yilni eslaymiz, murakkab mexanizmlarga kirish",
        "Chorak kirish: elektr mashinalar qanday ishlaydi?",
        "Chorak kirish: elektr hayvon-mexanizmlar bilan tanishuv",
        "Chorak kirish: sensorli modellar bilan tanishuv",
    ],
    "3-sinf": [
        "Chorak kirish: murakkab mexanizmlar va manipulyatorlar",
        "Chorak kirish: elektr hayvonlar — dinozavrlar va suv hayvonlari",
        "Chorak kirish: murakkab transport vositalari",
        "Chorak kirish: havo va suv transporti",
    ],
    "4-sinf": [
        "Chorak kirish: muhandislik dizayni jarayoni, yuk ko'targichlar",
        "Chorak kirish: patrul va qidiruv robotlari",
        "Chorak kirish: kosmik texnika va rover'lar",
        "Chorak kirish: bitiruv loyihasiga umumiy tayyorgarlik",
    ],
}

QUARTER_THEME = {
    "0-sinf": ["Oddiy mexanizmlar", "Yuk ko'tarish mexanizmlari", "Birinchi motorli modellar", "Sensorli figuralar"],
    "1-sinf": ["Richag va tishli g'ildirak", "Motorli modellar", "Qo'lda harakatlanuvchi mexanizmlar (YL Corps)", "Sensorli figuralar"],
    "2-sinf": ["Murakkab mexanizmlar", "Elektr mashinalar", "Elektr YL figuralari", "Sensorli aqlli modellar"],
    "3-sinf": ["Murakkab mexanika va manipulyatorlar", "Elektr hayvonlar", "Murakkab transport", "Havo/suv transporti (erkin tanlov)"],
    "4-sinf": ["Yuk ko'targich robotlar", "Patrul/qidiruv robotlari", "Kosmik texnika", "Bitiruv loyihasi (erkin tanlov)"],
}
